### ISSUE TITLE
[Feature Request] Non-keyboard way to enter floating mode

### ISSUE THREAD

**Issue by kolgza** [pop-os/shell#1002]
When auto-tiling is enabled, the only way to enable floating mode for windows is using the keyboard shortcut `Super` + `G`; it is not currently possible to enable floating mode for windows using only a mouse.

**Comment by derpmatt** [comment]
Go to the top panel menu icon and select "Floating window Exceptions" from the drop down. Click "Select" from the modal window.

**Comment by 13r0ck** [comment]
![Screenshot from 2021-12-22 13-44-07](https://user-images.githubusercontent.com/58987761/147153104-ce21093c-989d-4b52-9ab7-fbe2454174e6.png)

Click `Floating Window Exceptions`
