### ISSUE TITLE
Launcher not using system translations and showing double search results

### ISSUE THREAD

**Issue by maplehobo** [pop-os/shell#1006]
The launcher doesn't use my system language (spanish). It also gives me double search results when searching for applications. It shows entries for local desktop files (I'm guessing the ones at `.local/share/applications`) as well as system wide. It would be nice if there would be an option for selecting which ones to show (system or local) or for it to show only one entry if it detects it's repeated.

![Captura de pantalla de 2021-06-18 08-10-12](https://user-images.githubusercontent.com/13398794/122554156-ff85a400-d00e-11eb-8c3f-4949e55bcbd7.png)

**Comment by tomaswarynyca** [comment]
Any news there? @mmstick

**Comment by mmstick** [comment]
None yet.

**Comment by tomaswarynyca** [comment]
Is it possible to help translate the system?

**Comment by mmstick** [comment]
This was fixed a while back

**Comment by maplehobo** [comment]
This issue reappeared with a recent update to cosmic. Translation works, but double entries for local and system apps became present again. Also the app grid is blank when opened, apps appear after you search something with gnome shell search.

**Comment by mmstick** [comment]
The app grid isn't related to Pop Shell. Double entries could be worked out though. But the launcher is no longer a part of Pop Shell. It was replaced with Pop Launcher: github.com/pop-os/launcher/

**Comment by maplehobo** [comment]
> The app grid isn't related to Pop Shell

It seems to be a problem with cosmic dock. If I disable the dock, app grid shows normally.
