### ISSUE TITLE
Sleek App can't be controlled with tiling wm commands with minimize to tray enabled

### ISSUE THREAD

**Issue by JordyScript** [pop-os/shell#1009]
**(1) Issue/Bug Description:**
The [Sleek app](https://www.flathub.org/apps/details/com.github.ransome1.sleek) can't be controlled by tiling wm commands if minimize to tray bar is set to true in the settings. I can't change its location using the keyboard.

**(2) Steps to reproduce (if you know):**
install sleek.
set the minimize to tray bar option to true in the settings
Try to use commands to control the window position (super + enter, then arrow keys)

**(3) Expected behavior:**
Window tiles and moves about the various monitors

**(4) Distribution:**
 ```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**
`3.38.3-2ubuntu0.20.10.2pop1~1614116211~20.10~0176ca0`

**(6) Pop Shell version:**
```
pop-shell:
  Installed: 1.1.0~1624036583~20.10~93634d6
  Candidate: 1.1.0~1624036583~20.10~93634d6
  Version table:
 *** 1.1.0~1624036583~20.10~93634d6 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**
pop-os

**(8) Monitor Setup:**
built in 1080p display, with or without external monitors

**(9) Other Installed/Enabled Extensions:**
pop-os default extensions

**(10) Other Notes:**
This only happens when the minimize to tray bar is set to true, which I can live without. So it's not a high priority bug, but I thought I'd mention it, because perhaps something important can be learned from this bug. FYI Sleek is an electron app.

p.s. edited to correct my earlier faulty understanding of the cause of the bug

**Comment by jmmaranan** [comment]
This is due to pop-shell tracking windows that do not skip task bars as one criteria. When minimize tray is ON for Sleek the property for it is set to skip the task bar. I think @mmstick might have an idea why that was included as a criteria.

**Comment by jmmaranan** [comment]
When removing `!this.meta.is_skip_taskbar()`, it now works:
![image](https://user-images.githubusercontent.com/348125/123004248-5c23ee80-d382-11eb-95b9-065736d81cce.png)
