### ISSUE TITLE
Moving a floating exception window between monitors puts it in tiling tree

### ISSUE THREAD

**Issue by jmbuhr** [pop-os/shell#1016]
**(1) Issue/Bug Description:**
Moving a floating exception window between monitors puts it in the tiling tree, though only half-heartedly. The window supposedly stays floating, but other tiling windows make room for it. This room stays as a gap upon moving the window that is supposed to be floating with the mouse.
This only happens with windows in the exception list, not windows manually set to floating with `super+g`.

**(2) Steps to reproduce (if you know):**
Open a window listed in the floating exceptions (e.g. gnome-screenshot) and move it between monitors via the shortcut.

**(3) Expected behavior:**
Window stays floating and tiling windows don't make room for it.

**(4) Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**
GNOME Shell 3.38.4

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1624036583~21.04~93634d6
  Candidate: 1.1.0~1624036583~21.04~93634d6
  Version table:
 *** 1.1.0~1624036583~21.04~93634d6 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**
pop-os 21.04

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
Laptop and additional monitor as main monitor

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**
This must have been caused by one of the recent commits, as I did not observe this behavior before.

**Comment by bflanagin** [comment]
Nice find. Can confirm the issue is in 20.10 

```
pop-shell:
  Installed: 1.1.0~1624306081~20.10~47d4829
  Candidate: 1.1.0~1624306081~20.10~47d4829
  Version table:
 *** 1.1.0~1624306081~20.10~47d4829 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status
```

**Comment by bflanagin** [comment]
I've gone through all the major revisions of pop-shell between 20.10 and 21.04 and the issue is present in all of them. @jmbuhr could you give us your best guess on the time-frame for when the issue didn't present itself. Might help me narrow down the search.

**Comment by jmbuhr** [comment]
Unfortunately, I had no luck pinning it down either, yet.

**Comment by jmmaranan** [comment]
I think that issue has been there all this time when floating exceptions were initially created.

**Comment by mmstick** [comment]
It has, and I believe it's an easy fix.

**Comment by jmmaranan** [comment]
It looks like the exempted windows for floating are not recognized by the tiling->move() API. Either add the Tags.Floating to all exempted windows or ask windows_shall_float or combine both during the move() call.

**Comment by jmmaranan** [comment]
@mmstick - I'll send in a fix
