### ISSUE TITLE
Add experimental features to the extension prefs

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/shell#102]
Experimental Features:

- Show Window Titles
- Disable Outer Gap
- Disable Pop!_Shell

We'll refine active window hint and window titles after release. Disable outer gaps might make it to GNOME Settings after release as well. 

I suggest we drop the snap to grid toggle. At least for the moment. It doesn't apply to tiling and could be confusing.

**Comment by mmstick** [comment]
Move the snap-to-grid toggle to extension prefs? It does make it easy to manually tile windows in stacking mode, but people may not want it enabled by default.

**Comment by WatchMkr** [comment]
That works. Let's name it "Snap to Grid (Floating Mode)" so that users don't expect it to change anything in auto tiling mode.

**Comment by WatchMkr** [comment]
Removed Show Active Window Hint from here. Looks like it will make the tiling menu.

**Comment by WatchMkr** [comment]
FYI, added "Disable Pop!_Shell" as this will be a always-enabled extension so we need to give the user an option to disable it.
