### ISSUE TITLE
Sleek application cannot be focused,and is ignored using keyboard controls when "Minimize to tray bar" enabled

### ISSUE THREAD

**Issue by bflanagin** [pop-os/shell#1023]
**(1) Issue/Bug Description:**
When using Sleek (flatpak) with "Minimize to tray bar" enabled and with the keyboard control fix applied (https://github.com/pop-os/shell/pull/1021) you can control the Sleek window as long as it has focus. Moving focus to another app is possible but not the reverse. The issue also appears to affect the ability to move other windows in relation to Sleek. 

**(2) Steps to reproduce (if you know):**
(Assuming above fix is applied) 
Install Sleek via flatpak or Pop!_Shop
Enable "Minimize to tray bar" in Sleek
Add a Sleek window and one other window (not Sleek)

With tiling and active hint enabled:
  * Select Sleek via mouse and move it right or left. (should work)
  * Use keyboard to change focus to non Sleek window (should work)
  * Use keyboard to change focus to Sleek. (doesn't work)
  * Use keyboard to move non Sleek window left or right (doesn't work)

Having multiple monitors show similar results. 

**(3) Expected behavior:**

Sleek should behave the same whether or not "Minimize to tray bar" is enabled.

**(4) Distribution (run `cat /etc/os-release`):**

 Issue appears on 20.04,20.10,21.04

**(5) Gnome Shell version:**

Latest tested: `3.38.4-1ubuntu3~21.04.1ubuntu1pop1~1623339707~21.04~2a1865d`

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

Latest tested:  `1.1.0~1624408005~21.04~43a4386`

**(7) Where was Pop Shell installed from:**

Standard Distribution

**(8) Other Installed/Enabled Extensions:**

Default extensions installed by the OS

**Comment by jmmaranan** [comment]
@bflanagin - does this work?
Still figuring out alt tab and will do some code cleanup.

![image](https://user-images.githubusercontent.com/348125/123186484-3ec85080-d466-11eb-9f0c-094268cf9c26.png)
