### ISSUE TITLE
Make Search Hotkey wait for button release

### ISSUE THREAD

**Issue by arandomliz** [pop-os/shell#1025]
**(1) Issue/Bug Description:**
Launcher pops up directly on the button-down event of the configured hotkey combination. 

**(2) Steps to reproduce (if you know):**
- disable `/org/gnome/mutter/overlay-key` (disable default & set custom value to nothing)
- set `/org/gnome/shell/extensions/pop-shell/activate-launcher` to `['Super_L']`
- press the super button

The search should pop up instantly, blocking the use of super for any other hotkey combinations (i.e. `<Super>h`) 

**(3) Expected behavior:**
The expected behavior for me would be how the gnome shell reacts when super is pressed. No action will be taken, until the key was released (and no hotkey combination was used)

**(4) Distribution (run `cat /etc/os-release`):**
 ```
 NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
 ```

**(5) Gnome Shell version:**
```
GNOME Shell 3.36.9
```

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

Build locally running commit 3dd1fdd9cbb724134bdd1167ef2917bf850f8672

**(7) Where was Pop Shell installed from:**
Github, build locally with `make local-install`

**Comment by mmstick** [comment]
This is already the default behavior in COSMIC.

**Comment by Gansgar** [comment]
So this is an issue of the gnome-shell not pop-os shell?
