### ISSUE TITLE
Implement final tiling window menu

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/shell#103]
Needs #102 (Experimental features in ext prefs) and https://github.com/pop-os/shell-shortcuts/issues/1 (shortcuts help).

Gaps setting is disabled until Tile Windows is activated.

Not shown but add - **Show Active Windows Hint** toggle above the Gaps setting.

![extension-menu-1](https://user-images.githubusercontent.com/3430283/77426559-5237c800-6d9a-11ea-8c43-33c0321c67ce.png)

**Comment by mmstick** [comment]
Should we have a button for easy access to the prefs dialog?

**Comment by WatchMkr** [comment]
I consider anything in prefs to be experimental and not to be exposed through the general UI. As the project matures, these will move from extension prefs and into the tiling menu and g-c-c.
