### ISSUE TITLE
Change descriptions in Launcher Help and make files default.

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/shell#1032]
Currently, the descriptions in the Launcher Help have a lot of symbols framing the prefix that is confusing. We should change descriptions to be easier to understand omitting additional symbols. 

For calculations:
Perform calculation with "="

Web Search:
Search websites by name "ddg" "google" "amazon"

File Search:
Search files in the system by typing "files"

Terminal Commands:
Run commands by typing "run"

**Comment by WatchMkr** [comment]
This looks complete - with some nice touches included.
