### ISSUE TITLE
ddterm (drop-down terminal) is being tiled like other windows

### ISSUE THREAD

**Issue by nre-ableton** [pop-os/shell#1034]
**(1) Issue/Bug Description:**

Since the recent update of pop-shell (I _think_ it started happening after the most recent update, `1.1.0~1624922027~20.10~3f417b4`), [ddterm](https://github.com/amezin/gnome-shell-extension-ddterm) is being tiled and treated like a regular window. It should not be, since the point of ddterm is to briefly drop down from the top of the screen.

It's not possible to add a floating window exception for ddterm, because the window hides when the super key is pressed, and thus also hides when the floating window exception chooser is shown.

**(2) Steps to reproduce (if you know):**

1. Install ddterm from gnome-extensions
2. Enable tiling in pop-shell
3. Show ddterm using the hotkey (F12 by default)

**(3) Expected behavior:**

ddterm should be shown above other windows from the top of the screen, like the classic quake-terminal.

**(4) Distribution (run `cat /etc/os-release`):**
 
```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**

`GNOME Shell 3.38.3`

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1624559460~20.10~d59e373
  Candidate: 1.1.0~1624922027~20.10~3f417b4
  Version table:
     1.1.0~1624922027~20.10~3f417b4 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
 *** 1.1.0~1624559460~20.10~d59e373 100
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

Bundled with Pop!_OS

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1x 3440x1440

**(9) Other Installed/Enabled Extensions:**

ddterm

**(10) Other Notes:**

N/A

**Comment by TS-CUBED** [comment]
This is the same with other drop-down terminals, like Guake Terminal.

The solution is to add it to the floating windows exception list, which resides in `.config/pop-shell/config.json`

Unfortunately you cannot use the GUI exception manager, because the Guake window won't be selectable in the overview.

**Comment by nre-ableton** [comment]
Thanks for the tip, @TS-CUBED! For any others that may find their way here, I used `xprop` to find the actual window title.

**Comment by TS-CUBED** [comment]
I don't think we should close this issue.
These should be added to the default exception list that comes with pop-shell.

**Comment by nre-ableton** [comment]
Ok, that would be nice as well. I didn't want to add any extra burden to the maintainers, but if such applications could be added to the default exception list, that would be convenient.

**Comment by mmstick** [comment]
These applications should mark themselves in an identifiable way with the proper WindowType: https://developer.gnome.org/meta/stable/MetaWindow.html#MetaWindowType

But I'll add an exception since they're not doing that.

**Comment by nre-ableton** [comment]
@mmstick Thanks; I've also made a [GitHub issue](https://github.com/amezin/gnome-shell-extension-ddterm/issues/60) for ddterm to use the MetaWindow type.

**Comment by jmmaranan** [comment]
@nre-ableton - I included the default floats for Guake and ddterm on 1069.
