### ISSUE TITLE
Mouse cursor unexpectedly shifts when changing to a window on another display

### ISSUE THREAD

**Issue by ry167** [pop-os/shell#1042]
**(1) Issue/Bug Description:**

When I use the new application switcher/launcher (on super key press) to change my active window to one that is on another display, my cursor gets shifted to the top left of that window. 

This does not happen if changing to a window on the same display. 

Its not very useful as it makes it easy to lose the context of your mouse, so relative movements are all wrong and you have to search your screen for your mouse.

**(2) Steps to reproduce (if you know):**

as above.

**(3) Expected behavior:**

Do not shift my cursor.

**(4) Distribution (run `cat /etc/os-release`):**
 
Pop!_OS 21.04

**(5) Gnome Shell version:**

`GNOME Shell 3.38.4`

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

`1.1.0~1625023507~21.04~976106e`

**(7) Where was Pop Shell installed from:**

System76 Laptop, default install

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

Laptop Monitor + 24" USB C Monitor + DisplayPort daisy chain to second 24" monitor

**(9) Other Installed/Enabled Extensions:**

n/a

**(10) Other Notes:**

I believe this is the code causing this here: https://github.com/pop-os/shell/blob/96ae4065c77c681ef490271b5ad4c993ceefec8f/src/window.ts#L611

Some users may want this feature - but it should most definitely be configurable as its not a great default.

If you can point me to an example of setting up a configuration flag etc I am happy to make a PR for this.

**Comment by nre-ableton** [comment]
I have also noticed that when changing windows using the keyboard (super + arrow key) that the mouse pointer is relocated to the top left of the newly active window. It's driving me crazy. :sweat_smile: I wonder if this behavior is related?

**Comment by Spell-Rocker** [comment]
This behavior is driving me nuts!!! Anyone know a fix for this?

https://www.reddit.com/r/pop_os/comments/vb8jag/avoid_mouse_pointer_moves_when_switching_workspace/

**Comment by leviport** [comment]
Have you tried turning off the "Mouse cursor follows active window" setting in Extensions > Pop Shell settings?
![2022-06-13_09-20](https://user-images.githubusercontent.com/13512097/173387748-e18474a4-26cf-4fa8-9748-6a4cf85046ce.png)

**Comment by nre-ableton** [comment]
For the record, I no longer see this behavior, and I also don't see an option for "Mouse Cursor Follows Active Window" as is shown in the above screenshot. :shrug:

**Comment by Spell-Rocker** [comment]
My problem was resolved by disabling this option in the "pop shell" extension "Mouse cursor follows active window"
![image](https://user-images.githubusercontent.com/107240491/173501099-4a701d3f-1876-4e12-80c6-c745d7a55c8f.png)

**Comment by leviport** [comment]
Thanks for confirming! I'm going to close this issue then.
