### ISSUE TITLE
not an issue - feedback from poweruser

### ISSUE THREAD

**Issue by 8secz-johndpope** [pop-os/shell#1043]
I love this os.

Without an app called timeshift I would have been in a lot of trouble.
It's saved me many hours with broken configs. 
It gives me complete control over nvidia drivers / cuda toolkits.
https://github.com/teejee2008/timeshift

I don't know if there's a desire to help people more with nvidia technologies - but this would be awesome addition to bundle with os.

**Comment by jacobgkau** [comment]
Thank you for sharing. This repository is for the window tiling extension, Pop Shell. General Pop!_OS issues belong in https://github.com/pop-os/pop.

Additionally, GitHub issues are a development bug tracker, not a discussion forum. To discuss your usage with other users, the official Pop!_OS [subreddit](https://old.reddit.com/r/pop_os/) or [Mattermost chat room](https://chat.pop-os.org/) or the unofficial [Pop!_Planet website](https://pop-planet.info/) would all be great places to post.
