### ISSUE TITLE
Pop launcher crashes gnome when typing ~ with us intl keyboard

### ISSUE THREAD

**Issue by brunobmello25** [pop-os/shell#1047]
**(1) Issue/Bug Description:**

basically what this issue's title says: When running pop launcher and typing ~ it crashes gnome.

**(2) Steps to reproduce:**

1. Go to system keyboard settings and select English (US, intl., with dead keys) as your keyboard layout
2. Launch Pop Launcher with super+/ (or in my case super+D because I've remapped that shortcut)
3. Try and type a "~" using shift + ` + space. It should crash

**(3) Expected behavior:**

Should accept the ~ character normally

**(4) Distribution (run `cat /etc/os-release`):**

```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**

3.36.8

**(6) Pop Shell version:**

```
pop-shell:
  Installed: 1.1.0~1625079016~20.04~9970fd3
  Candidate: 1.1.0~1625079016~20.04~9970fd3
  Version table:
 *** 1.1.0~1625079016~20.04~9970fd3 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

From the default pop_os 20.04 iso

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1x 4k Primary and 1x FHD secondary

**(9) Other Installed/Enabled Extensions:**

- User Themes
- Alt Tab: Raise First Window
- Always Show Workspaces
- Desktop Icons NG (DING)
- Pop Shell
- Pop Shop Details
- System76 Power
- Ubuntu AppIndicators

**Comment by jmbuhr** [comment]
At first, I thought this was related to the file search issue (https://github.com/pop-os/shell/issues/1040), but I tried it out and was able to replicate this. Instead of the tilde symbol, it produces the ¬ symbol. Note, that this is to be expected:
![image](https://user-images.githubusercontent.com/17450586/124350722-a6189a00-dbf6-11eb-97d7-3a0512d80984.png)
the tilde symbol is actually here:
![image](https://user-images.githubusercontent.com/17450586/124350744-bc265a80-dbf6-11eb-87c3-e68a86bd4d34.png)
(you can click `show keyboard layout` in the layout-chooser that appear in the top bar if you have multiple layouts).
But the shell probably shouldn't crash when it gets this other symbol either.

**Comment by brunobmello25** [comment]
![image](https://user-images.githubusercontent.com/29875060/124358805-54710f00-dbf8-11eb-9ffa-19d6a3659bfe.png)
On the keyboard layout I mentioned it's not there

**Comment by jmbuhr** [comment]
Indeed, looks like I accidentally tried it with the UK instead of US version. Interesting that I was still able to reproduce the crash.

**Comment by PeSader** [comment]
Can confirm, I experienced the same issue.

**Comment by jmmaranan** [comment]
I think this is fixed now by the latest commit: acd91df80b614fab8bb31576e1f25090ba675aa6

**Comment by brunobmello25** [comment]
still crashing here

**Comment by jmmaranan** [comment]
This looks like a limitation of the cogl_pango library in gnome-shell 3.36. Don't think this is pop-shell

Aug 06 13:17:52 pop-os gnome-shell[17308]: pop-shell:  [INFO] got symbol 65104
**Aug 06 13:17:52 pop-os gnome-shell[17308]: invalid uninstantiatable type '(null)' in cast to 'GObject'**
Aug 06 13:17:52 pop-os gnome-shell[17308]: g_object_get_qdata: assertion 'G_IS_OBJECT (object)' failed
Aug 06 13:17:52 pop-os gnome-shell[17308]: invalid uninstantiatable type '(null)' in cast to 'GObject'
Aug 06 13:17:52 pop-os gnome-shell[17308]: g_object_set_qdata_full: assertion 'G_IS_OBJECT (object)' failed
Aug 06 13:17:52 pop-os gnome-shell[17308]: cogl_pango_ensure_glyph_cache_for_layout: assertion 'PANGO_IS_LAYOUT (layout)' failed
Aug 06 13:17:52 pop-os gnome-shell[17308]: pango_renderer_draw_layout: assertion 'PANGO_IS_LAYOUT (layout)' failed

**Comment by brunobmello25** [comment]
Hey everyone. I'll close this issue because it's been over 2 years since it's been open and I don't think I'll be able to contribute any further. Multiple releases have come already and I don't even use gnome with pop shell anymore.
