### ISSUE TITLE
Move windows to empty monitors with Super+Enter and direction keys.

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/shell#105]
This may be complete.

**Comment by aasutossh** [comment]
Sorry to barge in, but then why do we have `Super+Shift+direction`(for left and right monitor) in the keyboard shortcuts.
Should the tiling override the extra monitors?
I don't think so. Moving window to monitors should have highest priority.

**Comment by WatchMkr** [comment]
Super + left moves a window left, for example. If there is an empty monitor to the left, this command currently stops at the edge of the monitor instead of continuing to move the window over to the monitor on the left. This change makes moving windows consistent regardless of whether there are windows on the monitor to the left or not.

This won't override the Super+shift+direction shortcuts.

**Comment by aasutossh** [comment]
> Super + left moves a window left

Doesn't it just switches focus to the left window?
BTW I have `Tile Windows` enabled.

**Comment by WatchMkr** [comment]
I had to correct the text above. It's `Super + enter` then `left`.

**Comment by aasutossh** [comment]
> This won't override the Super+shift+direction shortcuts.

It kind of does. I have tiling enabled and one empty monitor. When I press `super+shift+right` (right monitor is empty), it won't move to right monitor.

**Comment by WatchMkr** [comment]
That shouldn't be the case. Please file a bug. Thanks!
