### ISSUE TITLE
Freeze after logging in - and opening overview

### ISSUE THREAD

**Issue by MKuranowski** [pop-os/shell#1051]
**(1) Issue/Bug Description:**
After installing the latest commit (78833ad73596f3ca127df207aaf151b1a15a0d6a), and logging in the whole Gnome Shell freezes.

This issue seems very similar to #969 or #971, upon login the whole Gnome Shell freezes.
However, for me downgrading to gjs 1.68.0 and/or mutter+gnome-shell to 40.0 doesn't help.

**(2) Steps to reproduce (if you know):**
1. Install the latest Pop Shell
2. Enable extension & reboot
3. Login

**(3) Expected behavior:**
No freezes

**(4) Distribution (run `cat /etc/os-release`):**
Arch, up to date @ 2021-07-04
```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

**(5) Gnome Shell version:**
gnome-shell: 40.0+80+ga08355931-1; then 40.2-1
mutter: 40.0+103+ga49dc7893-1; then 40.2.1-1
gjs: 1.68.0-3; then 1.68.1-1

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
commit 78833ad73596f3ca127df207aaf151b1a15a0d6a

**(7) Where was Pop Shell installed from:**
AUR (<https://aur.archlinux.org/packages/gnome-shell-extension-pop-shell-git/>)

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
Tested on multiple configurations (1080p+4K), single 1080p - seems irrelevant.

**(9) Other Installed/Enabled Extensions:**
None

**(10) Other Notes:**
I did some digging around in a fresh Arch install in a VM, and here are some findings:
1. Seems to only be present on Xorg sessions
2. After login there's nothing really interesting in the logs; but, after the screen locks I'm able to unlock the screen and the desktop seems to work fine - only when opening the overview the UI freezes.

  After that there's a single entry in journalctl that seems relevant:
  ```
  Jul 04 15:56:54 arch-vm gnome-shell[865]: JS ERROR: TypeError: app is null
    _init@resource:///org/gnome/shell/ui/windowPreview.js:125:9
    _addWindowClone@resource:///org/gnome/shell/ui/workspace.js:1350:21
    _init@resource:///org/gnome/shell/ui/workspace.js:1107:22
    _updateWorkspaces@resource:///org/gnome/shell/ui/workspacesView.js:462:29
    _init@resource:///org/gnome/shell/ui/workspacesView.js:121:14
    _updateWorkspacesViews@resource:///org/gnome/shell/ui/workspacesView.js:1091:24
    prepareToEnterOverview@resource:///org/gnome/shell/ui/workspacesView.js:1039:14
    animateToOverview@resource:///org/gnome/shell/ui/overviewControls.js:674:33
    animateToOverview@resource:///org/gnome/shell/ui/overview.js:93:24
    _animateVisible@resource:///org/gnome/shell/ui/overview.js:547:24
    show@resource:///org/gnome/shell/ui/overview.js:532:14
    toggle@resource:///org/gnome/shell/ui/overview.js:638:18
    _init/<@resource:///org/gnome/shell/ui/overviewControls.js:429:31
  ```

**Comment by xircon** [comment]
Same here aur/gnome-shell-extension-pop-shell-git r746.78833ad-1

**Comment by MKuranowski** [comment]
I did some further checks - my main PC runs `r710.93634d6-1` (commit 93634d6) without any issues. With the help of git-bisect I feel pretty certain that this bug was introduced with commit 5efd4c7.

**Comment by mmstick** [comment]
If so, could be something for @jmmaranan to look into

**Comment by jmmaranan** [comment]
I cannot reproduce this on Fedora 34 Gnome 40.1.0. But I think it is the isOverview function on both Workspace and WorkspaceThumbnail that were overriden.
What we can do is add the skip task bar logic as a toggle in prefs.js for the time-being.

**Comment by mmstick** [comment]
I'm personally not seeing an issue either, so something is a trigger.

**Comment by xircon** [comment]
I was out most of yesterday but I built d59e373, and am back running.

**Comment by ajay-actuary** [comment]
I have the same issue in Arch Linux as well

**Comment by MKuranowski** [comment]
Commenting out the overwrite of `Workspace.prototype._isOverviewWindow` at https://github.com/pop-os/shell/blob/acd91df80b614fab8bb31576e1f25090ba675aa6/src/extension.ts#L2546 resolves this issue, as @jmmaranan mentiones

**Comment by Wrzlprnft** [comment]
About what could be triggering this:
I too experience this issue with the same journalctl entry, but only when i want to go into **workspace** overview (super+d) while a window run using **wine/proton** is open. E.g. Age of Empires 2 DE via steam or Overwatch via Lutris.

Disabling the pop-shell extension or timeshifting to my backup from friday does resolve the issue, haven't done any bulding/bisecting to further narrow it down.

**Comment by jmmaranan** [comment]
@MKuranowski - thanks. Unfortunately, I cannot reproduce it - so would just rely on the logs provided here and there is one report on cosmic, https://github.com/pop-os/cosmic/issues/127, but for gnome-shell 3.38.4. It is really this same issue and not cosmic.

**Comment by MKuranowski** [comment]
I'm don't have much of an experience with pop-shell or Gjs, but it seems to me the new _isOverviewWindow now kinda does the opposite of what it's supposed to do.

The only window object that has a different return value then the original is of class `Gnome-shell` (window.toString() returns `[object instance wrapper GType:MetaWindowX11 jsobj@… native@…`).

The original _isOverviewWindow() returns `!window.skip_taskbar`, and the new function adds any window that has `skip_taskbar`, but is not of class Gjs.

Shouldn't that new function return `default_isoverviewwindow_ws(window) && window.get_wm_class() !== "Gjs"` to properly skip Gjs-class windows? Such version also properly skips the Gnome-shell GType:MetaWindowX11 window.

**Comment by jmmaranan** [comment]
> Shouldn't that new function return `default_isoverviewwindow_ws(window) && window.get_wm_class() !== "Gjs"` to properly skip Gjs-class windows? Such version also properly skips the Gnome-shell GType:MetaWindowX11 window.

The new changes were to handle #1022 and #1023. 

I am working on a fix to handle gnome-shell 40 and 3.3x. `Workspace._isOverviewWindow `override should be permanently off on gnome 40+ this is due to the new `WindowPreview._init()` code adds more than just _getCaption call. It can be revisited when it is time to handle gnome 40 - which is when the Ubuntu upstream of PopOs ships with 40 by default.

I am also adding a toggle for the skip taskbar by off by default.

**Comment by MKuranowski** [comment]
No hangs there, thanks :)

**Comment by benneti** [comment]
can confirm this branch works

**Comment by jmmaranan** [comment]
@mmstick - do you mind to review?

**Comment by jmmaranan** [comment]
@jacobgkau - please re-open this

**Comment by jmmaranan** [comment]
@MKuranowski - and others on gnome 40 please retain the built source you have for now so you can continue working. I'll send in a patch to include Pop LTS later or tomorrow.
