### ISSUE TITLE
launcher: laggy when first typing

### ISSUE THREAD

**Issue by matildepark** [pop-os/shell#1053]
**(1) Issue/Bug Description:**

Since installing 21.04, the launcher is much slower, noticeably slower; it seems to be searching even when I only type in a single character, which hangs for seconds and then speeds up when I type two characters, three characters, and so on. I removed plugins, but it persists.

**(2) Steps to reproduce (if you know):**

1. Open launcher.
2. Type a character.

**(3) Expected behavior:**

Well, you know.

**(4) Distribution (run `cat /etc/os-release`):**
 
```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**

3.38.4

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1625266132~21.04~78833ad
  Candidate: 1.1.0~1625266132~21.04~78833ad
  Version table:
 *** 1.1.0~1625266132~21.04~78833ad 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

Pop OS 21.04 clean install.

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1080p.

**(9) Other Installed/Enabled Extensions:**

Just Perfection

**(10) Other Notes:**

Can someone point out where in the codebase the search method is implemented? It probably just needs to be debounced; or wait until you stop typing; or search after 2 characters; or return the first 5 results and break out of the search, or really any of these. I can give it a shot.

**Comment by mmstick** [comment]
It is debounced here: https://github.com/pop-os/shell/blob/master/src/dialog_search.ts#L90
Every search invokes https://github.com/pop-os/shell/blob/master/src/dialog_launcher.ts#L40
Desktop entries are cached in memory when the launcher is opened
Each search performs a sort and drops everything sorted past 7 results

**Comment by mmstick** [comment]
I don't personally have the same issue, but some people are. Not sure what the root cause is, but most of what I've seen is that people who are having a laggy launcher are also having a laggy desktop in general, where even Firefox search lags majorly.

That said, I have been working on a Rust service to replace the meat of the launcher service. The goal is to have a DBus service that the shell extension will hook into for passing queries back and forth, since certain things just aren't easy to make fast in JavaScript (levenshtein algorithm is kind of slow).

**Comment by matildepark** [comment]
It's true that the system does lag more now than it did in 20.10, but it shouldn't have this kind of performance...

![Screenshot from 2021-07-04 16-24-55](https://user-images.githubusercontent.com/20846414/124398595-7942b080-dce4-11eb-9a04-e78de3d6791b.png)

It's curious that it isn't deterministic, means it's not as simple as I was thinking. Is there another issue? Maybe can isolate the shared factors.
