### ISSUE TITLE
Conky moves like a window on overview with pop-shell enabled. Works normally when pop-shell is disabled.

### ISSUE THREAD

**Issue by spxak1** [pop-os/shell#1055]
**(1) Issue/Bug Description:**

Conky (configured with ```own_window_type = 'desktop'```) should not appear on the task view (overview). When the task view is selected conky disappears. This is the **expected** operation. 

With the update from 20.10 to 21.04, conky now behaves as a window. [Here](https://imgur.com/v6BaKQI) is a screenshot with COSMIC and COSMIC Dock disabled in the extensions app. ![2021-07-04_21-24](https://user-images.githubusercontent.com/29977030/124402152-31dd1400-dd26-11eb-8935-018613f963fe.png)

COSMIC and COSMIC Dock make no difference if they are enabled or disabled.

The issue stops as soon as pop-shell is disabled. 

**(2) Steps to reproduce (if you know):**

1. Install Pop 21.04
2. Install conky (```sudo apt install conky```)
3. Start conky from the terminal (```conky &```)
4. Press ```super+d``` for overview (task view)
5. Conky moves and appears as a window
6. Disable pop-shell from the Extensions app
7. Conky now behaves properly, when super+d is pressed it just disappears from the screen, no Window appears.

See video [here](https://streamable.com/htg5oy)

**(3) Expected behavior:**

Conky disappears from view when the overview is selected.

**(4) Distribution (run `cat /etc/os-release`):**
 
```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**
GNOME Shell 3.38.4

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
 ```
pop-shell:
  Installed: 1.1.0~1625433688~21.04~acd91df
  Candidate: 1.1.0~1625433688~21.04~acd91df
  Version table:
 *** 1.1.0~1625433688~21.04~acd91df 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main i386 Packages
        100 /var/lib/dpkg/status
``` 

**(7) Where was Pop Shell installed from:**

Pop update to 21.04 (from 20.10)

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

Laptop screen 2560x1440.

**(9) Other Installed/Enabled Extensions:**

N/A

**(10) Other Notes:**

Conky behaved properly with pop-shell in 20.10 prior to the upgrade to 21.04.

Thank you.

**Comment by mmstick** [comment]
I assume you have the wrong window type. Normal window types are tiled.

```
own_window yes
own_window_class Conky
own_window_type override
background yes
```

**Comment by jmmaranan** [comment]
I think it is also related to the skip taskbar change. I'll send a fix on that toggled as off by default.

**Comment by spxak1** [comment]
> I assume you have the wrong window type. Normal window types are tiled.
> 
> ```
> own_window yes
> own_window_class Conky
> own_window_type override
> background yes
> ```

I added the window class and changed the type to override (from desktop). Makes no difference, conky still appears in the overview.

> I think it is also related to the skip taskbar change. I'll send a fix on that toggled as off by default.

I removed skip_taskbar, and made no difference.

Conky would not show in the overview up until maybe the last pop-shell version. Certainly before 21.04.

Here's a snippet of my conky config for referrence. 

~~~
conky.config = {
-- By Khiky_Merveilles
        background = true,
        use_xft = true,
        font = 'Product Sans Regular:size=9',
        xftalpha = 0.8,
        update_interval = 1,
        total_run_times = 0,
        own_window = true,
        own_window_type = desktop,
        own_window_transparent = true,
        own_window_class = Conky,
        own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
        double_buffer = true,
        draw_shades = false,
        draw_outline = false,
        draw_borders = false,
        draw_graph_borders = false,
        stippled_borders = 0,
        border_margin = '5',
        border_width = 1,
        default_color = '#000000',
        default_shade_color = '#000000',
        default_outline_color = '#000000',
        minimum_width = 500, minimum_height = 300,
        maximum_width = 500,
        gap_x = 0,
        gap_y = 0,
        alignment = 'bottom_left',
        no_buffers = true,
        uppercase = false,
        cpu_avg_samples = 2,
        net_avg_samples = 2,
        short_units = true,
        text_buffer_size = 2048,
        use_spacer = 'none',
        override_utf8_locale = true,
        imlib_cache_size = 0,

-- Color scheme #
        default_color = 'white',
        color1 = 'white',
        color2 = '#FD7F00',
        color3 = '#F5F24C',

        own_window_argb_value = 0,
        own_window_argb_visual = true,
        own_window_colour = '#000000',
};
~~~

As always, many thanks

**Comment by jmmaranan** [comment]
@spxak1 - apologies I was not clear. There was a feature that was implemented to handle windows that have skip task bars in them on Pop-Shell. I believe conky falls under skip_taskbar category even if you had it configured off in conkyrc. I was able to replicate when that feature is turned on in popshell.

Can you try this branch? https://github.com/pop-os/shell/pull/1061

You can toggle it to ON from Extensions > Pop-Shell or `Super+/ `, search for `Toggle Min`.

**Comment by spxak1** [comment]
I can confirm it Conky does **not** appear in the overview with that commit and Show Skip Taskbar Off.

I can see this was merged to master. How soon to push it to apt?

Thank you very much for the quick response and fix. Much appreciated.

**Comment by jmmaranan** [comment]
@jacobgkau - please reopen this as well
