### ISSUE TITLE
gjs file running

### ISSUE THREAD

**Issue by ZayRTun** [pop-os/shell#1056]
**(1) Issue/Bug Description:**
A file called `gjs` is always running but I can't switch to this application and I cannot quit it either.
Check the image file.
![20210705_095535](https://user-images.githubusercontent.com/31787822/124413858-7cd34780-dd77-11eb-8d34-03030ca9bce3.jpg)

**(2) Steps to reproduce (if you know):**
It simply appears after I boot the OS

**(3) Expected behavior:**
Shouldn't be there on it's own.

**(4) Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
 

**(5) Gnome Shell version:**
Gnome Shell version: 3.38.5

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```
pop-shell:
  Installed: 1.1.0~1625266132~21.04~78833ad
  Candidate: 1.1.0~1625433688~21.04~acd91df
  Version table:
     1.1.0~1625433688~21.04~acd91df 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main i386 Packages
 *** 1.1.0~1625266132~21.04~78833ad 100
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**
Was upgraded internally from pop os 20.04

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
2 x 1080p

**(9) Other Installed/Enabled Extensions:**
User Themes

**(10) Other Notes:**

**Comment by bflanagin** [comment]
You're right, it shouldn't be running automatically or at the very least it shouldn't be showing up in the alt tab interface. I would suggest launching the extensions that comes with gnome and turning off any extensions that aren't default. The hope is that one of those is causing the process to spawn. You may also want to check what applications are set to autostart. There may be something there that is causing the issue. 

If none of these work I suggest setting up an account over at https://chat.pop-os.org there may be someone in the community that has dealt with this problem.

**Comment by mmstick** [comment]
gjs is the JavaScript runtime that GNOME uses for GNOME Shell.

**Comment by jacobgkau** [comment]
We have a few users in Mattermost reporting gjs in the alt-tab menu and/or a blank icon showing up in Activities on 20.04 when `Show Minimize to Tray Windows` is enabled (the default setting.) I am not seeing this on my 20.04 test machine, but I'm re-opening the issue for further investigation.

**Comment by henriqueffc** [comment]
On my system (Pop! _OS 20.04 LTS) the ghost icon appeared with `Show Minimize to Tray Windows` enabled and the GNOME `WindowOverlay Icons` extension enabled as well. I disabled `WindowOverlay Icons` and the ghost icon disappeared. If I leave `WindowOverlay Icons` enabled I have to leave `Show Minimize to Tray Windows` disabled so the ghost icon doesn't show up. Of the two options, I preferred to disable `WindowOverlay Icons`.

**Comment by jacobgkau** [comment]
It seems there are two separate issues here.

1. DING + Wayland -> icon in Alt-Tab switcher.
2. WindowOverlay Icons extension (third-party) -> stray icon in Activities.

I would assume at least the second one can be fixed by adding something to the list of [skip taskbar exceptions](https://github.com/pop-os/shell/blob/b1b73f6789be7ee48cbe43613b20670a6ff58534/src/config.ts#L60).

**Comment by jmmaranan** [comment]
@henriqueffc - can you check if this happens with WindowOverlay Icons ext also turned on in the latest master branch?

**Comment by henriqueffc** [comment]
> @henriqueffc - can you check if this happens with WindowOverlay Icons ext also turned on in the latest master branch?

![Captura de tela de 2021-08-06 13-47-24](https://user-images.githubusercontent.com/78817824/128544868-f72de12c-66b6-4a00-b4d6-9fe97bcede91.png)

Yes. The icon still appears if WindowOverlay Icons and the Show Minimize to Tray Windows option in the Pop Shell are enabled together. If Show Minimize to Tray Windows in Pop Shell is disabled, the icon no longer appears. I use Pop!_OS 20.04 LTS and the system is up-to-date.

**Comment by jmmaranan** [comment]
The wm_class for the root in 3.36 is `Gnome-shell` where 3.38+ is now `Gjs`

**Comment by jmmaranan** [comment]
@henriqueffc or @jacobgkau - how do I repro the Alt+Tab with DING Gjs? Not sure if the new PR will fix it?

**Comment by jacobgkau** [comment]
> @henriqueffc or @jacobgkau - how do I repro the Alt+Tab with DING Gjs? Not sure if the new PR will fix it?

I'm able to recreate that one by enabling Wayland (comment out `WaylandEnable=false` in `/etc/gdm3/custom.conf`) and logging into a Wayland session using the gear in the bottom right. (The gear doesn't show up on an NVIDIA system, I'm using an Intel system to test.)

#1131 doesn't seem to fix that one (but it does fix the WindowOverlay Icons extension on X11 case.)
