### ISSUE TITLE
Third-party extensions are no longer loaded

### ISSUE THREAD

**Issue by nre-ableton** [pop-os/shell#1059]
**(1) Issue/Bug Description:**

Since I updated pop-shell to `1.1.0~1625433688~21.04~acd91df`, none of my third-party extensions are loaded. When I go to https://extensions.gnome.org/local/, I see them all there but switched off (the system extensions are shown as being loaded). When I toggle the switch to the "on" position, nothing happens. I've tried logging out/in and rebooting, and nothing fixes it. I also tried uninstalling and reinstalling some extensions, but the result was the same.

**(2) Steps to reproduce (if you know):**

Attempting to install any third-party extension.

**(3) Expected behavior:**

All extensions are loaded and shown.

**(4) Distribution (run `cat /etc/os-release`):**
 
```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**

`GNOME Shell 3.38.4`

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1625433688~21.04~acd91df
  Candidate: 1.1.0~1625433688~21.04~acd91df
  Version table:
 *** 1.1.0~1625433688~21.04~acd91df 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

Bundled with Pop!_OS.

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1x @ 3440x1440.

**(9) Other Installed/Enabled Extensions:**

- ddterm
- Emoji selector
- Pop theme toggle
- system-monitor
- Hue lights

**(10) Other Notes:**

**Comment by nre-ableton** [comment]
FWIW, this behavior also exists with `1.1.0~1625501479~21.04~b33c5e2`.

**Comment by bflanagin** [comment]
I'm unable to recreate the issue on my end on `b33c5e2` using the same extensions. I suggest heading over to https://chat.pop-os.org for further help as someone may have had a similar experience.

**Comment by jacobgkau** [comment]
Collecting logs with `sudo journalctl -b 0 > journalctl.txt` and providing the logs may show where the error is occurring. A screenshot of the Extensions app after you've tried to enable an extension may also be helpful.

**Comment by nre-ableton** [comment]
Hmm, it seems that something disabled extensions; I was unaware that there was an app to manage them (previously I have just relied on the Firefox extension and the Gnome Extensions webpage). :sweat_smile: I'm not sure how this happened, but at least it was an easy fix. Sorry for the noise!
