### ISSUE TITLE
Cannot resize beyond dock area when using keyboard shortcuts

### ISSUE THREAD

**Issue by krmbzds** [pop-os/shell#1065]
**(1) Issue/Bug Description:**

Cannot resize beyond dock are when using keyboard shortcuts
I have tried: (1) moving dock to the left, (2) disabling the dock.
The window will never expand beyond the bottom part of the screen (screen recording below).

**(2) Steps to reproduce (if you know):**

1. Move dock to the left, or hide dock, or disable dock from settings.
2. Use <kbd>Super</kbd>+<kbd>Enter</kbd> then tap <kbd>Shift</kbd>+<kbd>J</kbd> repeatedly to expand window towards the bottom.
3. The window will not expand beyond a designated area at the bottom of the screen even if the dock is: on the left/right, autohidden, or disabled.

**(3) Expected behavior:**

It should be possible to resize the window using keyboard shortcuts in a way that it's possible to cover the entire screen when the dock is auto-hidden, on the sides, or disabled.

**(4) Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**

```
3.38.4
```

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
  Installed: 1.1.0~1625501479~21.04~b33c5e2
  Candidate: 1.1.0~1625501479~21.04~b33c5e2
  Version table:
 *** 1.1.0~1625501479~21.04~b33c5e2 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

Official Pop! OS release.

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

Single monitor, 2560x1440 (16:9), Landscape.

**(9) Other Installed/Enabled Extensions:**

Initially tested on stock installation. Although I had installed 2 extensions before the screen recording, I have disabled them and restarted shell using <kbd>Alt</kbd>+<kbd>F12</kbd> and <kbd>r</kbd>, <kbd>Enter</kbd>. I had the same problem on fresh install. Also had the same problem on vanilla 20.04 before upgrading.

**(10) Other Notes:**

https://user-images.githubusercontent.com/1383035/124511647-50531600-dddf-11eb-86fd-79c4d8cbd6bb.mp4

**Comment by krmbzds** [comment]
I can now resize windows without any issues. There hasn't been any changes in my system (AFAIK) apart from the following `apt upgrade` since I have reported this:

```
Start-Date: 2021-07-08  16:31:11
Commandline: apt upgrade
Requested-By: kerem (1000)
Upgrade: avahi-autoipd:amd64 (0.8-5ubuntu3, 0.8-5ubuntu3.1),
         avahi-utils:amd64 (0.8-5ubuntu3, 0.8-5ubuntu3.1),
         libavahi-common-data:amd64 (0.8-5ubuntu3, 0.8-5ubuntu3.1),
         libavahi-core7:amd64 (0.8-5ubuntu3, 0.8-5ubuntu3.1),
         libdrm-nouveau2:amd64 (2.4.104-1build1, 2.4.105-3~21.04.1),
         libdrm-nouveau2:i386 (2.4.104-1build1, 2.4.105-3~21.04.1),
         [...]
         avahi-daemon:amd64 (0.8-5ubuntu3, 0.8-5ubuntu3.1),
         libdrm-common:amd64 (2.4.104-1build1, 2.4.105-3~21.04.1),
         [...]
         libavahi-common3:amd64 (0.8-5ubuntu3, 0.8-5ubuntu3.1),
         libdrm-amdgpu1:amd64 (2.4.104-1build1, 2.4.105-3~21.04.1),
         libdrm-amdgpu1:i386 (2.4.104-1build1, 2.4.105-3~21.04.1),
         libdrm-radeon1:amd64 (2.4.104-1build1, 2.4.105-3~21.04.1),
         libdrm-radeon1:i386 (2.4.104-1build1, 2.4.105-3~21.04.1),
         libdrm2:amd64 (2.4.104-1build1, 2.4.105-3~21.04.1),
         libdrm2:i386 (2.4.104-1build1, 2.4.105-3~21.04.1),
         libavahi-glib1:amd64 (0.8-5ubuntu3, 0.8-5ubuntu3.1),
         thermald:amd64 (2.4.3-1, 2.4.3-1ubuntu1),
         libavahi-client3:amd64 (0.8-5ubuntu3, 0.8-5ubuntu3.1),
         libuv1:amd64 (1.40.0-1, 1.40.0-1ubuntu0.1),
         libdrm-intel1:amd64 (2.4.104-1build1, 2.4.105-3~21.04.1),
         libdrm-intel1:i386 (2.4.104-1build1, 2.4.105-3~21.04.1),
         [...]
         End-Date: 2021-07-08  16:31:21
```

I can no longer replicate the original issue.

**Comment by jacobgkau** [comment]
Thank you for the update. I am also not able to recreate this. I'm going to close this for now, but if it starts happening again, please leave another comment and we can re-open to investigate further.
