### ISSUE TITLE
Active hint: could it be a border instead of a box?

### ISSUE THREAD

**Issue by leviport** [pop-os/shell#107]
I'm still seeing a lot of occurrences of Active Hint being drawn on top of windows, and I had a thought: if we were able to just turn it into a border, it wouldn't matter if it drew on top of a window because you could see straight through it. I'm not sure it's possible, but it might solve the problem if we can do it.

**Comment by mmstick** [comment]
Yes. A border would be 4 boxes

**Comment by leviport** [comment]
This is way better, nice work!
