### ISSUE TITLE
Pop Shell breaks Activities on Pop!_OS and Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by d0tsaint** [pop-os/shell#1072]
**(1) Issue/Bug Description:**
Shell seems to "break" Ubuntu Activities. When pop shell is enabled and I go to Activities overview by pressing Super or Clicking the top left, I can't exit out again program windows disappear. I haven't had this issue before, it happened yesterday with a fresh Ubuntu install. The only way to exit back to the desktop; is by logging out and in again or using `ALT+F2` and run `r` to restart.  

**(2) Steps to reproduce (if you know):**
Enable pop shell and go to Activities overview. 

**(3) Expected behavior:**
Cannot exit Activities and cannot see Workspaces. 

**(4) Distribution (run `cat /etc/os-release`):**
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)" 

**(5) Gnome Shell version:**
3.36.8

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
 

**(7) Where was Pop Shell installed from:**
Git clone. 

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
Single laptop monitor (Lenovo T490s)

**(9) Other Installed/Enabled Extensions:**
None.

**Comment by dotsainzed** [comment]
I can now confirm that this is not an issue on Ubuntu 21.04.

**Comment by AxcellF** [comment]
Not sure if this is helpful, but anyways:

I've experienced the same issue on a XPS 9560 and a VM (both running Ubuntu 20.04.2 LTS). Made sure to remove all other gnome extensions which didn't make any difference.

**Comment by jixbo** [comment]
I am also affected by this issue since I updated to the latest commit, to fix the VLC full screen issue #942.
I'm using Ubuntu 21.04 and wayland, and everything was working fine before with the older shell extension. What commit are you on @d0tsaint ?
I'm on the latest from master, f4894c801900f55f3fc4a8bccb36c19fae188a8c.

**Comment by jixbo** [comment]
Here are the logs of the issue:
```
gnome-shell[54799]: JS ERROR: Exception in callback for signal: trigger: too much recursion
                                             _show_skip_taskbar_windows/Workspace.prototype._isOverviewWindow@/home/jixbo/.local/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:2003:13
                                             _show_skip_taskbar_windows/Workspace.prototype._isOverviewWindow@/home/jixbo/.local/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:2004:17
                                             ... (same line many more times)
gnome-shell[54799]: Can't update stage views actor StBin is on because it needs an allocation.
gnome-shell[54799]: JS ERROR: TypeError: this._workspacesViews[index] is undefined
                                             _init/<@resource:///org/gnome/shell/ui/workspacesView.js:374:1
```
[Here is the full log file](https://github.com/pop-os/shell/files/6810079/pop_shell_issue.txt)

**Comment by Irving-Derin-Bose** [comment]
I'm having the same issue but what seems like a different failure than what @jixbo's logs show.

```
JS WARNING: [resource:///org/gnome/shell/ui/windowManager.js 1611]: reference to undefined property "show-desktop"
Window manager warning: META_CURRENT_TIME used to choose focus window; focus window may not be correct.
Object Meta.BackgroundActor (0x560558124bf0), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x56055552d8d0 ==
#0   7ffd6dbf7740 b   resource:///org/gnome/gjs/modules/core/overrides/GObject.js:571 (3dfdce9b6c40 @ 25)
#1   56055c4e84c8 i   /usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:209 (136c4822a3d0 @ 85)
#2   56055c4e8440 i   /usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:148 (136c4822a1f0 @ 12)
#3   56055c4e83b8 i   resource:///org/gnome/shell/ui/main.js:236 (3dfdce9d5e98 @ 12)
JS ERROR: Error: Argument 'instance' (type interface) may not be null
_init/GObject.Object.prototype.disconnect@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:571:24
_onDestroy@/usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:209:45
_init/<@/usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:148:44
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:236:16

Object Meta.BackgroundActor (0x560558124fc0), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x56055552d8d0 ==
#0   7ffd6dbf7740 b   resource:///org/gnome/gjs/modules/core/overrides/GObject.js:571 (3dfdce9b6c40 @ 25)
#1   56055c4e84c8 i   /usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:209 (136c4822a3d0 @ 85)
#2   56055c4e8440 i   /usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:148 (136c4822a1f0 @ 12)
#3   56055c4e83b8 i   resource:///org/gnome/shell/ui/main.js:236 (3dfdce9d5e98 @ 12)
JS ERROR: Error: Argument 'instance' (type interface) may not be null
_init/GObject.Object.prototype.disconnect@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:571:24
_onDestroy@/usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:209:45
_init/<@/usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:148:44
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:236:16


```

**Comment by Scarzer** [comment]
I'm having the same issues, but my logs seem to be showing something different that what @jixbo has.

```
JS WARNING: [resource:///org/gnome/shell/ui/windowManager.js 1611]: reference to undefined property "show-desktop"
Window manager warning: META_CURRENT_TIME used to choose focus window; focus window may not be correct.
Object Meta.BackgroundActor (0x560558124bf0), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x56055552d8d0 ==
#0   7ffd6dbf7740 b   resource:///org/gnome/gjs/modules/core/overrides/GObject.js:571 (3dfdce9b6c40 @ 25)
#1   56055c4e84c8 i   /usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:209 (136c4822a3d0 @ 85)
#2   56055c4e8440 i   /usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:148 (136c4822a1f0 @ 12)
#3   56055c4e83b8 i   resource:///org/gnome/shell/ui/main.js:236 (3dfdce9d5e98 @ 12)
JS ERROR: Error: Argument 'instance' (type interface) may not be null
_init/GObject.Object.prototype.disconnect@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:571:24
_onDestroy@/usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:209:45
_init/<@/usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:148:44
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:236:16

Object Meta.BackgroundActor (0x560558124fc0), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x56055552d8d0 ==
#0   7ffd6dbf7740 b   resource:///org/gnome/gjs/modules/core/overrides/GObject.js:571 (3dfdce9b6c40 @ 25)
#1   56055c4e84c8 i   /usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:209 (136c4822a3d0 @ 85)
#2   56055c4e8440 i   /usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:148 (136c4822a1f0 @ 12)
#3   56055c4e83b8 i   resource:///org/gnome/shell/ui/main.js:236 (3dfdce9d5e98 @ 12)
JS ERROR: Error: Argument 'instance' (type interface) may not be null
_init/GObject.Object.prototype.disconnect@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:571:24
_onDestroy@/usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:209:45
_init/<@/usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:148:44
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:236:16

```

**Comment by jacobgkau** [comment]
I am seeing this on Pop!_OS and Ubuntu 20.04. I believe the relevant portion of the logs is the section that appears at the time Activities is opened:

```
Jul 13 11:13:40 pop-os gnome-shell[2512]: JS ERROR: TypeError: meta_window.get_wm_class is not a function
                                          skiptaskbar_shall_hide@/usr/share/gnome-shell/extensions/pop-shell@system76.com/config.js:85:35
                                          _show_skip_taskbar_windows/Workspace.prototype._isOverviewWindow@/usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:2002:36
                                          _init@resource:///org/gnome/shell/ui/workspace.js:1173:22
                                          _updateWorkspaces@resource:///org/gnome/shell/ui/workspacesView.js:232:29
                                          _init@resource:///org/gnome/shell/ui/workspacesView.js:91:14
                                          _updateWorkspacesViews@resource:///org/gnome/shell/ui/workspacesView.js:682:24
                                          show@resource:///org/gnome/shell/ui/workspacesView.js:612:14
                                          show@resource:///org/gnome/shell/ui/viewSelector.js:276:33
                                          _animateVisible@resource:///org/gnome/shell/ui/overview.js:580:27
                                          show@resource:///org/gnome/shell/ui/overview.js:566:14
                                          toggle@resource:///org/gnome/shell/ui/overview.js:689:18
                                          vfunc_event@resource:///org/gnome/shell/ui/panel.js:482:31
```

`meta_window.get_wm_class` is called in code that was added in https://github.com/pop-os/shell/pull/1069/commits/dc0e306962064b93f00cc55a50ba9901971c4c92, the final commit in https://github.com/pop-os/shell/pull/1069.

**Comment by jacobgkau** [comment]
@jixbo The issue you're experiencing seems like a different problem since you're on 21.04 and Wayland, although your "full log file" is only a snippet, and I don't have enough information to recreate it. I'm not seeing the issue on Ubuntu 21.04 with Wayland after installing VLC (which you mentioned) and Sleek, which is a "skip taskbar window." Can you confirm if [this branch](https://github.com/pop-os/shell/pull/1080) stops the issue on your machine? Any information about other applications and shell extensions you have running might also be helpful.

**Comment by jixbo** [comment]
@jacobgkau thanks for the fast response.

Here you can find the [full gnome-shell logs](https://github.com/pop-os/shell/files/6811637/shell_error.txt) of today. The issue happened a few times, last one at 21.50, just after the laptop came back from suspension.
VLC is not related to this issue at all, but  #942 was the reason I updated to the latest commit, but that problem is now gone.

I'm getting this issue with "Activities" with no special application, after using the computer for a long time. It does not happen the first few times "Activities" gets triggered. It can happen triggering activities either with the mouse gesture on the corner, or the meta key. Today I was using telegram, google-chrome, visual studio and spotify.

I'll test the latest fix and report back, thank you.

**Comment by jtmackoy** [comment]
Stumbled upon this issue when I encountered this problem.  For anyone else, I've found that simply restarting gnome via `ALT + F2` and entering `r` then pressing Enter will get me out of the Activities overview with no ill effects.

**Comment by d0tsaint** [comment]
@jtmackoy That's my solution too. Unfortunately you can't restart shell with `ALT + F2`, `r` if you are running Wayland.

**Comment by jtmackoy** [comment]
New info - just discovered that if I uninstall (`make uninstall`) then [checkout commit 3873fc5bbe84c392d1ed424760dc6134aafcbced](https://github.com/pop-os/shell/tree/3873fc5bbe84c392d1ed424760dc6134aafcbced) and reinstall (`make local-install`), the problem goes away.

**Comment by jacobgkau** [comment]
> New info - just discovered that if I uninstall (`make uninstall`) then [checkout commit 3873fc5bbe84c392d1ed424760dc6134aafcbced](https://github.com/pop-os/shell/tree/3873fc5bbe84c392d1ed424760dc6134aafcbced) and reinstall (`make local-install`), the problem goes away.

Yes, that commit is before https://github.com/pop-os/shell/commit/dc0e306962064b93f00cc55a50ba9901971c4c92, which is the one that added the problematic function call.

**Comment by jtmackoy** [comment]
Apologies @jacobgkau - missed that detail in [your earlier comment](https://github.com/pop-os/shell/issues/1072#issuecomment-879274423).

**Comment by jixbo** [comment]
After the whole day using the latest fix from #1080 (latest version on master branch) , the problem didn't reoccur.
I'm pretty confident the issue is fixed, because it happened several times yesterday with a similar usage.

Thanks everyone, specially @jacobgkau for the quick support.

**Comment by jacobgkau** [comment]
@jixbo Glad to hear the 21.04 is fixed after that PR. This issue remains open for the 20.04 issue, which is separate.

**Comment by cb3inco** [comment]
Just ran into this issue also - ``Alt - F2 R`` seems to be the only solution at the moment:

Darter Pro 6
Pop!_OS 20.04
Gnome: 3.36.8
Windows System: X11

**Comment by redromnon** [comment]
Encountering the same exact problem as explained by @d0tsaint at the beginning. Hope it gets resolved soon...

**Comment by redromnon** [comment]
Happened right after a system update...

**Comment by redromnon** [comment]
Encountered this issue right after a system update...

**Comment by romen** [comment]
For the record, this workaround for 20.04 seems to be working: 
https://www.reddit.com/r/pop_os/comments/okfdvh/cant_get_out_of_activates_after_update/h58q94r/?utm_source=share&utm_medium=web2x&context=3

**Comment by jacobgkau** [comment]
A fix for this (https://github.com/pop-os/shell/pull/1085) has been merged. It will take some time to build and get released from proposed, but it should be available within a few hours.

**Comment by jacobgkau** [comment]
The fix is now published, 20.04 users can apply all updates and then restart GNOME Shell or reboot to get the fix.

**Comment by AlexandreCamillo** [comment]
> The fix is now published, 20.04 users can apply all updates and then restart GNOME Shell or reboot to get the fix. (To install updates without the Activities menu, use the Pop Shell launcher with `Super`+`/` to open a terminal or the Pop!_Shop.)

I've just done it and fixed the problem!! Thanks!

**Comment by romen** [comment]
@jacobgkau it seems there might be some minor issue pending, even after the updated package: https://chat.pop-os.org/pop-os/pl/poxuysakzjr5be5ypmsk4xtx5y

**Comment by redromnon** [comment]
> The fix is now published, 20.04 users can apply all updates and then restart GNOME Shell or reboot to get the fix. (To install updates without the Activities menu, use the Pop Shell launcher with `Super`+`/` to open a terminal or the Pop!_Shop.)

Finally! Just installed the latest Pop Shell update, works flawlessly now!

**Comment by zhfish** [comment]
good job

**Comment by e3b0c442** [comment]
Unfortunately this is not 100% resolved for me. I'm still seeing instances where the Activities menu is unresponsive during/after opening Battle.net client in Wine via Lutris. Disabling the "Show Minimize to Tray Windows" setting seems to be a usable workaround for now.

**Comment by vhakulinen** [comment]
This is still happening on my system after I start and login to steam (popos 20.04, all updates installed).

**Comment by danilopinotti** [comment]
> This is still happening on my system after I start and login to steam (popos 20.04, all updates installed).
> 
> Doing the `Alt + F2` and `r` command couple of times seems to "fix" it.

It stills happens here too...
Pop!_OS Shell Version: 1.1.0~1627383380~20.04~475b49d (updated today)

**Comment by vhakulinen** [comment]
FWIW, in the past few days, hasn't been happening that often anymore. Seems to be more random now.
