### ISSUE TITLE
"Floating Window Exceptions" doesn't open

### ISSUE THREAD

**Issue by lgaboury** [pop-os/shell#1073]
**(1) Issue/Bug Description:**
When selecting "Floating Window Exceptions" from pop shell extension menu, nothing happens.  The following appears in journalctl every time I take the action:

Jul 09 08:32:33 asus-laptop gjs[1173]: JS ERROR: TypeError: DEFAULT_RULES is undefined App@/home/lgaboury/.local/share/gnome-shell/extensions/pop-shell@system76.com/floating_exceptions/main.js:153:29 main@/home/lgaboury/.local/share/gnome-shell/extensions/pop-shell@system76.com/floating_exceptions/main.js:213:5 @/home/lgaboury/.local/share/gnome-shell/extensions/pop-shell@system76.com/floating_exceptions/main.js:216:1 Jul 09 08:32:33 asus-laptop gjs[1173]: Script /home/lgaboury/.local/share/gnome-shell/extensions/pop-shell@system76.com/floating_exceptions/main.js threw an exception.

This occurs whether I run gnome 40 on wayland or Xorg.

**(2) Steps to reproduce (if you know):**
Install pop shell extension from Arch AUR https://aur.archlinux.org/gnome-shell-extension-pop-shell-git.git

**(3) Expected behavior:**
The "Floating Window Exceptions" window should be displayed.

**(4) Distribution (run `cat /etc/os-release`):**
 NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux

**(5) Gnome Shell version:**

40.2.0

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**(7) Where was Pop Shell installed from:**

https://aur.archlinux.org/gnome-shell-extension-pop-shell-git.git

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

Laptop monitor (Asus Zenbook UX533)

**(9) Other Installed/Enabled Extensions:**

Arch Linux Updates Indicator
Native Window Placement

**(10) Other Notes:**

**Comment by jacobgkau** [comment]
Confirmed on Pop!_OS 20.10 (GNOME 3.38) on version `42ff8d4` (still in proposed.) I'm guessing this is a regression from dc0e306962064b93f00cc55a50ba9901971c4c92.

**Comment by mmstick** [comment]
This would indicate that you're missing the `config.js` file that should be located in `pop-shell@system76.com/floating_exceptions/`. This file is technically a symlink or copy of `pop-shell@system76.com/config.js`.

**Comment by lgaboury** [comment]
I have applied the recommended fix to my local copy of /usr/share/gnome-shell/extensions/pop-shell@system76.com/floating_exceptions/main.js and the Floating Window Exceptions feature is now working properly.  Thank you for the amazing response.
