### ISSUE TITLE
Launcher search results are sometimes not great

### ISSUE THREAD

**Issue by leviport** [pop-os/shell#108]
A good example can be seen when searching for "Files", whether Nautilus is open or not. I would expect Nautilus to be the top result, not Audacity.
![Screenshot from 2020-03-24 10-30-06](https://user-images.githubusercontent.com/13512097/77451667-976bf200-6dba-11ea-9406-225bab8baa0f.png)

**Comment by brs17** [comment]
I would suggest comparing this with the GNOME Activities search.

Another example I see is typing the letter `f`:
Activities shows Firefox, Files, USB Flasher, Fonts, and archive manager (4/5 have an f in them)
Launcher shows what appears to be an alphabetical list of all applications starting at A (About, Advanced Network config, archive manager, sound editor (Audacity), bluetooth,etc)
