### ISSUE TITLE
All windows stop responding after screen lock/suspend

### ISSUE THREAD

**Issue by talhajunaidd** [pop-os/shell#1081]
**(1) Bug Description:**
All windows stop responding after screen lock/suspend

**(2) Steps to reproduce (if you know):**

- Open Some window e.g settings or Brave browser as shown in video
- Lock the screen, and wait for it to go blank
- Unlock the screen, 
- Try to interact with the window.

**(3) Expected behavior:**
Windows should response, 

**(4) Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**
```
GNOME Shell 3.38.4
```

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1625501479~21.04~b33c5e2
  Candidate: 1.1.0~1625501479~21.04~b33c5e2
  Version table:
 *** 1.1.0~1625501479~21.04~b33c5e2 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main i386 Packages
        100 /var/lib/dpkg/status

```

**(7) Where was Pop Shell installed from:**
From pop os repositories

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
Monier 1: 1080p,
Moniter 2:  1080p

**(9) Other Installed/Enabled Extensions:**
Output of `gsettings get org.gnome.shell enabled-extensions`
```
'alt-tab-raise-first-window@system76.com', 'always-show-workspaces@system76.com', 'batteryiconfix@kylecorry31.github.io', 'pop-shell@system76.com', 'pop-shop-details@system76.com', 'system76-power@system76.com', 'gnomeGlobalAppMenu@lestcape', 'notes@maestroschan.fr', 'clipboard-indicator@tudmotu.com', 'gsconnect@andyholmes.github.io', 'InternetSpeedMeter@alshakib.dev', 'user-theme@gnome-shell-extensions.gcampax.github.com', 'ding@rastersoft.com', 'gnome-shell-audio-output-switcher@kgaut', 'night-light-slider.timur@linux.com', 'sound-output-device-chooser@kgshank.net', 'ubuntu-appindicators@ubuntu.com', 'ubuntu-dock@ubuntu.com', 'MultiClock@mibus.org', 'pop-cosmic@system76.com', 'google_calculator@awamper.gmail.com', 'NetMonitor@zdyb.tk', 'netspeed@hedayaty.gmail.com'
```

**(10) Other Notes:**

https://user-images.githubusercontent.com/6547611/125446318-24160a42-0206-4730-ba64-a4d8f55210f9.mp4

**Comment by bflanagin** [comment]
I'm not seeing the issue on my test hardware. @talhajunaidd mind giving us the make and model of the hardware in your system? We should only need the CPU/GPU information but any other hardware info you can provide would help. I'd also suggest turning off any manually installed extensions as they might have something to do with the issue as well. (though unlikely)

**Comment by talhajunaidd** [comment]
Thank you for suggestion.
Disabling and re-enabling third-party extensions did the trick,.
