### ISSUE TITLE
Constant Freezing of GNOME Shell in activities panel after system update

### ISSUE THREAD

**Issue by prikmm** [pop-os/shell#1092]
**(1) Issue/Bug Description:**
I recently installed Pop OS!. There were no bugs or glitchs both,  at the time of installation and just after completing the user registration. But, after I performed a system upgrade to get the latest packages, I have been experiencing freezing everytime I open the activities panel. I am able to click on apps, get all the apps present but thats all. The launched apps are not shown, the system goes in a freeze state and I get locked in the activites panel. I have to do <kbd>Alt</kbd> + <kbd>F2</kbd>, then press <kbd>r</kbd>, to perform a soft refresh. Only after this am I able to get out of the activites panel. 

(LOGS are at the bottom)

**(2) Steps to reproduce (if you know):**
Opening the activites panel, using top hot left corner, <kbd>super</kbd>, or activities icon in the upper left corner

**(3) Expected behavior:**
No Freezing of gnome shell when opening activities panel

**(4) Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
**(5) Gnome Shell version:**
GNOME Shell 3.36.7

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1626203716~20.04~021c931
  Candidate: 1.1.0~1626357201~20.04~c1f2ea4
  Version table:
     1.1.0~1626357201~20.04~c1f2ea4 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
 *** 1.1.0~1626203716~20.04~021c931 100
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**
Pre-built, downloaded the nvidia iso

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
Laptop - 1920x1080

**(9) Other Installed/Enabled Extensions:**
```
System Wide:
alt-tab-raise-first-window@system76.com
ding@rastersoft.com     
pop-shop-details@system76.com  
ubuntu-appindicators@ubuntu.com
always-show-workspaces@system76.com      
pop-shell@system76.com  
system76-power@system76.com

Locally installed:
gsconnect@andyholmes.github.io
hide-activities-button@gnome-shell-extensions.bookmarkd.xyz  
nohotcorner@azuri.free.fr  
wsmatrix@martin.zurowietz.de (Side Note: I found on internet that windows-grid is not supported for GNOME 3.x, so I tried this solution but no results)
```

**(10) Other Notes:**
I manually went into activities panel and performed soft refresh to get the logs. I found this error:
```
LOGS:
Jul 17 19:07:00 pop-os gnome-shell[2800]: JS ERROR: TypeError: meta_window.get_wm_class is not a function#012skiptaskbar_shall_hide@/usr/share/gnome-shell/extensions/pop-shell@system76.com/config.js:85:35#012_show_skip_taskbar_windows/Workspace.prototype._isOverviewWindow@/usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:2003:36#012_init@resource:///org/gnome/shell/ui/workspace.js:1173:22#012_updateWorkspaces@resource:///org/gnome/shell/ui/workspacesView.js:232:29#012_init@resource:///org/gnome/shell/ui/workspacesView.js:91:14#012_updateWorkspacesViews@resource:///org/gnome/shell/ui/workspacesView.js:682:24#012show@resource:///org/gnome/shell/ui/workspacesView.js:612:14#012show@resource:///org/gnome/shell/ui/viewSelector.js:276:33#012_animateVisible@resource:///org/gnome/shell/ui/overview.js:580:27#012show@resource:///org/gnome/shell/ui/overview.js:566:14#012toggle@resource:///org/gnome/shell/ui/overview.js:689:18#012_initializeUI/<@resource:///org/gnome/shell/ui/main.js:223:22

** I performed some activities in the activites panel in this duration but there were not registered, from the log I can see that there was a system freeze till the time I performed  a soft refresh**

**The below logs were generated after the soft refresh:**

Jul 17 19:07:23 pop-os gnome-shell[2800]: Window manager warning: META_CURRENT_TIME used to choose focus window; focus window may not be correct.
Jul 17 19:07:23 pop-os /usr/lib/gdm3/gdm-x-session[1700]: (II) modeset(0): EDID vendor "AUO", prod id 24813
Jul 17 19:07:23 pop-os /usr/lib/gdm3/gdm-x-session[1700]: (II) modeset(0): Printing DDC gathered Modelines:
Jul 17 19:07:23 pop-os /usr/lib/gdm3/gdm-x-session[1700]: (II) modeset(0): Modeline "1920x1080"x0.0  141.00  1920 2028 2076 2086  1080 1090 1100 1126 -hsync -vsync (67.6 kHz eP)
Jul 17 19:07:23 pop-os /usr/lib/gdm3/gdm-x-session[1700]: (II) modeset(0): EDID vendor "AUO", prod id 24813
Jul 17 19:07:23 pop-os /usr/lib/gdm3/gdm-x-session[1700]: (II) modeset(0): Printing DDC gathered Modelines:
Jul 17 19:07:23 pop-os /usr/lib/gdm3/gdm-x-session[1700]: (II) modeset(0): Modeline "1920x1080"x0.0  141.00  1920 2028 2076 2086  1080 1090 1100 1126 -hsync -vsync (67.6 kHz eP)
Jul 17 19:07:23 pop-os /usr/lib/gdm3/gdm-x-session[1700]: (--) NVIDIA(GPU-0): DFP-0: disconnected
Jul 17 19:07:23 pop-os /usr/lib/gdm3/gdm-x-session[1700]: (--) NVIDIA(GPU-0): DFP-0: Internal TMDS
Jul 17 19:07:23 pop-os /usr/lib/gdm3/gdm-x-session[1700]: (--) NVIDIA(GPU-0): DFP-0: 165.0 MHz maximum pixel clock
Jul 17 19:07:23 pop-os /usr/lib/gdm3/gdm-x-session[1700]: (--) NVIDIA(GPU-0):
Jul 17 19:07:23 pop-os gsd-media-keys[2984]: Failed to grab accelerators: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.gnome.Shell” on object at path /org/gnome/Shell
Jul 17 19:07:23 pop-os dbus-daemon[1645]: [session uid=1000 pid=1645] Activating service name='org.gnome.ChromeGnomeShell' requested by ':1.1675' (uid=1000 pid=200930 comm="/usr/bin/python3 /usr/bin/chrome-gnome-shell chrom" label="unconfined")
Jul 17 19:07:24 pop-os dbus-daemon[1645]: [session uid=1000 pid=1645] Successfully activated service 'org.gnome.ChromeGnomeShell'
```

I have also found similar threads on [Manjaro](https://forum.manjaro.org/t/activities-in-gnome-shell-broken-with-latest-stable/63708) and [Endeavor](https://forum.endeavouros.com/t/gnome-desktop-gets-stuck-in-activities-overview/13176) forums. There, a few have said that extensions are the problem (majority, dash to dock) but I have not even installed dash to dock, and have tried after disabling all other ones, but the problem still persists. 

Kindly help me, I don't want to reinstall the the system again.

**Comment by Nuxmin** [comment]
Hey there!

I think it's bugged, I was having the same issue.

I solved it using this solution:

https://www.reddit.com/r/pop_os/comments/okfdvh/comment/h58q94r/?utm_medium=android_app&utm_source=share&context=3

I hope it works for you too.

:)

**Comment by prikmm** [comment]
> Hey there!
> 
> I think it's bugged, I was having the same issue.
> 
> I solved it using this solution:
> 
> https://www.reddit.com/r/pop_os/comments/okfdvh/comment/h58q94r/?utm_medium=android_app&utm_source=share&context=3
> 
> I hope it works for you too.
> 
> :)

Yup!! Its working perfectly after this. Thank you so much!!
