### ISSUE TITLE
Alt-Tab shows duplicate menu of Android Studio when emulator is running

### ISSUE THREAD

**Issue by ydhnwb** [pop-os/shell#1094]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Android Studio 4.2.2 flatpack version

**Issue/Bug Description:**
When using ALT+TAB to change between apps, the Android Studio shows exactly the same menu (duplicated). As far as I know, it only happens on android studio app. See this pic.  

![IMG_20210717_052426](https://user-images.githubusercontent.com/26734262/126014771-ee2e2a6a-b219-4f50-8e50-04937623fea0.jpg)

The other:
![IMG_20210717_052429](https://user-images.githubusercontent.com/26734262/126014889-6f684767-f06a-4a9c-bd62-cc6198bfc217.jpg)

**Steps to reproduce (if you know):**

**Expected behavior:**
It should only one Android Studio menu only with multiple window.

**Other Notes:**

**Comment by jacobgkau** [comment]
The Emulator window and the Emulator icons window do not appear to have a WM_CLASS to except. The icons window also has no WM_NAME, although it does have a _NET_WM_NAME.

**Comment by maplehobo** [comment]
Same thing happens on IntelliJ IDEA when launching a Java game to test/debug.
