### ISSUE TITLE
Ctrl + Super + Up was assigned to multiple things

### ISSUE THREAD

**Issue by leviport** [pop-os/shell#11]
I know this is still early, but I discovered the cause of my biggest pain point with pop-shell so far. Somehow Ctrl + Super + Up was assigned to two actions: switch workspace up and restore window. Once I manually reset that hotkey, everything was much better. I did toggle the extension a few times, so maybe that's where the issue came from. I'm also running 20.04, in case that is relevant.

**Comment by leviport** [comment]
It appears this has gone away, so I'll close it for now.

**Comment by leviport** [comment]
This issue has returned, only now I cannot even move windows while in window management mode. The arrow keys send commands to the underlying windows instead.

**Comment by brs17** [comment]
I am having this issue with Ctrl + Super + Down being mapped to multiple things. It looks like it is currently mapped to "Restore Window" so I am unable to move workspaces.

**Comment by WatchMkr** [comment]
This should be fixed in 20.04.
