### ISSUE TITLE
Active hint remains drawn after hitting Super+D or minimizing all windows

### ISSUE THREAD

**Issue by leviport** [pop-os/shell#110]
If I hit Super+D or individually minimize all open windows on a workspace, I can see the active hint still drawn over the desktop. This happens in both tiling and floating mode.
![active-hint](https://user-images.githubusercontent.com/13512097/77460579-e3bd2f00-6dc6-11ea-9de4-271f54a37902.png)

**Comment by mmstick** [comment]
So watch for minimize event, and hide the active hint when minimized

**Comment by mrsnl** [comment]
Still an issue in 20.04 official release.

**Comment by leviport** [comment]
I'm seeing it as well

**Comment by jmmaranan** [comment]
@mmstick fixed on #487
