### ISSUE TITLE
[Feature Request] "Swap Focused with Main Window" Functionality

### ISSUE THREAD

**Issue by jbernh** [pop-os/shell#1101]
This may not be popular enough of an idea to justify, but the ability to "swap" the focused window with the main window, similar to XMonad's or Amethyst's (MacOS) handling, could be very helpful for window management.

**Comment by leviport** [comment]
With pop-shell, there isn't exactly a "main" window, but swapping is currently possible in window management mode. First, enter window management mode with Super + Enter. Then, hold Ctrl and use your arrows to select the window you want to swap with. Then hit Enter to make the swap. Is that along the lines of what you had in mind?

**Comment by jbernh** [comment]
Gotcha. I guess this is mostly the same functionality as what I've described. I can close this issue. Thanks!
