### ISSUE TITLE
b1b73f6 breaks extension Current screen only on window switcher

### ISSUE THREAD

**Issue by slmb3** [pop-os/shell#1103]
**(1) Issue/Bug Description:**
b1b73f6 and newer breaks extension Current screen only on window switcher
90b1ac7 and older does not break extension Current screen only on window switcher

**(2) Steps to reproduce (if you know):**
Install https://extensions.gnome.org/extension/1437/current-screen-only-for-alternate-tab/
Checkout 90b1ac7 and `make local-install`, and observe that Current screen only on window switcher extension works fine
Checkout b1b73f6 and `make local-install`, and observe that Current screen only on window switcher extension no longer works

**(3) Expected behavior:**
pop-os/shell does not break Current screen only on window switcher extension

**(4) Distribution (run `cat /etc/os-release`):**
Tested arch and ubuntu

**(5) Gnome Shell version:**
Tested on both gnome shell 40 and 3.36

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
b1b73f6

**(7) Where was Pop Shell installed from:**
`make local-install`

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
2 x 1080p

**(9) Other Installed/Enabled Extensions:**
None

**(10) Other Notes:**

**Comment by jmmaranan** [comment]
The Current screen switcher works in 9616931a2f8da33ff60d6332cbb1e4036c9ae2b3

**Comment by slmb3** [comment]
It didn't work for me. Any ideas how to debug?

**Comment by jmmaranan** [comment]
> It didn't work for me. Any ideas how to debug?

Yeah - you can open up a terminal and then use this:
`journalctl /usr/bin/gnome-shell` or if you have checked out the source `make debug`, CTRL + C to exit

**Comment by slmb3** [comment]
I'm using X11 window system btw. Here's the journal:
```
gnome-shell[1003]: Window manager warning: META_CURRENT_TIME used to choose focus window; focus window may not be correct.
gnome-shell[1003]: clutter_actor_iter_next: assertion 'ri->age == ri->root->priv->age' failed
gnome-shell[1003]: ATK Bridge is disabled but a11y has already been enabled.
gnome-shell[1003]: Skipping parental controls support as it’s disabled
gnome-shell[1003]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
gnome-shell[1003]: Will monitor session 3
gnome-shell[1003]: Telepathy is not available, chat integration will be disabled.
gnome-shell[1003]: Failed to create file /run/user/1000/gnome-shell-disable-extensions: Error opening file “/run/user/1000/gnome-shell-disable-extensions”: File exists
gnome-shell[1003]: found plugin at /home/me/.local/share/pop-shell/launcher//calc/meta.json
gnome-shell[1003]: found plugin: Calculator
gnome-shell[1003]: found plugin at /home/me/.local/share/pop-shell/launcher//files/meta.json
gnome-shell[1003]: found plugin: File Navigation
gnome-shell[1003]: found plugin at /home/me/.local/share/pop-shell/launcher//pulse/meta.json
gnome-shell[1003]: found plugin: PulseAudio Volume Control
gnome-shell[1003]: found plugin at /home/me/.local/share/pop-shell/launcher//recent/meta.json
gnome-shell[1003]: found plugin: Recent Documents
gnome-shell[1003]: found plugin at /home/me/.local/share/pop-shell/launcher//terminal/meta.json
gnome-shell[1003]: found plugin: Terminal Commands
gnome-shell[1003]: found plugin at /home/me/.local/share/pop-shell/launcher//web/meta.json
gnome-shell[1003]: found plugin: Web Search
gnome-shell[1003]: Error: GSettings schema org.gnome.shell.extensions.pop-cosmic not found
gnome-shell[1003]: JS ERROR: Could not load extension .git: Error: Missing metadata.json
                                           createExtensionObject@resource:///org/gnome/shell/ui/extensionSystem.js:283:19
                                           _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:583:34
                                           collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:28
                                           _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:567:19
                                           _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:597:18
                                           _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:628:18
                                           init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
                                           _initializeUI@resource:///org/gnome/shell/ui/main.js:269:22
                                           start@resource:///org/gnome/shell/ui/main.js:166:5
                                           @<main>:1:47
gnome-shell[1003]: loading user theme: /usr/share/themes/Yaru/gnome-shell/gnome-shell.css
gnome-shell[1003]: GNOME Shell started at <time>
gnome-shell[1003]: Registering session with GDM
gnome-shell[1003]: Can't update stage views actor MetaWindowGroup is on because it needs an allocation.
gnome-shell[1003]: Can't update stage views actor MetaWindowActorX11 is on because it needs an allocation.
gnome-shell[1003]: Can't update stage views actor MetaSurfaceActorX11 is on because it needs an allocation.
```

**Comment by slmb3** [comment]
I figured out part of the issue, and probably explains why you thought it was working when I didn't.

It was only due `show-skip-taskbar` getting enabled by default https://github.com/pop-os/shell/commit/b1b73f6789be7ee48cbe43613b20670a6ff58534#diff-c79e29b3b739c2e6fef975daa7ff7d7d217e0c3eac22d9beef5b7acff73076ed

Any idea is `show-skip-taskbar` enabled breaking `Current screen only on window switcher` functionality expected behavior? If not I can open a separate issue. 

For now I fix with `gsettings set org.gnome.shell.extensions.pop-shell show-skip-taskbar false`

**Comment by jmmaranan** [comment]
@slmb3 - looking at that extension's source code it is also modifying the App Switcher's default functionality. Skip taskbar enabled does the same thing. You can also disable `Skip taskbar` from Extensions > Pop Shell > Preferences, it is the `Show Minimized to Tray Windows` toggle.

**Comment by slmb3** [comment]
thanks!
