### ISSUE TITLE
Tilix in quake mode is being tiled like other windows

### ISSUE THREAD

**Issue by neodc** [pop-os/shell#1104]
**(1) Issue/Bug Description:**

Since I updated to the last version of Pop-shell (I don't do regular update so I don't know in which version it was introduce, sorry) Tilix in quake mode is being tiled like other windows, before tilix normal windows where tiled but not the quake ones.

While searching if the issue was already know I found this one that look like it but for an other application : #1034 but in the case I can't just add it to the exception because I can't differentiate the quake windows from the normal ones.

**(2) Steps to reproduce (if you know):**

1. Install tilix from apt repository
2. Enable tiling in pop-shell
3. Start Tilix in quake mode `tilix -q`

**(3) Expected behavior:**

Tilix should be shown above other windows from the top of the screen, like the classic quake-terminal.

**(4) Distribution (run `cat /etc/os-release`):**
 
```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**

3.36.8

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installé : 1.1.0~1626728027~20.04~9616931
  Candidat : 1.1.0~1626728027~20.04~9616931
 Table de version :
 *** 1.1.0~1626728027~20.04~9616931 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

Bundled with Pop!_OS

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

From left to right (all are horizontal) : 

* 1920x1080  @ 100%
* 3840x2160 @ 150%
* 1920x1200 @ 100%

**(9) Other Installed/Enabled Extensions:**

None

**(10) Other Notes:**

N/A

**Comment by neodc** [comment]
I also see that other element are tiled that where not before: Splash screen of Jetbrains application (PhpStorm and Datagrip in my case), screen recording indication of Teams for example.

Was there a global change of what should and shouldn't be tiled? All those case where correctly not tiled before the update =(

**Comment by jmmaranan** [comment]
I thought it is the skip taskbar issue but must be something else.

**Comment by neodc** [comment]
Do you want me to test anything? Can I give you more info?

**Comment by jmmaranan** [comment]
I'll check if how you can add it to Exceptions without making a code change. Though I think it should be added on the defaults. Did you try to open Tilix as only window and doing the floating exceptions?

**Comment by neodc** [comment]
That's what I do currently but then even normal Tilix windows are not tiled, not only the one in quake mode

**Comment by jmmaranan** [comment]
@neodc - yeah I think the issue was introduced when pop-shell started handling windows with skip-taskbar state (this state is present on some applications that has the minimized to tray option like Sleek). I looked at how to toggle it along with that option the other day and not successful.
