### ISSUE TITLE
Void linux Makefile problem

### ISSUE THREAD

**Issue by Sbatushe** [pop-os/shell#1107]
**(1) Issue/Bug Description:**
During the install on a Void linux system, the makefile fails to compile. i managed to find a workaround [here](https://www.reddit.com/r/voidlinux/comments/oq148a/installing_popshell/
). The problem is inside the Makefile, on rows 5-7, where it checks if `XDG_DATA_HOME` is empty, which at least on my machine it is. Because of that the program is stored on `$(HOME)/.local/share`, but it should be stored on `/usr/share/gnome-shell/extensions`, which is the path of other default extensions.
**(2) Steps to reproduce (if you know):**
`doas xbps-install make git pnpm`
`doas npm install -g typescript`
`git clone https://github.com/pop-os/shell`
`cd shell`
`make local-install`

**(3) Expected behavior:**
the makefile should install directly on the right directory: `/usr/share/gnome-shell/extensions`

**(4) Distribution (run `cat /etc/os-release`):**
NAME="void"
ID="void"
DISTRIB_ID="void"
PRETTY_NAME="void"

**(5) Gnome Shell version:**
40.2

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**(7) Where was Pop Shell installed from:**
compiled

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1280x800

**(9) Other Installed/Enabled Extensions:**
none

**(10) Other Notes:**

**Comment by mmstick** [comment]
local-install is for installs to your home folder. You'd want to use the regular install for system-wide installs.
