### ISSUE TITLE
[FEATURE REQUEST] Currency Converter in launcher

### ISSUE THREAD

**Issue by addy3494** [pop-os/shell#1108]
Feature Request - An in built currency converter in launcher would add more usable functionality. We can still use the launcher to google the results. Just a thought that it would be awesome to have this inbuilt.

Please consider the possibility.

Cheers!

**Comment by jacobgkau** [comment]
With the new launcher using Qalculate! (`qalc`) for the calculator plugin, currency conversions can be performed like this:

```
= 1 dollar to euros
```

or

```
=$1 to €
```

To get this working, I did have to enter `qalc` once in a terminal and attempt a conversion in order to make the exchange rates update.

**Comment by mmstick** [comment]
`=1 USD to EUR` also works.
