### ISSUE TITLE
Regression on changing orientation with a 3-window layout

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#111]
*To reproduce*:

1. Have 1 window on the left side of screen, 2 windows on the right.
2. Focus on the left window, and change orientation with `Super+O`

End result is a broken layout:

![Screenshot from 2020-03-24 14-39-23](https://user-images.githubusercontent.com/39338488/77464272-4d483800-6ddd-11ea-849b-0ad5bbc714d9.png)
![Screenshot from 2020-03-24 14-39-29](https://user-images.githubusercontent.com/39338488/77464277-4f11fb80-6ddd-11ea-850b-2510b1a9134e.png)

**Comment by mmstick** [comment]
Issue already known. I've partially fixed it in a WIP branch, but it's not done yet. It will be done later today
