### ISSUE TITLE
Handle display addition/removal events in auto-tile mode

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/shell#112]
When a monitor is unplugged, move each window to a separate workspace and put the remaining display in the Activities overview so the user can see where their windows went.

When a monitor is plugged in, leave windows where they are and don't go into the Activities overview.

**Comment by WatchMkr** [comment]
Additional note from @jackpot51 

If you have multiple workspaces then a new workspace would have to be created for each workspace with windows on the unplugged monitor.

Just something to make sure to test

**Comment by leviport** [comment]
To clarify, when you say we'll move each window to a separate workspace, is that only on the display that gets removed, like in this doodle?
![IMG_20200325_104702](https://user-images.githubusercontent.com/13512097/77563191-8ee0ed80-6e86-11ea-9e84-77c1c5b04d6f.jpg)

Would it be better to move everything that was on monitor B to its own workspace and preserve the tree structure? So everything in that doodle that was on monitor B would get moved to a new workspace below the current workspace and (hopefully) remain tiled the way it was before.

We may have to check for resolution differences, of course. A highly populated unscaled 4K or Ultrawide display simply can't be transferred to a 1080 display. If the displays are the same (or close?) it would be nice not to have to move every window back into one workspace and rearrange it to the way it was before the monitor removal. This might enter stretch-goal territory, but I think it would be a really neat feature.

**Comment by mmstick** [comment]
My intention was to update the location of the tree to a new workspace + monitor, and then adjusting the tree if the monitor is a different resolution.

**Comment by leviport** [comment]
Ah ok, we're probably all on the same page then. I just saw a potentially different interpretation and wanted to make sure I got it right.

**Comment by mmstick** [comment]
It's possible that we could split the tree to multiple workspace if there's a drastic difference in size, such as going from 4K to 2K, or to 1K.

**Comment by leviport** [comment]
That sounds extremely awesome. If one 100% scaled 4K can turn into 4x 1080 workspaces when the 4K is removed, I'll have to buy myself a big 4K monitor for myself.

**Comment by mmstick** [comment]
Displays are being handled on remove now
