### ISSUE TITLE
20.04 Activies crash with Proton games

### ISSUE THREAD

**Issue by SavexG** [pop-os/shell#1123]
Hello 
Im on popOS! 20.04 LTS 

https://user-images.githubusercontent.com/65229679/128024420-80710ad0-9f29-416f-8404-78de6e7a800f.mp4

please watch the video the first klick you hear is me pressing the windows key 

Ive been having this issue with the windows key function where when you press it you see all the windows you have opened at once
for me this is very convenient and Ive been using it a lot but since some time it bugs with Fullscreen applications
I used to be able to conveniently switch between Fullscreen windows as well
but now when I press the windows key while having a Fullscreen application running all the windows I have opened (not Fullscreen windows as well) disappear and I'm stuck on that screen as you can see in the video and no matter what I press nothing comes up the only thing I can do then is to restart or press ctrl + alt + f4 and use the terminal but that's not much of use for me 

but anyway restarting is the only fix Ive found to this so far 
idk is this a known bug? 

Im a linux noob if you want me to do anything specific so you can further investigate this issue don't hesitate to contact me

**Comment by jacobgkau** [comment]
This is not happening with Firefox in fullscreen mode, so it's not all fullscreened apps. Geometry Dash is a paid game, and I don't own it to test with.

If you change the `Show Minimize to Tray Windows` option in Extensions (green icon) -> Pop Shell, does that affect the behavior at all?

If you open a terminal (Super + T), type `xprop`, then click on the fullscreen Geometry Dash window, what output do you get? (The `WM_CLASS` and `WM_NAME` lines may be useful if an exception for that app needs to be added.)

Can you please also get logs using these steps?

1. Within Extensions -> Pop Shell, change `Log Level` from `OFF` to `DEBUG`.
2. Restart GNOME Shell with Ctrl-Alt-F2, r, Enter.
3. In a terminal, run `sudo journalctl -f` and enter your password.
4. Recreate the issue.
5. After Activities freezes, restart GNOME Shell with Ctrl-Alt-F2, r, Enter again, and copy/paste the entire terminal output into a text file, then attach that text file to a message.
6. Change `Log Level` back to `OFF` in the settings after you're finished collecting logs.

**Comment by SavexG** [comment]
Thank you for trying to help

first to clear things up with fullscreen applications I mean applications that are not as convenient to close as firefox 
I meant mostly video games that run in fullscreen mode that you are not able to close or minimize with ease I hope you understand what I mean now

here is the first terminal output:

save@pop-os:~ $ xprop
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_DESKTOP(CARDINAL) = 0
_GTK_EDGE_CONSTRAINTS(CARDINAL) = 170
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FULLSCREEN, _NET_WM_STATE_FOCUSED
_NET_WM_ICON(CARDINAL) = 	Icon (32 x 32):
	       ░░░░░░░░░░▒▒░░░░░░░░     
	  ░░░  ▒▒▒▒▒▒▒▒▒▒▓░▓▒▒▒▒▒▒▒░    
	  ▓▓▓░ ▓▓▓▓▓▓▓▓▓▓░ ░▓▓▓▓▓▓▓▓▒   
	  █▓▓░░▓▓▓▓▓▓▓▓▓░   ░▓▓▓▓▓▓▓▓▒░ 
	  ▓▓▓░░▓▓▓▓▓▓▓▓░     ░▓▓▓▓▓▓▓▓░ 
	     ░▒▓▓▓▓▓▓▓░       ░▓▓▓▓▓▓▓▒ 
	░ ░░░▓▓▓▓▓▓▓▓░   ▒▒    ░▓▓▓▓▓▓▒ 
	░▒▒▒▓▓▓▓▓▓▓▓░   ▒░▒▒    ░▓▓▓▓▓▒ 
	░▒▓▓▓▓▓▓▓▓▓░   ░▒  ▒▒   ░░▓▓▓▓▒ 
	░▒▓▓▓▓▓▓▓▓░     ▒░░▒  ▒░░░░▓▓▓▒░
	░▒▓▓▓▓▒▓▓░   ░   ▒▒  ▒▓▓░░░░▓▓▒░
	░▒▓▓▓▓▓▓░   ▒▒▒     ▒▒░░▓░░░░▓▒░
	░▒▒▒▒▓▓░   ▒░ ▒▒   ▒▒░░▒▒░░░░░▓░
	░▒▒▒▒▓░    ▒░ ░▒  ▒▒  ▒▒ ░░░░░░▓
	░▒▓▓▓▓▓░    ▒▒▒  ▒▒  ▒▒ ░░░░░░▓▒
	░▒▓▓▓▓▓▓░░   ▒  ▒▒  ▒▒░░░░░░░▓▓░
	░▒▓▓▓▓▒▓▓░░░░░░▒▒░ ▒▒░░░░░░░▓▓▒░
	░▒▓▓▒▒▒▓▓▓░░░░▒▓░░▒▒░░░░░░░▓▓▓▒░
	░▒▒▒░░▒▓▒▓▓░░░▒▓░▒▒░░░░░░░▓▓▓▒▒░
	░▒▒▒░░▒▒▒▒▓▓░░░▒▓▒░░░░░░░▓▓▒▒▒▒░
	░▒▒░▓▓░▒▒▒▒▓▓░░░░░░░░░░░▓▓▒▒▒▒▒░
	░▒▒░██░▒▒▒▒▒▓▓░░░░░░░░░▓▓▒▒▒▒▒▒░
	░▒░▓▓█▓░▒▒▒▒▒▓▓░░░░░░░▓▓▒▒▒▒▒▒▒░
	░▒░▓▓▓▓░▒▒▒▒▒▒▓▓░░░░░▓▓▒▒▒▒▒▒▒▒░
	░░▓▓▓▓▓▒░▒▒▒▒▒▒▓▓░░░▓▓▒▒▒▒▒▒▒▒▒░
	░▒▓▓▓▓▓▓░▒▒▒▒▒▒▒▓▓░▓▓▒▒▒▒▒▒▒▒▒▒░
	░▒▓▓▓▓▒▓▒░▒▒▒▒▒▒▒▓▓▓▒▒▒▒▒▒▒▒▒▒▒░
	░▒        ░░░░░░░░░░░░░░▒▒▒▒▒▒▒░
	░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░
	░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░
	░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░
	░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

	Icon (16 x 16):
	░░░▒▒▒▒▒▒▒▒▒▒░  
	░▓▒▒▓▓▓▓░░▓▓▓▓▒ 
	░▒░▒▓▓▓░  ░▓▓▓▓░
	░▒▒▓▓▓░ ░▒ ░▓▓▓░
	▒▓▓▓▓░ ░░░░░░▒▓░
	▒▓▓▓░ ░░░░▒▒░░▒░
	▒▒▓░ ░░▒ ▒░▒░░░▒
	▒▓▓▒░ ▒░▒░▒░░░▒▒
	▒▓▒▓▒░░▒░▒░░░▒▓▒
	▒▒░▒▓▒░▒▒░░░▒▓▒▒
	▒▒▓▒▒▒▒░░░░▒▓▒▒▒
	░▒▓▒▒▒▒▒░░▒▓▒▒▒▒
	▒▓▓▓░▒▒▒▒▒▓▒▒▒▒░
	░░░░░▒▒▒▒▒▒▒▒▒▒░
	░▒▒▒▒▒▒▒▒▒▒▒▒▒▒░
	░░░░░░░░░░░░░░░░


_NET_WM_NAME(UTF8_STRING) = "Geometry Dash"
WM_ICON_NAME(STRING) = "Geometry Dash"
WM_NAME(STRING) = "Geometry Dash"
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x7a00026
		bitmap id # of mask for icon: 0x7a00028
		window id # of group leader: 0x7c00001
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x26, 0x0, 0x0, 0x0
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 0
		window gravity: Static
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x7a0000f
XdndAware(ATOM) = BITMAP
_NET_WM_PID(CARDINAL) = 7961
WM_LOCALE_NAME(STRING) = "C"
WM_CLIENT_MACHINE(STRING) = "pop-os"
WM_CLASS(STRING) = "geometrydash.exe", "Wine"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING
STEAM_GAME(CARDINAL) = 322170
save@pop-os:~ $



and here is the pastebin link for the terminal output you told me to do in 6 steps:
https://pastebin.com/MzL7bppn

**Comment by jacobgkau** [comment]
> first to clear things up with fullscreen applications I mean applications that are not as convenient to close as firefox
> I meant mostly video games that run in fullscreen mode that you are not able to close or minimize with ease I hope you understand what I mean now

"With ease" isn't very technically specific. Firefox has a fullscreen mode (F11) that removes the titlebar (and, therefore, the "ability" to close/minimize with ease.) Geometry Dash sounds like it only allows fullscreen mode. I'll try recreating the issue on a 20.04 machine using another game that launches fullscreen.

Looking at your logs, the DING errors were [fixed yesterday](https://github.com/pop-os/desktop-icons-ng/pull/14) and should be unrelated to this issue. It looks like these are the most relevant log lines:

```
Aug 03 16:27:18 pop-os gnome-shell[3221]: JS ERROR: TypeError: app is null
                                          _getCaption@resource:///org/gnome/shell/ui/workspace.js:644:9
                                          WindowOverlay@resource:///org/gnome/shell/ui/workspace.js:498:48
                                          _addWindowClone@resource:///org/gnome/shell/ui/workspace.js:1857:23
                                          _init@resource:///org/gnome/shell/ui/workspace.js:1174:22
                                          _updateWorkspaces@resource:///org/gnome/shell/ui/workspacesView.js:232:29
                                          _init@resource:///org/gnome/shell/ui/workspacesView.js:91:14
                                          _updateWorkspacesViews@resource:///org/gnome/shell/ui/workspacesView.js:682:24
                                          show@resource:///org/gnome/shell/ui/workspacesView.js:612:14
                                          show@resource:///org/gnome/shell/ui/viewSelector.js:276:33
                                          _animateVisible@resource:///org/gnome/shell/ui/overview.js:580:27
                                          show@resource:///org/gnome/shell/ui/overview.js:566:14
                                          toggle@resource:///org/gnome/shell/ui/overview.js:689:18
                                          _initializeUI/<@resource:///org/gnome/shell/ui/main.js:223:22
Aug 03 16:27:22 pop-os gnome-shell[3221]: Object .Gjs_ui_workspace_WindowClone (0x5630de5fc420), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Aug 03 16:27:22 pop-os gnome-shell[3221]: == Stack trace for context 0x5630db96b8f0 ==
Aug 03 16:27:22 pop-os gnome-shell[3221]: #0   5630dc6a0f38 i   resource:///org/gnome/shell/ui/workspace.js:281 (24ccdc07ec40 @ 50)
Aug 03 16:27:22 pop-os gnome-shell[3221]: #1   5630dc6a0ea0 i   resource:///org/gnome/shell/ui/workspace.js:353 (24ccdc07f088 @ 17)
Aug 03 16:27:22 pop-os gnome-shell[3221]: #2   7ffc837acb20 b   self-hosted:1009 (1400b62a0cb8 @ 423)
Aug 03 16:27:22 pop-os gnome-shell[3221]: #3   5630dc6a0e18 i   resource:///org/gnome/shell/ui/main.js:236 (2ecf587d5e98 @ 12)
Aug 03 16:27:22 pop-os gnome-shell[3221]: == Stack trace for context 0x5630db96b8f0 ==
Aug 03 16:27:22 pop-os gnome-shell[3221]: #0   5630dc6a0f38 i   resource:///org/gnome/shell/ui/workspace.js:294 (24ccdc07ec40 @ 151)
Aug 03 16:27:22 pop-os gnome-shell[3221]: #1   5630dc6a0ea0 i   resource:///org/gnome/shell/ui/workspace.js:353 (24ccdc07f088 @ 17)
Aug 03 16:27:22 pop-os gnome-shell[3221]: #2   7ffc837acb20 b   self-hosted:1009 (1400b62a0cb8 @ 423)
Aug 03 16:27:22 pop-os gnome-shell[3221]: #3   5630dc6a0e18 i   resource:///org/gnome/shell/ui/main.js:236 (2ecf587d5e98 @ 12)
Aug 03 16:27:22 pop-os gnome-shell[3221]: == Stack trace for context 0x5630db96b8f0 ==
Aug 03 16:27:22 pop-os gnome-shell[3221]: #0   5630dc6a0ea0 i   resource:///org/gnome/shell/ui/workspace.js:354 (24ccdc07f088 @ 37)
Aug 03 16:27:22 pop-os gnome-shell[3221]: #1   7ffc837acb20 b   self-hosted:1009 (1400b62a0cb8 @ 423)
Aug 03 16:27:22 pop-os gnome-shell[3221]: #2   5630dc6a0e18 i   resource:///org/gnome/shell/ui/main.js:236 (2ecf587d5e98 @ 12)
Aug 03 16:27:22 pop-os gnome-shell[3221]: clutter_container_get_children: assertion 'CLUTTER_IS_CONTAINER (container)' failed
Aug 03 16:27:22 pop-os gnome-shell[3221]: Object .Gjs_ui_workspace_WindowClone (0x5630de5fc420), has been already deallocated — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Aug 03 16:27:22 pop-os gnome-shell[3221]: Object .Gjs_ui_workspace_WindowClone (0x5630de5fc420), has been already deallocated — impossible to emit any signal on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
```

Does the issue still occur if you disable the `Show Minimize to Tray` windows option like I previously asked? How about if you disable the entire Pop Shell extension from within the Settings app?

**Comment by SavexG** [comment]
> Does the issue still occur if you disable the `Show Minimize to Tray` windows option like I previously asked? How about if you disable the entire Pop Shell extension from within the Settings app?

oh yeah sorry  I  overread  that disabling "Show Minimize to Tray" option fixes the issue 
thank you

**Comment by jacobgkau** [comment]
> disabling "Show Minimize to Tray" option fixes the issue

Thank you for confirming. I've opened https://github.com/pop-os/shell/pull/1125 to exempt Geometry Dash from the skip taskbar behavior. Can you please turn that setting back on (so the issue occurs again), then install this development version of Pop Shell:

```
git clone https://github.com/pop-os/pop
./pop/scripts/apt add geometry-dash-skip-taskbar
sudo apt update
sudo apt upgrade
```

Then restart GNOME Shell (Alt-F2, r, Enter) and attempt to recreate the issue again? I want to confirm the following:

1. The problem should no longer occur.
2. Geometry Dash should show up in the Activities menu.

If both of those statements are true, then we can merge that PR to fix this for you and anyone else with this game. You can remove the development version of Pop Shell afterwards using these commands:

```
./pop/scripts/apt remove geometry-dash-skip-taskbar
sudo apt update
sudo apt upgrade
```

**Comment by jacobgkau** [comment]
I did install Steam on 20.04 and tried recreating this issue with Half-Life and Race the Sun, two games that launch in fullscreen, and neither had the issue. Half-Life switched to windowed mode automatically when I entered Activities (and back to fullscreen when I switched back to it), and Race the Sun's fullscreen display showed up normally in Activities.

**Comment by jacobgkau** [comment]
Because Geometry Dash appears to be running in WINE, I tried Sonix Adventure DX (another Proton game), and I am able to recreate the issue with that one.

**Comment by jacobgkau** [comment]
Because Geometry Dash appears to be running in WINE, I tried Sonix Adventure DX (another Proton game), and I am able to recreate the issue with that one. The window is not displayed in Activities, and I am unable to exit Activities after entering it:

![Screenshot from 2021-08-03 10-07-36](https://user-images.githubusercontent.com/7199422/128049168-be91d83f-254e-4520-806a-de9adefe38a1.png)

@mmstick (or @jmmaranan, author of the skip taskbar feature), any idea what's causing the GNOME Shell crash when this happens? I'm confused why the option to _show_ skip taskbar windows is causing the window to be hidden-- no other windows are being shown either, so it seems like something else isn't working correctly.

**Comment by ids1024** [comment]
I would check for errors in `journalctl /usr/bin/gnome-shell`. A JavaScript error could result in seemingly unrelated issues since other code doesn't run.

**Comment by jmmaranan** [comment]
Hi @jacobgkau would it be an option for pop shell to have it as default off, the last code change for this was to have it as default on. Until we can figure out the issues.

**Comment by SavexG** [comment]
> If both of those statements are true, then we can merge that PR to fix this for you and anyone else with this game. You can remove the development version of Pop Shell afterwards using these commands:

No the development version does not fix this issue for me in Geometry Dash and it also doesn't work in call of duty black ops 3 for me

**Comment by jacobgkau** [comment]
> No the development version does not fix this issue for me in Geometry Dash and it also doesn't work in call of duty black ops 3 for me

Okay, we'll try to figure out the error then, thank you for checking.

@jmmaranan While that's not entirely up to me, I'm not sure that's a solution. By defaulting to off, we likely won't have issues like this reported, so they won't get figured out very quickly. Also, the reason we defaulted to on was because window management of other apps are broken when it's off. If the number of bugs is too high and we can't keep up with adding exceptions, then changing the default would be possible. Just not my preference as of right now.

I'm grabbing logs from my test machine to compare to @SavexG's above, and checking if this issue also affects 20.04.

**Comment by jacobgkau** [comment]
@ids1024 Thanks. My logs have similar errors to the ones earlier:

```
Aug 03 10:35:35 pop-os gnome-shell[2335]: Source ID 804 was not found when attempting to remove it
Aug 03 10:35:35 pop-os gnome-shell[2335]: Error: GSettings schema org.gnome.shell.extensions.pop-cosmic not found
Aug 03 10:35:35 pop-os gnome-shell[2335]: gnome-shell-extension-system76-power: power profile was set: 'Balanced'
Aug 03 10:35:35 pop-os gnome-shell[2335]: Window manager warning: Overwriting existing binding of keysym 6f with keysym 6f (keycode 20).
Aug 03 10:36:04 pop-os gnome-shell[2335]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x2600005 specified for 0x26000a0.
Aug 03 10:36:52 pop-os gnome-shell[2335]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x2600005 specified for 0x2600225.
Aug 03 10:36:55 pop-os gnome-shell[2335]: JS ERROR: TypeError: app is null
                                          _getCaption@resource:///org/gnome/shell/ui/workspace.js:644:9
                                          WindowOverlay@resource:///org/gnome/shell/ui/workspace.js:498:48
                                          _addWindowClone@resource:///org/gnome/shell/ui/workspace.js:1857:23
                                          _init@resource:///org/gnome/shell/ui/workspace.js:1174:22
                                          _updateWorkspaces@resource:///org/gnome/shell/ui/workspacesView.js:232:29
                                          _init@resource:///org/gnome/shell/ui/workspacesView.js:91:14
                                          _updateWorkspacesViews@resource:///org/gnome/shell/ui/workspacesView.js:682:24
                                          show@resource:///org/gnome/shell/ui/workspacesView.js:612:14
                                          show@resource:///org/gnome/shell/ui/viewSelector.js:276:33
                                          _animateVisible@resource:///org/gnome/shell/ui/overview.js:580:27
                                          show@resource:///org/gnome/shell/ui/overview.js:566:14
                                          toggle@resource:///org/gnome/shell/ui/overview.js:689:18
                                          _initializeUI/<@resource:///org/gnome/shell/ui/main.js:223:22
Aug 03 10:36:58 pop-os gnome-shell[2335]: Window manager warning: META_CURRENT_TIME used to choose focus window; focus window may not be correct.
Aug 03 10:36:58 pop-os gnome-shell[2335]: Some code accessed the property 'CredentialManager' on the module 'credentialManager'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Aug 03 10:36:58 pop-os gnome-shell[2335]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Aug 03 10:36:58 pop-os gnome-shell[2335]: Will monitor session 2
Aug 03 10:36:58 pop-os gnome-shell[2335]: Telepathy is not available, chat integration will be disabled.
```

With `TypeError: app is null` being the one that occurs at the moment I try to access the overview.

I've also found that this does not happen in 21.04; I can access Workspaces (and Launcher/Applications) normally, with no crash. (On 21.04, when I switch to another workspace and then back, I do get some graphical issues within the game sometimes, but this game is fairly buggy and that's not the same problem.)

**Comment by SavexG** [comment]
So I  tested a few more games that I have installed the issue occurred on:
geomentry dash
dark souls 3
cod bo3
little nightmares 
outlast 2
plants vs zombies
vr chat

the only game where the issue didn't occur for me was "counterstrike global offensive" 

this issue might be more widespread then just a few games

**Comment by jacobgkau** [comment]
> this issue might be more widespread then just a few games

Yes, it sounds like it's any Steam game running in Proton/WINE. Thank you for the additional testing.

**Comment by jmmaranan** [comment]
@jacobgkau sure.

Hi @SavexG would you be able to tell the  `gnome-shell --version`, 3.36?

**Comment by jacobgkau** [comment]
> Hi @SavexG would you be able to tell the `gnome-shell --version`, 3.36?

My 20.04 test system shows `GNOME Shell 3.36.7`, @SavexG's should be the same.

**Comment by jmmaranan** [comment]
When the flag is on, the `app is null` should already have been handled here:
https://github.com/pop-os/shell/blob/master/src/extension.ts#L2597

And the error stack trace looks like it points to the branch `gnome-3-36`. And last release for 3.36.7 was 9 months ago.

@jacobgkau - did you have Skip taskbar on or off during your test on 20.04?

**Comment by jacobgkau** [comment]
> @jacobgkau - did you have Skip taskbar on or off during your test on 20.04?

`Show Minimize to Tray Windows` was enabled (the default setting.) If I turn it off, then the issue does not occur (but resumes when I turn it back on.)

**Comment by SavexG** [comment]
> gnome-shell --version
yeah the gnome shell version I had the issues with was 
GNOME Shell 3.36.7

**Comment by jmmaranan** [comment]
Thanks @jacobgkau and @SavexG - it will take me a while to setup a similar 20.04 and with proton (a possibility can do wine on a VM). But for now, as a work around can you disable the `Show Minimize to Tray Windows` @SavexG?

**Comment by SavexG** [comment]
> But for now, as a work around can you disable the `Show Minimize to Tray Windows` @SavexG?

Yes this works perfectly fine

**Comment by jacobgkau** [comment]
Just a couple more pieces of data:
- Word 2007 in WINE doesn't create the issue (although its only fullscreen option doesn't cover the top bar up, so it isn't really fullscreen.)
- Proton games (such as the Sonic game and others I have access to) show the issue even if they're set to windowed mode.

So rather than being specific to fullscreened windows, this could have to do with how Steam/Proton create windows.

**Comment by jmmaranan** [comment]
@jacobgkau - I think it works now on my local. I'll send a PR

![image](https://user-images.githubusercontent.com/348125/128264254-3ba21929-2f46-41d0-8150-bac1e067dc3f.png)

**Comment by DMGPage** [comment]
> > @jacobgkau - did you have Skip taskbar on or off during your test on 20.04?
> 
> `Show Minimize to Tray Windows` was enabled (the default setting.) If I turn it off, then the issue does not occur (but resumes when I turn it back on.)

Can confirm, that it fixed issues for me. Now windows key works just fine.
