### ISSUE TITLE
Workspace related features broken

### ISSUE THREAD

**Issue by supermar1010** [pop-os/shell#1128]
**(1) Issue/Bug Description:**
Moving windows to a upper workspace does not work. Moving them a workspace down works without a problem. I checked the keybindings in the gnome keyboard settings dialog, there all the keybindings seem to be right. 

I guess a similiar source is my problem with moving focus from window to window. For example Super+Up  works, but Super+down does not work. Same goes for Super+right, which works, but Super+left, moves the current window to the left half of the screen (like it was in vanilla gnome). I also checked the keybindings here, but they seem to be right in my opinion. Any way to check these, with another tool than the gnome gui program.

**(2) Steps to reproduce (if you know):**

**(3) Expected behavior:**
Moving windows workspaces up should work.

**(4) Distribution (run `cat /etc/os-release`):**
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux

**(5) Gnome Shell version:**
GNOME Shell 40.3

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

commits: `ab87042d2579c9ad9bb3271584b0281d97da7baa`

**(7) Where was Pop Shell installed from:**

Arch aur, compiled from source `gnome-shell-extension-pop-shell-git`

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1x3440x1440

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

**Comment by supermar1010** [comment]
I just did some more experimenting, for the Switch Focus to window shortcuts, it worked reassigning them to the same shortcut used before, and then removing the custom assignment.
For the moving to different workspaces it did not work however.

For moving to different workspaces, I did not find the shortcut assigned in the gnome settings so I set it myself, this works now. So it seems for me the setting of the keyboard shortcuts went wrong?

**Comment by RichardSieg** [comment]
Hey @supermar1010 could you explain how you solved your problem and in particular how you removed the custom assignment? I tried to set the GNOME keyboard shortcut for moving to another workspace several times now and nothing works.

**Comment by dmitri-d** [comment]
This is also an issue on Gnome 41 (Fedora 35, pop_os shell installed from fedora repository).

**Comment by aadilayub** [comment]
I had a similar problem in that after turning on the extension, shortcuts for maximizing and snapping windows (Super left, super right, super up, super down) and for moving the windows between workspaces (shift + super + pagedown, shift +super + pageup) stopped working when I have the extension disabled.
