### ISSUE TITLE
`20.04 lts` when I remove a '*.desktop' file in '~/.local/share/applications' and even in '/', it still could be found in Navigate through 'Super+/'

### ISSUE THREAD

**Issue by rogerBridge** [pop-os/shell#1135]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
I don't know its specific package name, Just use shortcuts 'Super+/' to open Navigate 

**Issue/Bug Description:**
for example, I manually install a binary file, '*.desktop' file in ~/.local/share/applications, and when I remove '*.desktop' file, in Gnome search, it will not exist, but When I use Navigate through 'Super+/', it still in there, I guess there exist some cache, but I don't know how to update it

**Steps to reproduce (if you know):**
1. create a '*.desktop' file in ~/.local/share/applications;
2. find it through 'Super+/';
3. rm desktop file in step 1;
4. it still could be found in 'Super+/';

**Expected behavior:**
1. it disappear in Navigate through shortcut: 'Super+/';

**Other Notes:**

**Comment by jacobgkau** [comment]
Restarting GNOME Shell with `Alt-F2`, `r`, `Enter` doesn't make the entry go away?

**Comment by rogerBridge** [comment]
hello, I am using wayland, so that didn't take effect

**Comment by jacobgkau** [comment]
> hello, I am using wayland, so that didn't take effect

How about rebooting or logging out and back in, then?

**Comment by rogerBridge** [comment]
> > hello, I am using wayland, so that didn't take effect
> 
> How about rebooting or logging out and back in, then?

I did, but it seems not take effect

**Comment by mmstick** [comment]
There's no cache. Files are read the moment the launcher is opened, so the file must exist in one of the paths searched.

**Comment by rogerBridge** [comment]
> There's no cache. Files are read the moment the launcher is opened, so the file must exist in one of the paths searched.

I use `sudo find -name '[specific].desktop' `, and I am sure, there is not exist `[specific].desktop`, but I still can get it from Navigate
