### ISSUE TITLE
Fork doesn't re-tile when windows are maximised to other screens

### ISSUE THREAD

**Issue by Benguin** [pop-os/shell#114]
On a system with 2 displays, if a window is tiled but then you maximise it to a display other than the one it was on (by dragging it to the top of the other screen, for instance) the fork doesn't retile, and the space it was using remains unoccupied.

Steps to reproduce (on a 2-screen system):
1. Open 2 windows on the left screen, tiled.
2. Hold super and drag one of the windows all the way to the top of the other screen, such that gnome-shell causes it to maximise.

Expected result:
Window will maximise on the right display, the left display will re-tile to fill the space.

Actual Result: 
The window maximises to the other screen, but the space remains vacant.

System:
Archlinux
Gnome Shell 3.36
Popshell  aur git package r293.53acb5b-1

**Comment by Benguin** [comment]
Would like to add as well, that if you move any _other_ windows on the original screen, the window you maximised will un-maximise and move back.

**Comment by mmstick** [comment]
Good to know. This is an easy fix
