### ISSUE TITLE
Changing shortcut

### ISSUE THREAD

**Issue by Shirobachi** [pop-os/shell#1143]
I installed on Ubuntu 21.04 pop shell, can you add shortcut change possibility? Or it's already available and I missed it?

**Comment by leviport** [comment]
Which shortcuts are you trying to change? They should all be customizable in Settings > Keyboard > Keyboard Shortcuts.

**Comment by Shirobachi** [comment]
I am not saying about system POPos but about ubuntu with pop shell, I did it w/ this tutorail: https://www.linuxuprising.com/2020/05/how-to-install-pop-shell-tiling.html

I am using super+return for running terminal and wanna change it

**Comment by leviport** [comment]
Oh I understand now, sorry about that. In Pop!\_OS, we modified Gnome Control Center a bit to expose those settings. To do the same in Ubuntu, you'd also need our version of Gnome Control Center. The easier way to modify them is probably by changing the gsettings in dconf-editor. You can find them at `/org/gnome/shell/extensions/pop-shell/`.

**Comment by Shirobachi** [comment]
Thanks, Ill do that!
