### ISSUE TITLE
Add krunner to floating window exceptions

### ISSUE THREAD

**Issue by code3z** [pop-os/shell#1149]
1. Install kde according to instructions
2. Use Pop as desktop
3. Use floating windows
4. Launch `krunner`

**Comment by mmstick** [comment]
Would you happen to the know the wm class / wm title?

**Comment by code3z** [comment]
No, but it can be started by running krunner.

**Comment by jacobgkau** [comment]
`WM_CLASS(STRING) = "krunner", "krunner"`
`WM_NAME(STRING) = "KRunner"`

An class/title exception of `krunner`/`KRunner` works, or just the class of `krunner`.
