### ISSUE TITLE
Extensions app doesn't launch

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/shell#1159]
I am able to launch the Extensions app (green icon, installed by default in Pop!_OS) from the Applications menu, but not from the Launcher. When I attempt to launch from the Launcher, the Launcher just closes with no visual feedback. I get a line like this in journalctl each time I attempt to launch the app:

```
Sep 01 10:32:17 pop-os gnome-shell[2479]: Could not create transient scope for PID 6829: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 6829 does not exist.
```

The PID in the message changes each time.

**Comment by mmstick** [comment]
It's still launching after several reboots on both Intel and NVIDIA graphics. The fact that the launcher closes means that pop-shell has already attempted to launch the desktop entry it was given. If it's not launching the desktop-entry, then perhaps `Shell.AppSys.lookup_desktop_wmclass()` is finding the `.desktop` file by the name of the desktop file it's given, but that seems unlikely. Perhaps I'll fall back to looking for an app by its ID as well.

**Comment by jacobgkau** [comment]
Fixed by https://github.com/pop-os/launcher/pull/9.
