### ISSUE TITLE
How to have Launcher show windows from ALL desktops?

### ISSUE THREAD

**Issue by jsonMartin** [pop-os/shell#116]
Hello, I'm trying to figure out how the Launcher can show applications from all Workspaces, like Alt-Tab does by default. According to the documentation, it says: "Pressing Return on a window will bring that window to focus, **switching to its workspace**, and unminimizing it if it was minimized."

However, I can't seem to figure out how to use the launcher to find windows running on other workspaces. Any help would be appreciated!

Great plugin by the way, I'm really enjoying it so far!

**Comment by mmstick** [comment]
I'll have a preference toggle for it when we get a preference dialog. There's no way to do that right now.

**Comment by jsonMartin** [comment]
OK, cool thank you =)

**Comment by WatchMkr** [comment]
With user testing, we've found that showing windows from all workspaces will improve launcher usability. The launcher introduces a new window switching pattern we'd like to establish to avoid going into the Activities overview or using `super` + `tab`.

Moving back to Milestone 1.0.0 for the 20.04 release.

**Comment by mmstick** [comment]
Should we default to showing all windows from all workspaces?

**Comment by WatchMkr** [comment]
Yes

**Comment by lunaryorn** [comment]
I am sorry to bump this ticket but I wonder whether this behaviour could be configured, even if only in a config file or with `dconf`?  For my personal workflow a launcher that only switches among windows of the current workspace would be much better.

**Comment by lunaryorn** [comment]
As an alternative, I'd also be happy if the launcher listed windows of the current workspace first, and had a visual indication, e.g. some kind of thin line, to mark the "end" of the current workspace in the list.

I tend to have a firefox window on every workspace with tabs relevant to the context of that workspace, and currently it's rather hard for me to find the "right" firefox to switch to among all the firefoxes listed in the launcher :slightly_smiling_face:
