### ISSUE TITLE
Super + / not working after last update

### ISSUE THREAD

**Issue by ciro-mota** [pop-os/shell#1161]
**(1) Issue/Bug Description:**
Today I updated my extension with the latest commit and the launcher via the `Super` + `/` keys is not activated. GNOME was restarted multiple times via the shortcuts `Alt` + `F2` and `r`, in addition to rebooting the OS itself.

No results.
`Super` + `Y` to trigger Tilling mode works normally.

**(4) Distribution (run `cat /etc/os-release`):**
 
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**(5) Gnome Shell version:**

GNOME Shell 3.36.8.

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```8be10fa```

**(7) Where was Pop Shell installed from:**

Compiled directly from repository

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1 x 1080p.

**(9) Other Installed/Enabled Extensions:**

![ksnip_20210903-160031](https://user-images.githubusercontent.com/57502603/132054218-0ad09cc6-48b6-4795-8c86-7db444c34780.png)

**Comment by mmstick** [comment]
The launcher is now a separate package from pop-shell: https://github.com/pop-os/launcher/
