### ISSUE TITLE
Launcher fails to start apps whose desktop files reside in subfolders

### ISSUE THREAD

**Issue by danielwe** [pop-os/shell#1163]
**(1) Issue/Bug Description:**

Launcher fails to open apps whose `.desktop` files reside in subfolders of `$XDG_DATA_DIRS/applications`. These apps do appear in the search, but absolutely nothing happens when selecting them---there is no visual feedback and no message logged to `journalctl`.

Common examples are wine apps---these tend to be installed in a directory tree that mirrors the Windows start menu layout, i.e., `$XDG_DATA_DIRS/applications/wine/Programs/Appname/Appname.desktop`.

The applications view and the dock are both able to start such apps.

**(2) Steps to reproduce (if you know):**

* Take any `.desktop` file in `~/local/share/applications` or `/usr/share/applications` and move into a subfolder
* Try starting the app using the applications view to confirm that the desktop entry still works
* Close the app and try starting it using launcher---nothing happens

**(3) Expected behavior:**

App launches. (Subfolders are supported by the Freedesktop desktop entry spec as per <https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#desktop-file-id>.)

**(4) Distribution (run `cat /etc/os-release`):**
 
```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**

```
gnome-shell:
  Installed: 3.38.4-1ubuntu3~21.04.1ubuntu1pop1~1623339707~21.04~2a1865d
```

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1630345490~21.04~0484ffb
```

**(7) Where was Pop Shell installed from:**

```
http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main
```

**Comment by mmstick** [comment]
The launcher service sees it, but GNOME Shell doesn't support lookup for them, apparently. I will make changes here to fall back to loading these by their path if the desktop entry cannot be found.

**Comment by danielwe** [comment]
I don't know exactly how the pop launcher interacts with GNOME Shell here, but do take note of the desktop file ID explained in the Freedesktop documentation (<https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#desktop-file-id>). It consists of the file path under `$XDG_DATA_DIRS/applications`, but with `/` replaced by `-`. For example, in the case of a wine app, it becomes `wine-Programs-Appname-Appname.desktop`. Using this ID works with `gtk-launch`, which is a GNOME binary, right?

```
$ gtk-launch wine-Programs-Appname-Appname.desktop  # Success! Also works without the .desktop extension
```

Pinging #1160 before it gets merged
