### ISSUE TITLE
[BUG] Custom scripts don't show in launcher

### ISSUE THREAD

**Issue by hovo1990** [pop-os/shell#1164]
**(1) Issue/Bug Description:**

Custom shell script in  ~/.local/share/pop-shell/scripts does not show up in launcher.

**(2) Steps to reproduce (if you know):**

After the latest update of pop-shell from Pop OS 20.04, the custom script does not show in the launcher.

**(3) Expected behavior:**
Be able to launch the custom script from Launcher.

**(4) Distribution (run `cat /etc/os-release`):**

```
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**

GNOME Shell 3.36.7

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```

pop-shell:
  Installed: 1.1.0~1630345490~20.04~0484ffb
  Candidate: 1.1.0~1630345490~20.04~0484ffb
  Version table:
 *** 1.1.0~1630345490~20.04~0484ffb 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

3x 1080p monitors

**Comment by mmstick** [comment]
The correct path is pop-launcher rather than pop-shell
