### ISSUE TITLE
Change positioning of launcher if screen is too small

### ISSUE THREAD

**Issue by LifeWatcher123** [pop-os/shell#1176]
In my particular setup, the launcher is too close to the bottom when searching. It'll be nice if users can configure the positioning or offset of the launcher (or if the launcher self-centers itself on dimension changes). 

![Preview Image](https://user-images.githubusercontent.com/43345572/133195072-cceeccc8-c619-448a-a1f4-b4389cd426d2.png)

**Comment by leviport** [comment]
Could you post the list of extensions you have installed, as well as your display's resolution and scaling?

**Comment by LifeWatcher123** [comment]
Display Resolution: 1360 x 768
Display Scaling: None

Installed and Enabled Extensions:
- Dash to Panel [auto-move-windows@gnome-shell-extensions.gcampax.github.com]
- Gamemode Indicator [gamemode@christian.kellner.me]
- GSConnect [gsconnect@andyholmes.github.io]
- Hibernate Status Button [hibernate-status@dromi]
- No Symbolic Icons [no-symbolic-icons@evanwelsh.com]
