### ISSUE TITLE
Resizing application breaks layout

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#118]
![bug_report](https://user-images.githubusercontent.com/39338488/77722239-90640000-6fc3-11ea-9bb2-cf53d5d580b4.gif)

Once this happens, it is not possible to get the windows back to occupying the full screen without restarting the shell.

**Comment by nicolae-stroncea** [comment]
Here's another example. Not sure if this is the same bug, but occurs in a similar layout. Let me know if I should submit a different issue for it instead.

![output](https://user-images.githubusercontent.com/39338488/78065258-00c2a680-7361-11ea-919a-eeb817cd35a2.gif)

* When one of the windows in the bottom right is minimized, it extends the whole layout downwards(similar to how issue above sort of reduces the size of the layout). Once the size of the layout is extended beyond size of screen, only way to go back to normal, is restart the shell.
* Weird overview artifact happens with weird shading on the left, and windows aren't displayed anymore

**Comment by mmstick** [comment]
It's a known issue. There are some layout bugs remaining.

**Comment by mmstick** [comment]
Is this still an issue?
