### ISSUE TITLE
Ruins screen scaling

### ISSUE THREAD

**Issue by danielzfranklin** [pop-os/shell#119]
I installed pop os shell on my Darter Pro laptop and rebooted. The status bar and applications now render at different incorrect resolutions.

![Screenshot from 2020-03-27 16-17-59](https://user-images.githubusercontent.com/10361846/77776877-96e78b80-7046-11ea-8083-22f17766511a.png)

In the screenshot firefox is roughly twice as large as normal and the status bar is roughly half as large as normal.

![Screenshot from 2020-03-27 16-19-31](https://user-images.githubusercontent.com/10361846/77777008-c9918400-7046-11ea-8ade-f6ca2717b76b.png)

I installed from a checkout of the default branch around ten minutes ago.

Edit:

The issue isn't resolved after uninstalling with `make uninstall`

**Comment by mmstick** [comment]
We don't make any changes to scaling values in Pop Shell. Something else may be responsible for causing that behavior.

**Comment by danielzfranklin** [comment]
You're completely right. This is quite embarrassing. Thanks for pointing out my mistake so quickly and politely.
