### ISSUE TITLE
[Feature request] Show application icons on stacking tabs

### ISSUE THREAD

**Issue by jdtimmerman** [pop-os/shell#1199]
When using stacked windows, I'd appreciate a more distinct visual clue to which application is underneath which tab.

Can icons be added to these tabs? With colorful icons this could become a bit distracting so an option to desaturate the icons might be a nice balance?

![pop-shell-stacked-icons](https://user-images.githubusercontent.com/4509518/135816745-2667749a-f48c-44af-97c0-cd5b238bd101.png)

**Comment by SevenSystems** [comment]
This would probably significantly improve workflow efficiency, especially for users who prefer visual navigation instead of using keyboard shortcuts. Would be great to have.

**Comment by SevenSystems** [comment]
Quick and dirty implementation for anyone who wants it **now** (sorry, first time I dabble in GNOME extensions -- probably a mess)

In stack.js, replace the 'add' function with:

    add(window) {
        if (!this.widgets)
            return;
        const entity = window.entity;
        const label = window.title();
        const active = Ecs.entity_eq(entity, this.active);
        const button = new St.Button({
            x_expand: true,
            style_class: active ? ACTIVE_TAB : INACTIVE_TAB
        });

        const iconLabel = new Clutter.Actor();
        const icon = window.icon(null, 16);
        icon.set_style('margin-top: 1px');
        iconLabel.set_x_align(Clutter.ActorAlign.CENTER);
        iconLabel.set_y_align(Clutter.ActorAlign.CENTER);
        iconLabel.add_child(icon);
        iconLabel.add_child(new St.Label({ text: label, style: 'margin-left: 22px' }));
        button.set_child(iconLabel);

        const id = this.buttons.insert(button);
        let tab = { active, entity, signals: [], button: id, button_signal: null };
        let comp = this.tabs.length;
        this.bind_hint_events(tab);
        this.tabs.push(tab);
        this.watch_signals(comp, id, window);
        this.widgets.tabs.add(button);
    }

**Comment by cspipaon** [comment]
I believe this issue should be closed now. This is the default behaviour on my machine at the moment. @mmstick 
@jdtimmerman @SevenSystems
