### ISSUE TITLE
Show window titles does show titles on some apps

### ISSUE THREAD

**Issue by LinuxHeki** [pop-os/shell#1211]
**(1) Issue/Bug Description:**
Feature Show window titles doesn't work on some applications like Gnome terminal, Nautilus, Firefox...

**(2) Steps to reproduce (if you know):**
Open terminal (Gnome default), turn off Show window titles and that's it.

**(3) Expected behavior:**
Doesn't show titles on apps like this.

**(4) Distribution (run `cat /etc/os-release`):**
 Pop!_OS 21.04

**(5) Gnome Shell version:**
3.38.5

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```1.1.0~1633445036~21.04~28c060e```

**(7) Where was Pop Shell installed from:**
Apt, preinstalled

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
2 x 1080p

**(9) Other Installed/Enabled Extensions:**
Blur my shell
GSConnect
Sound Input & Output Device Chooser

**(10) Other Notes:**

**Comment by mmstick** [comment]
Not possible with applications that use client-side decorations.
