### ISSUE TITLE
Desktop becomes unresponsive after certain mouse click combinations

### ISSUE THREAD

**Issue by j-tai** [pop-os/shell#1215]
**(1) Issue/Bug Description:**

In certain cases, the entire desktop and all applications will become unresponsive to mouse clicks. This can be fixed by pressing some other keyboard shortcuts like Super or Super+D.

**(2) Steps to reproduce (if you know):**

1. Enable window tiling.
2. Open a window.
3. Press Super+S to enable stacking on the window.
4. Place your mouse cursor on the tab bar (yellow bar that shows up when you enable stacking).
5. Hold down right click, press and release left click, then release right click.
    → The desktop becomes unresponsive.

Other combinations are also possible. For example: hold left click, press/release right click, then release left click.

**(3) Expected behavior:**

The desktop should not become unresponsive.

I have done these mouse combination on accident a few times, and it's annoying when it interrupts my workflow.

**(4) Distribution (run `cat /etc/os-release`):**

```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**

`3.38.4-1ubuntu3~21.04.1ubuntu1pop1~1623339707~21.04~2a1865d`

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1633445036~21.04~28c060e
  Candidate: 1.1.0~1633445036~21.04~28c060e
  Version table:
 *** 1.1.0~1633445036~21.04~28c060e 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

Installed by default in Pop!_OS

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

2 x 1080p, both horizontal. Secondary monitor is slightly offset upwards (not exactly side by side).

**(9) Other Installed/Enabled Extensions:**

None

**(10) Other Notes:**

**Comment by bflanagin** [comment]
Issue appears in `gnome-shell  3.38.4-1ubuntu3~21.04.1ubuntu1pop1~1623339707~21.04~2a1865d` as well.

**Comment by j-tai** [comment]
No longer happens on Pop 22.04.
