### ISSUE TITLE
Active hint of tiled window stays on screen in maximized state

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#122]
Here is the behaviour:

![output](https://user-images.githubusercontent.com/39338488/77838029-de9d0e80-713d-11ea-8c5a-e070054ffec6.gif)

Can be reproduced both by going into Activities overview by shortcut or cursor and then returning to maximized window.

EDIT: To add more details:

This will occur every time you go into Activities overview, and once the highlight shows, it's impossible to get rid of unless you minimize the window, and then maximize it again.

**Comment by leviport** [comment]
I can confirm this. Here is the console out put I see when it happens:
```
pop-shell: [DEBUG] displaying fork (0,0)
pop-shell: [DEBUG] displaying fork (1,0)
pop-shell: [DEBUG] displaying fork (2,0)
pop-shell: [DEBUG] displaying fork (3,0)
pop-shell:  [INFO] 

 Fork(0,0) [4,4,1912,1072]: {
    workspace: (0),
    left:  Window(1,0) (Rect(4,4,1912,1072)),
  }
 Fork(1,0) [1924,31,1912,1045]: {
    workspace: (0),
    left:  Window(2,0) (Rect(1924,31,1912,1045)),
  }
 Fork(2,0) [1924,31,1912,1045]: {
    workspace: (1),
    left:  Window(3,0) (Rect(1924,31,954,1045)),
    right: Window(4,5) (Rect(2882,31,954,1029)),
  }
 Fork(3,0) [4,4,1912,1072]: {
    workspace: (1),
    left:  Window(0,0) (Rect(4,4,1904,1069)),
  }

hiding active hint
hiding active hint
hiding active hint
hiding active hint
pop-shell:  [INFO] grab start
hiding active hint
showing active hint
```
