### ISSUE TITLE
Focused window behaviour with shortcuts

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#123]
*Maximizing focused window*:

![output](https://user-images.githubusercontent.com/39338488/77838157-31c39100-713f-11ea-976c-5ef26be96065.gif)

The expected behaviour is that the focused window is maximized on top of others. Current behaviour only maximizes correctly the window that was last clicked on or had any real user interaction

*Converting focused window to floating mode*

Similarly, if you convert a focused window to floating mode, it will move behind the layout if it's not the last window that had real user interaction. Expected behaviour is that it floats on top of all other 
windows.

Focused windows can be manipulated correctly in other instances: shortcuts move them correctly to other workspaces

**Comment by mmstick** [comment]
I haven't been able to replicate this in Pop 20.04; but I can have the window call `raise()` on focus. Maximization by default in GNOME will automatically bring it to the top of the window group, so what you're seeing shouldn't happen. Likewise for window focuses.

**Comment by nicolae-stroncea** [comment]
That fixed it for both issues, thanks :)
