### ISSUE TITLE
Some windows are not automatically tiled when tiling is enabled

### ISSUE THREAD

**Issue by rdgh8** [pop-os/shell#1256]
**(1) Issue/Bug Description:**

Some windows are not automatically tiled when tiling is enabled

**(2) Steps to reproduce (if you know):**

1. Open "Extensions" program
2. Open the settings for one of the extensions you have installed, ex. Pop Shell, by clicking on the cog icon

**(3) Expected behavior:**

The settings window for ex. Pop Shell is tiled 

**(4) Distribution (run `cat /etc/os-release`):**
 
Pop!_OS 21.10, Pop!_OS 21.04

**(5) Gnome Shell version:**

40.5, 3.38.4

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1637792694~21.04~676729f
  Candidate: 1.1.0~1637792694~21.04~676729f
  Version table:
 *** 1.1.0~1637792694~21.04~676729f 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main i386 Packages
        100 /var/lib/dpkg/status
```

```
pop-shell:
  Installed: 1.1.0~1633987844~21.10~7a80d8b
  Candidate: 1.1.0~1637635482~21.10~9b75a37
  Version table:
     1.1.0~1637635482~21.10~9b75a37 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
       1001 http://apt.pop-os.org/release impish/main i386 Packages
 *** 1.1.0~1633987844~21.10~7a80d8b 100
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

Came with Pop!_OS

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1 x 1080p horizontal

**(9) Other Installed/Enabled Extensions:**

Occurs when all other extensions are disabled 

**(10) Other Notes:**

Possibly related bug, but following on from the demonstration above, I cannot move the Pop Shell settings window to a different workspace from the Extensions window, which I haven't been able to reproduce with any other pair of windows.

**Comment by leviport** [comment]
I believe those extension settings windows are considered dialogs, and dialogs should never be tiled.
