### ISSUE TITLE
Launcher shows error icon next to every un-launched item

### ISSUE THREAD

**Issue by titojankowski** [pop-os/shell#1263]
**Distribution (run `cat /etc/os-release`):**
 Pop OS 21.04

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Pop Shop

**Issue/Bug Description:**
Next to results in the Launcher, each item has an icon to the left. For open programs/windows, this icon is kind of a window-y looking thing. But for programs that aren't launched, the icon is a black screen with a "do not do" symbol on it. (https://english.stackexchange.com/questions/156465/is-there-a-name-for-the-red-circle-and-slash-in-a-no-smoking-sign)

It comes across as an error to me as a user. And seems really redundant. Yes, I haven't launched those programs. No, I don't really need an icon to tell me that. This seems like a new addition, or is it something I'm just noticing now?

**Steps to reproduce (if you know):**

![Screenshot from 2021-12-04 14-13-42](https://user-images.githubusercontent.com/129060/144728670-183c2ce7-93c5-43b6-bfea-d8a79eaa7b98.png)

**Expected behavior:**
No icon next to un-launched applications.

**Other Notes:**

**Comment by mmstick** [comment]
It's because you're missing the icon

**Comment by titojankowski** [comment]
Ah that's it, had started messing around with Gnome Tweaks icon sets. Back to defaults for me. Closing this! @mmstick
