### ISSUE TITLE
pop-shell@system76.com/extensions.js" prevents Alt-TAB shortcut (switch application) from working

### ISSUE THREAD

**Issue by abrighton** [pop-os/shell#1264]
**(1) Issue/Bug Description:**

After installing updates, ALt-TAB keyboard shortcut (switch application) stopped working and syslog or journalctl
showed an error at line 2124 of /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js: "app is NULL".
The line in the original source (extension.ts) is 2728.

The original line was:

                        return app.get_name() === w_app.get_name();

The fix is to add a check:

                        return app ? app.get_name() === w_app.get_name() : false;

**(2) Steps to reproduce (if you know):**

Type Alt-TAB to switch applications.

**(3) Expected behavior:**

Switch applications.

**(4) Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1638556835~21.04~b2cfd69
  Candidate: 1.1.0~1638556835~21.04~b2cfd69
  Version table:
 *** 1.1.0~1638556835~21.04~b2cfd69 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

system

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

**Comment by mmstick** [comment]
Please create a PR with the change.

**Comment by jacobgkau** [comment]
I am not able to recreate this on Pop!_OS 21.04 (the version it was reported on.) I've tried having regular windows, Spotify, Floating Window Exceptions, the `break-my-pop-shell.py` script, and a Proton game open, but I still see the alt-tab switcher work.

@abrighton Are there any particular apps you have open when this issue occurs, that we can use to check for this and similar issues in the future?

**Comment by abrighton** [comment]
I think the culprit may be LibreOffice Calc, which I have set to autostart (via a .desktop file in ~/.config/autostart/
) and which always displays a "recovery" window when it is autostarted, foe example after a reboot. This little window, which shows you the last documents that were open and asks if you want to recover them, seems to cause "app" to be null when switching applications with Alt-TAB.

**Comment by jacobgkau** [comment]
Thank you, I can recreate the issue by inducing the Document Recovery dialog in LibreOffice.

**Comment by gruvw** [comment]
same issue here, how to fix ?

**Comment by jacobgkau** [comment]
@gruvw the issue was fixed with https://github.com/pop-os/shell/pull/1265 and should no longer be occurring. (This issue should have been closed when that PR was merged.) Can you please provide the output of `apt policy pop-shell` to confirm what version you're running?

**Comment by gruvw** [comment]
Finally, I don't thing it is the same issue, after checking the `extensions.js` the line has been modified.

Output of `apt policy pop-shell`:
```
pop-shell:
  Installed: 1.1.0~1639174177~21.10~de901ae
  Candidate: 1.1.0~1639174177~21.10~de901ae
  Version table:
 *** 1.1.0~1639174177~21.10~de901ae 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
       1001 http://apt.pop-os.org/release impish/main i386 Packages
        100 /var/lib/dpkg/status
```

My issue is that the window selection menu stays display on the screen after releasing alt tab.
I created a new issue on pop-os/pop.

**Comment by jacobgkau** [comment]
Excellent, we'll continue with your issue [there](https://github.com/pop-os/pop/issues/2138) and I'll close this one.
