### ISSUE TITLE
[Feature Request] Option to mark all tiled window as maximized

### ISSUE THREAD

**Issue by xsrvmy** [pop-os/shell#1272]
Is it possible for there to be a way to mark tiled windows as maximized? This would mean
- Window decorations would not be rounded, which looks cleaner when gaps are off, and there would be a visual indication of whether a window is floating or not
- The terminal app can be freely sized. 
- A rendering bug when Firefox or Chrome is near a monitor edge would no longer happen

Note that I believe that this may be possible because I was able to produce a windows that is considered maximized but not covering the entire monitor by moving a maximized window onto a different monitor with lower scaling via keyboard.

**Comment by mmstick** [comment]
It's not possible to achieve this in the Javascript layer. It'd be an unreliable hack that breaks a lot of functionality that depends on maximization logic, too.
