### ISSUE TITLE
Desktop background not updating  on wallpaper change

### ISSUE THREAD

**Issue by rysteph** [pop-os/shell#1276]
After upgrading to 21.10, the desktop background does not update to reflect a change in wallpaper. It does appear to have changed when showing all workspaces, but then reverts to the previous background when a workspace is selected.

**Comment by StarpTech** [comment]
Hi, I can reproduce it too. Any fix?

**Comment by rysteph** [comment]
I have the problem on an older Acer laptop, but not on a gateway of about the same age. I haven't found a fix. If I do switch background using Settings->Background, I then switch to Settings->Displays and toggle the 'Fraction Scaling' button off and back on again which seems to fix things up. I wish there was an easier way like F5 to refresh the desktop or something. A proper fix would be better.

**Comment by jacobgkau** [comment]
This is a duplicate of https://github.com/pop-os/pop/issues/2066.

If the issue stops after disabling the Pop Shell extension, please leave a comment on that issue so we can transfer it to the appropriate repository.

**Comment by rysteph** [comment]
That did it. Thanks!

**Comment by rysteph** [comment]
Pop Shell extension is still disabled and the issue is happening again :(

**Comment by Daasin** [comment]
> Pop Shell extension is still disabled and the issue is happening again :(

Same for me 🤔
