### ISSUE TITLE
Lost ability to close the windows via ctrl+q in the launcher

### ISSUE THREAD

**Issue by dodalovic** [pop-os/shell#1278]
If I recall correctly, once I press the Super key, and if I want to close the highlighted app, I was able to do it previously via `ctrl+q` combo. 
It doesn't work anymore. 

Any thoughts?
Thanks for the wonderful product!

**Comment by mmstick** [comment]
That was never supported. The Super key is always held with OS shortcuts. Ctrl + Q would be an application-level shortcut that not every application is going to support.

**Comment by dodalovic** [comment]
https://github.com/pop-os/shell/issues/857#issuecomment-829093307

**Comment by 13r0ck** [comment]
Closed via pop-os/launcher#75
