### ISSUE TITLE
Windows on different workspaces sometimes appear behind windows on the current workspace

### ISSUE THREAD

**Issue by isantop** [pop-os/shell#128]
Occasionally when using the system, a window from another workspace will be visible behind the windows on the current workspace. When this is the case, the window can't be interacted with except for very basic tasks (like restoring a maximized window). Clicking on the window does not change focus, and controls within the window cannot be clicked or otherwise interacted with. Sometimes, changing workspaces will make the issue go away. 

I can reliably trigger this by opening popover widgets, and by opening the Extensions app. This happens with tiling enabled or disabled (but does not happen if I disable Pop Shell in Extensions).

**Comment by isantop** [comment]
![Screenshot from 2020-03-30 14-58-21](https://user-images.githubusercontent.com/5883565/77961969-ef619780-7297-11ea-8d4b-df61073d12b6.png)

In this screenshot, VS Code is actually on the workspace above my current workspace, not on this one. However, it showed up when I opened the that's open.

**Comment by mmstick** [comment]
This is a bug in GNOME 3.36.0

https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1869358
https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1868911

**Comment by mmstick** [comment]
New upstream version of GNOME Shell may have fixed this. We'll find out soon.

https://github.com/pop-os/gnome-shell/commit/34b47948235cb95e1b4a60e8d7ae7dfb1dbc5aaf

**Comment by mmstick** [comment]
Fixed upstream
