### ISSUE TITLE
Tiling doesn't work in Fedora 35 Gnome 41.2 (X11)

### ISSUE THREAD

**Issue by josephmahede** [pop-os/shell#1281]
**(1) Issue/Bug Description:**
Enabling "Tile windows" does nothing, the shell doesn't seem to be working.

**(2) Steps to reproduce (if you know):**
Fedora 35 with Gnome. Installed from source.

**(3) Expected behavior:**
idk

**(4) Distribution (run `cat /etc/os-release`):**
 ```
AME="Fedora Linux"
VERSION="35 (Workstation Edition)"
ID=fedora
VERSION_ID=35
VERSION_CODENAME=""
PLATFORM_ID="platform:f35"
PRETTY_NAME="Fedora Linux 35 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f35/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=35
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=35
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```
**(5) Gnome Shell version:**
41.2 X11

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

From pop shell in Gnome extensions, it says version 2.

**(7) Where was Pop Shell installed from:**
cloned the repo from github page and ran ```make local-install```

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
Primary (5120x1440), Secondary (2560x1440)

**(9) Other Installed/Enabled Extensions:**
Dash to panel
ArcMenu
Espresso
Improved Workspace Indicator
No overview at start-p
Tray Icons: Reloaded
Removable Drive Menu
Sound Input & Output Device Chooser
Material Shell (I have it installed but not enabled)

**(10) Other Notes:**
N/A

**Comment by praxis88** [comment]
I fixed this by installing something called xprop

It was throwing all kinds of errors in the system journal from popshell looking for xprop

**Comment by josephmahede** [comment]
@praxis88 Thanks that worked!

**Comment by praxis88** [comment]
It probably should be listed as a dependency
