### ISSUE TITLE
Blank desktop pop-up notifications after upgrading to 21.10

### ISSUE THREAD

**Issue by varajala** [pop-os/shell#1297]
**(1) Issue/Bug Description:**
All desktop pop-up notifications are "empty". They are still shown correctly in the notification list when Super+V is pressed...

![blank-notification](https://user-images.githubusercontent.com/73927942/147821576-ffb6ce06-5679-4edd-b893-983280b08656.png)

![notification-list](https://user-images.githubusercontent.com/73927942/147820780-b6c7fa1b-9a0e-45af-ad62-c99965478a75.png)

**(2) Steps to reproduce (if you know):**

With notify-send:

```notify-send 'Hello world!' 'This is an example notification.' --icon=dialog-information```

**(3) Expected behavior:**
Pop-up displays as in notification list.

**(4) Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**
40.5 (from gnome-shell --version)

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1639174177~21.10~de901ae
  Candidate: 1.1.0~1639174177~21.10~de901ae
  Version table:
 *** 1.1.0~1639174177~21.10~de901ae 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
       1001 http://apt.pop-os.org/release impish/main i386 Packages
        100 /var/lib/dpkg/status

```

**(7) Where was Pop Shell installed from:**
Pop!_OS repos, installed by default, notifications went blank after upgrading to 21.10.

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
One external display in addition to the laptop display. Using only the laptop display does not fix this issue.

**(9) Other Installed/Enabled Extensions:**
User Themes. Disabling User Themes and reverting back to default Pop!_OS theme does not fix this issue.
No custom icon theme.

**(10) Other Notes:**
Clicking on the notification still works. For example when notification for available system updates comes, clicking the pop-up will open Pop-Shop.

**Comment by mmstick** [comment]
Closing because this issue is unrelated to Pop Shell.

I would verify if the theme is causing this issue with notifications.
