### ISSUE TITLE
Active hint leaves artifact when window closed from overview

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#130]
Steps to reproduce:

1. Open 2 terminal windows
2. Close one of them from activity overview

Active hint remains on the screen for a long time afterwards.

**Comment by mmstick** [comment]
This I can't replicate. Exiting the overview causes the remaining terminal to grab focus, and the active hint then begins tracking the remaining terminal.

**Comment by nicolae-stroncea** [comment]
Here's an example of what I'm referring to:

![output](https://user-images.githubusercontent.com/39338488/78064566-f358ec80-735f-11ea-9cca-345bf6e47140.gif)

**Comment by leviport** [comment]
Same here, I just don't see it happen on the latest commits.

**Comment by nicolae-stroncea** [comment]
I'm on Gnome 3.34.4.  I'll update this if it still happens once I move to 3.36
