### ISSUE TITLE
Pop-OS launcher not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by lucastrschneider** [pop-os/shell#1302]
**(1) Issue/Bug Description:**
When installing pop-shell from source in a fresh Ubuntu 20.04 install, the launcher doesn't show running applications and doesn't show any of the installed applications when searching.
OBS; Tiling works fine, only the launcher seems to be broken.

**(2) Steps to reproduce (if you know):**
- Boot on a fresh Ubuntu 20.04 install
- Follow [system76's guide](https://support.system76.com/articles/pop-shell/) to install pop shell
```bash
sudo apt install git node-typescript make
git clone https://github.com/pop-os/shell.git
cd shell
make local-install
``` 
- Reboot
- Try to use Pop launcher (`super + /`)

**(3) Expected behavior:**
See all running applications and being able to search and launch installed applications

**(4) Distribution (run `cat /etc/os-release`):**
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**(5) Gnome Shell version:**
GNOME Shell 3.36.9

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
Latest commit on master
c7390c8c370c81aaad285b47cd3915a7c4708b98

**(7) Where was Pop Shell installed from:**
Built locally

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
2 x 1080p (Horizontal)

**(9) Other Installed/Enabled Extensions:**
- User Themes

**(10) Other Notes:**
After that, I tried building from the [latest release](https://github.com/pop-os/shell/releases/tag/1.2.0), and everything works fine.

**Comment by mmstick** [comment]
The launcher service is in the pop-os/launcher repository

**Comment by dhd0004** [comment]
I have the same problem.
`                                                                                                                                                                                                                                                   
gnome-shell --version                                                                                                                                                                                                                                                         
GNOME Shell 41.1
`
This is what i see when i launch the "pop launcher".
![2022-01-19_10-49](https://user-images.githubusercontent.com/1458162/150106291-084b738a-d08f-4c7a-8ab6-681a20509892.png)

**Comment by viciousvaquita** [comment]
Workaround for me was to go back to release 1.2.0:
`git checkout 1.2.0 (it goes to 891525b)`
`make local-install`
launcher worked again

**Comment by carbeer** [comment]
Had the same issue, going back to 1.2.0 resolved the issue for me as well, thanks @viciousvaquita!

**Comment by dhd0004** [comment]
With 1.2.0 i dont have problems. But i would like to update pop-shell beacuse i have other problems. Like resizing windows.
https://github.com/pop-os/shell/issues/1232

**Comment by mmstick** [comment]
You have to install pop-os/launcher

**Comment by EmilyisWIP** [comment]
Hey there, I am having the same issues, I have installed pop-os/launcher and even tried cosmic-launcher, which works, but doesn't use a nice interface.

Any chance of re-opening this?

![image](https://user-images.githubusercontent.com/26607304/174812378-be0ea9c2-4619-4bd1-99a9-3d7904a514bd.png)
![image](https://user-images.githubusercontent.com/26607304/174812405-749c53e2-4cb9-4f2c-b78a-a5de77608075.png)

**Comment by YSW0630** [comment]
https://github.com/pop-os/launcher
@mmstick thx, finally work😄
