### ISSUE TITLE
x-terminal-emulator does not exist in all distros

### ISSUE THREAD

**Issue by coxackie** [pop-os/shell#131]
User of Arch linux. In Launcher mode, `t:` will fail because the virtual package `x-terminal-emulator` does not exist. Presumable it will be the same in other distros as well.

**Comment by mmstick** [comment]
`x-terminal-emulator` is symlink that points to the system's default terminal emulator via Debian's alternatives system. Arch has no way defining a default terminal, so this will have to be a configuration setting requiring you to define which terminal emulator to use. I could display a dialog asking the user to write in the path of the terminal to use on first use if the OS doesn't support alternatives.

**Comment by coxackie** [comment]
Defaulting to gnome-terminal and having a config setting to change this would make most sense for gnome environments.
