### ISSUE TITLE
Pop-Shell prevents flameshot to close after pressing CTRL-C or ESC

### ISSUE THREAD

**Issue by ad-on-is** [pop-os/shell#1315]
Flameshot usually closes when a selection is copied to the clipboard CTRL-C or when the ESC-key is hit. This however does not work, when pop-shell tiling mode is active.

## Steps to reproduce
- Enable tiling mode in pop-shell
- Open flameshot to take a screenshot
- Press ESC to exit flameshot (does not work)
- Select an area and press CTRL-C to copy the selection to clipboard (does not work)

When I disable tiling-mode in pop-shell, everything works as expected.

## System 
- EndeavourOS - 5.15.13-arch1-1
- GNOME 41.3

**Comment by leviport** [comment]
I'm seeing the same thing in both the .deb and flatpak versions of Flameshot.

**Comment by ad-on-is** [comment]
Updating to the newest version of pop-shell solved the issue for me.

```
Name            : gnome-shell-extension-pop-shell-git
Version         : r846.b3b2e35-1
Description     : Pop Shell - Tiling window management in Gnome (WIP)
Architecture    : any
URL             : https://github.com/pop-os/shell
Licenses        : GPLv3
Groups          : None
Provides        : None
Depends On      : gnome-shell  pop-shell-shortcuts-git  pop-launcher-git  fd
Optional Deps   : gnome-shell-extensions: native-window extension for improved window placement [installed]
Required By     : None
Optional For    : None
Conflicts With  : gnome-shell-extension-pop-shell
Replaces        : None
Installed Size  : 369,26 KiB
Packager        : Unknown Packager
Build Date      : Do 13 Jän 2022 17:42:21
Install Date    : Do 13 Jän 2022 17:42:29
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : None
```
