### ISSUE TITLE
Popovers in the header in Steam can not be clicked on in tiling mode

### ISSUE THREAD

**Issue by SER-3604** [pop-os/shell#1321]
**(1) Issue/Bug Description:**

When tiling mode is on, using the header bar of the Steam application (the Steam, View, Friends, Games, Help menu bar as well as the quick navigation like Store, Library, Community, and User) don't work, except as simple buttons. The popovers that appear upon hovering over various buttons/text cannot be clicked on.

When not in tiling mode, this does not occur.

**(2) Steps to reproduce (if you know):**

1. Enable tiling mode in the pop-shell.
2. Open the Steam application (native package, not flatpak, if that matters).
3. Hover over any of the text buttons in the header/nav bar and attempt to click on any of the content in the popover.
4. Additionally, click on the account menu on the top right and attempt to click on the popover that appears there.

**(3) Expected behavior:**

The content in the popovers are clickable.

**(4) Distribution (run `cat /etc/os-release`):**
 
Pop!_OS 21.10

**(5) Gnome Shell version:**

40.4.0

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1642015119~21.10~b3b2e35
  Candidate: 1.1.0~1642015119~21.10~b3b2e35
  Version table:
 *** 1.1.0~1642015119~21.10~b3b2e35 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
       1001 http://apt.pop-os.org/release impish/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

The official pop/system76 repositories for Pop!_OS.

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1 x 1440p

**(9) Other Installed/Enabled Extensions:**

All default Pop!_OS extensions:
Cosmic Dock
Cosmic Workspaces
Desktop Icons (disabled by me)
Pop COSMIC
System76 Power
Ubuntu AppIndicators

No other extensions added by me.

**(10) Other Notes:**

I had thought the latest commit would fix this issue, but it didn't. Still, I think it's related to #1312.

**Comment by leviport** [comment]
Will be fixed by https://github.com/pop-os/shell/pull/1319

**Comment by SER-3604** [comment]
Alright, I’ll go ahead and close the issue early.

**Comment by jacobgkau** [comment]
Thank you, but it's good to keep the issue open for tracking purposes until the fix is merged.
