### ISSUE TITLE
Enabling Tile Windows option in Pop Shell causes Steam to become unresponsive

### ISSUE THREAD

**Issue by italoghost** [pop-os/shell#1324]
**(1) Issue/Bug Description:**

Since the last two updates on Pop Shell, enabling the "Tile Windows" option makes the top menu bar on Steam become unresponsive. Sometimes it works when I click in one of the options, but generally it doesn't work.

I don't know if it is happening with other applications.

**(2) Steps to reproduce (if you know):**

1) Open Steam with "Tile Windows" option enabled;
2) Try to click in one of the options on the top menu bar - it won't work.
3) Disabling it makes the options to work as usual.

**(3) Expected behavior:**

The Pop Shell shouldn't interfere with the buttons on Steam while the "Tile Windows" option is enabled.

**(4) Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**

GNOME 40.5

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Instalado: 1.1.0~1642182148~21.10~21745c4
  Candidato: 1.1.0~1642182148~21.10~21745c4
  Tabela de versão:
 *** 1.1.0~1642182148~21.10~21745c4 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
       1001 http://apt.pop-os.org/release impish/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

Natively

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1 x 1080p

**(9) Other Installed/Enabled Extensions:**

- Bluetooth Quick Connect
- Cosmic Dock
- Cosmic Workspaces
- Desktop Icons
- Extension List
- Freon
- GameMode
- Pop COSMIC
- Pop Shell
- Sound Input and Output Device Chooser
- System 76 Power
- Ubuntu AppIndicators

**(10) Other Notes:**

**Comment by SER-3604** [comment]
Have you restarted your system since installing the latest pop-shell update?

**Comment by mmstick** [comment]
Was fixed the day before
