### ISSUE TITLE
Firefox not respecting the tiling

### ISSUE THREAD

**Issue by justdanyul** [pop-os/shell#133]
I'm on Arch Linux , kernel 5.5.13, Gnome 3.36 and firefox 74.0-2

Now, Firefox doesn't get titled, all other apps I tried does (including Chrome).

**Comment by justdanyul** [comment]
Switching to Xorg fixed it.

**Comment by mmstick** [comment]
Do you have this setting set in Firefox?

![Screenshot from 2020-03-31 17-17-58](https://user-images.githubusercontent.com/4143535/78083744-9c5d1280-7373-11ea-8fc5-2c49b9715e48.png)

**Comment by mmstick** [comment]
Duplicate of #32
