### ISSUE TITLE
Empty launcher (super + /) after installing on Ubuntu 20.04

### ISSUE THREAD

**Issue by dodalovic** [pop-os/shell#1331]
After following the instructions, after I press `super + /`, I just get an empty launcher, no matter what I type in.

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

**Comment by cmdoret** [comment]
Same, but as mentioned in https://github.com/pop-os/shell/issues/1329, it works if you build from the latest release

**Comment by JJGadgets** [comment]
> Same, but as mentioned in #1329, it works if you build from the latest release

To install for all users in a directory that is definitely in `$PATH`, I ran this make command to install to `/usr` where the `pop-launcher` binary will go to `/usr/bin`:
``` shell
make && sudo PWD=$PWD DESTDIR=/ make install
```

**Comment by dhd0004** [comment]
i have the same problem. Launcher is empty in last build.

**Comment by mmstick** [comment]
You have to install pop-os/launcher

**Comment by amireldor** [comment]
I also had to put pop-launcher in my PATH for stuff to work (then logout and login).
