### ISSUE TITLE
[Fedora 35/GNOME Shell 41] Nothing works under Xorg

### ISSUE THREAD

**Issue by pesader** [pop-os/shell#1334]
**(1) Issue/Bug Description:**
The extension if not working under Xorg.
Its applet appears on the panel (showing it was properly enabled) but window auto-tilling, navigation, resizing and moving don't work. The launcher does not show open windows.
Everything is working perfectly under Wayland.

**(2) Steps to reproduce (if you know):**
- Log out into gdm
- Select "GNOME on Xorg" and log back in
- The extension will load, but will not work

**(3) Expected behavior:**
The extension should work on Xorg.

**(4) Distribution (run `cat /etc/os-release`):**
 ```
NAME="Fedora Linux"
VERSION="35.20220123.0 (Silverblue)"
ID=fedora
VERSION_ID=35
VERSION_CODENAME=""
PLATFORM_ID="platform:f35"
PRETTY_NAME="Fedora Linux 35.20220123.0 (Silverblue)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-silverblue/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=35
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=35
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Silverblue"
VARIANT_ID=silverblue
OSTREE_VERSION='35.20220123.0'
```

**(5) Gnome Shell version:**
GNOME Shell 41.3

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```git
commit 21745c4a8076ad52c9ccc77ca5726f5c7b83de6c (HEAD -> master, origin/master, origin/HEAD)
Author: Michael Aaron Murphy <mmstick@pm.me>
Date:   Thu Jan 13 19:35:17 2022 +0100

    fix(tiling): Steam sub-menus are unclickable in tiling mode
```

**(7) Where was Pop Shell installed from:**
Built locally

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
2560 x 1080, Horizontal

**(9) Other Installed/Enabled Extensions:**
![image](https://user-images.githubusercontent.com/65264536/150690388-c0df8a95-469f-44ec-9531-a97280c90f0f.png)

**(10) Other Notes:**
Reproduced the bug with every other extension disabled.
I also tried re-compiling and re-installing, but that didn't fix the issue.

As usual, thanks for developing pop-shell. Couldn't do without it :)

**Comment by pesader** [comment]
Update: I checked the logs and it seems like `xprop` was missing. I was not aware that this was a dependency though, as it is not documented anywhere as such.

I ran Silverblue on a VM and installed pop-shell same way as I did in the host. This time it worked perfectly fine on Xorg, without `xprop`, so I don't know what caused the issue in the first place.

**Comment by jacobgkau** [comment]
xprop is listed in the installation instructions for Fedora: https://github.com/pop-os/shell#packaging-status 

It was added in this PR: https://github.com/pop-os/shell/pull/1273

Feel free to open a PR with your suggested changes if you feel this should be called out anywhere else.

**Comment by pesader** [comment]
Oooh, I usually prefer to install via your `make install` script. May I submit a PR that includes the `xprop` dependency on the [Developers](https://github.com/pop-os/shell#developers) section of the README?
