### ISSUE TITLE
In tiling mode I cannot move windows to the middle screen, if it's empty

### ISSUE THREAD

**Issue by FrederikP** [pop-os/shell#1375]
**(1) Issue/Bug Description:**

The following is an issue with the Tiling mode.

I am using three monitors and when I switched the right monitor to a new one with a higher resolution I began facing this issue (again. I already had that pre-covid when I was still in the office with a similar setup).
So the current setup is:
left: 1080p, middle 1440p, right 1440p

Before it was: left: 1080p, middle 1440p, right 1080p With this setup the bug wasn't the same, but it was still weird because I sometimes had to press Super+Up to get windows to the middle screen.

But let's concentrate on the bug I currently face. When there are no windows on the middle screen, then I'm not able to move any window there from the right or left side. They always skip the middle screen and end up on the screen on the opposite side. As soon as there is a window on the middle screen it's possible to move other windows there from the left or right screen. So as a workaround I open a terminal on the middle screen and then move the other window there and close the terminal again, but that's annoying.

I created a screen recording to show you what happens. Also for comparison I created a window on the middle screen to show that it works then.

https://user-images.githubusercontent.com/483596/159651154-6abf9b74-a021-4d84-a3a6-2dcf139c38ae.mp4

**(2) Steps to reproduce (if you know):**

Probably have a similar monitor setup and have no window in the middle.

**(3) Expected behavior:**

I should be able to move windows from the left screen to the middle (SUPER+RIGHT) and the right screen to the middle (SUPER+LEFT), even if there is no window in the middle yet.

**(4) Distribution (run `cat /etc/os-release`):**
 
```
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**

```
GNOME Shell 40.5
```

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1646843863~21.10~396b2f3
  Candidate: 1.1.0~1646843863~21.10~396b2f3
  Version table:
 *** 1.1.0~1646843863~21.10~396b2f3 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
       1001 http://apt.pop-os.org/release impish/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

Official repos. Didn't tinker around

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

left: 1080p, middle 1440p, right 1440p
all horizontal
middle primary

**(9) Other Installed/Enabled Extensions:**

nothing, only pop-os vanilla stuff

**(10) Other Notes:**

Like I said: I think that this bug already existed far back in early 2020 as I had a deja vu last week when I changed my monitor setup.

**Comment by leviport** [comment]
I also see this on my home setup (1440p left, 4k@100% middle, 1440p left) and my work setup (1080p left, 4k@100% middle, 1440p left). I usually work around it by moving the window up instead of left or right. Since the middle monitor is taller, it usually ends up there. I'd be curious to know if it happens with 3 displays of the same resolution, all aligned horizontally with each other.

**Comment by FrederikP** [comment]
> Since the middle monitor is taller, it usually ends up there.

Yes that worked for me as well, when my right monitor was only 1080p and thus the middle monitor was a bit taller.

Glad to see that I'm not the only one with these issues.

**Comment by mmstick** [comment]
I don't have three screens to test with but I assume it's because the algorithm for selecting a window to attach doesn't account for an empty screen being between it and the nearest window found.
