### ISSUE TITLE
Handle workspaces being created between workspaces

### ISSUE THREAD

**Issue by ccwky11** [pop-os/shell#139]
As the title says, this is the issue I have been facing since installing this extension, I have also found that the keybinds seem to not work as intended. System info:

> **Manjaro 19.0.2
> Gnome 3.36
> Wayland**

**Notable other extensions:** 
> **Dash to panel**
> **NoAnnoyance v2
> Panel OSD**

I am using the latest version of the extension at the moment of this post.

**Comment by mmstick** [comment]
I'm not sure what you mean. Does this issue happen in X11?

**Comment by ccwky11** [comment]
What I mean is that when I drag a window to a new workspace in overview, oftentimes a different window will also move to that new workspace, I haven't found a way to consistently replicate it. (i.e. I intend to drag google chrome to a new workspace and telegram also moves to that workspace from an entirely different workspace) 

I haven't checked X11 yet but I have found that the issue doesn't seem to appear if I drag windows via my touchscreen.

 I have also noticed that when I use the Parsec Gaming client to connect to my desktop, the mouse is constantly moving inside my connection until I kill the connection, set the window to floating and then I can resume with no issue, perhaps this is somehow related?

**Comment by mmstick** [comment]
I haven't seen this behavior before, hence why I'm wondering if it's specific to X11. I can't say for certain if Parsec Gaming has anything to do with this. That is a different issue that should reported.

**Comment by ccwky11** [comment]
New Update:
I have now discovered that this issue presents itself when creating a workspace in between 2 already existing workspaces. the issue also presents itself in both X11 (per very limited testing) and wayland. the issue seems not to present when moving items to a brand new workspace at the very bottom of the list of workspaces.

**Comment by jeroen7s** [comment]
yup, i'm having the same issue.
This basically makes the tiling functionality unusable for me.

**Comment by WatchMkr** [comment]
This bug appears fix in the latest release. I'm able to create and destroy new workspaces between other workspaces and windows are tiled correctly in the new workspaces.

**Comment by leviport** [comment]
How about a new workspace at the beginning of the list? I still see arbitrary windows move to the new workspace if I do that.

**Comment by WatchMkr** [comment]
I have bugs with that description already. Trying to triage these down. As this one is between workspaces I'm closing it.
