### ISSUE TITLE
launcher is off-center if dock is on the right/left

### ISSUE THREAD

**Issue by smezzy** [pop-os/shell#1394]
![image](https://user-images.githubusercontent.com/25137901/162346409-80e2961e-82e4-4cad-9ef1-333c293cbb65.png)
![image](https://user-images.githubusercontent.com/25137901/162346460-c72ecac1-d58a-4b08-99f4-72c501e89bad.png)

this is pop os 21.10, but still happens in pop os 22.04

**Comment by dabasdev** [comment]
I have the same problem , launcher position not in the center , how can i re-center the launcher ?
Note: I'm using pop 22
![Screenshot from 2022-05-21 20-19-20](https://user-images.githubusercontent.com/46471427/169662511-14317cb4-6083-4971-9046-1f28bd43b42d.png)
?

**Comment by dabasdev** [comment]
I don't know how fix that !

**Comment by jacobgkau** [comment]
@dabasdev You are not experiencing the same issue being described here because your dock is set to the bottom of the screen in your screenshot. The issue you are experiencing is https://github.com/pop-os/shell/issues/1384.
