### ISSUE TITLE
[GNOME 41] Wrong active hint position and weirdly display in activities overview after close 1 of 2 Kitty windows

### ISSUE THREAD

**Issue by davidhoang05022009** [pop-os/shell#1395]
**(1) Issue/Bug Description:**
Kitty shows active hint on a half of window and if I go to activities overview, I see it display another half window of Kitty outside of workspace overview

**(2) Steps to reproduce (if you know):**
Open 1 Kitty window, then open another, then close one of them 
[*Reproduce video*](https://user-images.githubusercontent.com/71539678/162668329-ee85c1c9-4882-47e8-9153-19363182987a.mp4)

**(3) Expected behavior:**
Kitty has a normal active hint and shows normally in workspace overview like a maximized window

**(4) Distribution (run `cat /etc/os-release`):**
```
NAME="Fedora Linux"
VERSION="35 (Workstation Edition)"
ID=fedora
VERSION_ID=35
VERSION_CODENAME=""
PLATFORM_ID="platform:f35"
PRETTY_NAME="Fedora Linux 35 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f35/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=35
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=35
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

**(5) Gnome Shell version:**
`GNOME 41.4`

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

Commit cb76a4cae1fec93de196f833f39cdd06a31093ce 
(before using Git version I used 1.2.0^4.1fddaa8-2.fc35 because of issue #1345 in 1.2.0^5.21745c4-1.fc35)

**(7) Where was Pop Shell installed from:**
From Git

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1 x 1920x1080 primary laptop display

**(9) Other Installed/Enabled Extensions:**

*Installed:*
```
pop-shell@system76.com
apps-menu@gnome-shell-extensions.gcampax.github.com
background-logo@fedorahosted.org
launch-new-instance@gnome-shell-extensions.gcampax.github.com
places-menu@gnome-shell-extensions.gcampax.github.com
window-list@gnome-shell-extensions.gcampax.github.com
user-theme@gnome-shell-extensions.gcampax.github.com
```
*Enabled*
```
pop-shell@system76.com
background-logo@fedorahosted.org
```

**(10) Other Notes:**

_Update:_ This issue still exists on GNOME 42

**Comment by rivenirvana** [comment]
This bug does not occur if I revert my kitty config to showing window decorations ("hide_window_decorations off" in kitty.conf).
Using Fedora 36 Beta, Wayland in GNOME 42

**Comment by MichaelAquilina** [comment]
Is there a chance this would be fixed? It seems like only a workaround was suggested rather than fixing the root issue?
