### ISSUE TITLE
Feature request: Maximize lone windows in autotiling

### ISSUE THREAD

**Issue by Chrysostomus** [pop-os/shell#1396]
**(1) Issue/Bug Description:**
When the windows are autotilen, the rounded window corners leave weird gaps along the top panel. 
![image](https://user-images.githubusercontent.com/12002226/163459241-c75bb57c-8912-4bba-bdb2-bcc1413a3ae1.png)

**(2) Steps to reproduce (if you know):**

Open one or more windows in autotiling mode

**(3) Expected behavior:**
When there are only 1 or 2 open windows on a desktop, leverage mutters native maximize and half tile functions so that there are no weird gaps.
![image](https://user-images.githubusercontent.com/12002226/163459565-e9d1fdb2-1011-4d11-9150-142578db852e.png)

**(4) Distribution (run `cat /etc/os-release`):**
Manjaro, but this is irrelevant 

**(5) Gnome Shell version:**
42.0-1

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

 ```cb76a4cae1fec93de196f833f39cdd06a31093ce``` 

**(7) Where was Pop Shell installed from:**

Manjaro repositories

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

15" 1920x1080p, 2x 27" don't know the resolution, not 4k but more than full hd

**(9) Other Installed/Enabled Extensions:**

appindicatorsupport@rgcjonas.gmail.com
dash-to-dock@micxgx.gmail.com
gnome-ui-tune@itstime.tech
pamac-updates@manjaro.org
pop-shell@system76.com

**Comment by leviport** [comment]
I think this might be a duplicate of https://github.com/pop-os/shell/issues/1369

**Comment by Chrysostomus** [comment]
Not entirely because the other issue might be related to smart gaps, but similar enough to be merged.
