### ISSUE TITLE
Gnome-extensions-app doesn't open

### ISSUE THREAD

**Issue by gabriele2000** [pop-os/shell#1399]
**(1) Issue/Bug Description:**

This application doesn't open since updating to Pop!_Os 22.04, it simply crash at startup

**(2) Steps to reproduce (if you know):**

Try to open it, or run `gnome-extensions-app`

**(3) Expected behavior:**

`gnome-extensions-app` opens, I am able to manage the extensions

**(4) Distribution (run `cat /etc/os-release`):**
 
`NAME="Pop!_OS"
VERSION="22.04 LTS"`

**(5) Gnome Shell version:**

GNOME Shell 42.0

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```< Installed: 1.1.0~1649099191~22.04~cb76a4c >```

**(7) Where was Pop Shell installed from:**

apt, automatic installation since the operating system is Pop!_Os

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1080p, Primary (Horizontal)

**(9) Other Installed/Enabled Extensions:**

It doesn't matter

**(10) Other Notes:**

the CLI output gives a generic `segmentation fault (core dumped)`

**Comment by mmstick** [comment]
Can't replicate. this appears to be from the beta.

**Comment by gabriele2000** [comment]
> Can't replicate. this appears to be from the beta.

Well it's still present... what's the package name in your PC?

**Comment by jacobgkau** [comment]
> Well it's still present... what's the package name in your PC?

I am able to open it successfully with the `gnome-extensions-app` command from your issue description.

Is there a reason you think this is related to Pop Shell, the window tiling extension, or is it a general Pop!_OS issue? If you run `gnome-extensions disable pop-shell@system76.com` to disable Pop Shell and then run `gnome-extensions-app`, does it work? (If not, then this would not be a Pop Shell issue.)

**Comment by gabriele2000** [comment]
No, still (segmentation fault) and reinstalling the package doesn't help

Il mar 3 mag 2022, 22:18 Jacob Kauffmann ***@***.***> ha
scritto:

**Comment by gabriele2000** [comment]
After reinstalling the package by purging everything releated, I am now able to run it.
