### ISSUE TITLE
Can not enable pop-shell extension nixos

### ISSUE THREAD

**Issue by Micka-R** [pop-os/shell#1401]
**(1) Issue/Bug Description:**

After the installation of the pop-shell extension,  I can not enable it. Through the extension GUI, I have this message:
`GLib.FileError: Failed to open file “/home/pkngr/.local/share/gnome-shell/extensions/pop-shell@system76.com/schemas/gschemas.compiled”: open() failed: No such file or directory`
And through my terminal I get a black screen

**(2) Steps to reproduce:**
1- clone the repo / install typescript / install GNU make
2- make local-install
3- logout to make the extension appear as I can not restart gnome-shell on Wayland
4- This is where I am.

**(3) Expected behavior:**
I should be able to enable the extension.

**(4) Distribution:**
 
NAME=NixOS
ID=nixos
VERSION="21.11 (Porcupine)"
VERSION_CODENAME=porcupine
VERSION_ID="21.11"
BUILD_ID="21.11.337053.2f06b87f64b"
PRETTY_NAME="NixOS 21.11 (Porcupine)"
LOGO="nix-snowflake"
HOME_URL="https://nixos.org/"
DOCUMENTATION_URL="https://nixos.org/learn.html"
SUPPORT_URL="https://nixos.org/community.html"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"

**(5) Gnome Shell version:**

GNOME Shell 41.1

**(9) Other Installed/Enabled Extensions:**

dash to dock

**Comment by DAlperin** [comment]
Just ran into this. It's because glib-compile-schemas is not available. I'm gonna try and package something that exports that command sometime this week. I'll let you know.

**Comment by heywoodlh** [comment]
@DAlperin any updates on packaging that command?

**Comment by DAlperin** [comment]
Turns out nothing needs to be packaged. Use the existing `glib.dev` package :)

**Comment by vrinek** [comment]
> Turns out nothing needs to be packaged. Use the existing `glib.dev` package :)

@Micka-R, did the above suggestion solve your issue?

**Comment by Micka-R** [comment]
Well, I didn't have to try it popshell was added in the nixos package manager recently and it is working fine now.
