### ISSUE TITLE
Window lost focus if I move back and forth to a new workspace.

### ISSUE THREAD

**Issue by dth0** [pop-os/shell#1404]
**(1) Issue/Bug Description:**

Right after I updated my desktop to 22.04 I noticed an strange behavior, if I change my current workspace to a new/empty one and move back to the previous one (or any other workspace already in use) the shell will lose it focus, so I have to click on any window to regain the focus. 

https://user-images.githubusercontent.com/5497906/165548356-9bf2f1dc-c18d-4510-95dc-27e906003c70.mp4

I kept the active hint enabled so you can see when the focus is lost. (sorry for its quality)

**(2) Steps to reproduce (if you know):**
-> enable the tilling mode
-> open a few windows in different workspaces
-> move to between them to make sure one window will always be focused.
-> move now to an new/empty workspace and move back to the previous workspace.
-> you will see that the focus was lost and you have to click in one window to gain it again.

**(3) Expected behavior:**
Move back and forth between workspaces should always keep focus in one window. 

**(4) Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**
4.2

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```
pop-shell:
  Installed: 1.1.0~1649099191~22.04~cb76a4c
  Candidate: 1.1.0~1649099191~22.04~cb76a4c
  Version table:
 *** 1.1.0~1649099191~22.04~cb76a4c 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status
```

**(9) Other Installed/Enabled Extensions:**

![image](https://user-images.githubusercontent.com/5497906/165544709-d40a9d4f-e573-4dcf-aa72-aff1825c210d.png)

This issue also happens in another machine which doesn't have any extension installed

**Comment by leviport** [comment]
Is this the same as https://github.com/pop-os/beta/issues/415?

**Comment by oguzkarayemis** [comment]
@leviport, yeah, it's the same issue.

**Comment by leviport** [comment]
Thanks for confirming. I'll close this as a duplicate so as much information as possible is kept in just one place.
