### ISSUE TITLE
[bug] Some window types are invisible

### ISSUE THREAD

**Issue by herder** [pop-os/shell#141]
Hi, thank you for a great plugin!

With commit 3ede7c779d8c740eac11c297e6a4ea45e80f2d1b some app windows become invisible at startup. The app I have problems with is IntelliJ idea, but I suspect it might be the same for other Java apps. I have tested with Jetbrains CLion too, and that has the same behavior.

Popup dialogs from the main window are visible though: I see the startup tips and confirm exit dialogs at start and close.

This occurs whether I have Active hint enabled or not.

**Comment by mmstick** [comment]
Are you sure it's that commit? The changes in that commit are strictly exclusive to the launcher. It doesn't affect any part of window creation or management.

**Comment by herder** [comment]
No sorry, I got a false positive and pasted the wrong commit. I edited the issue to the correct one.

**Comment by herder** [comment]
Setting the `animate_windows` bool to false in extension.ts fixes the problem.

**Comment by kvaneesh** [comment]
was facing this with gnome 3.34 and commit 457b9a84b53227bf6a9f5043c13af8129944f93e. I had issues with gnome-terminal, chrome browser, etc. The above-suggested change fixed issue for me.

**Comment by mmstick** [comment]
IDEA works fine on my end. Are you both on 3.34? 3.34 is not supported.

**Comment by mmstick** [comment]
If you have this issue with 3.36, re-open this issue with logs
