### ISSUE TITLE
Suspend Issues

### ISSUE THREAD

**Issue by iAmG-r00t** [pop-os/shell#1413]
**(1) Issue/Bug Description:** I am unable to suspend my laptop both when connected to two external displays and when not connected to an external device.

When connected to external devices and I try to send the suspend signal, it locks the screen goes dim then turns on once again. If I try to close the lid, it doesn't suspend it stays on and when I open the lid it starts to glitch like the video below and I have to force shutdown of the laptop.

[video link](https://drive.google.com/file/d/1YUyMNYb4oRIuHatxYtzy5jAxOm0g3yak/view?usp=sharing)

**FYI:** I am using integrated graphics, with two external monitors

**(2) Steps to reproduce (if you know):**

**1st Issue:**
1. send suspend signal and wait to see if it will suspend.

**2nd Issue:**
1. Close lid without suspending
2. Open lid.

**(3) Expected behavior:**

1st issue; the device doesn't go to hibernate mode.

2nd issue; the device doesn't go to hibernate mode and then starts to glitch.

**(4) Distribution (run `cat /etc/os-release`):**
 
```sh
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**

GNOME Shell 42.0

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```sh
pop-shell:
  Installed: 1.1.0~1651514427~22.04~15e7acf
  Candidate: 1.1.0~1651514427~22.04~15e7acf
  Version table:
 *** 1.1.0~1651514427~22.04~15e7acf 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

Upgrade from 21.04

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

2 x 1080p external monitors all horizontal.  

**(9) Other Installed/Enabled Extensions:**

Clipboard indicator

**(10) Other Notes:**

**Comment by leviport** [comment]
Also I believe this may be a duplicate of https://github.com/pop-os/system76-power/issues/340

**Comment by iAmG-r00t** [comment]
This issue #449 actually fixed it. Running this command: `sudo kernelstub -a mem_sleep_default=deep` then restarting my PC fixed it. Now I can suspend even when having Bluetooth device connected.
