### ISSUE TITLE
No window is focused after moving window between workspaces and returning to previous workspace

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/shell#1421]
**(1) Issue/Bug Description:** After moving a window to another workspace, then returning to the first workspace, no window on that workspace is focused. This breaks keyboard navigation.

**(2) Steps to reproduce (if you know):**
1. Open multiple windows on two workspaces.
2. Move a window from one workspace to the other with Super-Shift-Up/Down.
    - At this stage, focus may be lost as described in https://github.com/pop-os/shell/issues/1415 (separate but related).
3. Return to the initial workspace.
    - No window is focused.
    - The active hint may erroneously show on an unfocused window.

**(3) Expected behavior:**
- A window should always be focused when navigating with the keyboard.
- The active hint should only ever show up on a window that is actually focused.

**(4) Distribution (run `cat /etc/os-release`):** Pop!_OS 22.04

**(5) Gnome Shell version:** 42

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):** 15e7acf

**(7) Where was Pop Shell installed from:** Pop!_OS repo.

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):** 1x 1080p

**(9) Other Installed/Enabled Extensions:** Pop!_OS defaults only.

**(10) Other Notes:**

https://github.com/pop-os/shell/issues/1415 is about a moved window not being focused after moving to a new workspace; this issue is about other windows not being focused when returning to the previous workspace.

Video examples:

- Firefox gets active hint, but is not actually focused, as can be seen from the lack of highlight on the dock:

https://user-images.githubusercontent.com/7199422/167172112-9e7ca147-170c-401e-976d-4022a2e26301.mp4

- No window has active hint after returning to previous workspace:

https://user-images.githubusercontent.com/7199422/167172116-af50a469-65e0-4fd2-a7a5-612224273aef.mp4

- Longer sequence for no window having active hint (may provide a better clue of the cause):

https://user-images.githubusercontent.com/7199422/167172127-4bd81348-d17a-4438-bf75-e9c335dc4263.mp4

**Comment by jacobgkau** [comment]
I'm assuming this is more fallout from https://github.com/pop-os/shell/pull/1408, which saves the last-active window per workspace. If we just moved the last-active window out of a workspace, then we need to pick a new active window on returning to that workspace.

**Comment by MathieuDR** [comment]
> I'm assuming this is more fallout from #1408, which saves the last-active window per workspace. If we just moved the last-active window out of a workspace, then we need to pick a new active window on returning to that workspace.

I think this has even more fallout.

I just experienced this:

1. Click a link that wants to opens something in an application that's in another workspace
2. Changes focus to app outside of workspace
3. Pop!_OS switches to the workspace automatically
4. #1408 will set focus to last application in that workspace
5. Lost focus of step 1.
