### ISSUE TITLE
Bug moving window to third right monitor while not-maximized and maximized

### ISSUE THREAD

**Issue by voltsonic** [pop-os/shell#1423]
**(1) Issue/Bug Description:**
When using the 

Super Key + Shift + Right arrow key

to move a window from my center monitor to my right it becomes offset on the window and will not respond correctly to the maximize shortcut. If it's on the third monitor offset and I maximize it then it maximizes in the center monitor instead.

Another issue which may be related is that when the window is maximized in the center monitor I'm not even able to move it to the right monitor with the above shortcut command. 

This was working at one point on 20.04 and an update broke it (apologies I did not catalog when the update occurred that broke it). However this also occurs on a live CD boot.

Hardware (for below):
- AORUS x570 Elite Wi-Fi Pro motherboard.
- AMD Ryzen 7 2700x CPU (Virtualization enabled)
- GeForce GTX 1650 (TU117)
- Monitors (main):
  - Left: LG 24'' Class Full HD TN Monitor with AMD FreeSync (23.8'' Diagonal) (However in Displays it is classified as 22")
  - Center: HP 27mx 
  - Right: AOC 24" I do not have the exact model on this one.
- Monitors (extra):
  - HP Pavilion 27xw

**(2) Steps to reproduce (if you know):**

Here is how to reproduce the problem. Not sure if this is a hardware support issue but you can check my specs above to see if there could be any issue.

Step 1: Window starts in center monitor not maximized
![step1--window-start-center](https://user-images.githubusercontent.com/6464019/167263723-3ddd5993-10ed-485f-b9b3-2e270cd82428.png)

Step 2: Super + Shift + Left Arrow to move window to left monitor (works great)
![step2--window-move-left](https://user-images.githubusercontent.com/6464019/167263725-6748e9fb-4651-423a-996a-a3f91d7c7dd7.png)

Step 3: Super + Shift + Right Arrow to move window back to center monitor (works great)
![step3--window-move-back-to-center](https://user-images.githubusercontent.com/6464019/167263732-430c168b-2229-4df8-bbec-313a53232845.png)

Step 4: Super + Shift + Right Arrow to move window to right monitor. This is where the bug occurs as you can see it's offset on the window. If I try to use Super + M to maximize it will then go back to the center screen
![step4--window-move-to-right-issue](https://user-images.githubusercontent.com/6464019/167263737-bdc97a97-3232-46de-860d-78fc62077fdc.png)

Some other notes:
- Now if the window is maximized it moves between left and center monitor just fine however moving a maximized window from center to right will not occur just stays on the center monitor.
- I have removed each monitor from the setup down to 2 monitors and it works just fine moving between any combination of just two monitors - the issue only occurs when i have 3 monitors plugged in.
- I have also tried a different monitor for the right monitor and the issue still occurs (see hardware for the 4th attempted)
- I have also moved the monitor order in the Displays. (aka making the right monitor to the left monitor) and the problem still occurs on the Right most monitor in the order.

**(3) Expected behavior:**
Window to move to same area as it does in the left and center monitor.

**(4) Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

However this did occur on 21.10 and 20.04

**(5) Gnome Shell version:**
42.0.0

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```
pop-shell:
  Installed: 1.1.0~1651514427~22.04~15e7acf
  Candidate: 1.1.0~1651514427~22.04~15e7acf
  Version table:
 *** 1.1.0~1651514427~22.04~15e7acf 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**
Main LTS iso from Pop_OS site.

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
- Monitors (main):
  - Left: LG 24'' Class Full HD TN Monitor with AMD FreeSync (23.8'' Diagonal) (However in Displays it is classified as 22")
  - Center: HP 27mx 
  - Right: AOC 24" I do not have the exact model on this one.
- Monitors (extra):
  - HP Pavilion 27xw

**(9) Other Installed/Enabled Extensions:**
- Caffeine (problem occurs without this extension however)

**(10) Other Notes:**
n/a

I tried searching for a similar problem but theres to many issues and the words are to generic so if it's a duplicate please point me in the right direction thank you.

**Comment by voltsonic** [comment]
While the issue still exists, I have purchased an ultrawide to replace two of the monitors and now I no longer have the issue. Using auto-tiling I can still organize the windows.

**Comment by sajeshcherian** [comment]
I have this exact same issue. This does not occur with auto-tiling.

Happens with my laptop connected to 3 monitors (1 HDMI + 1 USB-C passing through two HDMI via hub) and also on my desktop connected with 3 DisplayPorts.
