### ISSUE TITLE
Mouse snaps to application on another monitor when scrolling in workspaces view

### ISSUE THREAD

**Issue by MyNameIsArko** [pop-os/shell#1424]
**(1) Issue/Bug Description:**

When in workspaces view if you have multiple apps open on multiple monitors and you use scroll to switch between apps, mouse randomly snaps to the app on another monitor making user lose track of the mouse and requiring him to make additional moves to get back mouse on the right monitor.

https://user-images.githubusercontent.com/47687092/167288173-4d4029c2-7b95-4872-be05-e0c9c3c2c388.mp4

**(2) Steps to reproduce (if you know):**

Launch apps on both monitors on at least 2 workspaces and watch how the mouse are randomly snapping to the another monitor.

**(3) Expected behavior:**
Mouse stay on the same monitor you are working on.

**(4) Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**
42.0

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```1.1.0~1651514427~22.04~15e7acf```

**(7) Where was Pop Shell installed from:**

Together with system installation

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

2x1080p, same size

**(9) Other Installed/Enabled Extensions:**

```
GSConnect
```

**(10) Other Notes:**

I saw #1188 but it's not exatly the same. There, they are using win + arrows to change window and it is expected behavior to move mouse. But when scrolling in workspaces view it doesn't seem right to move mouse. Especially if the user has fullscreen windows and moving mouse not only means losing track of the mouse but also mouse positioning on workspaces button, thus making it  impossible to scroll more.

**Comment by sompodsign** [comment]
Facing same issue after 22.04

**Comment by AKK9** [comment]
As a potential workaround you could try compiling from source and then disabling the `Mouse Cursor Follows Active Window` option:

![image](https://user-images.githubusercontent.com/6625166/167424089-39a025f8-35ce-4736-a6d0-e70cc378dd71.png)

**Comment by BJCaasenbrood** [comment]
> As a potential workaround you could try compiling from source and then disabling the `Mouse Cursor Follows Active Window` option:
> 
> ![image](https://user-images.githubusercontent.com/6625166/167424089-39a025f8-35ce-4736-a6d0-e70cc378dd71.png)

Could you point out where to find the "Mouse Cursor Follows Active Window" option?

Also, the issue seems related to [#848](https://github.com/pop-os/shell/issues/848)

**Comment by AKK9** [comment]
My advice is actually already out of date. That change is now included in the most recent pop-shell update. Make sure you have the latest version.

You'll find the option in Gnome Extension settings. On Pop_OS! I open the `Extensions` app, and then under the `Pop Shell` entry I click `Settings` to find the option there:

![image](https://user-images.githubusercontent.com/6625166/167568779-cfb55983-d26a-4308-b58f-3c092aaf85a8.png)

**Comment by BJCaasenbrood** [comment]
> My advice is actually already out of date. That change is now included in the most recent pop-shell update. Make sure you have the latest version.
> 
> You'll find the option in Gnome Extension settings. On Pop_OS! I open the `Extensions` app, and then under the `Pop Shell` entry I click `Settings` to find the option there:
> 
> ![image](https://user-images.githubusercontent.com/6625166/167568779-cfb55983-d26a-4308-b58f-3c092aaf85a8.png)

Seems to have fixed the issue for me, thanks!

**Comment by Michael-Duivestein** [comment]
Not sure if it's related, but every time I click on the second workspace in workspace overview, the mouse pointer moves to position 0,0 (top left of screen). The contents of that workspace doesn't seem to matter.
Setup is two screens, one above the other (1920*2160). Main screen is the bottom screen.

**Comment by RyanFreitasG4** [comment]
> My advice is actually already out of date. That change is now included in the most recent pop-shell update. Make sure you have the latest version.
> 
> You'll find the option in Gnome Extension settings. On Pop_OS! I open the `Extensions` app, and then under the `Pop Shell` entry I click `Settings` to find the option there:
> 
> ![image](https://user-images.githubusercontent.com/6625166/167568779-cfb55983-d26a-4308-b58f-3c092aaf85a8.png)

cool, i was facing the same problem, when i clicked on an app that was open in another work window, and this solution solved it for me

**Comment by jacobgkau** [comment]
This issue seems related to https://github.com/pop-os/shell/issues/1412 -- it doesn't seem related to mulitiple displays, the cursor shouldn't snap at all when scrolling through workspaces or clicking workspaces (only when using keyboard shortcuts or touchpad guestures.)
