### ISSUE TITLE
[Bug] Can't remove windows borders in the settings

### ISSUE THREAD

**Issue by RobinOpletal** [pop-os/shell#143]
As seen in the picture below, right now there is no option to turn off the window borders.

![image](https://user-images.githubusercontent.com/49439044/78538552-790de980-77f1-11ea-9b2c-9f9cd68550a2.png)

I am running Arch latest with the latest build of the extension

**Comment by leviport** [comment]
If you're referring to the window gaps, that option is in the "Appearance" dropdown. There are also options in the extension's settings to change the inner and outer gap independently of each other, if you're like me and like to play with that.

**Comment by RobinOpletal** [comment]
Thanks for the reply @leviport, I was asking about the window decorations

**Comment by leviport** [comment]
Sorry, I'm still not sure what you mean. Window decorations as in the window title bar? If so, that setting has also moved to the extension's settings panel.

**Comment by mmstick** [comment]
The window in your screenshot doesn't have a title bar.

**Comment by RobinOpletal** [comment]
The window in the screenshot is Google Chrome which doesn't have a border even when using stock Gnome.

On this picture, none of the windows have the window decoration (top panel)

https://raw.githubusercontent.com/pop-os/shell/master_focal/screenshot.webp

**Comment by mmstick** [comment]
The option to remove title bars is in the prefs dialog
