### ISSUE TITLE
Opening pop-launcher breaks gnome-shell and pop-shell shortcuts

### ISSUE THREAD

**Issue by SquareWhite** [pop-os/shell#1434]
**(1) Issue/Bug Description:**
When I open and then close the pop-launcher all the gnome and pop-shell shortcuts stop working. I can't switch workspaces, can't move between windows, can't `Ctrl+Q` etc.  I've found that turning pop-shell extension off and on again resolves this issue, but only up until the point when I need to use the launcher again. The tiling still works though.

This bug appeared after #1426 was merged; I believe on commit 7c3a151, the previous two commmits I can't install because of the `logError`, and then on the 0680690 the launcher works as it should.

Here're the logs I get when I open and close the pop-launcher:
```bash
$ journalctl -o cat -n 0 -f "$(which gnome-shell)" | grep -v warning

pop-shell: [DEBUG] starting pop-launcher service
Error: incorrect pop
pop-shell:  [INFO] stopping pop-launcher services
```

**(2) Steps to reproduce (if you know):**
`Super + /` and then either close the launcher or select something to launch.

**(3) Expected behavior:**
Shortcuts should still be working

**(4) Distribution (run `cat /etc/os-release`):**
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

```

**(5) Gnome Shell version:**
`GNOME Shell 3.38.6`

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

from 7c3a151 to the latest one 

**(7) Where was Pop Shell installed from:**
This repo

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1 laptop monitor

**(9) Other Installed/Enabled Extensions:**
Reproduces when all the other extensions are disabled

**(10) Other Notes:**

**Comment by mmstick** [comment]
You are using the GNOME 42 branch of pop-shell. Unfortunately GNOME 38 isn't supported

**Comment by SquareWhite** [comment]
Ah, ok, got it
I've switched to master and it seems to be working fine now. I guess I'll stick to using this version, thanks!
