### ISSUE TITLE
GNOME "Edge Tiling" remains active when using the Pop Shell's tiling mode

### ISSUE THREAD

**Issue by JanPokorny** [pop-os/shell#1438]
**Distribution (run `cat /etc/os-release`):** `Pop!_OS 22.04 LTS`
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
pop-shell:
  Installed: 1.1.0~1652463555~22.04~034fb14
  Candidate: 1.1.0~1652463555~22.04~034fb14
  Version table:
 *** 1.1.0~1652463555~22.04~034fb14 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:** When the tiling mode of Pop Shell is enabled, it is still possible to use GNOME's "Edge Tiling" feature (also known as windows snapping) which resizes windows to full screen when dragged to the top of the screen, and to half screen when dragged to a side edge. However, if "Edge Tiling" is used (which can happen accidentally when dragging windows with mouse), the tiling manager gets confused and starts ignoring the snapped window.

**Steps to reproduce (if you know):** Enable tiling mode in Pop Shell, open several windows, drag one to a screen edge and observe the behavior

**Expected behavior:** "Edge Tiling" should be disabled when the tiling mode is active, as the behavior is conflicting and redundant.

**Other Notes:** For the time being, "Edge Tiling" can be disabled by:

```
gsettings set org.gnome.mutter edge-tiling false
```

There is a related issue, pop-os/gnome-control-center#231, which asks for a toggle to completely disable this feature regardless of tiling mode. If this gets implemented, I believe that the correct course of action would be to always disable "Edge Tiling" in the Pop Shell's tiling mode regardless of the toggle position, as there is no conceivable use for it in this mode.

**Comment by jacobgkau** [comment]
There was a UX discussion around this with the update to GNOME 42/GNOME Control Center 41. It was decided that a GUI toggle for the edge snapping feature probably isn't needed, but pop-shell should disable edge snapping automatically when tiling is enabled and re-enable edge snapping when tiling is disabled. (The rationale is that users, especially mouse-centric ones, expect the snapping functionality, but pop-shell provides equivalent functionality with tiling when it's enabled.)

**Comment by JanPokorny** [comment]
@jacobgkau I have to say that the edge snapping feature confused me at first when trying the tiling mode for the first time -- I had to figure out that what I want is the "orange snapping", not the "blue snapping" 😆. Disabling it automatically with the tiling mode makes a lot of sense.
