### ISSUE TITLE
Maximized floating window returns to previous state after losing & regaining focus

### ISSUE THREAD

**Issue by weebs** [pop-os/shell#1440]
**(1) Issue/Bug Description:**

When maximizing a window included in the floating windows exception list, it will return to an un-maximized state after switching focus to another window, then switching back

**(2) Steps to reproduce (if you know):**

- Add a window to the floating windows list
- Maximize the window
- Focus another window
- Switch focus back to the original maximized window

**(3) Expected behavior:**

The window should remain maximized

**(4) Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**

GNOME 42

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

pop-shell:
  Installed: 1.1.0~1652463555~22.04~034fb14
  Candidate: 1.1.0~1652463555~22.04~034fb14
  Version table:
 *** 1.1.0~1652463555~22.04~034fb14 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status

**(7) Where was Pop Shell installed from:**

Included as part of PopOS install

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

Two monitors, one is a built in laptop display (oryx pro), another is a 2560x1440 144Hz HDMI monitor above it

**(9) Other Installed/Enabled Extensions:**

Dash 2 Panel
Sound Input & Output Device Chooser
CPU Power Manager

**(10) Other Notes:**

**Comment by assert-0** [comment]
I have the same issue on 22.04 LTS.
It is also on a dual monitor setup (4k@60Hz and 1440p@144Hz),
and shell version is also `1.1.0~1652463555~22.04~034fb14`.
Also using CPU Power Manager.

(edit)
This behavior only started today for me, which means it did work normally on 22.04 before.

**Comment by frezbo** [comment]
I also have a similar issue, on the current screen have two windows in tiling mode (firefox and vscode). I have maximized firefox and then when i change focus to terminal on another monitor and comes back to the maximized firefox windows, it gets reverted to the minimized mode where both windows are tiled, this started happening a while ago

https://user-images.githubusercontent.com/18496730/170004734-832ea92d-57f5-4809-9f98-60e5371e9b67.mp4

**Comment by frezbo** [comment]
The issue still seems to be not resolved after the update.

```bash
❯ apt policy pop-shell
pop-shell:
  Installed: 1.1.0~1653677645~22.04~44ca2cd
  Candidate: 1.1.0~1653677645~22.04~44ca2cd
  Version table:
 *** 1.1.0~1653677645~22.04~44ca2cd 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status
```

When there are two apps on a monitor and one is maximized, moving focus to another window and coming back to the original windows the apps reverts back to tiled side by side mode, this was not the behavior previously and the apps would be keeping the state as it was before moving focus.

I wonder if I need to clear some stale state or something
