### ISSUE TITLE
Active hint sometimes missing after moving floated window between workspaces

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/shell#1441]
**(1) Issue/Bug Description:** After moving a floating window between workspaces with the keyboard, for some sequences, the active hint doesn't show after the move (so no window has the active hint.)

**(2) Steps to reproduce (if you know):**
1. Tile two windows on a workspace
2. Focus one of the windows
3. Open the Workspaces menu and move the _other_ (non-focused) window to a new workspace
4. Move to that new workspace
5. Float the window with Super-Shift-G
6. Move the window back to the original workspace with the keyboard

**(3) Expected behavior:** The floated, focsued window should have an active hint.

**(4) Distribution (run `cat /etc/os-release`):** Pop!_OS 22.04

**(5) Gnome Shell version:** 42

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):** `mater_jammy` branch (034fb14), `shell_jammy` branch (8d6ebf6).

**(7) Where was Pop Shell installed from:** Pop!_OS staging & release repos

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):** 1x 1080p

**(9) Other Installed/Enabled Extensions:** Pop!_OS defaults only

**(10) Other Notes:** Video:

https://user-images.githubusercontent.com/7199422/169096219-ee740895-5fa6-465b-8ba7-9608068db7d6.mp4

Not caused by or fixed by https://github.com/pop-os/shell/pull/1439, but discovered while testing that PR.

**Comment by n3m0-22** [comment]
@jacobgkau I've come across a case of this happening and afterward `Super` + `O` no longer works until the pop-shell extension is reset. Have you noticed anything like this?
