### ISSUE TITLE
Launcher shifts position on screen

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#145]
I haven't been able to reproduce the conditions for when this happens, but the launcher will sometimes shift to a new position on the screen. Sometimes it will start above center, sometimes it will start top-left of the center. Once that happens, it will keep generating in that position until shell is restarted. This is on Gnome 3.36.

![Screenshot from 2020-04-06 19-46-33](https://user-images.githubusercontent.com/39338488/78615430-8225a780-783f-11ea-8d34-843ec7deaa0c.png)

**Comment by nicolae-stroncea** [comment]
To reproduce:

*  Execute `Super /` twice, one after the other.

First time launcher willl appear normally, second time, launcher will appear shifted up. After that, all subsequent calls to the launcher will be in the heightened position.

Not sure if this is the only case when the bug happens,

**Comment by WatchMkr** [comment]
I don't see this issue any longer. Feel free to re-open if you're still seeing it.
