### ISSUE TITLE
Firefox acts as floating window while Tile Windows is toggled on.

### ISSUE THREAD

**Issue by dysonsphere-startmail** [pop-os/shell#1451]
**(1) Issue/Bug Description:**
With Tile Windows toggled on, Firefox acts as a floating window, even though it is not on the Floating Windows Exceptions list. It opens maximized on a free display and when the window is selected it re-sizes to a floating window.  Toggling Tile Windows Off and then back on re-establishes it as a tiled window.

**(2) Steps to reproduce (if you know):**
Toggle Tile Windows to "On".  Open Firefox.  Select the Firefox window.  Witness it re-size and become a floating window.  Toggle Tile Windows Off and the On again.  Witness Firefox become a tiled window.

**(3) Expected behavior:**
Firefox should open and its window should tile.

**(4) Distribution (run `cat /etc/os-release`):
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os**
 

**(5) Gnome Shell version:**
GNOME Shell 42.0

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```pop-shell:
  Installed: 1.1.0~1652463555~22.04~034fb14
  Candidate: 1.1.0~1652994129~22.04~0358b15
  Version table:
     1.1.0~1652994129~22.04~0358b15 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
 ***  1.1.0~1652463555~22.04~034fb14 100
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**
Pop!_OS installation image

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
```Screen 0: minimum 8 x 8, current 5120 x 1201, maximum 32767 x 32767
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-0 connected 1920x1080+3200+0 (normal left inverted right x axis y axis) 480mm x 270mm
   1920x1080     60.00 +  74.97*   59.94    50.00  
   1680x1050     59.95  
   1600x900      60.00  
   1440x900      59.89  
   1400x1050     59.98  
   1280x1024     75.02    60.02  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    59.94    59.93  
DP-2 connected primary 1920x1080+1280+0 (normal left inverted right x axis y axis) 344mm x 194mm
   1920x1080    144.00*+  60.00  
DP-3 connected 1280x1024+0+177 (normal left inverted right x axis y axis) 375mm x 300mm
   1280x1024     60.02*+  75.02  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
DP-4 disconnected (normal left inverted right x axis y axis)
```

**(9) Other Installed/Enabled Extensions:**
```
'alt-tab-raise-first-window@system76.com', 'always-show-workspaces@system76.com', 'batteryiconfix@kylecorry31.github.io', 'pop-shop-details@system76.com', 'system76-power@system76.com', 'ubuntu-appindicators@ubuntu.com', 'user-theme@gnome-shell-extensions.gcampax.github.com', 'caffeine@patapon.info', 'sound-output-device-chooser@kgshank.net', 'gsconnect@andyholmes.github.io', 'Resource_Monitor@Ory0n', 'gamemode@christian.kellner.me', 'topiconsfix@aleskva@devnullmail.com', 'audio-switcher@AndresCidoncha', 'system-monitor@paradoxxx.zero.gmail.com', 'radio@hslbck.gmail.com', 'extension-list@tu.berry', 'cosmic-dock@system76.com', 'system-monitor-next@paradoxxx.zero.gmail.com', 'Vitals@CoreCoding.com', 'tweaks-system-menu@extensions.gnome-shell.fifi.org', 'pop-cosmic@system76.com', 'ding@rastersoft.com', 'pop-shell@system76.com'

```

**(10) Other Notes:**

**Comment by jacobgkau** [comment]
> Installed: 1.1.0\~1652463555\~22.04\~034fb14
> Candidate: 1.1.0\~1652994129\~22.04\~0358b15

Your output shows that your Pop Shell is out of date. Can you please confirm the issue still occurs after updating and rebooting or restarting GNOME Shell with Alt-F2, r, Enter?

**Comment by dysonsphere-startmail** [comment]
Fixed with update and reboot:
```pop-shell:
  Installed: 1.1.0~1652994129~22.04~0358b15
  Candidate: 1.1.0~1652994129~22.04~0358b15
  Version table:
 *** 1.1.0~1652994129~22.04~0358b15 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status
```
