### ISSUE TITLE
Maximized IntelliJ window turns non-maximized after opening search files dialog with tile windows activated

### ISSUE THREAD

**Issue by cesarrew** [pop-os/shell#1458]
**(1) Issue/Bug Description:**

With IntelliJ and another app, like Nautilus, opened in a workspace with tile windows activated, if I maximize IntelliJ and open the search file dialog with the shortcut, the Intellij main window turns non-maximized.

It's started to happen a few days ago.

**(2) Steps to reproduce (if you know):**

See Issue/Bug Description.

**(3) Expected behavior:**

The IntelliJ main window should stay maximized after opening the search dialog.

**(4) Distribution (run `cat /etc/os-release`):**
 
22.04 LTS

**(5) Gnome Shell version:**

42.1

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```1.1.0~1653580316~22.04~42102e9```

**(7) Where was Pop Shell installed from:**

Pop OS 22.04 Clean Install

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1 horizontal monitor, 2560 X 1080

**(9) Other Installed/Enabled Extensions:**

None

**(10) Other Notes:**

https://user-images.githubusercontent.com/17600341/170778904-57afb3b3-3298-4f43-bfba-4bb2e4aae2b2.mp4

**Comment by jacobgkau** [comment]
Maybe a side effect of https://github.com/pop-os/shell/pull/1426/commits/6c3cfd7892db4d42a80fc1eb37989d2debaa4f65.

What you're requesting would be to not unmaximize/unsnap windows on floating window focus (only on non-floating window focus.) Off the top of my head, that seems reasonable from a usage standpoint, as long as it doesn't break anything else with tiling or stacking.

Out of curiosity, what do you use maximization for in this particular case, why not just have that window in its own workspace? I assume you normally have something else open besides a blank Gedit window?

**Comment by cesarrew** [comment]
Usually I use many workspaces, each one with 2 or 3 windows separated by the context. For example, I could be using IntelliJ with Chrome, reading some documentation in Chrome and writing code in IntelliJ. If I need more space using IntelliJ for some moment, I can maximize it and continue my work. However, if I decide to change the IntelliJ workspace instead, I would need to find a free workspace and, if I need to get back and follow the documentation again, I would need to move the Intellij window again, searching for the workspace with Chrome.

**Comment by pepawel** [comment]
I can reproduce it.

Also I noticed the same issue occurs when swithing workspaces (no matter if using mouse or keyboard shortcuts):
1. I maximize Rubymine.
2. I switch to another workspace.
3. I switch back to RM workspace. RM becomes non-maximized.
