### ISSUE TITLE
Launcher does not appear when a full screen window is active

### ISSUE THREAD

**Issue by benfuddled** [pop-os/shell#1465]
I've noticed in the last week or so the pop launcher refuses to appear when I hit the Super key and a full screen window is active.

I can reproduce it in a multiple places, namely when I'm using Remmina to RDP into my work machine or watching Netflix full screen.

Not sure if this is a bug or an intentional change of behavior, but it's definitely less convienent as now I have to minimize what I'm doing in my full screen window if I want to invoke another application via the launcher.

**Comment by mmstick** [comment]
Intentional. No one wants a launcher to appear while playing a video game.

**Comment by benfuddled** [comment]
I don't do much in the way of PC gaming but I could see how that would be frustrating. 

Would you consider an pull request to toggle that behavior in pop shell? I'd be more than happy to work on it.

**Comment by nathansgithub** [comment]
I also liked the previous behavior better, and I like being able to use the launcher to switch to another application at any time, including while I have a fullscreen game or other window up.

**Comment by eshwarz** [comment]
> I don't do much in the way of PC gaming but I could see how that would be frustrating.
> 
> Would you consider an pull request to toggle that behavior in pop shell? I'd be more than happy to work on it.


Would be great to have a toggle settings, I want to use launcher from full screen IDE to any other app.

**Comment by AyoItsYas** [comment]
I work on my secondary monitor running most of my applications full screen it would be use full to have the launcher still working. Is there a configurable flag in the pop shell to tweak manually for the time being?
