### ISSUE TITLE
Stacking Mode(Super+S) makes the last line of terminal unusable.

### ISSUE THREAD

**Issue by the1derer** [pop-os/shell#1476]
**(1) Issue/Bug Description:**

Stacking Mode(Super+S) makes the last line of my terminal unusable. The terminal I am using is **alacritty**.

**(2) Steps to reproduce (if you know):**

(i) sudo apt install alacritty
(ii) open alacritty terminal
(iii) Turn on stacking mode by Super + S
(iv) Try to go to last line of terminal  --> you won't be able to
(v) Turn off Stacking mode by again pressing (Super + S), now you will be able to use the last line

**(3) Expected behavior:**

Should be able to use the last line of terminal even if stacking mode is turned on.

**(4) Distribution (run `cat /etc/os-release`):**

 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**

42.1

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

pop-shell:
  Installed: 1.1.0~1654621639~22.04~b299641
  Candidate: 1.1.0~1654621639~22.04~b299641
  Version table:
 *** 1.1.0~1654621639~22.04~b299641 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status

**(7) Where was Pop Shell installed from:**

Came installed with Distribution(Pop!_OS)

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

Standard 1080p Laptop Screen

**(9) Other Installed/Enabled Extensions:**

Other Extension that came pre-installed with Pop_OS and Caffeine

**(10) Other Notes:**

**Comment by n3m0-22** [comment]
I'm seeing this as well.

![Captura de tela de 2022-06-13 07-11-03](https://user-images.githubusercontent.com/11048214/173361786-bad5ae21-63bc-490a-b91d-1a477cfd7332.png)
![Captura de tela de 2022-06-13 07-11-13](https://user-images.githubusercontent.com/11048214/173361791-5e0363f2-5123-449b-a465-ee6c0ab6133a.png)

**Comment by mmstick** [comment]
Issue is in Alacritty

**Comment by n3m0-22** [comment]
@the1derer I'm closing this issue since it is not a problem with shell but Alacritty.

**Comment by the1derer** [comment]
> Issue is in Alacritty

Thanks @mmstick for the reply,

Could you tell a bit more on how you found that the issue is in Alacritty( and what could be the possible cause of the issue), so I can submit a bug there?

Thanks a lot.

**Comment by mmstick** [comment]
This extension doesn't have any control over how an application renders. It's only moving and resizing windows. So the issue would have to be in alacritty.
