### ISSUE TITLE
suggestion: wasd-controls for workspace switching

### ISSUE THREAD

**Issue by Chrysostomus** [pop-os/shell#148]
Material-shell extension uses super+(shift)+w to move focus/(window) one workspace up and super+(shift)+s to move to move focus/(window) one workspace down. I think these are very good keybindings because they are easily accessible with one hand. 

Material-shell also uses super+a to move window focus to previous window and super+d to the next window on workspace, but those might be less useful for this extension because pop-shell does not include a task bar.

**Comment by leviport** [comment]
WASD is a good idea, and we did consider it in the planning phase. We decided that vim-style HJKL is better for home-row navigation in the end, but hotkeys will be customizable so users will be able to change them to WASD if they prefer.
