### ISSUE TITLE
Bug: windows are not autotiled when a window is moved to another workspace

### ISSUE THREAD

**Issue by Chrysostomus** [pop-os/shell#149]
Currently, when a window is moved to another workspace, the windows in the new workspace do not rearrange and the moved window is not resized before you move it within its new workspace.

**Comment by nicolae-stroncea** [comment]
I experience the same issue, with the addition that the windows in the previous workspace to do not retile to account for 1 less window, and when you interact with the window in the new workspace, it jumps back to its previous one.

**Comment by mmstick** [comment]
This happens if the workspace change was not reported by GNOME Shell, but it shouldn't be an issue with the latest commit anymore.

**Comment by nicolae-stroncea** [comment]
I'm on the latest commit, and issue still occurs

**Comment by mmstick** [comment]
Is it fixed now?

**Comment by nicolae-stroncea** [comment]
Works good now, with the exception that if I use keyboard shortcuts and move it from one workspace to another, windows will not retile in the old workspace

**Comment by Chrysostomus** [comment]
On xorg it no longer happens 95% of the time. On wayland it still regularly happens, and if I move a window to get it autotiled, it snaps back to its previous workspace.

**Comment by mmstick** [comment]
Okay. I found the issue. The tweener does not always call the `onComplete` closure on completion, but I have something that works more reliably for checking this.

**Comment by mmstick** [comment]
Should be fixed by aff19c6
