### ISSUE TITLE
Tabbed Mode

### ISSUE THREAD

**Issue by jsco2t** [pop-os/shell#150]
I love the Window Tiling feature. But I commonly find that I want to have a group of the same kinds of windows pinned to a tile area. Basically some sort of hybrid between `tiling` and `stacking`. 

Here is example:
- On the right hand side of the screen in a column I want a terminal session (full height of the screen).
- On the left hand side of the screen I want N number of code editors all pinned into the same column (not tiled but stacked). Ex: 4 instances of Visual Studio Code all stacked but "pinned" into the same tile area.  

I understand the goal with tiling is to make every window visible - but I often find myself using the feature more to create "spaces" where specific kinds of applications are held. 

Along these same lines - if I launch N+1 of the same code editor (say Visual Studio Code) I want it to automatically show up grouped with it's peers.

**Comment by mmstick** [comment]
This feature is planned, but it may not make it in the first release. The feature in i3 is called "tabbed mode".

**Comment by jsco2t** [comment]
Thanks @mmstick - great to hear this is on the roadmap.

If there is anything I can do to help land the feature let me know. Happy to test bits...etc.

Thanks,

- Jason
