### ISSUE TITLE
Icons in Stacking Tabs do not match icons elsewhere in OS

### ISSUE THREAD

**Issue by brs17** [pop-os/shell#1512]
**(1) Issue/Bug Description:**
When launching gedit, the icon that shows up in the stacking tab is predominately yellow. In the launch, it is predominately white.

Stacking Tab:
![Screenshot from 2022-08-24 15-06-44](https://user-images.githubusercontent.com/7460774/186526468-4714cabe-affd-4419-a379-0579d1b22aa1.png)

Launcher:
![Screenshot from 2022-08-24 15-25-09](https://user-images.githubusercontent.com/7460774/186526511-847eb48a-2ec5-499b-b973-41b00be41a2d.png)

Application Menu:
![Screenshot from 2022-08-24 15-25-46](https://user-images.githubusercontent.com/7460774/186526597-cc31777b-bfee-4a8e-b9e5-5eb2532b25c3.png)

**(2) Steps to reproduce (if you know):**
Launch `gedit`

**(3) Expected behavior:**
 I would not expect a different icon in the Stacking tab vs the launch or application menu.

**(4) Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**
`Installed: 42.3.1-2ubuntu1pop1~1660592271~22.04~ca01bf8`

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```  Installed: 1.1.0~1659996551~22.04~08abba0```

**(7) Where was Pop Shell installed from:**
By default: `http://apt.pop-os.org/release jammy/main amd64 Packages`

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

2 x 1920*1080 horizontal

**(9) Other Installed/Enabled Extensions:**

None

**(10) Other Notes:**
None

**Comment by jacobgkau** [comment]
Looking at the various sizes of the Gedit icon available in `/usr/share/icons`, I believe this is just due to the size. The one in `16x16` is being used by Pop Shell since that size is very small, where the launcher uses the larger icon (the one that's in e.g. `48x48`) because it's larger.

**Comment by jacobgkau** [comment]
Not sure if this would be a Pop Shell bug since it's picking out an icon of the appropriate size. Seems like it might be more on Gedit to provide consistent icons across all of the sizes.

**Comment by brs17** [comment]
That is a good point. This is a design decision by gedit upstream.
