### ISSUE TITLE
Full screen sometimes slides down

### ISSUE THREAD

**Issue by Kartonrealista** [pop-os/shell#152]
![Screenshot from 2020-04-12 15-17-14](https://user-images.githubusercontent.com/63356574/79069786-538d4e00-7cd1-11ea-8e6a-b2e1227ea37a.png)
Pop!_OS 20.04 beta

With a window in full screen mode sometimes while right-clicking or clicking on a second display the window occasionally slides down for no reason, leaving an empty bar on the left and on top of the original screen.

**Comment by mmstick** [comment]
I've seen this often, so I'm aware of it. I will try to fix this today.

**Comment by mmstick** [comment]
Can you tell me if this is fixed now?

**Comment by Kartonrealista** [comment]
No, I rebooted just in case but the problem persists after updating
