### ISSUE TITLE
Unable to unstack stacked windows 

### ISSUE THREAD

**Issue by asnimansari** [pop-os/shell#1521]
**(1) Issue/Bug Description:**
Clicking `Super` + `S` converts a window to stack mode and further applications are getting stacked, but pressing `Super`+ `S` again is not unstacking it 

**(2) Steps to reproduce (if you know):**

Use `Super` + `S` to stack, then open few windows on that stack, again press `Super` + `S`, you will see that it still is in that stack

**(3) Expected behavior:**
This should remove the stack mode and make each window individual one

**(4) Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
 

**(5) Gnome Shell version:**
`42.2`

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```
pop-shell:
  Installed: 1.1.0~1661535383~22.04~4c03091
  Candidate: 1.1.0~1663100384~22.04~f0e9232
  Version table:
     1.1.0~1663100384~22.04~f0e9232 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
 *** 1.1.0~1661535383~22.04~4c03091 100
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**
System76

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1 x 1080P

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

**Comment by lkonga** [comment]
I am reproducing same behavior of unstacking not happening and it does present same behavior when inside management mode (by pressing the default shortcut `S`). 

It can interfere with workflows as sometimes windows can get stacked inadvertently when dragging them.
 
 **Pop Shell version:**
`apt policy pop-shell`

```
pop-shell:
  Installed: 1.1.0~1664465783~22.04~aaf86e4
  Candidate: 1.1.0~1664465783~22.04~aaf86e4
  Version table:
 *** 1.1.0~1664465783~22.04~aaf86e4 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status
```

**Comment by vish9812** [comment]
Facing the same issue. I installed the NVIDIA version.
btw, any way to unstack it even with mouse? otherwise, auto-tiling is just not that useful with multiple windows open.

**Comment by mmstick** [comment]
You can drag and drop the window or move it out with Super + Enter and directional keys.
