### ISSUE TITLE
Stop being disrespectful to real engineers

### ISSUE THREAD

**Issue by ghost** [pop-os/shell#1526]
This post is in response to the pathetic & disrespectful lies which misuse the word "Engineering" and "Engineer" in it, in their fake and wannabe claims.Stop making lies about real Engineering. Engineering has nothing to do with sitting behind a keyboard and writing code. Engineering is a real subject. Engineering means designing and building real mechanical systems, like vehicular engines and turbojets. Software devs have absolutely nothing to do with engineering, and they are being stupid wannabe liars. 

They will never be engineers, in fact, they don't even know what it takes to be an engineer. None of you are engineers, and you'll never even be close. So stop being disrespectful to real engineers (mechanical engineering is real engineering, and nothing else).

@mmstick

**Comment by mmstick** [comment]
Try reading a dictionary sometime.
Oxford Dictionary. Engineer. Verb. "Skilfully arrange for (something) to occur."
Oxford Dictionary: Engineering. Verb. "the action of working artfully to bring something about."
Case closed.
Fun fact, originally the word meant someone who built defensive fortifications and weapons.
