### ISSUE TITLE
Feature request: When toggling orientation, tile windows depending on windows focus

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#153]
Currently, there is a default behaviour for windows shifting from horizontal to vertical layout and viceversa. For my use case, when I toggle from horizontal to vertical orientation, sometimes I want the left window to be on top, and sometimes the right one(and similarly when switching from a vertical to a horizontal orientation). Currently, I need to toggle the orientation, and then also change the position of the windows. 

Ideal behaviour would be that focusing on the window will put it on top if shifting to a horizontal orientation, and will put it on the left if shifting to a vertical orientation.

**Comment by mmstick** [comment]
Orientation toggling will now swap branches with every 2nd toggle.
