### ISSUE TITLE
[GNOME 3.38 on Zorin OS] Opening Launcher with `super+/` cause whole shell to hang

### ISSUE THREAD

**Issue by xxKeefer** [pop-os/shell#1536]
**(1) Issue/Bug Description:**

When I use `super+/` the launcher doesn't work and then the whole shell just hangs and becomes uninteractable, i am unable to launch any other application even with shortcuts, in fact all the shortcuts seem to not work it's like it won't detect the super key anymore

I am able to work around the issue by logging out and signing in again

**(2) Steps to reproduce (if you know):**
just launch the launcher

**(3) Expected behavior:**
it should work

**(4) Distribution (run `cat /etc/os-release`):**
```
NAME="Zorin OS"
VERSION="16.2"
ID=zorin
ID_LIKE=ubuntu
PRETTY_NAME="Zorin OS 16.2"
VERSION_ID="16"
HOME_URL="https://zorin.com/os/"
SUPPORT_URL="https://help.zorin.com/"
BUG_REPORT_URL="https://zorin.com/os/feedback/"
PRIVACY_POLICY_URL="https://zorin.com/legal/privacy/"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**(5) Gnome Shell version:**
GNOME Shell 3.38.4

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
commit 886a069c0582b371e90ac3602b1747ea5fba616c (HEAD -> master_jammy, origin/master_jammy, origin/HEAD)
Author: Lunarmagpie <Bambolambo0@gmail.com>
Date:   Tue Oct 11 15:12:44 2022 -0400

    feat: Move mouse focus position config to gnome extension options

M       schemas/org.gnome.shell.extensions.pop-shell.gschema.xml
M       src/config.ts
M       src/focus.ts
M       src/prefs.ts
M       src/settings.ts
M       src/window.ts
```

**(7) Where was Pop Shell installed from:**
installed locally using the installation instructions on this repo

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
2 x 1080p, both horizontal

**(9) Other Installed/Enabled Extensions:**
this is the output of `gsettings get org.gnome.shell enabled-extensions`
```
[
  'drive-menu@gnome-shell-extensions.gcampax.github.com',
  'remove-dropdown-arrows@mpdeimos.com',
  'user-theme@gnome-shell-extensions.gcampax.github.com',
  'x11gestures@joseexposito.github.io',
  'zorin-appindicator@zorinos.com',
  'zorin-desktop-icons@zorinos.com',
  'zorin-printers@zorinos.com',
  'zorin-connect@zorinos.com',
  'native-window-placement@gnome-shell-extensions.gcampax.github.com',
  'pop-shell@system76.com'
]
```

**(10) Other Notes:**
I am able to work around the issue by logging out and signing in again
Really love your work guys <3 hopefully they will accept this shell in gnome!

i saw some similar issues talking about `journalctl`  I'm still mostly a Linux novice but here's my output in case it helps
```
journalctl -f -o cat /usr/bin/gnome-shell
Ignoring excess values in shadow definition
clutter_input_focus_set_cursor_location: assertion 'clutter_input_focus_is_focused (focus)' failed
clutter_input_focus_set_cursor_location: assertion 'clutter_input_focus_is_focused (focus)' failed
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Error: incorrect pop
```

**Comment by xxKeefer** [comment]
in the mean time i have rebound the launcher shortcut with the instructions in #1187

**Comment by jacobgkau** [comment]
> in the mean time i have rebound the launcher shortcut with the instructions in #1187

If the launcher works when launched with a shortcut not utilizing the Super key, then it sounds like another extension in Zorin OS (probably their Start menu-like launcher?) is also trying to listen for the Super key and is conflicting with Pop!_Shell.

> GNOME Shell 3.38.4

I do want to mention that recent releases of Pop!_Shell (on the `master_jammy` branch) are not being tested against GNOME 3.38 anymore. The plain `master` branch may be better-supported with 3.38. (Pop!_OS is shipping GNOME 42 at this point.)
