### ISSUE TITLE
Window doesn't tile properly after maximizing

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#154]
Multiple ways to reproduce this:

First way:
1. Have 1 single terminal window
2. Double click on the header-bar.
3. Press `Super M`

Results:

![image](https://user-images.githubusercontent.com/39338488/79183872-aefa3180-7de0-11ea-90af-5d8d82b1d28e.png)

Another way of reproducing:
1. Have 1 single terminal window.
1. Press `Super M` multiple times, or double click the headerbar multiple times.

EDIT:
I noticed this doesn't only happen for 1 window, but will happen if you have multiple windows as well, although it's been a lot harder to reproduce consistently so I'm not sure if it's the same bug.

Found a way to reproduce it.
1. Drag window by header-bar to the top bar, which will maximize it.
2. Double click on the header-bar

![image](https://user-images.githubusercontent.com/39338488/79188782-02bf4780-7dee-11ea-8bf0-996067bba0a5.png)

**Comment by leviport** [comment]
I can confirm this one. Tapping `super`+`m` a few times is usually enough to make it happen on my machine.

**Comment by mmstick** [comment]
Is this issue fixed?

**Comment by nicolae-stroncea** [comment]
Its fixed, but there is now a weird glitch when I snap a window back to screen from fullscreen, where it glitches and contracts. The gifs i attach show it as smoother than it actually is, due to the framerate.

![bug_report_3](https://user-images.githubusercontent.com/39338488/79369142-7f514380-7f1e-11ea-9507-9afe92bc3a57.gif)

![bug_report](https://user-images.githubusercontent.com/39338488/79368691-ce4aa900-7f1d-11ea-9a2a-f639ac22347d.gif)

![bug_report_2](https://user-images.githubusercontent.com/39338488/79368888-1cf84300-7f1e-11ea-8e52-fb5593fa185f.gif)

**Comment by mmstick** [comment]
That's because GNOME Shell throws it around when you unmaximize, and we're compensating by tiling it back into place.
