### ISSUE TITLE
[BUG] Chrome with GTK+ theme got huge padding around window after extension was enabled

### ISSUE THREAD

**Issue by sergiorussia** [pop-os/shell#1543]
**(1) Issue/Bug Description:**
Google Chrome with builtin GTK+ theme got huge padding around window when Adaptive Screen Edges are turned On in Gnome settings and Chrome window is snapped to left or right screen edge
![Screenshot from 2022-11-09 00-02-56](https://user-images.githubusercontent.com/22471371/200681330-223e2c39-19c3-48ee-85da-5c1d47f1fe9e.png)

**(2) Steps to reproduce (if you know):**
- Fedora 36, Wayland
- `sudo dnf install --setopt=install_weak_deps=False gnome-shell-extension-pop-shell xprop`
- log out, log in, enable extension
- **open Chrome**, open eg text editor
- enable tiling
- disable tiling
- disable extension
- now (or maybe right after tiling is enabled, dunno) Chrome got huge padding when is snapped to screen edges...

**(3) Expected behavior:**
at least after extension is disabled / removed everything should be just as before extension

**(4) Distribution (run `cat /etc/os-release`):**
 ```
❯ cat /etc/os-release
NAME="Fedora Linux"
VERSION="36 (Workstation Edition)"
ID=fedora
VERSION_ID=36
VERSION_CODENAME=""
PLATFORM_ID="platform:f36"
PRETTY_NAME="Fedora Linux 36 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:36"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f36/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=36
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=36
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

**(5) Gnome Shell version:**
```
❯ gnome-shell --version
GNOME Shell 42.5
```

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```
❯ dnf info --installed gnome-shell-extension-pop-shell
Installed Packages
Name         : gnome-shell-extension-pop-shell
Version      : 1.2.0^7.4c03091
Release      : 1.fc36
Architecture : noarch
Size         : 415 k
Source       : gnome-shell-extension-pop-shell-1.2.0^7.4c03091-1.fc36.src.rpm
Repository   : @System
From repo    : updates
Summary      : GNOME Shell extension for advanced tiling window management
URL          : https://github.com/pop-os/shell
License      : GPLv3
Description  : Pop Shell is a keyboard-driven layer for GNOME Shell which allows
             : for quick and sensible navigation and management of windows.  The
             : core feature of Pop Shell is the addition of advanced tiling
             : window management - a feature that has been highly-sought within
             : our community.  For many - ourselves included - i3wm has become
             : the leading competitor to the GNOME desktop.
```

**(7) Where was Pop Shell installed from:**
```
❯ sudo dnf install --setopt=install_weak_deps=False gnome-shell-extension-pop-shell xprop
```

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
single monitor, 1920 x 1200, horizontal

**(9) Other Installed/Enabled Extensions:**
https://extensions.gnome.org/extension/19/user-themes/
https://extensions.gnome.org/extension/1160/dash-to-panel/

**(10) Other Notes:**
for now only Chrome with GTK+ theme is affected (Classic theme is not broken), other apps with regular client-side-decorations are not (including flatpak apps). issue remains even after extension is disabled / removed :(

PS: just noticed that snapping of Incognito window is completely broken now :(

**Comment by sergiorussia** [comment]
small demo
[Screencast from 09.11.2022 00:53:08.webm](https://user-images.githubusercontent.com/22471371/200683836-cb4b1344-e27f-4ed4-b568-33a1c226da41.webm)

**Comment by Neo-29** [comment]
same on xorg gnome 43 arch

**Comment by sergiorussia** [comment]
i were digging around modified dconf settings like this `dconf dump /`, reset all the extension settings back to defaults and found nothing related to Chrome, nothing helped. then i googled a bit for Chrome and padding and so on and noticed questions related to system title bar. but modern Chrome does not have such settings, BUT then i found this old thread https://support.google.com/chrome/thread/127138612?hl=en&msgid=127291804 and it hinted with `Ozone platform` flag (see chrome://flags/#ozone-platform-hint). i indeed set it to `Auto` a couple **weeks** ago so i tried to set it back to `Default` (which causes Chrome to use X11 instead of Wayland) and the issue is gone. turn it back to Auto - it's back. so for me this narrows down to setup like this:

Chrome `Ozone platform` set to `Auto` or `Wayland` + Chrome theme set to `GTK+` + pop-os shell were enabled at least once

PS: @Neo-29 did u set this Ozone platform flag?
PPS: my current Chrome version is `107.0.5304.110 (Official Build) (64-bit)`

**Comment by Neo-29** [comment]
> i were digging around modified dconf settings like this `dconf dump /`, reset all the extension settings back to defaults and found nothing related to Chrome, nothing helped. then i googled a bit for Chrome and padding and so on and noticed questions related to system title bar. but modern Chrome does not have such settings, BUT then i found this old thread https://support.google.com/chrome/thread/127138612?hl=en&msgid=127291804 and it hinted with `Ozone platform` flag (see chrome://flags/#ozone-platform-hint). i indeed set it to `Auto` a couple **weeks** ago so i tried to set it back to `Default` (which causes Chrome to use X11 instead of Wayland) and the issue is gone. turn it back to Auto - it's back. so for me this narrows down to setup like this:
> 
> Chrome `Ozone platform` set to `Auto` or `Wayland` + Chrome theme set to `GTK+` + pop-os shell were enabled at least once
> 
> PS: @Neo-29 did u set this Ozone platform flag? PPS: my current Chrome version is `107.0.5304.110 (Official Build) (64-bit)`

I didn´t but as far as all the extension is broken with last version of `mutter`I stopped using it for the moment

**Comment by sergiorussia** [comment]
i've set up a virtual machine to check if this ozone platform flag caused or the extension and it turns out that this is a Chrome bug, not extenstion. here's 2 screenshots with Fedora live image, only Chrome was installed and only it's flag was changed.

![Screenshot from 2022-11-11 20-15-21](https://user-images.githubusercontent.com/22471371/201394837-a73da1dd-f71a-4b36-b68b-090fc35ad20d.png)

![Screenshot from 2022-11-11 20-16-59](https://user-images.githubusercontent.com/22471371/201394846-b6a03318-149e-4953-9668-a47f284e2754.png)

i'm closing the issue, sorry for interruption.
