### ISSUE TITLE
Allow disabling moving cursor to window when switching workspaces

### ISSUE THREAD

**Issue by aboledaink** [pop-os/shell#1557]
Steps to replicate:
- have a program on a different workspace
- click on that program icon in the dock

workspace gets changed and the mouse is moved to the top left corner of the program window.
I would like an option to disable this, it is very annoying :)

**Comment by n3m0-22** [comment]
I believe the setting you are looking can be found in `Extensions` > `Pop Shell` > `Settings`. From there turn off `Mouse Cursor Follows Activate Window`. 

![Screenshot from 2022-12-29 11-34-32](https://user-images.githubusercontent.com/11048214/209994807-dc2ecf95-cada-4379-a657-94fd6b6f52d4.png)

**Comment by aboledaink** [comment]
hi Randall, thank you!

**Comment by aboledaink** [comment]
This is resolved as Randall pointed out.
