### ISSUE TITLE
Attempting to run a JS callback during garbage collection - forever spewing syslog 

### ISSUE THREAD

**Issue by masip85** [pop-os/shell#1572]
Hello
I've had a bug that  originally reported here. But **it only happens when extensions are enabled.**. so here I am.
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/1868#note_1573153

This is the log I've prepared. When my python process creates a new window, bug happens after a while (sometimes it happens in a few seconds, sometimes takes 30s or more), then my gnome is completely unresponsive.
[log.txt](https://github.com/pop-os/cosmic/files/9852785/log.txt)

This log continues like this very long, and **it also fill many GB at syslog.**
I only use the default popOS extensions, and I haven't installed anything to gnome. Not even themes.

System:
`Linux pop-os 5.19.0-76051900-generic #202207312230~1663791054~22.04~28340d4 SMP PREEMPT_DYNAMIC Wed S x86_64 x86_64 x86_64 GNU/Linux`

**Comment by mmstick** [comment]
window.js:512 calls this statement:

```js
win.raise();
```

It is unclear why [Meta.Window.raise](https://gjs-docs.gnome.org/meta11~11/meta.window#method-raise) would cause a JS callback issue. Seems to be some internal issue in gnome-shell if it permits this kind of odd execution state. Sounds like it shouldn't allow JS callbacks to be called during garbage collection.

**Comment by masip85** [comment]
I've checked and now works perfectly. No issues at all.

**Comment by masip85** [comment]
Hello, 

The issue has been gone for a few days. But,again, is back, I've been able -many many times- of making this work perfectly these days. But,is back again:

Linux pop-os 6.1.11-76060111-generic #202302091138~1675975749~22.04~f771a7f SMP PREEMPT_DYNAMIC Thu F x86_64 x86_64 x86_64 GNU/Linux


[newlog.txt](https://github.com/pop-os/shell/files/10827238/newlog.txt)


I am attempting to get a python script minimal to reproduce this

**Comment by mmstick** [comment]
No updates have been released in the last 3 days, so nothing's changed.
