### ISSUE TITLE
[NixOS] Cannot change Active Hint Color & Active Border Radius

### ISSUE THREAD

**Issue by eureka-cpu** [pop-os/shell#1582]
**(1) Issue/Bug Description:**
Cannot change Active Hint Color, or Active Border Radius from dropdown menu 😞 Trying to change the Hint Color olor results in the menu closing, nothing happens when changing the value in Border Radius

**(2) Steps to reproduce (if you know):**
Open dropdown menu for settings, click either setting for Active Hint Color & Border Radius.

**(3) Expected behavior:**
I used to use Pop so I expected it to work the same, ie a pop up window opens for the Hint Color and the Border Radius should change when the value changes.

**(4) Distribution (run `cat /etc/os-release`):**
 NixOS 22.11 (Raccoon)

**(5) Gnome Shell version:**
`gnome-shell --version` produces GNOME Shell 43.2

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
here is the source provided by the Nix package: https://github.com/NixOS/nixpkgs/blob/af96094e9b8eb162d70a84fa3b39f4b7a8b264d2/pkgs/desktops/gnome/extensions/pop-shell/default.nix#L7

**(7) Where was Pop Shell installed from:**
I added
```nix
environment.systemPackages = [
    pkgs.gnomeExtensions.pop-shell
  ];
```
to my `configuration.nix` then rebuilt & restarted

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
Primary monitor is an LG ultrawide, secondary is the laptop monitor itself (HP Dev One notebook)

**(9) Other Installed/Enabled Extensions:**
The only other extension enabled is User Themes, and I currently don't have a user theme in use.

**(10) Other Notes:**
All in all, I'd like to say I'm rather happy other than a few small things. Opening one other issue after this, if both could be solved within the year I'd be supremely happy with my setup (granted I stay away from r/unixporn).

**Comment by jacobgkau** [comment]
Are you using X11 or Wayland? If you're using Wayland, can you check if the issue also occurs in X11?

**Comment by eureka-cpu** [comment]
> 

Using Wayland, will do

**Comment by eureka-cpu** [comment]
Tested on X11 (sorry for delay) and the problem with the active hint color persists. One difference I noticed that may be the reason(?), Pop!_OS had a color application pre-installed but I don't see one that came with vanilla Gnome on my NixOS system. Could it be, I just lack a color application that Pop Shell is attempting to open?

**Comment by skulldogged** [comment]
I have a similar problem with NixOS unstable and pop-shell installed from nixpkgs. I can't open the "tiling window exceptions" menu, nor can I change the active hint color without using `gsettings`.

It might be worth noting that these issues persist even when using pop-shell imperatively.

**Comment by eureka-cpu** [comment]
Installing the gnome color picker extension didn't help (seems it just copies the hex to clipboard). What color picker does Pop use?

**Comment by arcbra** [comment]
Did anyone find a solution? Still not working

**Comment by eureka-cpu** [comment]
> Did anyone find a solution? Still not working

I gave up, the shell works fine aside from the above issue for me at least.

**Comment by arcbra** [comment]
Yes it works fine for me to. Also I find out that, in other distros to display de color changer, they use "gjs". I added it in my system but still not working.

**Comment by grnqrtr** [comment]
> nor can I change the active hint color without using `gsettings`.

So you were able to change the hint color with gsettings? How exactly do you do that if you don't mind explaining. I would appreciate it!

**Comment by rihafilip** [comment]
> So you were able to change the hint color with gsettings? How exactly do you do that if you don't mind explaining. I would appreciate it!

Not OP, but I found a workaround.

For changing the border color, use (with your preferred r, g and b values, also note the double quoting)
```
dconf write /org/gnome/shell/extensions/pop-shell/hint-color-rgba "'rgba(r, g, b, 1)'"
```
and for the radius 
```
dconf write /org/gnome/shell/extensions/pop-shell/active-hint-border-radius "@u your-radius"
```

Also if you are using home manager, you can change the dconf settings with it.

There seems to be problem with gjs in Nix, as the color picker is called externally. There is a patch to this extensions in nixpkgs, but it seems like it is not working properly.

Hope this helps!

**Comment by grnqrtr** [comment]
@rihafilip Thank you very much, that worked!

**Comment by AndrewKvalheim** [comment]
Sounds like NixOS/nixpkgs#156033 and NixOS/nixpkgs#256889.

**Comment by eureka-cpu** [comment]
Tagging the maintainer, @genofire to make them aware of it. Seems the issue on the nixpkgs repo should be sufficient so I'm closing this. Thanks for refs @AndrewKvalheim and @rihafilip for the temp solution <3
