### ISSUE TITLE
Sharing screen in any app shows a black screen

### ISSUE THREAD

**Issue by eureka-cpu** [pop-os/shell#1583]
**(1) Issue/Bug Description:**
Trying to share my screen to a colleague but the desktop is black save my mouse cursor.

**(2) Steps to reproduce (if you know):**
Open a google meet/slack huddle/etc and try to share screen, all screen selection options are black and when selecting one the result is as described above.

**(3) Expected behavior:**
The option to share desktop should show my desktop & applications when using screen share software.

**(4) Distribution (run `cat /etc/os-release`):**
 NixOS 22.11 (Raccoon)

**(5) Gnome Shell version:**
`gnome-shell --version` produces GNOME Shell 43.2

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

here is the source provided by the Nix package: https://github.com/NixOS/nixpkgs/blob/af96094e9b8eb162d70a84fa3b39f4b7a8b264d2/pkgs/desktops/gnome/extensions/pop-shell/default.nix#L7

**(7) Where was Pop Shell installed from:**
I added
```nix
environment.systemPackages = [
    pkgs.gnomeExtensions.pop-shell
  ];
```
to my configuration.nix then rebuilt & restarted

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
Primary monitor is an LG ultrawide, secondary is the laptop monitor itself (HP Dev One notebook)

**(9) Other Installed/Enabled Extensions:**
The only other extension enabled is User Themes, and I currently don't have a user theme in use.

**(10) Other Notes:**
Thanks for reading!

**Comment by eureka-cpu** [comment]
Here's a screenshot of what it might look like, in this instance I tried to use Jitsi to no avail:
![Screenshot from 2023-02-09 16-29-24](https://user-images.githubusercontent.com/57543709/217953858-dafd6502-db02-4758-8674-94d3e42057ea.png)

**Comment by jacobgkau** [comment]
Pop!_Shell is a GNOME Shell extension handling window placement, and shouldn't have anything to do with screen sharing. Can you please confirm that this issue does not occur if you disable the Pop!_Shell extension on your NixOS installation?

**Comment by eureka-cpu** [comment]
Right you are, looks like this is actually just a Gnome issue

**Comment by leviport** [comment]
I saw you mention that you were using Wayland in https://github.com/pop-os/shell/issues/1582#issuecomment-1424932172. I've definitely heard of screen sharing issues with Wayland in the past, so I'd probably check that in X11 as well.

**Comment by eureka-cpu** [comment]
There's an open issue [here](https://github.com/NixOS/nixpkgs/issues/91218) for Nix/Wayland, thanks @leviport

**Comment by eureka-cpu** [comment]
Another thread from discourse for anyone stumbling upon this: https://discourse.nixos.org/t/configuring-x11-for-gnome/19113/11
