### ISSUE TITLE
Make local-install kills Wayland

### ISSUE THREAD

**Issue by ibrahima** [pop-os/shell#1584]
**(1) Issue/Bug Description:**

As reported in https://github.com/pop-os/shell/discussions/1552, running `make local-install` kills Wayland without restarting it and completing the installation.

**(2) Steps to reproduce (if you know):**

- Check out shell repo at `master_jammy` (currently afa7510141830192968391ecbd981304de72d9f0)
- Run `make local-install`

**(3) Expected behavior:**

PopOS Shell is installed locally

**(4) Distribution (run `cat /etc/os-release`):**
 
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**(5) Gnome Shell version:**

42.5

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

afa7510141830192968391ecbd981304de72d9f0

**(7) Where was Pop Shell installed from:**

GitHub

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1 4k internal laptop screen

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

The discussion thread above has some suggested workarounds.

**Comment by jasmeet0915** [comment]
Hi @ibrahima I am facing the same issue. Were you able to solve this by any chance?

**Comment by jasmeet0915** [comment]
> Hi @ibrahima I am facing the same issue. Were you able to solve this by any chance?

I was able to solve it by installing the recommended nvidia drivers and then switch to x11 instead of Wayland.

**Comment by ibrahima** [comment]
I followed the suggestion in https://github.com/pop-os/shell/discussions/1552#discussioncomment-4301672 to run the individual steps and that worked for me on Wayland.

**Comment by mbana** [comment]
If you want to get around it try, `touch .confirm_shortcut_change` then `make local-install` it won't fix your issue but will prevent a restart.

**Comment by ibrahima** [comment]
The above didn't work for me, but it seems like we should be able to detect wayland and skip the restart in the Makefile.

I just went ahead and submitted a PR to fix this since I ran into this again after an Ubuntu upgrade: https://github.com/pop-os/shell/pull/1698
