### ISSUE TITLE
Opening link in maximized application does not exit full screen

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#160]
To reproduce:
1. Open up a web browser and Geary on same workspace.
2. Make Geary full screen.
3. Open a link from Geary email(example: unsubscribe links, etc).

Result:
![image](https://user-images.githubusercontent.com/39338488/79271285-89ffd000-7e6d-11ea-95db-8ec9139d588c.png)

I'm not sure if this is intended behaviour. In all other scenarios, if I open an application whilst another application is maximized, the maximized application is un-maximized, and everything is tiled correctly on the screen.

EDIT: similar behaviour occurs if you open a link from VSCode

**Comment by nicolae-stroncea** [comment]
Also happens when opening a notification when in full-screen.

**Comment by nicolae-stroncea** [comment]
Opening links and other applications while in full-screen now works correctly, thanks!

I noticed that now if you focus on a notification it immediately exits full-screen. Focusing on the notification should not exit full-screen, as I hover over it just to see the entire notification(example email notification expands the notification when focusing on it). I should exit only if I launch another application, with the notification that would be clicking on the notification and it explicitly launching a new window

**Comment by nicolae-stroncea** [comment]
Similarly, opening a pop-up from within the same application will also quit full-screen, even though it shouldn't.

Example: 
1. Make Nautilus full screen
2. Right click, new folder
3. Nautilus exits full-screen, even though it should still be in it.

**Comment by nicolae-stroncea** [comment]
Further breaks occur when an application is maximized on half of the screen(by dragging it to the left/right), and focus shifts to the other side of the screen. The application quits being maximized

**Comment by nicolae-stroncea** [comment]
Another serious breakage: Closing an application in full-screen seems to break the shell

**Comment by WatchMkr** [comment]
@nicolae-stroncea please open new issues for these so that we can get them triaged. Thanks!
