### ISSUE TITLE
Pop OS tiling creates empty windows with Wayland

### ISSUE THREAD

**Issue by TCROC** [pop-os/shell#1608]
**(1) Issue/Bug Description:**

I just updated Pop OS.  The tiling feature is now spawning empty windows while running Wayland. Running XOrg works fine.

Here is my multimonitor setup:

![image](https://user-images.githubusercontent.com/24307049/231004288-fe8a04e5-695d-49e4-85fd-c949ad2b54c5.png)

Its somewhat hard to tell which is which monitor so here are some lines attempting to separate them:

![image](https://user-images.githubusercontent.com/24307049/231005255-84693f1a-5019-4590-8e0e-2c5004a001a5.png)

And if I try to move one of my tabs on to that empty space it creates a tab for the empty window:

![image](https://user-images.githubusercontent.com/24307049/231004490-f9d98791-20e0-406d-8298-95516ffbccb0.png)

**(2) Steps to reproduce (if you know):**

Run Pop OS with Wayland

**(3) Expected behavior:**

These empty windows should not be spawned

**(4) Distribution (run `cat /etc/os-release`):**

```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**

```
gnome-shell --version

** (process:29535): WARNING **: 17:41:58.572: Failed to set RT scheduler: Operation not permitted
GNOME Shell 42.5
```

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1680708801~22.04~a3a1b7b
  Candidate: 1.1.0~1680708801~22.04~a3a1b7b
  Version table:
 *** 1.1.0~1680708801~22.04~a3a1b7b 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

The iso installer from system76 website.

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

3 1080p horizontal monitors.

**(9) Other Installed/Enabled Extensions:**

Manually installed extensions:

![image](https://user-images.githubusercontent.com/24307049/231004955-3b11d258-f78b-46e3-b6f5-8e1d31deabf5.png)

- Application Volume Mixer
- Sound Input & Output Device Chooser
- Vitals

**Comment by TCROC** [comment]
Yay I fixed it!  Another window called "gjs" needs to be added to the "floating window exceptions" now since the last update:

![image](https://user-images.githubusercontent.com/24307049/231006914-1c303203-3b4d-49ae-a985-4152ef589156.png)

Steps to fix locally:

1. Have a monitor without any applications currently open on it:
![image](https://user-images.githubusercontent.com/24307049/231007068-11a6c853-420d-4208-b33f-23871cd35c6d.png)

1. Turn on tiling

1. Open "Floating Window Exceptions" from the tiling option:
![image](https://user-images.githubusercontent.com/24307049/231007265-6655d172-8a0b-4214-8622-fcf5dc485f03.png)

1. Drag the tiling application so the empty window and flowing window exceptions are tabbed together:
![image](https://user-images.githubusercontent.com/24307049/231007386-23fda54d-3d11-43e6-b294-a8d507fb5f7c.png)

1. Select > Click Empty Monitor > This App's Windows

Now "gjs" will be added to the exceptions
![image](https://user-images.githubusercontent.com/24307049/231007582-2a834467-3667-45f7-b8e6-6f5c92feb93f.png)

**Comment by TCROC** [comment]
Can we add "gjs" to "System Exceptions" so that it is included by default?

**Comment by jstdk** [comment]
This fixes it for me too. Thanks

**Comment by TCROC** [comment]
Np!  Glad I could help!  Do you know how we go about getting this added to the official list of floating window exceptions?

**Comment by jstdk** [comment]
It should. Will drop this issue in the system76 chat tomorrow in case no system76 developer picked up this thread. I was on the verge of going back to Sway until I saw your solution. Would be sad if others get stuck and move on.

**Comment by n3m0-22** [comment]
I was able to reproduce this issue. I was also able to confirm your fix. It seems to have been caused by this PR https://github.com/pop-os/shell/pull/1605 that fixed an issue in X11. I'm currently looking into how this can be fixed for X11 without affecting Wayland.

**Comment by TCROC** [comment]
> It should. Will drop this issue in the system76 chat tomorrow in case no system76 developer picked up this thread. I was on the verge of going back to Sway until I saw your solution. Would be sad if others get stuck and move on.

I agree.  That would be a bummer.  I too was on the verge of going back to Ubuntu.  Hopefully the fix gets in soon.
