### ISSUE TITLE
[WAYLAND] pop-shell enabled breaks full-screen applications under wayland session

### ISSUE THREAD

**Issue by MaCroX95** [pop-os/shell#161]
This issue started happening today morning after the pop-shell update (not the last pop-shell update but one before that)

>` Pop-shell version:
> pop-shell:
>   Installed: 0.1.0~1586823586~20.04~63b89d0
>   Candidate: 0.1.0~1586891130~20.04~aff19c6
>   Version table:
>      0.1.0~1586891130~20.04~aff19c6 1001
>        1001 http://ppa.launchpad.net/system76/proposed/ubuntu focal/main amd64 Packages
>        1001 http://ppa.launchpad.net/system76/proposed/ubuntu focal/main i386 Packages
>  *** 0.1.0~1586823586~20.04~63b89d0 100
>         100 /var/lib/dpkg/status
>      0.1.0~1586537457~20.04~b55bbb5 1001
>        1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
>        1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages`

What happens:

Full-screen software offsets, and when exiting full-screen mode it leaves original state (if maximized it becomes offset after closing full-screen mode.

![Screenshot from 2020-04-14 12-09-19](https://user-images.githubusercontent.com/21268648/79274117-5e4c0c80-7ea4-11ea-90a0-98dd352373cd.png)

**Comment by mmstick** [comment]
Issue related to #152
