### ISSUE TITLE
js102 102.10.0 breaks tiling on Wayland

### ISSUE THREAD

**Issue by yochananmarqos** [pop-os/shell#1616]
**(1) Issue/Bug Description:**

Tiling stopped working completely on Wayland after updating `js102` from 102.9.0-1 to 102.10.0-1. Pop Shell appears to be functional, but toggling tiling does nothing.

It works properly switching to a Xorg session or downgrading `js102` back to 102.9.0-1 on a Wayland session.

```
❯ journalctl -b | grep pop-shell
Apr 16 09:39:13 inspirognome gnome-shell[703]: Extension pop-shell@system76.com already installed in /usr/share/gnome-shell/extensions/pop-shell@system76.com. /usr/share/gnome-shell/extensions/pop-shell@system76.com will not be loaded
Apr 16 09:39:22 inspirognome gnome-shell[1332]: pop-shell:  [INFO] init
Apr 16 09:39:22 inspirognome gnome-shell[1332]: pop-shell:  [INFO] enable
Apr 16 09:39:22 inspirognome gnome-shell[1332]: pop-shell: [DEBUG] override workspace._getCaption
Apr 16 09:39:58 inspirognome gnome-shell[1332]: JS ERROR: SyntaxError: nothing to repeat @ /usr/share/gnome-shell/extensions/pop-shell@system76.com/config.js:79:21
Apr 16 09:40:29 inspirognome gnome-shell[1332]: JS ERROR: SyntaxError: nothing to repeat @ /usr/share/gnome-shell/extensions/pop-shell@system76.com/config.js:79:21
Apr 16 09:40:43 inspirognome gnome-shell[1332]: JS ERROR: SyntaxError: nothing to repeat @ /usr/share/gnome-shell/extensions/pop-shell@system76.com/config.js:79:21
Apr 16 09:40:59 inspirognome gnome-shell[1332]: pop-shell:  [WARN] system76-scheduler may not be installed and running: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name com.system76.Scheduler was not provided by any .service files
```

**(2) Steps to reproduce (if you know):**

Be fully up to date on Manjaro (unstable branch) or Arch.

**(3) Expected behavior:**
Pop Shell should tile windows.

**(4) Distribution (run `cat /etc/os-release`):**

<details>
<summary>cat /etc/os-release</summary>

```
NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux
```

</details>

**(5) Gnome Shell version:**

43.4

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

a3a1b7b

**(7) Where was Pop Shell installed from:**

My Manjaro [package](https://gitlab.manjaro.org/packages/community/gnome/gnome-shell-extension/-/tree/master/gnome-shell-extension-pop-shell).

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1 x 1080p laptop monitor

**(9) Other Installed/Enabled Extensions:**

<details>
<summary>gnome-extensions list --enabled</summary>

```
space-bar@luchrioh
batterytime@typeof.pw
mullvadindicator@pobega.github.com
bluetooth-quick-connect@bjarosze.gmail.com
gnome-ui-tune@itstime.tech
appindicatorsupport@rgcjonas.gmail.com
native-window-placement@gnome-shell-extensions.gcampax.github.com
user-theme@gnome-shell-extensions.gcampax.github.com
caffeine@patapon.info
rounded-window-corners@yilozt
lockkeys@vaina.lt
AlphabeticalAppGrid@stuarthayhurst
pop-shell@system76.com
gamemode@christian.kellner.me
GPaste@gnome-shell-extensions.gnome.org
gsconnect@andyholmes.github.io
gnome-fuzzy-app-search@gnome-shell-extensions.Czarlie.gitlab.com
pamac-updates@manjaro.org
```

</details>

<details>
<summary>gnome-extensions list --disabled</summary>

```
keyboard-backlight-menu@ophir.dev
custom-accent-colors@demiskp
dash-to-dock@micxgx.gmail.com
apps-menu@gnome-shell-extensions.gcampax.github.com
auto-move-windows@gnome-shell-extensions.gcampax.github.com
drive-menu@gnome-shell-extensions.gcampax.github.com
launch-new-instance@gnome-shell-extensions.gcampax.github.com
places-menu@gnome-shell-extensions.gcampax.github.com
screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com
window-list@gnome-shell-extensions.gcampax.github.com
windowsNavigator@gnome-shell-extensions.gcampax.github.com
workspace-indicator@gnome-shell-extensions.gcampax.github.com
dash-to-panel@jderose9.github.com
gtk4-ding@smedius.gitlab.com
arcmenu@arcmenu.com
material-shell@papyelgringo
```

</details>

**(10) Other Notes:**

**Comment by rkylberg** [comment]
How do we downgrade "js102 back to 102.9.0-1 on a Wayland session" while waiting for a fix?

**Comment by yochananmarqos** [comment]
@rkylberg See https://wiki.archlinux.org/title/Downgrading_packages

**Comment by rkylberg** [comment]
Thanks for the link.

I am running on PopOS!  which is using apt for  package management so I found these [instructions to downgrade](https://www.makeuseof.com/how-to-downgrade-packages-linux/) but apt list js102 is empty and I don't see it in my /var/log/dpkg.log.

I have a ticket in with System76 and will update if/when they reply.

Meanwhile, any ideas if js102 is the cause of my woes and/or next steps to try to resolve this would be appreciated.

Thanks!

**Comment by yochananmarqos** [comment]
@rkylberg This issue is regarding Arch packages. I don't see how this issue applies at all to Pop!_OS. Whatever issue you may be having is not related to this issue. I invite you to create your own instead of hijacking this one.

**Comment by rkylberg** [comment]
k, cool. Thanks for the clarification. Did not intend to hijack your issue and will open another. Hope your issue gets sorted out.

**Comment by yochananmarqos** [comment]
I tested again today and cannot reproduce it on two machines. :man_shrugging:
