### ISSUE TITLE
[Nobara Linux, GNOME 43] Active hint not working on the first window opened

### ISSUE THREAD

**Issue by ghost** [pop-os/shell#1623]
**(1) Issue/Bug Description:**

Active hint not working on the first window opened, the second one, third one, etc works properly, but every window that is open for first time on a workspace don't get the hint, is pretty incosistent

**(2) Steps to reproduce (if you know):**
Open a window for first time on a workspace with active hint on 

**(3) Expected behavior:**
Window should have the active hint on the start and when more windows get opened

**(4) Distribution (run `cat /etc/os-release`):**
 
NAME="Nobara Linux"
VERSION="37 (Thirty Seven)"
ID=nobara
ID_LIKE="rhel centos fedora"
VERSION_ID=37
VERSION_CODENAME=""
PLATFORM_ID="platform:f37"
PRETTY_NAME="Nobara Linux 37 (Thirty Seven)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=nobara-logo-icon
CPE_NAME="cpe:/o:nobaraproject:nobara:37"
HOME_URL="https://www.nobaraproject.org/"
DOCUMENTATION_URL="https://www.nobaraproject.org/"
SUPPORT_URL="https://www.nobaraproject.org/"
BUG_REPORT_URL=""
REDHAT_BUGZILLA_PRODUCT="Nobara"
REDHAT_BUGZILLA_PRODUCT_VERSION=37
REDHAT_SUPPORT_PRODUCT="Nobara"
REDHAT_SUPPORT_PRODUCT_VERSION=37
PRIVACY_POLICY_URL=""
VARIANT_ID=workstation

**(5) Gnome Shell version:**
43

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**(7) Where was Pop Shell installed from:**

github

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1x1920x1080 horizontal

**(9) Other Installed/Enabled Extensions:**

Aylur widgets
Bluetooth Quick Connect
Logo Menu
Rounded window corners
Just perfection
User Themes

**(10) Other Notes:**

**Comment by ghost** [comment]
related to https://github.com/pop-os/shell/issues/1437

**Comment by leviport** [comment]
This is using Wayland, I presume? I haven't seen things like this happen under X11, but there are definitely some oddities with active hint under Wayland.

**Comment by ghost** [comment]
no, x11 session here

**Comment by ghost** [comment]
to fix this i disabled smart gaps, this option maximize the first window so there is no active hint at the start or after, not the best if you prefer the first window maximized but a good solution for me at least for now

**Comment by ghost** [comment]
(smart gaps option is on extension settings in the extension app)
