### ISSUE TITLE
In Tiling Mode, Active Border Radius does not change the thickness of Active Hint line

### ISSUE THREAD

**Issue by jlangson** [pop-os/shell#1629]
**Distribution (run `cat /etc/os-release`):**

 22.04 LTS
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Not sure. Maybe gnome-shell?
```

gnome-shell:
  Installed: 42.5-0ubuntu1pop1~1675984688~22.04~f574f54
  Candidate: 42.5-0ubuntu1pop1~1675984688~22.04~f574f54
  Version table:
 *** 42.5-0ubuntu1pop1~1675984688~22.04~f574f54 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     42.5-0ubuntu1 500
        500 http://apt.pop-os.org/ubuntu jammy-updates/main amd64 Packages
     42.0-2ubuntu1 500
        500 http://apt.pop-os.org/ubuntu jammy/main amd64 Packages
```

**Issue/Bug Description:**
When in Tiling Mode there is an Active Hint to see a line around the window that is active. There is a setting Active Border Radius, which should set the thickness Active Hint's line. However, adjusting the values for Active Border Radius has no affect on the border's Active Hint's thickness.

**Steps to reproduce (if you know):**

1. Turn on Tiling Windows
2. Turn on Show Active Hint
3. Open a window and see how thick the border is.
4. Change Active Border Radius and notice that thickness of the boarder is unchanged.

**Expected behavior:**

The Active Hint's line thickness changes based on the Active Border Radius.

**Other Notes:**

**Comment by leviport** [comment]
The radius setting is for the radius of the curve in the corners of the active hint. I believe that the thickness changing upon changes to the corner radius would be unexpected behavior. Creating an "Active Hint Thickness" setting in the extension's settings would be a nice new feature though.
