### ISSUE TITLE
Blurry JetBrains IDEs until maximizing and unmaximizing

### ISSUE THREAD

**Issue by szmikler** [pop-os/shell#1632]
**(1) Issue/Bug Description:**

Since some of the last Gnome updates, I've got this strange but not very major bug, where when I launch PyCharm I get this blurry looking window. I can avoid this by disabling pop-shell. Blurriness goes away after "maximizing" (ctrl+M) and "unmaximizing" the window. The next two screens how it looks like:

* Blurry window (font is larger than usually, the window was expanded)
![Screenshot from 2023-06-13 00-48-50](https://github.com/pop-os/shell/assets/43541355/705290c7-1ab8-4266-9c9d-b0c4670022b6)

* Not blurry, clear window (after maximizing and minimizing)
![Unsaved Image 1](https://github.com/pop-os/shell/assets/43541355/32207029-b20b-42f1-9f99-8ba954bc27e1)

I am reporting this for JetBrains IDEs, but I expect it might be happening for more applications. Will report if I notice it anywhere else.

**(2) Steps to reproduce (if you know):**

Launch PyCharm or other JetBrains IDE

**(3) Expected behavior:**

Non blurry

**(4) Distribution (run `cat /etc/os-release`):**
 
Manjaro

**(5) Gnome Shell version:**

44

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

community/gnome-shell-extension-pop-shell 1.2.0+293+gb5accce-1

**(7) Where was Pop Shell installed from:**

pacman

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

2x ultrawide 1440p + 1x 1440p

I confirmed this still happens after disabling all other extensions.

**Comment by jacobgkau** [comment]
Is this the same thing as https://github.com/pop-os/shell/issues/1621?

**Comment by szmikler** [comment]
Oh, yes, looks like the same thing. But happens 99% times for JetBrains IDEs.

**Comment by jacobgkau** [comment]
Good to know. I'm going to close this as a duplicate so we can keep all the relevant info in one place. Sounds like @mmstick might have a theory on what's causing it in the other issue.
