### ISSUE TITLE
Updates for Wayland/Gnome on 22.04 LTS? [Request]

### ISSUE THREAD

**Issue by pflanzenandi** [pop-os/shell#1633]
Are you planning on updating Wayland libraries for 22.04 LTS? Because I'll stay on this release for this machine until the latter dies. But there are some problems which make it a bit rough to run Wayland:
[Wayland-chromium](https://aur.archlinux.org/packages/wayland-chromium) and missing Fractional Scaling patches.

**Comment by jacobgkau** [comment]
Pop!_Shell is the GitHub repository for the window tiling GNOME extension. The repositories you're looking for would more likely be https://github.com/pop-os/gnome-shell or https://github.com/pop-os/mutter. You can also run `apt policy` for the packages of the specific libraries you're referring to to see if they're packaged by Pop!_OS (`apt.pop-os.org/release`) or Ubuntu (`apt.pop-os.org/ubuntu`).

A major GNOME version backport to 22.04 is not something that's planned as far as I know. The new [COSMIC Epoch](https://github.com/pop-os/cosmic-epoch) desktop environment will be Wayland-native, but the GNOME experience on Pop!_OS 22.04 was shipped with Xorg (with Wayland being disabled by default).
