### ISSUE TITLE
super + Direction key can't switch window foucus

### ISSUE THREAD

**Issue by DreamMaoMao** [pop-os/shell#1640]
os: ubuntu23.04 
desktop env : xorg

when i keydown super + left direction key or super + down direction key  ,it still work in previous function of ubuntu.

**Comment by DreamMaoMao** [comment]
The problem disappeared after I reboot the system a few times...

**Comment by DreamMaoMao** [comment]
The problem appeared when I reboot again.

**Comment by mmstick** [comment]
Make sure you installed with `make local-install`, and have installed and are using the https://github.com/pop-os/session session on the login screen. You'll also need the other cosmic extensions and pop-launcher installed.
