### ISSUE TITLE
Pop Shell incompatible with Gnome 44

### ISSUE THREAD

**Issue by Spilios06** [pop-os/shell#1647]
**(1) Issue/Bug Description:**

I am running vanilla arch and I am on a fresh Gnome install with everything on the latest version and I just installed pop shell from the AUR (the binary version), and after I went to enable it from the extensions app it wouldn't let me turn the extension on and it simply said "The extension is incompatible with the current Gnome version"

**(2) Steps to reproduce (if you know):**

Install arch with the latest version of gnome and try to download the extension from the AUR I guess.

**(3) Expected behavior:**

Error message mentioned above.

**(4) Distribution (run `cat /etc/os-release`):**
 
Arch Linux

**(5) Gnome Shell version:**

GNOME Shell 44.3

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**(7) Where was Pop Shell installed from:**
AUR

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

One monitor, 1920x1080 60Hz

**(9) Other Installed/Enabled Extensions:**

ArcMenu, Rounded Window Corners, UserThemes, Dash to Dock and Blur my Shell

**(10) Other Notes:**

**Comment by mmstick** [comment]
Build from github instead with `make local-install`
