### ISSUE TITLE
GNOME 45 Cannot Open Settings

### ISSUE THREAD

**Issue by kzhe2059** [pop-os/shell#1663]
**(1) Issue/Bug Description:**

Can't open extension settings on GNOME 45, I get the following message:

Issue with Pop Shell on Endeavour OS with GNOME 45, getting the following when I try to open extension settings.

The settings of extension pop-shell@system76.com had an error:
```
ImportError: Unable to load file from: resource:///org/gnome/shell/extensions/extension.js (The resource at “/org/gnome/shell/extensions/extension.js” does not exist)
```

Stack trace:
```
loadURI@resource:///org/gnome/gjs/modules/internal/loader.js:88:21
loadURI@resource:///org/gnome/gjs/modules/internal/loader.js:290:30
resolveModule@resource:///org/gnome/gjs/modules/internal/loader.js:179:33
moduleResolveHook@resource:///org/gnome/gjs/modules/internal/loader.js:339:29
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**(2) Steps to reproduce (if you know):**

1. Open GNOME Extensions
2. Scroll to Pop Shell
3. Hit Settings

**(3) Expected behavior:**

Settings opens

**(4) Distribution (run `cat /etc/os-release`):**
 
NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/arch-based-related-questions/bug-reports"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"

**(5) Gnome Shell version:**

45

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**(7) Where was Pop Shell installed from:**

Downloaded the zip and ran make local-install

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

One 1080p

**(9) Other Installed/Enabled Extensions:**

AppIndicator and KstatusNotifier, Arch Linux Updates Indicator, Bedtime Mode, Burn my Windows, Caffeine, Dark Variant, Firefox PIP Always on Top, Focus Changer, Force Quit, Just Perfection, Panel Scroll, Pano, Tactile, Tiling Assistant, User Themes (some of these are left over from before installing pop shell and now extraneous)

**(10) Other Notes:**

**Comment by Neo-29** [comment]
confirmed here too on archlinux
Despite that, the extension works.

**Comment by caribo** [comment]
the errors are originating from log.js which imports the extension in order to read the log level from settings

import {Extension} from 'resource:///org/gnome/shell/extensions/extension.js';
.
.
.
export function log_level() {
    let settings = Extension.lookupByURL(import.meta.url).getSettings();
    let log_level = settings.get_uint('log-level');
    return log_level;
}
.
.

Unfortunately I don't have the knowledge to fix this ..
