### ISSUE TITLE
Pop Shell not expanding remaining windows when one leaves the current workspace.

### ISSUE THREAD

**Issue by isantop** [pop-os/shell#167]
Pop Shell is allocating space for windows which have been moved off of the workspace using the Shift+Super+Arrow shortcuts. 

Steps to reproduce:
1. Set up a workspace with two windows in tiling mode, so that they half-tile.
2. Set up another workspace with one window below that one
3. Move a window from the two-window workspace to the empty bottom one using Shift+Super+Down.

The workspace in the middle (originally the one with one window) should how have one window taking up half the screen, with the other half of the screen empty.

**Comment by mmstick** [comment]
This issue was fixed yesterday, I believe. I'm not able to replicate it currently.

**Comment by WatchMkr** [comment]
Looks good to me.

**Comment by smasher-101** [comment]
I have this issue but only sometimes, such as when I launch UPlay from lutris and then close it it will leave a blank space consistently. I can submit a gif of it if it will help. This is the only program closing I have found to consistently cause the bug but it does happen sometimes with others and it is quite irritating as I don't know of a way to fix it without moving everything out of that desktop and into a new one.
