### ISSUE TITLE
Show hide windows title doesn't work on Wayland 

### ISSUE THREAD

**Issue by Neo-29** [pop-os/shell#1670]
https://github.com/pop-os/shell/commit/1c5899cdd830d0b4debbf349a0fa22caaf1f864b#commitcomment-131302476

**Comment by leviport** [comment]
I believe this is the same as https://github.com/pop-os/shell/issues/1671. I'm going to close this one as a duplicate, despite it being opened first, because https://github.com/pop-os/shell/issues/1671 is a much more detailed bug report.

**Comment by Neo-29** [comment]
> I believe this is the same as #1671. I'm going to close this one as a duplicate, despite it being opened first, because #1671 is a much more detailed bug report.

Get it, but it's not concerning only QT applications.
