### ISSUE TITLE
Hide windows title doesn't work with Qt Applications

### ISSUE THREAD

**Issue by pbui** [pop-os/shell#1671]
**(1) Issue/Bug Description:**

Recent commit 3386f42 has introduced a regression with Qt applications.  With this commit, Qt applications such as OBS studio, Zoom, and VLC no longer hide their window titles if this setting is enabled.

**(2) Steps to reproduce (if you know):**

Disable Show Window Titles and then start a Qt application such as OBS studio, Zoom, or VLC.

**(3) Expected behavior:**

The window title should be hidden as it was before this commit.

**(4) Distribution (run `cat /etc/os-release`):**

``` 
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**

42.5

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1698186494~22.04~3386f42
  Candidate: 1.1.0~1698186494~22.04~3386f42
  Version table:
 *** 1.1.0~1698186494~22.04~3386f42 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

Pop!_OS Apt repository.

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1080p, Primary (Horizontal)

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

I made my intial comments here: https://github.com/pop-os/shell/pull/1661#issuecomment-1785930603

**Comment by jacobgkau** [comment]
Confirmed this regression with KWrite. The regression testing document currently only suggests LibreOffice Writer and the Pop!_Shell Shortcuts dialog for testing this option; I also checked Evolution while testing https://github.com/pop-os/shell/pull/1661. Looks like we need to add a checkbox for a Qt app.

We will need to either revert https://github.com/pop-os/shell/pull/1661 or gate the change behind a GNOME version check.
