### ISSUE TITLE
Pop shell fails to load on GNOME 44.1

### ISSUE THREAD

**Issue by benny-sec** [pop-os/shell#1673]
**(1) Issue/Bug Description:**

Similar to #1649 Pop Shell fails to load on GNOME 44.1

```
SyntaxError: import declarations may only appear at top level of a module
```

**(2) Steps to reproduce (if you know):**

Install on Gnome 44.1 from git repo using make local_install

**(3) Expected behavior:**

Should work normally

**(4) Distribution (run `cat /etc/os-release`):**
 ```
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION_ID="2023.3"
VERSION="2023.3"
VERSION_CODENAME=kali-rolling
ID=kali
ID_LIKE=debian
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
ANSI_COLOR="1;31"
```
**(5) Gnome Shell version:**

```
GNOME Shell 44.1
```

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
Commit 1c5899cdd830d0b4debbf349a0fa22caaf1f864b
```

**(7) Where was Pop Shell installed from:**

locally build from master_mantic branch

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

Since I'm not familiar with TypeScript a very basic attempt was made to add 44.1 into metadata.json as below but the issue remained the same.

```json

{
    "name": "Pop Shell",
    "description": "Pop Shell",
    "version": 2,
    "uuid": "pop-shell@system76.com",
    "settings-schema": "org.gnome.shell.extensions.pop-shell",
    "shell-version": [
        "44.1",
        "45"
    ]
}
```
Attempts has also been made by directly building from the original pull request for 1660 but still failed.

**Comment by jacobgkau** [comment]
> locally build from master_mantic branch

`master_mantic` corresponds to Ubuntu 23.10 and supports GNOME 45+. For GNOME 3.36 through 44 support, use `master_jammy`.

**Comment by Benny-TalentzQ** [comment]
@jacobgkau  Thank you for the clarification and it helped. Kindly excuse me for the inconvenience caused as I misinterpreted the error 'import declarations may only appear at top level of a module to be associated with the ESM switch. I apologize for the inconvenience caused.  If it's not too much to ask can we please add your comment "_master_mantic corresponds to Ubuntu 23.10 and supports GNOME 45+. For GNOME 3.36 through 44 support, use master_jammy_." to the [Installation section of the README.md](https://github.com/pop-os/shell/tree/master_mantic#installation)
