### ISSUE TITLE
Proposal : Adding Launcher Themes to Pop Launcher

### ISSUE THREAD

**Issue by shivamksharma** [pop-os/shell#1677]
I would like to introduce a feature that enables users to customize the look and feel of their launcher through the addition of launcher themes. Themes provide users with a way to personalize their experience, allowing them to choose from a variety of designs, colorschemes, and styles to suit their preferences.

Benefits of Launcher Themes 👍🏻 
**Enhanced User Experience**: Themes offer a visual customization option, enhancing user satisfaction and engagement with the launcher. A vibrant theme ecosystem that allows users to express their individuality.
**Increased User Retention**: Personalization features like themes can contribute to higher user retention rates, as users are more likely to stick with a launcher that reflects their individual style. Increased community engagement through theme contributions and discussions.
**Community Engagement**: The addition of themes can foster creativity within the community, encouraging developers and designers to contribute their unique designs. Positive impact on user satisfaction and retention.
I am eager to hear your thoughts on this proposal and welcome any feedback. Together, I believe we can enhance the Pop Launcher experience and create a more dynamic and user-friendly platform for our PopOS community.

**Comment by mmstick** [comment]
This will be replaced with cosmic-launcher in the near future, which is already themeable with COSMIC's theme engine, so I'm not sure it's worth the effort here.
