### ISSUE TITLE
Active Hint not showing

### ISSUE THREAD

**Issue by proudhon** [pop-os/shell#1680]
**(1) Issue/Bug Description:**
Active window hint not showing

**(3) Expected behavior:**
Active hint showing

**(4) Distribution (run `cat /etc/os-release`):**
Arch Linux

**(5) Gnome Shell version:**
45.1

**(6) Pop Shell version**
```1.2.0+299+gaafc945-1```

**(7) Where was Pop Shell installed from:**
AUR

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1. 1080, Laptop Display Secondary 1080
2. 2k Primary Horizontal
3. 2. 2k Secondary Horizontal

**Comment by jacobgkau** [comment]
Are you running GNOME on Xorg or Wayland?

**Comment by proudhon** [comment]
Wayland, 

I don't know what actually solved this but reinstalling the extension a couple of times solved the problem.
