### ISSUE TITLE
import declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by gauravgulia26** [pop-os/shell#1688]
**(1) Issue/Bug Description:**
In the Pop!_OS Shell Integration for Debian, an error occurs that hampers the activation of extensions on Debian distributions. The current limitation, which restricts import declarations to the top level of a module, interferes with the normal functioning of extensions and prevents them from being enabled.

**(2) Steps to reproduce (if you know):**
1. Attempt to enable an extension on a Debian distribution that relies on the Pop!_OS Shell 
2. Encounter an error indicating that import declarations are only permitted at the top level of the module.
3. Extension activation fails due to the imposed restriction.

**(3) Expected behavior:**
Import declarations should be allowed at any level within the module, ensuring that extensions relying on the Pop!_OS Shell Integration can be activated successfully on Debian distributions.

**(4) Distribution (run `cat /etc/os-release`):**
Debian GNU/Linux 12 (bookworm)

**(5) Gnome Shell version:**
Gnome 43.9

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**(7) Where was Pop Shell installed from:**
Git Repository

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
2 x 1080p

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

**Comment by mmstick** [comment]
Sounds like you built the wrong version. Which branch did you install pop-shell from? The mantic branch is suitable for newer GNOME releases, as seen in Ubuntu Mantic and later.

**Comment by gauravgulia26** [comment]
I used the default branch from system76 official page, i guess they are using the mantic branch that you have mentioned.

**Comment by JmbFountain** [comment]
I'm running into the same issue on Debian Sid (Gnome 44)

**Comment by gauravgulia26** [comment]
Issue is resolved, just use mantic-jammy branch or something else to clone. Read the description they have mentioned gnome version with compatible branch.

**Comment by gauravgulia26** [comment]
I have fixed the issue, just clone from jammy branch not from main
