### ISSUE TITLE
Pop-shell Launcher not working Fedora 39 Gnome

### ISSUE THREAD

**Issue by hoosainmadhi** [pop-os/shell#1693]
**(1) Issue/Bug Description:**
launcher does not work as expected. Shortcut "Super / " opens launcher, but no applications appear. Launcher doesn’t show anything, it only shows the search bar.

**(2) Steps to reproduce (if you know):**
Fresh install F39
Install pop-shell using :
`sudo dnf install gnome-shell-extension-pop-shell
`

**(3) Expected behavior:**
Applications, running applications, etc… are shown and can be searched through / executed.

**(4) Distribution (run `cat /etc/os-release`):**
NAME="Fedora Linux"
VERSION="39 (Workstation Edition)"

**(5) Gnome Shell version:**
45

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

`1.2.0^21.aafc945-1.fc39
`

**(7) Where was Pop Shell installed from:**
sudo dnf install gnome-shell-extension-pop-shell

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1x1080p

**(9) Other Installed/Enabled Extensions:**
Vanilla install of gnome

**(10) Other Notes:**

**Comment by leviport** [comment]
The Launcher is a separate package. You'll probably need to install that one as well. I'm not sure what its name is in the Fedora repos though.

**Comment by hoosainmadhi** [comment]
> The Launcher is a separate package. You'll probably need to install that one as well. I'm not sure what its name is in the Fedora repos though.

The launcher is installed and does "launch" but does not behave as expected.

**Comment by jacobgkau** [comment]
> The launcher is installed and does "launch" but does not behave as expected.

No, the launcher would not "launch" since it's a background service. What you're seeing pop up on your screen is the frontend in Pop!_Shell. The backend is separate: https://github.com/pop-os/launcher 

If the backend (launcher) isn't installed, then you'll see the frontend (shell) pop up but not show any results.

**Comment by jacobgkau** [comment]
I don't see Pop Launcher packaged in Fedora right now, only the shell part: https://packages.fedoraproject.org/search?query=gnome-shell-extension-pop 

This would be a packaging issue in Fedora. The best solution would be for the maintainer to package pop-launcher and then make the [pop-shell package](https://packages.fedoraproject.org/pkgs/gnome-shell-extension-pop-shell/gnome-shell-extension-pop-shell/) depend on that. (Other frontends to pop-launcher already exist, and will also include the COSMIC Launcher, so having it as a separate package is worthwhile.)

**Comment by mmstick** [comment]
Since this is packaging issue in Fedora we should close this.

**Comment by jacobgkau** [comment]
The launcher service can be installed manually in the meantime using the instructions in the launcher repo's readme: https://github.com/pop-os/launcher

**Comment by hoosainmadhi** [comment]
> The launcher service can be installed manually in the meantime using the instructions in the launcher repo's readme: https://github.com/pop-os/launcher

thanks for  clarifying
