### ISSUE TITLE
Gnome 46 launcher

### ISSUE THREAD

**Issue by slaclau** [pop-os/shell#1706]
**(1) Issue/Bug Description:**
On Gnome 46, when using the lates PRs, the items in the launcher have inconsistent width.

**(2) Steps to reproduce (if you know):**
Install on Gnome 46

**(3) Expected behavior:**
Width should be consistent as with older  versions of Gnome

**(4) Distribution (run `cat /etc/os-release`):**
 Arch

**(5) Gnome Shell version:**
46

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
56e6be07079f8327f7b41ea3b797ca3972192c6d

**(7) Where was Pop Shell installed from:**
Local build from github

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

**Comment by lmassach** [comment]
I also have the same issue, here is a screenshot in case it can help
![image](https://github.com/pop-os/shell/assets/62757383/6cbfc5f3-3a96-40ee-9cec-587ce597a13a)

**Comment by lmassach** [comment]
@garaevdi Thanks for the fix, works perfectly
![image](https://github.com/pop-os/shell/assets/62757383/a7ea3113-9b80-4821-81c6-5521ba09ea27)

**Comment by kzhe2059** [comment]
How would one go about installing the above fix?
