### ISSUE TITLE
Predictable preserved order of workspaces between connecting/disconnecting external display

### ISSUE THREAD

**Issue by cmihail** [pop-os/shell#1716]
I've got the following setup at home: one laptop with PopOS and an external monitor. Due to personal reasons I need to disconnect/re-connect to the external monitor multiple times during the same so that I can work either from my desk or from another room when I need to be present in that other room. Here is a description of how I expect this to work: https://unix.stackexchange.com/questions/761355/preserve-order-of-workspaces-in-popos-gnome-wayland-when-disconnecting-reconnect

Currently this is not the case with Cosmic DE, as it doesn't preserve the order of the workspaces. More exactly, if laptop display has apps in 2 workspaces and external right monitor also has apps in 2 workspaces, then on disconnect workspace 1 from external right monitor is placed after the 2 workspaces from the laptop display, while on reconnect workspace 1 from external monitor will be empty, workspace 2 will contain what used to be in the first workspace in the external monitor and workspace 3 will contain what used to be in the second workspace in the external monitor. The order of the workspaces in the laptop display are preserved on reconnect.

If needed I can add a video with this behavior.

--------------------------------------

This is one of the main headaches I have with current PopOS based on Gnome and the main reason I'd like to switch to another DE with auto-tiling.

**Comment by leviport** [comment]
To clarify, are you using the alpha version of [COSMIC DE](https://github.com/pop-os/cosmic-epoch), or are you using the Gnome-based Cosmic experience that's currently the default in Pop!\_OS 22.04? This repo is for that Gnome extension, but you mention COSMIC DE explicitly.

**Comment by cmihail** [comment]
> To clarify, are you using the alpha version of [COSMIC DE](https://github.com/pop-os/cosmic-epoch), or are you using the Gnome-based Cosmic experience that's currently the default in Pop!_OS 22.04? This repo is for that Gnome extension, but you mention COSMIC DE explicitly.

Sorry, this was for COSMIC DE. Created another issue in the right repo: https://github.com/pop-os/cosmic-epoch/issues/360
