### ISSUE TITLE
Re-Tile Windows When the Primary Display Changes

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/shell#172]
This is to account for the top panel and could be combined with #171 

Before
![before_changing_primary_display](https://user-images.githubusercontent.com/3430283/79387992-d577b400-7f29-11ea-9a13-1c35cb38370b.png)
After (notice the gap above the setting window.
![after_changing_primary_display](https://user-images.githubusercontent.com/3430283/79388004-d9a3d180-7f29-11ea-8af1-1ec4ab0df0aa.png)

**Comment by mmstick** [comment]
This was fixed
