### ISSUE TITLE
Windows are stretched verticallly and horizontally after you unlock screen

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#174]
Steps to reproduce:
1. Tile some windows
2. Lock screen
3. Unlock screen

![image](https://user-images.githubusercontent.com/39338488/79391808-34482800-7f40-11ea-86a0-4ef9ed208287.png)

Appears to affect all workspaces with more than 1 window. Only way to fix afterwards is to restart the shell.

EDIT: System: Fedora with Gnome 3.36, Xorg.

**Comment by WatchMkr** [comment]
Do you have dual monitors?

**Comment by nicolae-stroncea** [comment]
This is on my default laptop screen

**Comment by WatchMkr** [comment]
I'm seeing this as well though with multiple monitors.

**Comment by nicolae-stroncea** [comment]
It seems that upon unlocking, the tiling ignores the topbar, and windows tile under it as well. Not sure what happens to the sides though, and if fixing the top bar issue would also fix the side issue.

**Comment by mmstick** [comment]
This should be fixed by 4869b48fc86cf3b6f075ef64cdf0bdb934d97c2a

**Comment by nicolae-stroncea** [comment]
Issue doesn't occur anymore, thanks
