### ISSUE TITLE
Gnome 47 support on non-Ubuntu distributions - SERIOUS.

### ISSUE THREAD

**Issue by CodedIsTaken** [pop-os/shell#1743]
Hiya, I’m on Fedora rawhide / gnome 47, I installed pop-shell though the packages on Fedora’s repos and it said it was not supported, it looks like the team is not putting focus on non-Ubuntu based distributions anymore, please update or find a workaround for gnome 47, as it is disabled on gnome 47.

**Comment by jackpot51** [comment]
Sounds like the fedora package is out of date, we can't fix that.

**Comment by CodedIsTaken** [comment]
> Sounds like the fedora package is out of date, we can't fix that.

this is not completed, you did not specify any workaround non-ubuntu users, or just fedora users are able to take.

**Comment by jackpot51** [comment]
Install it from the repository: https://github.com/pop-os/shell, which is where you are creating issues. I can't update Fedora packaging, ask a Fedora maintainer.
