### ISSUE TITLE
Can't use pop shell on debian 12 gnome 43.9

### ISSUE THREAD

**Issue by dos2803** [pop-os/shell#1746]
**(1) Issue/Bug Description:**
I clone it to my debian 12 but it said the extension incompatible with my GNOME version
```
SyntaxError: import declarations may only appear at top level of a module

Stack trace:
  _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:23:33
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
  async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:368:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:401:34
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
  

**(2) Steps to reproduce (if you know):**
...

**(3) Expected behavior:**

cool and awesome features .-.

**(4) Distribution (run `cat /etc/os-release`):**
 ![image](https://github.com/user-attachments/assets/c9d4991f-1725-4a29-9068-1d7aebe9a637)

**(5) Gnome Shell version:**
43.9

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
lastest

**(7) Where was Pop Shell installed from:**
make local-install, from official repo

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

Single screen laptop 14", 1920x1080

**(9) Other Installed/Enabled Extensions:**

nothing

**(10) Other Notes:**

**Comment by siddhpant** [comment]
You need to use the correct branches: https://github.com/pop-os/shell?tab=readme-ov-file#installation

**Comment by jacobgkau** [comment]
Like @siddhpant said, please make sure you're using the `master_jammy` branch for GNOME 43 (with `git checkokut master_jammy` after cloning and before building). Let us know if you still have an issue with that branch, or if that solves the problem.

**Comment by dos2803** [comment]
> Like @siddhpant said, please make sure you're using the `master_jammy` branch for GNOME 43 (with `git checkokut master_jammy` after cloning and before building). Let us know if you still have an issue with that branch, or if that solves the problem.

Thank you, I resolved it

**Comment by dos2803** [comment]
> You need to use the correct branches: https://github.com/pop-os/shell?tab=readme-ov-file#installation

Thank you too, I resolved it
