### ISSUE TITLE
Does not work with Fedora 41 (47.1)

### ISSUE THREAD

**Issue by suuuehgi** [pop-os/shell#1747]
**(1) Issue/Bug Description:**
Does not work with Fedora 41.
The extensions app (`gnome-extensions-app`) states

```log
The installed version of this extension (2) is incompatible with the current version of GNOME (47.1). The extension has been disabled.
``` 

**(2) Steps to reproduce (if you know):**
```
git clone https://github.com/pop-os/shell
cd shell
git checkout origin/master_noble
make local-install
```

**(3) Expected behavior:**
Work

**(4) Distribution (run `cat /etc/os-release`):**
 Fedora 41 (Workstation Edition)

**(5) Gnome Shell version:**
47.1

**Comment by mmstick** [comment]
You checked out the wrong branch. You need to check out master_mantic.

**Comment by michalvankodev** [comment]
Do you know what is the status of the `gnome-shell-extension-pop-shell` fedora package for F41? It doesn't work reporting that is not compatible with the Gnome version used by Fedora 41.

**Comment by jacobgkau** [comment]
We don't maintain the Fedora package, we only maintain the upstream project and the Pop!_OS package. Who is the Fedora packager who packaged the `gnome-shell-extension-pop-shell` package?

**Comment by jacobgkau** [comment]
It looks like someone has already filed a bug report on Fedora's downstream package bug tracker: https://bugzilla.redhat.com/show_bug.cgi?id=2322524 That would be the bug report for the package being out-of-date in Fedora.

For reference, you can search Fedora packages and access their downstream bug trackers from this website: https://packages.fedoraproject.org/pkgs/gnome-shell-extension-pop-shell/

**Comment by suuuehgi** [comment]
> You checked out the wrong branch. You need to check out master_mantic.

Your README.md states:

```
GNOME 45: Use the master_mantic branch.
GNOME 46+: Use the master_noble branch.
```

as does the corresponding `metadata.json`.
(And the problem persists using `master_mantic`.)

**Comment by suuuehgi** [comment]
After installing / uninstalling mantic, noble and the updated Fedora repository version a couple of times, it suddenly works using `master_noble`. A few minutes ago it was not. I will just not touch it anymore.
