### ISSUE TITLE
Possibly convert to TypeScript

### ISSUE THREAD

**Issue by mmstick** [pop-os/shell#18]
Apparently, [this is very possible to do with shell extensions](https://github.com/timbertson/shellshape#hacking). Changes required should be minimal, as it is mostly adding types to functions and fixing type errors reported by the compiler.

**Comment by Mazuh** [comment]
Hi! I'd like to help on that. How can we proceed?

**Comment by mmstick** [comment]
I have a typescript branch which is almost complete. I will merge it as soon as I've fix the few remaining issues. It was relatively easy to convert, and it uncovered a few JavaScript bugs along the way.

**Comment by Mazuh** [comment]
(a lot of questions ahead!)

what branch is that? may I help on these issues? you're fixing these bugs or just typing?

**Comment by mmstick** [comment]
Development is actively happening in the typescript branch. I am working on it right now. I will complete it today.

**Comment by mmstick** [comment]
This is now complete
