### ISSUE TITLE
Application quits half full-screen when focus shifts to other side of screen

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#188]
To reproduce:

1. Maximize a window on the left side of the screen by dragging it to left edge.
2. Focus on something on the right side of the screen
3. Application on the left quits occupying left side of the screen and snaps back into the layout.

Started ocurring after 37135dc48ae73970efa156260cd2fc9aa5097a5f.

**Comment by mmstick** [comment]
It will now only unmaximize if the focused window is behind the maximized window
