### ISSUE TITLE
Active Hint not applied after exiting full-screen of browser

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#189]
For some reason this only occurs with web browsers(tested on Firefox and Chromium).

To reproduce:

1. Open Firefox and another window.
2. Maximize Firefox, then quit full-screen.
3. Active Hint is not applied anymore.

Occurs on Gnome 3.36 with Xorg

**Comment by WatchMkr** [comment]
Good catch. That's weird.

**Comment by nicolae-stroncea** [comment]
Also occurs with VsCode and Chromium

**Comment by WatchMkr** [comment]
This is fixed.
