### ISSUE TITLE
Treat large monitors as multiple displays

### ISSUE THREAD

**Issue by danielyzli** [pop-os/shell#191]
I noticed in the docs that it is planned to treat ultrawide monitors as two displays side-by-side by default, which makes sense. Is it possible to make this behaviour configurable (i.e. default # of display rows / columns). For instance, this would make sense for those large 43" 4K displays which are essentially 4 21.5" monitors, as well as the super wide 32:9 displays that could be split in 3 columns. Thanks and really appreciate your work!

**Comment by dustymabe** [comment]
I do this today with i3 with a little known feature called `fake-outputs`. You can find some references to it in the i3 FAQ ([link](https://faq.i3wm.org/question/1659/force-one-i3-instanceworkspace-across-multiple-monitors.1.html)). For example I carve out my `3840x2160` display into 4 different rectangles with:

```
#              fake-0           fake-1           fake-2           fake-3        
fake-outputs 1440x1080+0+0 1440x1080+0+1080 2400x1080+1440+0 2400x1080+1440+1080
```

in my i3 config. I would love to have this concept/feature in pop-os/shell. It may be possible already, I'm just now getting to a point where I can try this project out but I've been wanting "i3wm for gnome-shell" for a long time and I really hope the `fake-outputs` functionality is something that is being considered.

**Comment by WatchMkr** [comment]
We're tracking a potential configurable columns feature here: https://github.com/pop-os/shell/issues/204

**Comment by dustymabe** [comment]
Hey @WatchMkr - Is the word "Columns" taken literally? The fake-outputs feature of i3 really allowed you do define any area to be used as a separate logical monitor. For example, I have two 27" widescreen monitors that I rotated vertically (portrait mode) and then I split them in half (so two "rows", not two "columns". I also have another setup with a single 43" TV as the monitor and I've got it split up into 4 unequal partitions (all treated as a separate monitor essentially). With i3 fake-outputs you can slice it up any way you'd like given x,y coordinates.

**Comment by WatchMkr** [comment]
Right considering vertical layouts, column isn’t the best description for customizing the split.

**Comment by dustymabe** [comment]
Hey @WatchMkr - I'm not sure this feature request is covered by #204. In https://github.com/pop-os/shell/issues/191#issuecomment-616231383 I describe an i3 configuration for i3wm that allows you to split up your single monitor into multiple displays. It treats each virtual space just as if you had that many monitors physically plugged in. Is there another issue that covers this use case? Should we re-open this feature request?

I apologize if there is a feature and or documentation that I've missed.
