### ISSUE TITLE
Resolution of some apps distorted after exiting full-screen, if they're on the bottom

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#192]
**Distribution:**
 
Fedora 32, Gnome 3.36, Xorg.
 
**Details on system**:

1 display, 1080p screen
 
**Related Application and/or Package Version:**

Commit 0b31993db308d09dc4e8ab6ffb622ee849473715.

**Issue/Bug Description:**

I've experienced this bug for a long time and was finally able to find a reproducible pattern. After you exit full-screen of browser, in certain conditions the resolution of the browser will be noticeably distorted. I don't think I've observed this with any other applications, but it might still be possible.

Might be related with #189.

![image](https://user-images.githubusercontent.com/39338488/79585872-67a0c900-809e-11ea-8760-29c5f3a4a25a.png)

**Steps to reproduce (if you know):**

1. Tile 2 browsers horizontally on top of each other.
2. For the bottom one, maximize it with `Super M` and then exit full-screen again with `Super M`.
3. Compare the resolution on the 2 browsers and notice that the bottom one is significantly distorted. This can be most easily seen by comparing how crisp the tabs are in the browser above compared to the browser below.

**Expected behavior:**

Resolution is not distorted.

**Other Notes:**

This only seems to occur if the browser is tiled somewhere on the bottom. Moreover, if you move the distorted browser on the bottom, to the top, it instantly corrects itself.

**Comment by nicolae-stroncea** [comment]
Upon further experimenting, this is not unique to browsers.
You can reproduce the same behaviour with VSCode, Chromium

**Comment by nicolae-stroncea** [comment]
Seems to occur for non-GTK apps

**Comment by mmstick** [comment]
It's a race condition in GNOME Shell. The blurry effect is applied when a window is being animated by the Tweener. It clears up after the window's frame is actually moved at the end of the animation, but sometimes the frame resize does not redraw the window. I've been looking for a solution to this for a while. I may need to simply use a hacky workaround for this issue in GNOME.

**Comment by Dark-Matter7232** [comment]
i can confirm that it occurs for GTK apps also

**Comment by mmstick** [comment]
Related upstream GNOME bug: https://gitlab.gnome.org/GNOME/mutter/issues/860

**Comment by danielyzli** [comment]
Sometimes occurs even without having to maximize the bottom window. A temporary fix is to drag the blurry window a tiny bit then let it settle back where it was...gets rid of the blurriness.

**Comment by cpisto** [comment]
Seeing this regularly on latest Pop!_OS 20.04 w/ an Nvidia gpu (desktop).
My display resolution 1080p, Non HiDPI, in case that's an important variable.

Seems to happen most often when:
1. Tiling is enabled
2. A single application window is maximized (for example, Firefox)
3. A second application is launched causing a 50/50 tile split.

In this instance the new window appears slightly blurry, and moving or resizing it fixes it.

I haven't found a specific set of circumstances that reliably reproduce the issue, but its happening with GTK, QT, and Electron applications many times per day for me.

**Comment by hypergig** [comment]
> It's a race condition in GNOME Shell. The blurry effect is applied when a window is being animated by the Tweener. It clears up after the window's frame is actually moved at the end of the animation, but sometimes the frame resize does not redraw the window. I've been looking for a solution to this for a while. I may need to simply use a hacky workaround for this issue in GNOME.

I can agree with this. If you enter adjustment mode and leave it, the tile goes back to normal.

**Comment by mmstick** [comment]
Combining this issue with #457

**Comment by laichiaheng** [comment]
So...has it been fixed?

**Comment by jmmaranan** [comment]
@laichiaheng - No, duplicates are being closed. Please track it on #457.
