### ISSUE TITLE
Resizing by cursor often doesn't work

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#197]
**Distribution (run `cat /etc/os-release`):**
 
 Fedora 32, Gnome 3.36
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

Commit 0b31993db308d09dc4e8ab6ffb622ee849473715

**Issue/Bug Description:**

Very often resizing by dragging the edge of a window doesn't register and doesn't work. 

**Steps to reproduce (if you know):**

I haven't found a consistent pattern, it seems to occur randomly. Open 2 terminals, keep resizing them a couple of times, and in my case 30%+ of the resize attempts won't work.

**Expected behavior:**

Resizing works as intended

**Comment by mmstick** [comment]
How do they not work? Is this because a resize attempts to resize a window smaller than that window can be resized, so the window does nothing? Or because it hits the minimum length of a sibling (256)?

**Comment by nicolae-stroncea** [comment]
![bug_report](https://user-images.githubusercontent.com/39338488/79618244-83749100-80d7-11ea-9bd6-d5813ae4311f.gif)

Here's a video showing it. Resizing don't work when they should. In this example, I am dragging the window to the right, but it's not actually being dragged. It occurs seemingly randomly but very often

**Comment by mmstick** [comment]
That's weird. I haven't seen this before. Logs would be useful. We actually don't manipulate windows being resized with a drag operation until after GNOME Shell has given the drag-end signal.

**Comment by nicolae-stroncea** [comment]
I did make listen, and tried to resize. It again failed, but no logs were generated

**Comment by nicolae-stroncea** [comment]
![bug_report](https://user-images.githubusercontent.com/39338488/79623277-5c26bf80-80e9-11ea-99fb-ee01ac877368.gif)

**Comment by nicolae-stroncea** [comment]
I turned Active Hint off and it seems to work without a glitch. Since Active hint is implemented as 4 boxes, is it possible that when I try to resize with cursor, it's interpeted as a click on the hint box?

**Comment by nicolae-stroncea** [comment]
Issue seems to be fixed
