### ISSUE TITLE
Feature Request: Execute aliased commands from launcher

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#199]
Currently when trying to execute a command by an alias i defined in my .bashrc file, I get *Command not found*

**Comment by mmstick** [comment]
Try executing the command with bash. The launcher executes commands in `/bin/sh` by default.

**Comment by laichiaheng** [comment]
> Try executing the command with bash. The launcher executes commands in `/bin/sh` by default.

How to execute the command with bash in launcher?

**Comment by jleseane23** [comment]
> Try executing the command with bash. The launcher executes commands in `/bin/sh` by default.

Tried this. Same result.

I also tried adding the alias to the system profile. Same result.

I don't think aliases work with ulauncher either.

I was able to make a function for the alias and run it that way though.

**Comment by s0kil** [comment]
Would like to be able to set the launcher shell to bash

**Comment by s0kil** [comment]
Most language/library/framework version managers, rvm, nvm, asdf, sdkman require `.bashrc` configuration. If I've installed ruby with asdf into $HOME directory, `/bin/sh` won't pick it up, making it more difficult to launch python interpreter from application launcher.
