### ISSUE TITLE
Feature request: Move "Show Window Titles" To Extension Menu

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#200]
For my use case, when I'm in a video call with somebody, I will set the window with the video call to floating and  "always on top" so I can hover it above the actual applications I'm using. For the applications which do not have a headerbar (most non-GTK applications) this is only possible by right clicking on a titlebar for them.

I have "Show Window Titles" to off by default to maximize screen usage, and when I need to have a video call with somebody, I have to navigate to overview, click on "Extensions", click on pop shell settings, then click "show window titles", and only then I can set a window to "always on top".

**Comment by WatchMkr** [comment]
We plan to move this feature to the menu once we've worked through consistency issues.
