### ISSUE TITLE
Configuring number of columns

### ISSUE THREAD

**Issue by tcabanski** [pop-os/shell#204]
I have a 3440 wide display and the grid ends up with 3 columns.  I would really prefer 2.  Any way to configure this?

**Comment by WatchMkr** [comment]
Not at the moment but we'll be considering maximum column settings in the next release.

**Comment by bizharvest** [comment]
Along with this change it would be nice to be able to have additional rows per screen. I have 3 screens, where 1 is vertical. I use it for my communications screen, slack, email, ticket desk, etc. As far as I can tell, I can only place 2 apps stacked on top of each other. Any more apps create a matrix of 2 rows x 2 columns. I would prefer (only on that one screen) to have 3 or 4 rows with 1 column.

**Comment by mmstick** [comment]
You can have as many rows or columns as you want. Use `Super + O` to toggle the orientation of a node.

**Comment by bizharvest** [comment]
Thank you for your prompt reply. I did not see that in any documentation. I probably missed in on GitHub.

Matt
Matt Furister | Owner
a: Biz Harvest | 1823 65th Ave Suite 1 | Greeley, CO 80634
e: matt@bizharvest.com (mailto:matt@bizharvest.com) | w: bizharvest.com (http://bizharvest.com/)
m: +1 (970) 978-8063 (tel:+1%20(970)%20978-8063) | p: +1 (720) 316-7796 (tel:+1%20(720)%20336-0461)
NEED HELP?

We offer the following resources for assistance, website updates, or to report an issue.

Status Page
status.bizharvest.com (http://status.bizharvest.com)

Enter a Ticket
care.bizharvest.com (http://care.bizharvest.com)

Send an Email
care@bizharvest.com (mailto:%20care@bizharvest.com)

General Knowledge Base
kb.bizharvest.com (http://kb.bizharvest.com)

Orange Seed Tutorials
okb.bizharvest.com (http://okb.bizharvest.com)

**Comment by kaisellgren** [comment]
Where can you configure this?

**Comment by mmstick** [comment]
@kaisellgren `Super + O` on a node in the tree.
