### ISSUE TITLE
Shell does not like GitKraken

### ISSUE THREAD

**Issue by tcabanski** [pop-os/shell#205]
When it comes up, I see an error message toaster that says roughly "does not have actor and cannot move".  It it is on the screen/workspace by itself, it seems to work OK, but if it is on the same workspace as other windows (e.g. VSCode), it sometimes starts overlapping windows and ends up hiding the right side of the GitKraken windows.  This seems to happen more often when I have a term window in the middle column (my display is 3440x1440). I don't have exact steps to reproduce at this point since it only happens sometimes.  I tried different orders of opening the apps but can't seem to hit on a reliable reproduction except that the error opening GitKraken always appears.

**Comment by tcabanski** [comment]
Closing a window that is on the screen with GitKraken when there are at least three windows tiled on the display (3 columns) appears to create the overlapping problem reliably.

**Comment by mmstick** [comment]
Overlapping is a side effect of the window not being able to shrink to fit in the requested space. We can't force a window with Mutter to shrink smaller than its limit. The actor error is a different thing entirely.

**Comment by wmutschl** [comment]
I also have issues with gitkraken and pop shell. Particularly, when I close it, I still have it in my dock, but cannot open it there. I explicitly have to right click on the icon and open it in a new window.

**Comment by wmutschl** [comment]
Is there a way to explicitly exclude applications from pop shell?

**Comment by WatchMkr** [comment]
The solution we're working on is to adjust the layout to the minimum size of the window that won't shrink further. We're using this issue for tracking: https://github.com/pop-os/shell/issues/85
