### ISSUE TITLE
Resolution change reconnects display, which moves windows to a new workspace

### ISSUE THREAD

**Issue by leviport** [pop-os/shell#209]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 20.04
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
https://github.com/pop-os/shell/commit/8ee8268f282b7951c2adf15992661c462450b875

**Issue/Bug Description:**
I have 2 displays set up: the laptop's internal 1920x1080 and a 2560x1440 set up above it. Here is a screenshot of what this looks like: 
![Screenshot from 2020-04-20 11-49-43](https://user-images.githubusercontent.com/13512097/79783791-6f5ea880-82fe-11ea-8876-a87b1bb33333.png)

Now if I reduce the resolution of the top display to 1920x1080, the window grid stays the same size and spills off the edges. 
![Screenshot from 2020-04-20 11-50-09](https://user-images.githubusercontent.com/13512097/79783852-8ef5d100-82fe-11ea-892c-468eef9f3fc3.png)

And then if I increase the resolution of the top display back to 2560x1440, it gets even scarier:
![Screenshot from 2020-04-20 11-50-39](https://user-images.githubusercontent.com/13512097/79784032-dd0ad480-82fe-11ea-80c9-0b72fd797f63.png)

**Steps to reproduce (if you know):**
See above

**Expected behavior:**
If a resolution change triggered a re-tile, it might take care of the issue.

**Other Notes:**
I also noticed some similar weirdness when switching the scaling factor, but it seemed less reproducible. It may be worth investigating since it seems like the same sort of issue.

**Comment by mmstick** [comment]
Is this still an issue?

**Comment by leviport** [comment]
It looks like it now re-tiles the windows to the correct size, but the two that were on the external display get moved to a separate workspace. I wonder if a resolution change triggers the same thing that detects when a display gets removed.

**Comment by mmstick** [comment]
That sounds like what's happening. Perhaps there needs to be a timeout when displays are disconnected and reconnected after a display change.

**Comment by leviport** [comment]
Oh also, the part where the window on the bottom monitor gets covered by the top bar is still present. Forgot to mention that.

**Comment by WatchMkr** [comment]
I also see this when I leave a laptop w/ external monitor locked for an extended period.

**Comment by mmstick** [comment]
Is this still an issue?

**Comment by leviport** [comment]
It appears to be fixed now
