### ISSUE TITLE
Extra active hint box is created during moving windows with cursor

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#212]
**Distribution (run `cat /etc/os-release`):**
 
 Fedora 32, Gnome 3.36, Xorg
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

8ee8268f282b7951c2adf15992661c462450b875

Issue wasn't occuring with 0b31993db308d09dc4e8ab6ffb622ee849473715.

**Issue/Bug Description:**

Behaviour before:
![before](https://user-images.githubusercontent.com/39338488/79813676-4bc14f80-834a-11ea-8607-7fadc5879381.gif)

Behaviour currently:

![after](https://user-images.githubusercontent.com/39338488/79813690-5380f400-834a-11ea-97f9-a88dda3dffce.gif)

Active hint before was generated smoothly. Now an active hint box is generated during the transition as well.

**Steps to reproduce (if you know):**

Drag a window with the cursor somewhere else on the screen.

**Comment by mmstick** [comment]
It's a workaround for now to fix the issue with certain windows (Firefox) losing their active hint on unfullscreens.

**Comment by WatchMkr** [comment]
This appears to be fixed.

**Comment by nicolae-stroncea** [comment]
I'm on latest commit in develop 83372aee05b778d2585402cdc070574665a247a2 and the issue still persists
