### ISSUE TITLE
Terminal in tiling mode has border/gap when none is set

### ISSUE THREAD

**Issue by TheChiefMeat** [pop-os/shell#213]
**Distribution**

NAME="Pop!_OS"
VERSION="20.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**
The terminal window has a border/gap, despite the tiling gap size being set to 0.

**Steps to reproduce (if you know):**
Turn on tiling mode, open a window plus a terminal window. Set Gaps to 0.

**Expected behavior:**
When the terminal is open in tiling mode and gap is set to 0, there should be no gap.

Edit

Added below image for reference:

![2020-03-29_17-42](https://imgur.com/nqKm8RH.png)

**Comment by mmstick** [comment]
The gap is created by GNOME Terminal itself, because it resizes itself to certain increments.

**Comment by TheChiefMeat** [comment]
@mmstick Is there any way in PopOS to get rid of that gap?
