### ISSUE TITLE
Issue with reopening from dock/panel icons after closing windows

### ISSUE THREAD

**Issue by kubj31196** [pop-os/shell#218]
**Distribution (run `cat /etc/os-release`):**
 Pop OS 20.04
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
0.1.0~1587486784~20.04~0e79c1a

**Issue/Bug Description:**
When closing the window, the application still register the closed window as a minimize instance on the dock/panel that can not be manually close, blocking the access of the application via traditional method.

**Steps to reproduce (if you know):**
https://streamable.com/8mct5o

**Comment by leviport** [comment]
Thank you for the report! It has been filed here https://github.com/pop-os/beta/issues/70 already so I'm going to close this one.
