### ISSUE TITLE
Applications can't be moved between monitors in Overview sometimes

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/shell#22]
I'm not quite sure what is triggering it but applications sometimes can't be moved between monitors or workspaces. It happens in Pop 19.10 though it seems to correct itself sometimes.

**Comment by mmstick** [comment]
This should be fixed now

**Comment by ahoneybun** [comment]
It seems to only happen in Auto Tile mode.

**Comment by mmstick** [comment]
Is this still an issue?

**Comment by ahoneybun** [comment]
I haven't been able to recreate it recently. I have seen different behavior now and I'll create a new bug for it.
