### ISSUE TITLE
Firefox titlebar double-up

### ISSUE THREAD

**Issue by flukejones** [pop-os/shell#228]
Happens when Firefox has titlebar disabled, but shell has titlebars enabled. Ends up looking like this:

![Screenshot from 2020-04-28 07-21-56](https://user-images.githubusercontent.com/2015870/80422659-aeaa7c00-8932-11ea-8bb7-6731c9162b0b.png)

Firefox needs to have titlebar enabled for it to look right with shell enabled with tiling disabled.

**Comment by leviport** [comment]
Thanks for the report! We're tracking this one here: https://github.com/pop-os/beta/issues/2
