### ISSUE TITLE
Pop Shell does not respect shell theme choice

### ISSUE THREAD

**Issue by Dark-Matter7232** [pop-os/shell#231]
**Distribution (run `cat /etc/os-release`):**
 NAME=Fedora
VERSION="32 (Workstation Edition)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation

 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
[commit](https://github.com/pop-os/shell/commit/16b4c33a8542969f19471b13b90764575a45ccf9)

**Issue/Bug Description:**
when using non default shell theme, pop shell reverts my choice of theme to system default shell theme on session start(restart or login)

**Steps to reproduce (if you know):**
Select a non default shell theme and logout or restart, pop shell will revert the theme to default

**Expected behavior:**
Shell theme should be as it was before login/restart

**Comment by sdkmor** [comment]
Same for me.
Using:

NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**Comment by patrick-tang** [comment]
Same problem here. I'm using Manjaro with default theme "Matcha-sea". Once I enable pop-shell extention the shell theme will behaviour like Adwaita Dark.
Using:
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.manjaro.org/"
SUPPORT_URL="https://www.manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux

**Comment by patrick-tang** [comment]
I think someone else also reported same issue here:
https://github.com/pop-os/shell/issues/230

**Comment by debatego** [comment]
Same problem here.

**Comment by Lincoln504** [comment]
Can confirm, same problem on Fedora.

**Comment by nitinsareen** [comment]
can confirm the same plus getting this error while changing themes (attached).

Pop Shell Error:
failed to load stylesheet: Error: Argument 'file' (type interface) may not be null.
![Screenshot from 2020-05-03 09-16-40](https://user-images.githubusercontent.com/7134429/80898414-c31aba00-8d20-11ea-8380-173ede4d8514.png)

**Comment by wout-junius** [comment]
Same here:
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**Comment by jambonmcyeah** [comment]
Well I encountered the same issue and decided to fix it
Just clone my PR #269 and compile the extension yourself

**Comment by birobirobiro** [comment]
Same here:

NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
