### ISSUE TITLE
Windows can't be moved to another workspace

### ISSUE THREAD

**Issue by jannikbuhr** [pop-os/shell#233]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
pop-shell:
  Installed: 0.1.0-1588101002~20.04-16b4c33
  Candidate: 0.1.0-1588101002-20.04-16b4c33
  Version table:
 *** 0.1.0-1588101002-20.04-16b4c33 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
When in tiling mode, attempting to move a window to the next workspace using
Super+Shift+Down temporarily moves the window to the next workspace but reverts it (and the focus) back to the original workspace within about 1 second and shifts focus to another window.
Moving a window to another workspace that is empty works via drag and drop in overview mode, but moving it back onto a workspace that already contains windows does not work. 

**Steps to reproduce (if you know):**
This appears to happen independent of whether I am working with just the laptop monitor or an additional monitor, which was my first guess for a source of the bug.

**Expected behavior:**
The window moves to the next workspace and is re-tiled accordingly.

**Other Notes:**
I reproduced this with all manually installed extensions disabled.

**Comment by brs17** [comment]
I have been able to replicate this issue. Attached is a video showing the issue in action.
[233.zip](https://github.com/pop-os/shell/files/4553145/233.zip)

**Comment by AdamoPrincipe** [comment]
Same here!

**Comment by seandjones92** [comment]
I built the extension earlier today and it was working, just did a git pull to build again and I am now seeing this behavior as well. Looks like something recent introduced it?

Currently running the extension built on commit 57fd88ce38b1ec5e4f06db051f881dd9fd053943

**Comment by mmstick** [comment]
Fixed
