### ISSUE TITLE
Why aren't shell-shortcuts included in this extension

### ISSUE THREAD

**Issue by seandjones92** [pop-os/shell#234]
Would like to see https://github.com/pop-os/shell-shortcuts get merged directly into this project. It doesn't make sense to try opening the shortcut UI only to be told that some other package needs to be installed. To make matters worse there are no install instructions in the README of the shell-shortcuts.

I'm building this on vanilla Ubuntu 20.04

**Comment by mmstick** [comment]
They're two entirely different projects. This is a GNOME extension, that is a GTK Rust application. The pop-shell package depends on pop-shell-shortcuts. If you are building from source, there's already debian packaging rules you can use for Debian platforms, or use the makefile everywhere else.
