### ISSUE TITLE
Option to hide titlebar for better utilisation of space.

### ISSUE THREAD

**Issue by mokshchaudhary** [pop-os/shell#236]
Hiding the titlebar in tile mode will help in space utilisation and more immersive tile mode.

**Comment by brs17** [comment]
Thank you for filing this issue, as stated here: https://github.com/pop-os/shell/issues/200 the option currently exists in the settings for shell in the extension's settings in either GNOME Extensions or GNOME tweaks. Once the feature is a bit more stable it will be added to the extension dropdown menu.
