### ISSUE TITLE
Minimizing window does not retile layout

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#237]
**Distribution (run `cat /etc/os-release`):**
 
Fedora 32, Gnome 3.36, Xorg
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

57fd88ce38b1ec5e4f06db051f881dd9fd053943

**Issue/Bug Description:**

When you minimize a window, the layout isn't retiled and the space remains empty where the window used to be.

**Steps to reproduce (if you know):**

* Minimize a window

**Comment by mmstick** [comment]
And fixed

**Comment by jmmaranan** [comment]
@nicolae-stroncea - do you still remember what types of applications are not able to minimize? QT, Electron, or GTK based?

**Comment by jmmaranan** [comment]
@mmstick - looking at the apps mentioned in #290 - this is fixed. Android studio, etc

**Comment by nicolae-stroncea** [comment]
@jmmaranan  unfortunately I don't remember which apps that occured for. I did a couple of small tests right now for Electron and GTK and they seemed to work fine

**Comment by jmmaranan** [comment]
@mmstick, I think this can be closed too
