### ISSUE TITLE
Ctrl+Super+Left tiles window to left side of screen

### ISSUE THREAD

**Issue by brs17** [pop-os/shell#24]
When launching an application with "Launch windows tiled" disabled, <kbd>Ctrl</kbd>+<kbd>Super</kbd>+<kbd>Left</kbd> will tile the program to the left side of the screen. Pressing it again will untile the program. <kbd>Ctrl</kbd>+<kbd>Super</kbd>+<kbd>Right</kbd> does not do anything.

**Comment by mmstick** [comment]
The shortcuts are now disabled in the `rebuild.sh` script: 15e2789

**Comment by WatchMkr** [comment]
Closing in favor of discussing this functionality here: https://github.com/pop-os/shell/issues/36
