### ISSUE TITLE
Sometimes, focused window is hidden in auto-tiling mode

### ISSUE THREAD

**Issue by Booteille** [pop-os/shell#240]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
pop-shell:
  Installé : 0.1.0~1588274983~20.04~586efcc
  Candidat : 0.1.0~1588274983~20.04~586efcc
 Table de version :
 *** 0.1.0~1588274983~20.04~586efcc 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
The focused window is sometimes  hidden.
Keyboard is still interacting with it.
We can see the window in a flash when trying to move from one other workspace to the one having the window.
We can also see the window in a flash when trying to move it from one workspace to another one.

Here is a short video showing the behavior:
![Video](https://user-images.githubusercontent.com/2203721/80780299-d1c16f80-8b6e-11ea-96a1-8b01b8d19b61.gif)

**Steps to reproduce (if you know):**
Unknown.

**Expected behavior:**
I expect the application to not be hidden.

**Other Notes:**
Even disabling auto-tiling didn't change the behavior of the window.

**Comment by WatchMkr** [comment]
This behavior appears to have been fixed along with workspace fixes in the latest release.
