### ISSUE TITLE
ctrl+super+left/right still snaps windows

### ISSUE THREAD

**Issue by Jom97** [pop-os/shell#241]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
 

**Issue/Bug Description:**
Pressing ctrl + super + left/right snaps the window to the left side or right side of the screen, even though ctrl + super + up/down have different functions now. And the shortcuts ctrl+ super + left/right doesn't seem to be listed in the keyboard shortcuts.

**Comment by Jom97** [comment]
Ok, this is just weird. It seems like the shortcuts are inconsistent. Sometimes they work and sometimes they don't.

**Comment by m1waterman88** [comment]
Pop!_OS 19.10 (Nvidia iso): ```ctrl``` + ```super``` + ```left```/```right``` snaps windows to the left/right respectively.

Pop!_OS 20.04 (Nvidia iso): ```ctrl``` + ```super``` + ```left``` still works like in 19.10, but ```ctrl``` + ```super``` + ```right``` no longer snaps windows to the right; it seems to do nothing.

Completely up to date. I update/upgrade like an addict.

**Comment by schiorean** [comment]
There's quite a few (relate) issues with keyboard shortcuts https://github.com/pop-os/pop/issues/409

**Comment by mmstick** [comment]
Closing this for now. If it still occurs with today's updates, please reopen.
