### ISSUE TITLE
Unable to move a window to a second monitor that has a floating window on it

### ISSUE THREAD

**Issue by robert-sandor** [pop-os/shell#246]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
``` 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```
pop-shell:
  Installed: 0.1.0~1588274983~20.04~586efcc
  Candidate: 0.1.0~1588274983~20.04~586efcc
  Version table:
 *** 0.1.0~1588274983~20.04~586efcc 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
Moving windows to other screens is inconsistent when the second screen has a floating window on it. Moving with either adjument mode, or just using Super+Shift+Left/Right doesn't do anything.

**Steps to reproduce (if you know):**
Dual monitor setup, open a window on one monitor and set it to floating, and try moving another window from the other monitor with keybindings.

**Expected behavior:**
Windows should move seamlessly between monitors even if the second monitor contains any active floating windows.

**Other Notes:**
Moving with the mouse works as expected, and it seems like the only workaround as of right now.

**Comment by jannikbuhr** [comment]
I also notice this when in tiling mode even with no windows on the target monitor. A tiled window is unable to be moved to another screen via the shortcut (My monitors are stacked, so the shortcut is Ctrl+Shift+Super+Down). It only briefly blinks on the target monitor and stays in it's position. Moving via mouse works. Making it floating with Super+G, then moving it with the shortcut and making it tile again with Super+G works, so does moving it in Super+Enter mode.

**Comment by mmstick** [comment]
What you described is moving the window across workspaces. You have to enter window management mode and move the window with the arrow keys.

**Comment by enurseitov** [comment]
@mmstick it is not related to Workspaces. I face the same issue as @jannikbuhr described. Steps to reproduce:

- configure dual-monitor setup with vertical layout (one monitor is on top of another)
- enable auto-tiling
- open window on the upper monitor
- try to move the window to lower monitor using "Move window one monitor down" hotkey
  - window moves to the lower screen but **returns back** to upper screen instantly after

Expected behavior:
- the window should stay on the lower screen

**Comment by jannikbuhr** [comment]
As far as shortcuts go, workspaces use Ctrl or Shift to move a window or move focus, but using Ctrl **and** Shift (+Super + Arrow) is supposed to move a window across monitors, at least according to the description. The window management mode does indeed work, like I mentioned in my comment above. Maybe the plan is to remove or repurpose the old shortcut?

**Comment by robert-sandor** [comment]
I made a small video - gif (albeit pretty poor, but it should get the point across on what i mean here): [imgur](https://imgur.com/a/a0DDetw)
you can see that i have a floating window on the right monitor, and when trying to move the terminal, you can see the other window expand, but the terminal stays on the first display (and trying to do this in adjustment mode, using Mod+Right)

**Comment by enurseitov** [comment]
Here is an example what happens in my case. It shows that you don't even need to have a floating window on the second screen.. The problem also appears in a horizontal setup.
In essence, moving windows between monitors is impossible with auto-tiling enabled (unless you move it through floating mode with a mouse). That makes auto-tiling completely useless for multi-monitor setups (in particular in 20.04 where there's no more shortcuts to swap windows to occupy half of a screen)
![Peek 2020-05-05 12-08](https://user-images.githubusercontent.com/10921645/81055585-470fa600-8ec9-11ea-8be3-4d5684f35579.gif)

**Comment by jannikbuhr** [comment]
I can confirm that the issue only appears with "Workspaces span displays".

**Comment by WatchMkr** [comment]
> As far as shortcuts go, workspaces use Ctrl or Shift to move a window or move focus, but using Ctrl **and** Shift (+Super + Arrow) is supposed to move a window across monitors, at least according to the description. The window management mode does indeed work, like I mentioned in my comment above. Maybe the plan is to remove or repurpose the old shortcut?

Yes, that's the plan. Moving window to anywhere on the desktops and across monitors is `super` + `enter` then `arrow/direction keys`. Moving workspace is `super + control` and `arrow/direction keys up/down`. 

We didn't want to remove or break the previous `ctrl` +`left/right` to half-tile in floating mode, preferring to ease people into tiling and hopefully make that key combination less useful and then, perhaps, use that combination for horizontal workspaces to keep things consistent.

**Comment by WatchMkr** [comment]
I can replicate the OP issue. I'm unable to move a window to a monitor that has only a floating window on it.

**Comment by sundbp** [comment]
I'm in the same boat - in tiling mode I can not move windows between monitors (when workspaces span monitors). Regardless of the content of the monitor I'm moving a window to (incl empty).

**Comment by christophcemper** [comment]
Same setup. Same issue, 
**only when you set "Workspaces span displays" in gnome tweaks**

**Comment by lainor** [comment]
> Same setup. Same issue,
> **only when you set "Workspaces span displays" in gnome tweaks**

Extended dual monitor setup. I can confirm the same issue with **"Workspaces span displays" in gnome tweaks**

**Comment by jannikbuhr** [comment]
One interesting thing I notice: It works if you first attempt to move the window in the opposite direction. This sort of unlocks all movement. E.g. in adjustment mode pressing Super+k before Super+j when trying to move a window to a second monitor under the first.
Does this happen for others as well?

**Comment by mmstick** [comment]
Recently fixed by implementing workspace management in Pop Shell

**Comment by wpietri** [comment]
I am experiencing a bug that sounds very similar. I'm using pop-shell 1.1.0~1613083995~20.04~6b2287f. The box is a recent purchase from System76 and has two monitors placed side by side.

Right now my left monitor has gkrellm configured like this:

![image](https://user-images.githubusercontent.com/83547/108542901-2f0ee480-7299-11eb-8ce1-8c6b241f57a7.png)

There are no other windows on the left monitor. On the right monitor, I have 4 standard windows that I can manage normally with Pop Shell shortcuts, but I can't move any of those windows to the right monitor. However, if I use the mouse to drag a window to the left monitor, I can focus on a window on the right monitor, do Super-Enter and then hit left arrow until it ends up on the left. At that point, I can move normal windows back and forth with the Pop Shell keys.

However, once I move the last normal window off the left monitor, I can no longer move normal window back to the right monitor.

If I manually drag gkrellm to the right monitor, I can once again use the Pop Shell keys to move windows to the left monitor. So I think, @mmstick, that this is perhaps not fixed. (If it's a different bug, let me know and I'm glad to open a new issue.)
