### ISSUE TITLE
Window Titles option should be active only in tiling mode

### ISSUE THREAD

**Issue by Amathadius** [pop-os/shell#247]
As soon as the extension is activated, the window title option is active even if I am not in tiling mode. Either the option is disabled and several windows have no window title, or the option is enabled and some windows have two window titles.
So I have to go to the new gnome extension application to disable the extension completely if I don't want to be in tiling mode.

**Comment by WatchMkr** [comment]
Show window titles is the default behavior in GNOME. This appears to be describing a recently fixed bug where Firefox showed two title bars. Looks fixed in the latest release.
