### ISSUE TITLE
Video not taking full screen if window is not maximized

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#248]
**Distribution (run `cat /etc/os-release`):**
 
Fedora 32, Gnome 3.36, Xorg
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

586efccee1f572f11873c70f4028f5178eac89fb

**Issue/Bug Description:**

If the window that contains the video is not maximized(with `Super M`), then the video does not take full screen, when expanded.

[bug_report.zip](https://github.com/pop-os/shell/files/4564728/bug_report.zip)

Bug occurs even with 1 window open, if it is not maximized

**Steps to reproduce (if you know):**

1. Open up a window, making sure it's not maximized.
2. Open a video and expand it.

**Expected behavior:**

Video takes the entire screen

**Comment by mmstick** [comment]
This has already been fixed by #242

**Comment by laichiaheng** [comment]
> This has already been fixed by #242

It says that it is blocked.

**Comment by mmstick** [comment]
Its just waiting for QA review
