### ISSUE TITLE
journalctl polluted with pop-shell messages on each mouse click when click is on desktop

### ISSUE THREAD

**Issue by BTBlueSkies** [pop-os/shell#250]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
'journalctl -f' is reporting a constant stream of messages for each click, ie, right click press and again on right click release. These messages are as follows:

May 01 11:05:48 pop-os gnome-shell[2211]: pop-shell: [DEBUG] unblocking signals for 0,0
May 01 11:05:48 pop-os gnome-shell[2211]: ../../../gobject/gsignal.c:2696: handler '30215' of instance '0x55a325a62620' is not blocked
May 01 11:05:48 pop-os gnome-shell[2211]: ../../../gobject/gsignal.c:2696: handler '30216' of instance '0x55a325a62620' is not blocked
May 01 11:05:48 pop-os gnome-shell[2211]: ../../../gobject/gsignal.c:2696: handler '30217' of instance '0x55a325a62620' is not blocked
May 01 11:05:48 pop-os gnome-shell[2211]: ../../../gobject/gsignal.c:2696: handler '30218' of instance '0x55a325a62620' is not blocked
May 01 11:05:48 pop-os gnome-shell[2211]: pop-shell:  [INFO] focused Window(0,0) {
                                            name: Terminal,
                                            rect: Rect(650,89,1126,848),
                                            wm_class: "Gnome-terminal",
                                            monitor: 2,
                                            workspace: 0,
                                            cmdline: /usr/libexec/gnome-terminal-server,
                                            xid: 0x200000a,
                                          }

**Steps to reproduce (if you know):**
journalctl -f and then right click desktop background

**Expected behavior:**
just a click.. no need for journal entries on every click

**Other Notes:**
This is new pop-release 20.04. I am using twin nvidia gpus (2080 TI's) on Ryzen 3900X

**Comment by mmstick** [comment]
Technically not a bug. Code is executed each time you focus a window. Logs are generated to be useful in the event that we need those logs for debugging.

**Comment by BTBlueSkies** [comment]
Well, you are failing to realize that the journalctl -f that looks like below destroys the ability to use the logging system in any meaningful way as it's so polluted with garbage that it's like email these days. This is my computer these messages are rendering on... and you make my best diagnostic tool unusable.

ay 04 01:07:31 pop-os gnome-shell[2477]: pop-shell: [DEBUG] unblocking signals for 2,0
May 04 01:07:31 pop-os gnome-shell[2477]: ../../../gobject/gsignal.c:2696: handler '70332' of instance '0x5620e93b0dc0' is not blocked
May 04 01:07:31 pop-os gnome-shell[2477]: ../../../gobject/gsignal.c:2696: handler '70333' of instance '0x5620e93b0dc0' is not blocked
May 04 01:07:31 pop-os gnome-shell[2477]: ../../../gobject/gsignal.c:2696: handler '70334' of instance '0x5620e93b0dc0' is not blocked
May 04 01:07:31 pop-os gnome-shell[2477]: ../../../gobject/gsignal.c:2696: handler '70335' of instance '0x5620e93b0dc0' is not blocked
May 04 01:07:31 pop-os gnome-shell[2477]: pop-shell:  [INFO] focused Window(2,0) {
                                            name: Terminal,
                                            rect: Rect(4533,25,1094,644),
                                            wm_class: "Gnome-terminal",
                                            monitor: 1,
                                            workspace: 0,
                                            cmdline: /usr/libexec/gnome-terminal-server,
                                            xid: 0x320000a,
                                          }
May 04 01:07:32 pop-os gnome-shell[2477]: pop-shell: [DEBUG] unblocking signals for 2,0
May 04 01:07:32 pop-os gnome-shell[2477]: ../../../gobject/gsignal.c:2696: handler '70332' of instance '0x5620e93b0dc0' is not blocked
May 04 01:07:32 pop-os gnome-shell[2477]: ../../../gobject/gsignal.c:2696: handler '70333' of instance '0x5620e93b0dc0' is not blocked
May 04 01:07:32 pop-os gnome-shell[2477]: ../../../gobject/gsignal.c:2696: handler '70334' of instance '0x5620e93b0dc0' is not blocked
May 04 01:07:32 pop-os gnome-shell[2477]: ../../../gobject/gsignal.c:2696: handler '70335' of instance '0x5620e93b0dc0' is not blocked
May 04 01:07:32 pop-os gnome-shell[2477]: pop-shell:  [INFO] focused Window(2,0) {
                                            name: Terminal,
                                            rect: Rect(4533,25,1094,644),
                                            wm_class: "Gnome-terminal",
                                            monitor: 1,
                                            workspace: 0,
                                            cmdline: /usr/libexec/gnome-terminal-server,
                                            xid: 0x320000a,
                                          }

**Comment by jackpot51** [comment]
I agree, we should decrease logging in the extension to show only info or higher levels. It could potentially be changed to show debug messages with a gsetting

**Comment by mmstick** [comment]
These logs have been removed

**Comment by BTBlueSkies** [comment]
Thank you.. much appreciated!
