### ISSUE TITLE
Application Always Float

### ISSUE THREAD

**Issue by TomFaulkner** [pop-os/shell#254]
One nice feature of i3 and other tiling window managers is the ability to make an application always float, or at least open floating.

Currently programs that typically start with a smaller window, such as the Calculator application that ships with Pop, get resized to an awkwardly large size to be tiled.

A similar issue, small dialog windows tend to get their own tile rather than floating over the window that spawned them.

Is there a way to make certain applications, or window titles, always float?
Can we get floating dialogs?

Also, is there a config file that i can edit and commit to my dotfiles?

Thanks for the hard work.

**Comment by the1derer** [comment]
One more application if this feature could be extended to `Picture-in-Picture(PiP)` mode of Google Chrome and Mozilla Firefox where the `PiP` windows get resized to unwanted large size.

**Comment by WatchMkr** [comment]
If we're to implement this feature, GNOME Settings > Applications is a natural place for an Always Float toggle.

**Comment by folke** [comment]
What about "saving" the tiling or floating mode for a window between sessions?

This way, when you start the calculator app the first time, simply press `<Super> G` to toggle floating mode, and after restarting the calculator app it will start in floating mode.

**Comment by davidrhoderick** [comment]
One application that this seems to work for out-of-the-box is the GNOME screenshot app (not sure if it's named differently outside of Pop!_OS).  Whenever I open it, it's automatically floating.  Whatever they did to force that (hopefully it's something simple) should work for apps like Calculator et al.
