### ISSUE TITLE
Launcher customizations (example with pass)

### ISSUE THREAD

**Issue by LouisKottmann** [pop-os/shell#257]
**Distribution (run `cat /etc/os-release`):**

 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

pop-shell:
  Installed: 0.1.0~1588274983~20.04~586efcc
  Candidate: 0.1.0~1588274983~20.04~586efcc
  Version table:
 *** 0.1.0~1588274983~20.04~586efcc 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

I would like to hack around the PopOS launcher to integrate [pass](https://www.passwordstore.org/) with it, much like I used with an [albert](https://github.com/albertlauncher/albert) [extension](https://github.com/albertlauncher/python/blob/dev/pass.py).

However, looking at the source code for the launcher, while is does allow special syntax like `:`, `:t` and `=`, it does not seem to be made customisable.

I could provide an extension as a PR to this repo but I bet you'd prefer to have those in dedicated repositories. Not everyone uses pass.

**Steps to reproduce (if you know):**

**Expected behavior:**

It should work like this:
- I open the launcher with `<super> - /`
- I enter `:pass ` in it, this directs the query to the pass extension we are talking about
- The extension filters available passwords by fuzzy-matching whatever I put after `:pass `
- On pressing enter on the desired entry, it is copied to my clipboard

**Other Notes:**

As the PopOS launcher is new and "bare" if I may say, it's probably worth looking at being compatible with extensions from popular launchers like Rofi or Albert. That would save everyone a lot of work.

**Comment by WatchMkr** [comment]
Comments added to https://github.com/pop-os/shell/issues/198 to consolidate launcher discussion.
