### ISSUE TITLE
Tray icon remains after disabling extension

### ISSUE THREAD

**Issue by daveriedstra** [pop-os/shell#259]
**Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 0.1.0~1588274983~20.04~586efcc
  Candidate: 0.1.0~1588274983~20.04~586efcc
  Version table:
 *** 0.1.0~1588274983~20.04~586efcc 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

Tray icon still present after pop shell extension is disabled

**Steps to reproduce (if you know):**

1. Disable extension

**Expected behavior:**

Tray icon shouldn't be present when extension is disabled

![image](https://user-images.githubusercontent.com/3504098/80918050-f2d1be00-8d30-11ea-9000-6fbf2cbd7371.png)

**Comment by nicolae-stroncea** [comment]
Can confirm same behaviour on Fedora 32

**Comment by daveriedstra** [comment]
After a restart the icon is gone. This is similar to [my experience](https://www.reddit.com/r/pop_os/comments/gcjk5i/some_theme_settings_reset_on_login/) with #230 and #231 so might be related.

**Comment by isantop** [comment]
I can also confirm this behavior on Pop_OS 20.04

**Comment by rthery** [comment]
I believe I've located the source of the issue, the indicator is not destroyed in `disable()` (as suggested to do so in https://wiki.gnome.org/Projects/GnomeShell/Extensions/Writing).

I'll prepare a PR for it after testing today if all goes well!
