### ISSUE TITLE
Opening 4+ windows on 1080p screen does not tile as designed

### ISSUE THREAD

**Issue by brs17** [pop-os/shell#26]
With tiling on by default, on a 1080p display, the fourth window opened (without changing focus of the windows other than by opening the second and third windows) does not follow the window tiling guidelines as defined here: https://github.com/pop-os/shell/issues/9.

Screenshot of current behavior:
![Screenshot from 2020-02-25 10-38-13](https://user-images.githubusercontent.com/7460774/75274439-1839cd00-57c0-11ea-81a9-b7600bde2460.png)

Screenshot of behavior defined in https://github.com/pop-os/shell/issues/9:
![defaulttiling](https://user-images.githubusercontent.com/7460774/75274604-5cc56880-57c0-11ea-9790-73a75e97199a.png)

**Comment by WatchMkr** [comment]
We need to update the specification. Michael (and subsequently Maria and I after seeing it) concluded that splitting the focused windows makes more sense.
