### ISSUE TITLE
Unable to lock the screen with Super+L

### ISSUE THREAD

**Issue by laichiaheng** [pop-os/shell#262]
**Distribution (run `cat /etc/os-release`):
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.manjaro.org/"
SUPPORT_URL="https://www.manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux

**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):r397.586efcc-1

**Issue/Bug Description:Unable to lock the screen by pressing Super+L

**Steps to reproduce (if you know):Super+L

**Expected behavior:The screen is locked.

**Other Notes:**

**Comment by FrankAlbella** [comment]
This is expected behavior and is mentioned in the readme under "Overridden GNOME Shortcuts". Lock has been changed to `Super` + `Esc`

**Comment by laichiaheng** [comment]
> This is expected behavior and is mentioned in the readme under "Overridden GNOME Shortcuts". Lock has been changed to `Super` + `Esc`

It doesn't work, either.
