### ISSUE TITLE
Launcher shortcut

### ISSUE THREAD

**Issue by xdursoc** [pop-os/shell#263]
**Distribution (run `cat /etc/os-release`): Ubuntu 20.04
 
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**Issue/Bug Description: The launcher shortcut does not work on **Italian keyboard** due to the fact the Super + / corresponds to Super + 7. In Linux systems based on ubuntu typing Super + number allow to launch an application from the dock corresponding to the number chosen. 

**Steps to reproduce (if you know):**

**Expected behavior:

**Other Notes:**

**Comment by andree-rehnberg** [comment]
Also experiencing this on a Swedish keyboard.

**Comment by ThaSiouL** [comment]
Seems like it's the same topic as #196.

**Comment by mmstick** [comment]
Duplicate of #196
