### ISSUE TITLE
None of the Overridden GNOME Shortcuts work.

### ISSUE THREAD

**Issue by laichiaheng** [pop-os/shell#268]
**Distribution (run `cat /etc/os-release`):
```
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.manjaro.org/"
SUPPORT_URL="https://www.manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally): r397.586efcc-1

**Issue/Bug Description: None of the Overridden GNOME Shortcuts work.

**Steps to reproduce (if you know): Try to lock the screen by pressing `Super+Esc`.

**Expected behavior: It locks the screen.

**Other Notes: None.

**Comment by mmstick** [comment]
You have to change these shortcuts in GNOME. The extension won't do it for you.
