### ISSUE TITLE
Resizing tiled window pushes second window into unusable space

### ISSUE THREAD

**Issue by brs17** [pop-os/shell#27]
With two windows opened and tiled vertically, resizing the left window with <kbd>Super</kbd>+<kbd>Enter</kbd> and then the right direction, eventually the second window gets pushed off of the screen in a way where it is not usable.
![Screenshot from 2020-02-25 11-43-28](https://user-images.githubusercontent.com/7460774/75277879-1c68e900-57c6-11ea-8576-b7b347341c33.png)
![Screenshot from 2020-02-25 11-43-31](https://user-images.githubusercontent.com/7460774/75277883-1c68e900-57c6-11ea-9fc1-970721a07154.png)
![Screenshot from 2020-02-25 11-43-33](https://user-images.githubusercontent.com/7460774/75277884-1d017f80-57c6-11ea-9bc7-365d0eedd4c1.png)
![Screenshot from 2020-02-25 11-43-35](https://user-images.githubusercontent.com/7460774/75277885-1d017f80-57c6-11ea-9177-f015f0f9b09a.png)

**Comment by mmstick** [comment]
Same as #16
