### ISSUE TITLE
[question] Rationale for tiling windows on a ultrawide monitor

### ISSUE THREAD

**Issue by luisfpg** [pop-os/shell#272]
I have recently tried pop-os shell on Gnome shell, but I'd like to ask something regarding the rationale of tiling windows. As what happened when I tried i3wm, I just felt uncomfortable and went back.

> Suppose you are a lucky — or perhaps unlucky — owner of an ultra-wide display

I do have a ultrawide monitor, and actually use it as 2 monitors. Without the pop-os shell extension, I just use the key binding Super + Arrow Left / Right to tile windows to either side. And I always have at least 6 windows open (2 browsers, Thunderbird, Eclipse, VSCode and Tilix). Of course I need to alt-tab between windows, or dash-to-dock to select the window I want.

When I enable window tiling with pop-os shell, as I open the windows, they start tiling and become very small (1/8, 1/16 of the monitor size). This makes windows unusable. Is window tiling supposed to define a "limit" of open windows so you can focus on a specific amount of windows? In my case, where I need that many windows open at the same time, how can I benefit from tiling?

Perhaps there's something I didn't get in the whole thing... Thanks.

**Comment by mmstick** [comment]
You have more than one workspace. If you somehow manage to require more screen space than an ultra-wide provides, then you can start organizing your tasks by workspaces.
