### ISSUE TITLE
Feature Request: grouping in tiling

### ISSUE THREAD

**Issue by peey** [pop-os/shell#273]
A popular tiling shell extension for GNOME [shelltile](https://github.com/emasab/shelltile) offers offers support for grouping windows. Simply put, this allows grouped windows to be minimized together. It's best describe through [a short demo video](https://www.youtube.com/watch?v=hNncF9Pc6PY)

Would this be a suitable feature for pop shell, and if so then could this be considered as a feature request?

I think that what it implements can also be achieved by keeping different windows open in different workspaces and having a lot of workspaces, but since I've seen this feature I thought I'll ask what pop shell maintainers think about it.

**Comment by mmstick** [comment]
The way tiling works here is fundamentally different from the way it works in Shelltile. With tiling enabled, all windows on a display are technically grouped together in the same tree, and I don't think it'd make sense to have every window on the screen minimize.

With auto-tile off, there is a feature to snap window movements to a grid, but none of these windows are technically grouped. It'd be possible to have a feature that groups windows in stacking mode, though.

**Comment by peey** [comment]
I think I'll use Pop's own tiling and adjust it into my workflow, before I can judge if I want to request this feature in stacking mode. You may close this issue unless there's more interest in grouping in stacking mode.

**Comment by WatchMkr** [comment]
A feature that combines windows into groups (stacked or tabbed) is planned here: https://github.com/pop-os/shell/issues/150
