### ISSUE TITLE
Window maximization issue

### ISSUE THREAD

**Issue by v-marinkov** [pop-os/shell#277]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

upgraded from 19.10
 
 
**Issue/Bug Description:**

Clicking the maximize button on the title bar or double clicking on the title bar itself causes Electron or Qt applications (GTK ones seem fine) to enter a maximized window state but with a glitched visual appearance. However, maximizing with a keyboard shortcut or dragging to a snap edge works as expected.

![Screencast from 04-05-20 13_22_36_2](https://user-images.githubusercontent.com/7135724/80965992-85469000-8e0b-11ea-9f24-ad6f7077b547.gif)

**Comment by Moxymore67** [comment]
+1. I had this bug too, and many others (like fullscreen issue, or multiple bugs with messaging app which doesn't like PopOS Shell).

**Comment by mmstick** [comment]
The fullscreen issue shouldn't be an issue anymore

**Comment by v-marinkov** [comment]
I had the `pop-shell` extension disabled and all was working great. I notice an update today but kept it disabled. Now that I saw your message I decided to enable it. This turned my screen black only with a cursor and even a reboot doesn't fix it!!

How can I restore access to the DE? My computer is unusable right now...

**Comment by stealthybox** [comment]
I am also seeing this exact issue on a refresh install of Pop! OS 20.04.
The behavior and compositing offset look the same as the provided gif, where it's transparent on the top and left sides, and clicks are offset from where the window is rendered.

I ended up disabling the pop shell extension and restarting gnome (`Alt+F2:  r`).

**Comment by jmmaranan** [comment]
@stealthybox - do you still see this in the latest apt release or pulling from master_focal branch (if compiling by yourself)?

@v-marinkov - sorry that you had that experience, while I did not replicate what you just had in May, I hope you can still consider to try it. If it happens again, you can open another session by pressing (CTRL + ALT + F3), then after logging in, type `gnome-extensions disable "pop-shell@system76.com"`. Restart. If by disabling the extension, it still happens then it might not be pop-shell. You can restore it by typing in a similar session: `gnome-extensions enable "pop-shell@system76.com"`. Restart.
