### ISSUE TITLE
Tile windows: Maximize should match appearance of single window (with gaps)

### ISSUE THREAD

**Issue by aral** [pop-os/shell#279]
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
n/a

**Issue/Bug Description:**

When there’s a single window in a workspace with window tiling on, it takes up the full space, minus the gaps.

When you have multiple windows in a workspace with tiling and you maximize a window, it fills up the whole screen without the gaps. This is inconsistent.

**Expected behavior:**

Maximizing a window when tiling is active should match the behaviour of having a single window in a workspace.

Alternative: have a modifier that achieves this effect (e.g., Super Shift M).

**Comment by mmstick** [comment]
I think this would give the illusion that there's only one window in that display's tree. Having the window maximized without gaps lets the user know that they have a window maximized on this screen.

**Comment by aral** [comment]
You’re right, I hadn’t considered that.

That said, for some reason maximized feels claustrophobic once you’re used to gaps… would you be up for considering Super Alt or Super Shift M with gapped maximize behaviour? (I haven’t looked at the codebase so I’m not sure how large of an ask that is in terms of complexity. If it’s anything but trivial I’d consider it very low priority and a nice to have.) :)

**Comment by WatchMkr** [comment]
Thanks for the suggestion. At this point we'll stick with the current behavior for maximized windows.
