### ISSUE TITLE
Expected behavior for window focus dialog with no programs open

### ISSUE THREAD

**Issue by brs17** [pop-os/shell#28]
What is the expected behavior of the Window focus dialog (<kbd>Super</kbd>+<kbd>/</kbd>) when there are no programs open?

Right now the search box appears but there isn't anything that can be done from this list.

**Comment by WatchMkr** [comment]
To launch applications by command or desktop file name - both before and after windows are open.

**Comment by mmstick** [comment]
So this can be closed?

**Comment by brs17** [comment]
I believe so.
