### ISSUE TITLE
Use a develop branch

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#285]
Before Pop!_OS 20.04 was released, master had all of the latest features. This enabled the community to quickly test latest commits and submit any bug reports. 

This is currently very difficult to do, because each change has a different branch. If all of the changes would be pushed to a develop branch, this allows beta testers to provide QA as well, which will help find issues sooner, and ease the quality-assurance burden on Pop engineers.

**Comment by mmstick** [comment]
This is up to @pop-os/quality-assurance. I'll do whatever is most convenient for them.

**Comment by mmstick** [comment]
Currently experimenting with approaches that would enable us to continue to have proper code reviews and QA testing per-change. There's currently a `dev_focal` branch that has some of the PRs rolled up.
