### ISSUE TITLE
Cannot hide window titles

### ISSUE THREAD

**Issue by ishan9299** [pop-os/shell#287]
**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

  Installed: 0.1.0~1588624471~20.04~dfb378c
  Candidate: 0.1.0~1588624471~20.04~dfb378c
  Version table:
 *** 0.1.0~1588624471~20.04~dfb378c 1001

**Issue/Bug Description:**
Some applications don't obey the 'Show window titles'. 

**Steps to reproduce (if you know):**
I have enabled the option but after a reboot applications like vscode don't obey the settings I have to turn off the the setting and turn on again to fix it.

**Expected behavior:**
Applications which cannot hide the title bar should not show the title bar when the option is enabled and should remember the settings after the session ends.

**Comment by steven-jeanneret** [comment]
I have the same problem.

I found an alternative with [this link](https://joshtronic.com/2017/07/26/hide-title-bars-in-gnome-shell/)

**Comment by WatchMkr** [comment]
This issue is being tracked here: https://github.com/pop-os/shell/issues/32
