### ISSUE TITLE
Full screen video unexpected behaviour

### ISSUE THREAD

**Issue by rybber78** [pop-os/shell#288]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
pop-shell:
  Installed: 0.1.0~1588274983~20.04~586efcc
  Candidate: 0.1.0~1588274983~20.04~586efcc
  Version table:
 *** 0.1.0~1588274983~20.04~586efcc 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
Browser full screen buttons does not yield 100% full screen when using tiling. Screenshots from youtube+firefox and netflix+chrome and VLC tiled with 3 other windows

![youtube+Firefox](https://i.imgur.com/bSVtUcf.png)
![Netflix+chrome](https://i.imgur.com/aMiDrQG.png)
![VLC](https://i.imgur.com/vGKM8XI.png)

**Steps to reproduce (if you know):**

**Expected behavior:**
Should fill the entire screen. Seems to be related to tiling of windows

**Other Notes:**

**Comment by jannikbuhr** [comment]
This should be fixed by this PR https://github.com/pop-os/shell/pull/242 , which was merged 22 hours ago so you might need to wait for the update.
