### ISSUE TITLE
Window Focus dialog appears underneath tiling mode window selection

### ISSUE THREAD

**Issue by brs17** [pop-os/shell#29]
When a window is selected with <kbd>Super</kbd>+<kbd>Enter</kbd> and then <kbd>Super</kbd>+<kbd>/</kbd> is selected, the window focus dialog is below the window highlighting from the window having focus. 

![Screenshot from 2020-02-25 13-10-28](https://user-images.githubusercontent.com/7460774/75283799-bdf53800-57d0-11ea-98c2-bfeba4fbef62.png)

I see that when launching the window focus dialog first, upon executing <kbd>Super</kbd>+<kbd>Enter</kbd>, the focus dialog closes (although a bit glitchy).

**Comment by mmstick** [comment]
I found the solution to this, and it is fixed now with 63d1be3
