### ISSUE TITLE
Minimizing window does not retile layout (not fixed)

### ISSUE THREAD

**Issue by Warkorentin** [pop-os/shell#290]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 20.04 LTS 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
pop-shell:
  Installed: 0.1.0~1588624471~20.04~dfb378c
  Candidate: 0.1.0~1588624471~20.04~dfb378c
  Version table:
 *** 0.1.0~1588624471~20.04~dfb378c 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
When you minimize a window, the layout isn't retiled and the space remains empty where the window used to be.

**Steps to reproduce (if you know):**
Minimize a window

**Expected behavior:**
Other windows should use the now available space

**Other Notes:**
This issue has already been brought here : https://github.com/pop-os/shell/issues/237#issue-610049537 and is marked as fixed, but I'm still experiencing it on the latest pop-shell version

**Comment by sonicdebris** [comment]
For me, retiling on minimize works fine with some apps (eg: terminal, gedit. When I minimize them the space they left behind is filled) and not with others (eg: firefox, android studio).

**Comment by leviport** [comment]
Thank you for the report. I've reopened https://github.com/pop-os/shell/issues/237 .  Please comment on closed issues that they need to be reopened instead of making new issues.
