### ISSUE TITLE
Launcher showing duplicate entries while Activites does not (Extensions, specifically)

### ISSUE THREAD

**Issue by echosa** [pop-os/shell#293]
**Distribution (run `cat /etc/os-release`):**
 ```
$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```
$ apt policy pop-shell
pop-shell:
  Installed: 0.1.0~1588624471~20.04~dfb378c
  Candidate: 0.1.0~1588624471~20.04~dfb378c
  Version table:
 *** 0.1.0~1588624471~20.04~dfb378c 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
When I search for the new Extensions application using the pop-shell launcher, it see two entries: one which woks and one does not. Activities only shows one.

pop-shell launcher:

![image](https://user-images.githubusercontent.com/133786/81080123-03f80780-8eb6-11ea-8616-9693ed43d5e2.png)

Activities search:

![image](https://user-images.githubusercontent.com/133786/81080162-0d816f80-8eb6-11ea-8301-b4a3dff51825.png)

**Steps to reproduce (if you know):**
Search for "extensions" using both pop-shell launcher (Super+/) and Activities (Super).

**Expected behavior:**
There shouldn't be duplicate entries.

**Comment by scaryrawr** [comment]
I think this is happening because they're are multiple desktop entries in the /usr/share/applications:
```sh
org.gnome.Shell.Extensions.desktop
39:Name=Extensions

org.gnome.Extensions.desktop
38:Name=Extensions
```
I was thinking we could check if the Exec is valid, but it gets weirder for things like Geary:
```sh
 ✘ mike@lagann  /usr/share/applications  ag Exec= geary-autostart.desktop
174:TryExec=geary
175:Exec=geary --gapplication-service
 mike@lagann  /usr/share/applications  ag Exec= org.gnome.Geary.desktop
163:TryExec=geary
164:Exec=geary %U
224:Exec=geary mailto:
242:Exec=geary --new-window
```

**Comment by scaryrawr** [comment]
Ah, I think we should filter out things with `NoDisplay=true`
