### ISSUE TITLE
Application icons wrong in the launcher

### ISSUE THREAD

**Issue by echosa** [pop-os/shell#294]
**Distribution (run `cat /etc/os-release`):**
 ```
 $ cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```
$ apt policy pop-shell
pop-shell:
  Installed: 0.1.0~1588624471~20.04~dfb378c
  Candidate: 0.1.0~1588624471~20.04~dfb378c
  Version table:
 *** 0.1.0~1588624471~20.04~dfb378c 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
When I use the pop-shell launcher to open Slack, it does not show the icon correctly. However, Activities does. Also, once Slack is open, the launcher shows the the correct icon for the window, but still not for the application itself.

launcher when Slack is closed:

![image](https://user-images.githubusercontent.com/133786/81080630-94364c80-8eb6-11ea-9941-76f03b81510f.png)

launcher when Slack is open:

![image](https://user-images.githubusercontent.com/133786/81080660-9bf5f100-8eb6-11ea-99e8-58883a5ed27c.png)

Activities:

![image](https://user-images.githubusercontent.com/133786/81080671-a1533b80-8eb6-11ea-8ddc-e43e23b664d9.png)

**Steps to reproduce (if you know):**
Search for Slack using both launcher and Activities.

**Expected behavior:**
The icon should always be correct.

**Other Notes:**
I'm using the .deb install of Slack, not the Flatpak.

**Comment by vancanhuit** [comment]
I also have the same issue with the VS Code.
![Screenshot from 2020-05-06 18-52-03](https://user-images.githubusercontent.com/18382438/81173840-e2d50b00-8fca-11ea-9954-312ad06114cc.png)

**Comment by echosa** [comment]
Thanks for that example, @vancanhuit. I'll update the issue title to be more general.

**Comment by mmstick** [comment]
This has been fixed
