### ISSUE TITLE
Window focus dialog remains open on lockscreen

### ISSUE THREAD

**Issue by brs17** [pop-os/shell#30]
When the window focus dialog (<kbd>Super</kbd>+<kbd>/</kbd>) is launched, locking the screen or letting the system lock itself on powersaving timeout, does not close out of the dialog. From the locked screen I can see what applications are open but cannot interact with this menu.

**Comment by mmstick** [comment]
is this still a thing?

**Comment by leviport** [comment]
Nope, can't reproduce any longer
