### ISSUE TITLE
Feature Request: Auto-hide CSD and Nautilus sidebar when tiling is active (Maximize Real-Estate)

### ISSUE THREAD

**Issue by jlacroix82** [pop-os/shell#304]
This is just a feature request.

When tiling is enabled, I think it would be great if the CSD could be hidden. Perhaps the CSD of a window can be exposed when you move the mouse near the top edge of it. There were extensions that hid the titlebars, one called No Title Bar and another called Pixel Saver, IIRC. Neither of them are maintained anymore, but perhaps some code in there could be useful.

Also, I recommend the same thing for the sidebar in Nautilus windows. Normally, you can press F9 in Nautilus and that will hide the sidebar. Perhaps it can be hidden by default when tiling is active, and exposed by moving the mouse near it?

I'm not sure if these items are possible, but I think together they can maximize screen real-estate when tiling is active.

**Comment by hype3** [comment]
I also want this and that the user can set the border width in px and also the color of the border

**Comment by WatchMkr** [comment]
Thanks for the suggestion. We're working on a feature to intelligently toggle title bars for all scenarios. We're tracking it here: https://github.com/pop-os/shell/issues/32

We aren't considering disabling the Nautilus sidebar at the moment. I believe the proper UX would be that Nautilus displays the same elements that it does in floating mode, and changes to a slimmer view when it's narrower - similar to GNOME settings today.
