### ISSUE TITLE
Swapping windows sometimes immediately swaps them back

### ISSUE THREAD

**Issue by leviport** [pop-os/shell#306]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 20.04
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
pop-shell:
```
  Installed: 0.1.0~1588624471~20.04~dfb378c
  Candidate: 0.1.0~1588624471~20.04~dfb378c
  Version table:
 *** 0.1.0~1588624471~20.04~dfb378c 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
Swapping windows sometimes results in them swapping, but then immediately swapping back to where they were
![swapswap](https://user-images.githubusercontent.com/13512097/81216924-00897c80-8f99-11ea-8cb0-53f018b3f2dd.gif)

**Steps to reproduce (if you know):**
- With tiling activated, have two windows tiled vertically (one on top, one on bottom)
- With the bottom window active, enter window management mode with Super+Enter
- Swap with the top window with Ctrl + up arrow and then hit enter

**Expected behavior:**
Swap should stick

**Other Notes:**
I've seen it occasionally with two windows tiled side-by-side as well. It only seems to happen with windows that are the same size though. I've not seen it happen with windows that are different sizes.

**Comment by bergmannf** [comment]
I have this happen quite a bit, when attempting to move a windows from one monitor to another one by swapping it with a window that is already on that other monitor.
