### ISSUE TITLE
Setting gap values of 0 clears value and does not apply

### ISSUE THREAD

**Issue by brs17** [pop-os/shell#31]
When I enter either an inner or outer gap of 0, when pressing `Enter` to apply the change the value in the box disappears.
![zeros](https://user-images.githubusercontent.com/7460774/75355533-e120f580-586b-11ea-8444-4b4530e237fc.png)

It also appears that this change of setting either gap to 0 does not apply when pressing `Enter`.

**Comment by leviport** [comment]
I'm now unable to set a gap size of zero. The number stays in the box like it applied, but the gap size does not change. It looks like the absolute smallest I can make the gaps is 4.

**Comment by leviport** [comment]
I am now able to set gap sizes of zero!
