### ISSUE TITLE
Opening firefox as first window breaks everything

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#317]
**Distribution (run `cat /etc/os-release`):**
 
NAME=Fedora
VERSION="32 (Workstation Edition)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation

Using X11
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

Bug seems to occur due to 4e60d4ca647141e308ea313074e3d0adf097f90b.

**Issue/Bug Description:**

When you launch firefox as the first window, it is moved to the second workspace, from where you cannot access it anymore, as every time you move to second workspace, Firefox is moved up one workspace above. Only way this is fixed is by opening another app on the first workspace.

**Steps to reproduce (if you know):**

1. Close all windows.
2. Open firefox in the first workspace.
3. Undefined behaviour occurs

[bug_report.zip](https://github.com/pop-os/shell/files/4595982/bug_report.zip)

It's not 100% reproducible now, but once it occurs, it won't stop. Often happens right after starting a session, restarting a shell, unlocking.

EDIT: This is not the only thing which triggers it. It also occurs if you remove all of the windows in the first workspace, when firefox is on the second workspace

**Comment by nicolae-stroncea** [comment]
Doesn't seem to be firefox specific, just had it happen with other applications as well

**Comment by mmstick** [comment]
Is this still happening in dev_focal?

**Comment by nicolae-stroncea** [comment]
Hasn't happened for the last 3 hours on 8e5c50a6849b8708830ed37fa601afb3e0e7ef0c, but because it's not perfectly reproducible, I'll update again in a couple of days on whether it happened again.

**Comment by likern** [comment]
> Is this still happening in dev_focal?

Yes. Right now I'm using latest commit from `dev_focal`. On **Fedora 32** I can successfully login. As soon as I open any application - Fedora hangs forever, only physical  restart helps.

**Comment by mmstick** [comment]
@likern That sounds like a different issues. Are you on Wayland?

**Comment by likern** [comment]
> Is this still happening in dev_focal?

Even if I just turn on "Tile Windows" setting in menu Fedora becomes hanging and I have to restart.

**Comment by likern** [comment]
> @likern That sounds like a different issue. Are you on Wayland?

Thank you for response. Yes, I was on "GNOME" I think that meant Wayland. When I switched on "GNOME on Xorg" hanging eliminated.

**Comment by mmstick** [comment]
@likern Your issue would be #166

**Comment by mmstick** [comment]
Closing this for now. If it still occurs with today's updates, please reopen.
