### ISSUE TITLE
Complete Window-Title Toggle Feature

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/shell#32]
By default Brave (and other Chrome browsers) have headerbars and enabling it adds a double headerbar though it removes it for other applications.

This is on Pop 20.04 LTS which may void out this bug report which is fine.

gnome-shell --version
GNOME Shell 3.34.3

Just pulled the shell from git a few minutes ago.

**Comment by mmstick** [comment]
This should be fixed by 0ad8552

**Comment by WatchMkr** [comment]
It appears that window titles are now show up for applications where they didn't previously. Firefox for instance has a title bar now even with Show Window Titles disabled.

**Comment by mmstick** [comment]
Temporary fix for now would be to disable the title bar in Firefox's Customize view

**Comment by jeroen7s** [comment]
Disabling title bar in firefox "Customize" options does not work on the 20.04 beta

**Comment by mcmamcma** [comment]
I would like to confirm what Jeroen7s said. Disabling the title bar in firefox "customize" in 20.04 doesn't work.

**Comment by rscircus** [comment]
+1 basically this options doesn't do anything.

![image](https://user-images.githubusercontent.com/1167114/86513299-6499b700-be09-11ea-99df-bed53e81a472.png)

Am glad to help in any way. Trying to work through this, for now: https://joshtronic.com/2017/07/26/hide-title-bars-in-gnome-shell/
