### ISSUE TITLE
Super not working in non-English layouts

### ISSUE THREAD

**Issue by v-marinkov** [pop-os/shell#320]
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

============================================

The "super" key doesn't launch the Activities overview in non-English layouts (even in "US, alt. intl"). Super+A for all applications and other Super+ shortcuts work fine in all layouts, however. This was not a problem in 19.10.

**Comment by v-marinkov** [comment]
A friend reported that changing the layout to non-English automatically enables the scroll lock which cannot be disabled. It goes off once the layout is switched back to English.
This needs to be verified though.

**Comment by leviport** [comment]
Thanks for the report. We're tracking the super key bug here: https://github.com/pop-os/beta/issues/98

The scroll lock light may be related. We'll know once Gnome's fix makes its way to us. Sometimes it takes a while for them to get to the Ubuntu repos.
