### ISSUE TITLE
Feature Request: keyboard shortcut to Tile Windows

### ISSUE THREAD

**Issue by zhandosweb** [pop-os/shell#321]
Hello! 

I'm first time to trying Pop-OS Shell. It's amazing!

But I think, that we need to specific keyboard shortcut to enable/off Windows Tile mode. 

For example, I launch web-browser + Visual Studio code. And thats what I need to work with code for my site. I see 2 tilled windows on my screen and its what I need.

Then if I launch FIles, it will launch like third window and its very don't convenient. And I should off Window Tile-mode to launch Files like separate app in own window. 

For that we need Keyboard Shortcut to fast on/off Windows Tile mode. 

Sorry for bad English, im joke )) Im still learning и все такое!

Spasibo!

**Comment by leviport** [comment]
We were thinking of a hotkey to toggle tiling/floating mode as a whole, but we instead opted for <kbd>Super</kbd>+<kbd>g</kbd> which un-tiles a single window at a time, while leaving tiling mode active. Does that do what you need, or do you still feel like a hotkey toggle to completely turn tiling on and off would still be helpful for your workflow?

**Comment by omrihar** [comment]
I think it may still be useful to have a shortcut to turn off tiling mode. For example when I disconnect my computer from the 4k monitor I use and switch to laptop mode, I often prefer to switch off tiling, or, for watching a video in full-screen mode while the bug still persists that it doesn't work properly.

**Comment by cgarciae** [comment]
+1

I've been using `super + g` so much that it become more useful just to turn it tiling after I get the windows I want tiled. 

What about `super + shift + g` so that all new windows are created in floating mode? That way you could force them back to tile mode individually via `super + g`.

**Comment by WatchMkr** [comment]
Which apps do you choose to float and why? We are considering adding the ability to make an application always float. That might be a better method for your use case.

**Comment by cgarciae** [comment]
Right now I don't have an external monitor so I only tile chat windows (slack + ferdi) and vscode windows, the rest I keep them float.

BTW: Zoom is super annoying to use on tile mode since it opens up a couple of small widgets that count as windows.

**Comment by dimgrav** [comment]
To add @cgarciae, this happens to Slack, Skype and any other other that uses a floating preview or call management widget. A global keyboard shortcut would be ideal I think.

**Comment by WatchMkr** [comment]
Better to fix the interaction with those apps rather than bail out.

**Comment by cgarciae** [comment]
I think its going to be hell for the dev team to try to fix every possible interaction. 1 or 2 global toggles seem easier to implement.

**Comment by timrichardson** [comment]
Global toggle key board would be excellent, if only because some tiling bugs can be fixed by tiling off and tiling on.

**Comment by timrichardson** [comment]
I have coded a toggle tiling keyboard shortcut, lacking imagination I have mapped it to Super Y.
I'll make a pull request. I added a method to Extension to toggle tiling, and moved the relevant code from panel_settings.tiled() into this new Extension  method.
Reading the discussion above, I don't know whether you think this is a valuable feature, but I like it, so you can decide once I remember how to do nice pull requests.

**Comment by timrichardson** [comment]
My PR has been merged into dev_focal, super Y toggles tiling although it still doesn't have a visual indicator that tiling is on, and I just realised that the panel switch does not update when tiling changes.
