### ISSUE TITLE
[Feature Request] Pixel Saver gnome extension integration within the Pop!_OS Shell

### ISSUE THREAD

**Issue by argosatcore** [pop-os/shell#324]
Hello,

Big fan of the Pop!_OS Shell (and of System76 in general). I would like to state the following feature request:
- I've encountered some integration issues with another Gnome extension, namely the 'Pixel Saver' (this extension removes the top bar of an app when it is opened in full screen and repositions it on the top bar of the Gnome Desktop to provide more real screen state to the application itself). Since one of the objectives of Pop! _OS Shell is to make efficient use of the real state of the screen, would it be possible to include this feature as something that comes baked in Pop! _OS Shell's tiling? I include an image of Pixel Saver in action here to better illustrate my point (see upper left corner of screenshot).

Thank you for your consideration!

![Screenshot from 2020-05-08 15-34-54](https://user-images.githubusercontent.com/64110504/81451380-9c55ec80-9141-11ea-8a99-d478125f16f7.png)

**Comment by jannikbuhr** [comment]
If you search for extensions and click the wheel next to Pop Shell, you can disable the option "Show Window Titles". It has a similar effect to Pixel Saver for a lot of applications.

**Comment by argosatcore** [comment]
Thanks for the information! I guess this pretty much solves my issue.

**Comment by AmosNimos** [comment]
> If you search for extensions and click the wheel next to Pop Shell, you can disable the option "Show Window Titles". It has a Similar effect to Pixel Saver for a lot of applications.

lot of applications?, some for sure, but it's inconsistent which make's it worst to my taste to not using it, it's almost trying to sell a bug as a feature... so far no way to remove ALL title bar on POP OS.

**Comment by jmbuhr** [comment]
This is because unfortunately not all title bars are created equal. Some applications really don't like being robbed of their title bar. Note that your use of the word "sell" might be considered offensive. These amazing folks are making this piece of software available for free. Your are welcome to submit a fix for the applications which don't work, or, in the very least, start a list and asses the commonalities between them.
