### ISSUE TITLE
[Feature Request] Allow Custom Keybindings

### ISSUE THREAD

**Issue by FrasSmith** [pop-os/shell#326]
**Other Notes:**
I've been using Pop!_shell for a week now and have customized some key bindings to more suit my workflow.

Today, I've updated by pulling the latest version and running rebuild.sh. It worked, but it has over written my customized keybindings and reset to default.

Please implement a means for users to customize config that won't be over-written with every update.

**Comment by mmstick** [comment]
You may already use gsettings to define your own keybindings (as the rebuild script does). If you're simply updating directly from the source repo, call `make && make install` instead. The rebuild script is for testing purposes primarily.
