### ISSUE TITLE
2-26 Feedback Meeting

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/shell#33]
- [x] Super Q for closing windows (To avoid the destructive action of closing a window when closing browser tabs (CTRL+W) was the intent)
- [x] Rename "Launch Windows Tiled" to "Tile Windows"
  - [x] Change functionality to tile all open windows when activated
  - [ ] Give the largest space the browser
- [x] When in tiling mode Super+Enter and then direction keys moves the window to a different tree
- [x] When in tiling mode Super+Enter then Shift+direction keys resizes the tree
- [x] Add Appearance drop down to the extension with Inner Gaps, Outer Gaps, and Show Widow Titles options.
- [x] Adjust gap sizes as the setting is changed (rather than on enter)
- [x] `Super` + `W` to convert a window to floating and vice versa
- [x] Change toggle orientation to `Super` + `O`
- [x] Add application launching
  - [x] Search via desktop files
  - [x] Command line execution
  - [x] sudo command handling
- [x] Fix resizing issues

**Comment by leviport** [comment]
Apologies for missing this meeting. Looking over these notes, I'm a bit concerned about remapping Super+Space since that's the default hotkey for changing between keyboard layouts on Pop as well as many other OS's and DE's.

**Comment by WatchMkr** [comment]
Right, thanks for bringing that up. We’ll need to pick a different shortcut.

**Comment by mmstick** [comment]
The floating status may now be toggled. I've set the shortcut to `Super` + `W` for now, until we know which one would be better for it.

**Comment by mmstick** [comment]
Direction  keys now move windows around the tree in management mode

**Comment by mmstick** [comment]
Moved remaining item to #135
