### ISSUE TITLE
No longer tiles windows to use full width of my native 4k monitor

### ISSUE THREAD

**Issue by timrichardson** [pop-os/shell#336]
**Distribution (run `cat /etc/os-release`):**
 pop!os 20.04
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
tim@keynes:~$ apt policy pop-shell
pop-shell:
  Installed: 0.1.0~1588944981~20.04~fe12571
  Candidate: 0.1.0~1588944981~20.04~fe12571
  Version table:
 *** 0.1.0~1588944981~20.04~fe12571 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

```

**Issue/Bug Description:**

4k in native. As of update today, full screen windows extend to the right margin (where they run into my vertical panel) but leave a big gap on the left.

**Steps to reproduce (if you know):**
auto-tiling on
close all windows.
open a new window 
(and can add a second window too)

**Expected behavior:**
should use the entire space

Does not.

**Other Notes:**
one screen shot of 4K monitor.
One of all three monitors.

![ksnip_20200513-095339](https://user-images.githubusercontent.com/927458/81756670-bc016200-94ff-11ea-962e-dec389b2e559.png)
![ksnip_20200513-095527](https://user-images.githubusercontent.com/927458/81756734-e7844c80-94ff-11ea-83e7-cbfc141b2b4b.png)

**Comment by timrichardson** [comment]
Also, grabbing left border and stretching to the right just snaps back

**Comment by timrichardson** [comment]
Note, there was a minimized  window. When I moved this to another workspace, normal behaviour resumed. But when I moved this window back to desktop 1 and minimised it again, I can reproduce this problem. There is also other weird behaviour. The minimised app is a VMWare Workstation window.

**Comment by mmstick** [comment]
There's an update going out soon. Check back if it's still occurring and reopen this issue

**Comment by timrichardson** [comment]
I just received some updates, I will turn it back on the and report back in two days

**Comment by timrichardson** [comment]
have not seen any recurrence of this, thanks.
