### ISSUE TITLE
Active hint does not show when using custom shell theme

### ISSUE THREAD

**Issue by dieggywegz** [pop-os/shell#337]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.04 LTS" 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
pop-shell:
  Installed: 0.1.0~1588944981~20.04~fe12571
  Candidate: 0.1.0~1588944981~20.04~fe12571
  Version table:
 *** 0.1.0~1588944981~20.04~fe12571 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
When using a custom shell theme and enabling pop-shell, active window hint does not appear when tiling is enabled.

**Steps to reproduce (if you know):**
Change shell theme to a user installed theme (I'm using Materia-light-compact).

**Expected behavior:**
pop-shell tiling works and active window hint appears as normal.

**Other Notes:**

**Comment by mmstick** [comment]
Closing this for now. If it still occurs with today's updates, please reopen.
