### ISSUE TITLE
[Feature Request] Add emacs shortcuts while navigating in the launcher. 

### ISSUE THREAD

**Issue by Anatzum** [pop-os/shell#339]
Having emacs movement bindings would provide an alternative to having to use arrow keys which is currently the only way possible to navigate at this point. This in my opinion would complete the experience of little to no wrist movement while using pop_shell.

Even just the simple C-f, C-b, C-n, C-p would do wonders for me.

**Comment by lungtendo** [comment]
I have been thinking the same about the new launcher. Either the Emacs binding or Super+(j,k) for selecting the apps would be it for the launcher.

**Comment by WatchMkr** [comment]
Navigating down and up the launcher with `Control` `j/k` has been added in the latest release.
