### ISSUE TITLE
Setting gap to 1 or 2 breaks Dash-to-dock. Dock stutters when opening

### ISSUE THREAD

**Issue by JensVanhooydonck** [pop-os/shell#340]
**Distribution (run `cat /etc/os-release`):** Pop!_OS 20.04 LTS
 
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):** GNOME Version 3.36.1 and Dash to Dock version 68

**Issue/Bug Description:** When the gap is set to 1 or 2, Dash to Dock stutters/bounces. This can be seen in the [video]( https://www.youtube.com/watch?v=bmvVXoLe7s8) linked in the Dash To Dock Issue.

**Steps to reproduce (if you know):** 
1. Install Dash To Dock
2. Enable Tiling
3. Set gap to 1 or 2
4. Try to open Dock

**Expected behavior:** No stuttering, and the dock should keep open

**Other Notes:**

[Dash To Dock issue](https://github.com/micheleg/dash-to-dock/issues/1207)

**Comment by WideEyedSerpant** [comment]
Can confirm the same issue on Fedora 32.

**Comment by mmstick** [comment]
Issue in Dash to Dock

**Comment by cb3inco** [comment]
The way I read this @mmstick is that it's a Dash to Dock issue, is that correct? Since it's happening in Fedora apparently too?

**Comment by JensVanhooydonck** [comment]
> The way I read this @mmstick is that it's a Dash to Dock issue, is that correct? Since it's happening in Fedora apparently too?
Correct me if i'm wrong but you can also install the Pop Shell in Gnome on Fedora.

However i do think it is a Dash to Dock issue, because other people, who aren't using the Pop shell, also have this issue. Therefor this issue is closed.
