### ISSUE TITLE
Add default float or tiling mode per app

### ISSUE THREAD

**Issue by davidrhoderick** [pop-os/shell#352]
**Distribution (run `cat /etc/os-release`):**
 
```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
``` 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 0.1.0~1589559052~20.04~80c6299
  Candidate: 0.1.0~1589559052~20.04~80c6299
  Version table:
 *** 0.1.0~1589559052~20.04~80c6299 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

This is more a feature request; I'd love to be able to set default behavior for apps.  For example, every time I open the calculator, I really just want it to float, not take up half the screen.

**Steps to reproduce (if you know):**

Try enabling Pop!_OS and then Firefox (or whatever full-screen app you like) then open calculator to do some simple calculations.  You'll find it's taken up half the screen and it's a bit gratuitous.

**Expected behavior:**

That some apps can be specified to automatically float, such as calculator, Zoom, Android simulator, etc.

**Comment by WatchMkr** [comment]
This functionality could be added to GNOME Settings > Applications.

**Comment by folke** [comment]
What about "saving" the tiling or floating mode for a window between sessions?

This way, when you start the calculator app the first time, simply press `<Super> G` to toggle floating mode, and after restarting the calculator app it will start in floating mode.

**Comment by WatchMkr** [comment]
Duplicate. We'll track the feature here at the first bug https://github.com/pop-os/shell/issues/254
