### ISSUE TITLE
Tiling windows horizontally in thirds

### ISSUE THREAD

**Issue by davidrhoderick** [pop-os/shell#353]
**Distribution (run `cat /etc/os-release`):**
 
```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
``` 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 0.1.0~1589559052~20.04~80c6299
  Candidate: 0.1.0~1589559052~20.04~80c6299
  Version table:
 *** 0.1.0~1589559052~20.04~80c6299 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

When trying to have three applications tiled horizontally (each taking up a third of the screen horizontally), it is very hard to change the width of the apps.  Occasionally, resizing one app kicks another off the screen.

**Steps to reproduce (if you know):**

Open Skype, Viber, and Slack (these were the apps I really struggled with) and try to arrange them in thirds using Pop Shell.  Sometimes, it is possible, other times, it takes a lot of effort and is sometimes impossible.  These apps are generally terrible for resizing, especially on smaller screens.

**Expected behavior:**

That resizing windows would be much easier and wouldn't be buggy.

**Comment by afolarin** [comment]
similar issue here: #431

I also notice that handling of some windows that have a minimum width may also be problematic for the layout

**Comment by mmstick** [comment]
This was fixed about 2 months ago
