### ISSUE TITLE
Window not focused after you return from overview

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#355]
**Distribution (run `cat /etc/os-release`):**
 
 Fedora 32, Gnome 3.36, Xorg
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

339817fd7eea8e1cf58e57b217630262f01614c0

**Steps to reproduce (if you know):**

0. Turn on active hint to clearly see the bug.
1. Open up 2 windows(can be reproduced with 2+).
2. Focus on window on the left
3. Go into overview.
4. While in overview, move your mouse to the other side of the screen(so that upon returning to normal, you will start focused on the other window).
5. Return to the normal layout.
6. Once returned, the focus should be on the new window. Instead it is on the window that you focused on before entering the overview. You can move the mouse through the window but until you click on it, actual focus will still be on the old window. 

[bug_report.zip](https://github.com/pop-os/shell/files/4637575/bug_report.zip)

**Expected behavior:**

Focus should be on the new window.

**Other Notes:**

* This bug has on more than a couple of times resulted in destructive actions, where I will expect my focus to be on the window where my mouse is, and press `Super Q` to close the application. What ends up happening is that the application that I had my focus originally on closes instead. Lost more than a couple of Firefox sessions that way.
* The bug also occurs if you go into the overview of your installed applications.
* It also occurs if you launch the launcher, and then when you exit it, you are focused on another window.

**Comment by mmstick** [comment]
Not really an issue. Focus doesn't follow mouse, so exiting from overview should keep you in the same window as before.
