### ISSUE TITLE
Remove Switch Monitor Ctrl+Super+Left/Right Shortcuts

### ISSUE THREAD

**Issue by leviport** [pop-os/shell#36]
After a discussion with @maria-komarova , we think we may want to reconsider overriding Ctrl+Super+Left and Right for half-tiling windows left or right on the screen. I'm not certain it will work great in tiling mode, but in the default non-tiling mode, it breaks immersion and takes far more keypresses. What used to be a single hotkey now requires me to enter window management mode, move the window, resize the window, then hit enter. The process seems likely to monopolize the user's attention span, which is detrimental for productivity.

**Comment by WatchMkr** [comment]
This one is tricky. The feature isn't directly compatible between floating and tiling. In tiling mode, the window can not cover an existing window on the left and right. Of course in tiling mode the windows half tile automatically anyway.

To avoid the confusion of a shortcut doing something in one mode and not the another, in tiling mode these shortcuts could move the window left and right and up and down the same as Super+Enter then arrow keys. The window movement would be similar to what occurs in the floating mode.

**Comment by mmstick** [comment]
Currently, these shortcuts control focus-monitor left/right. Should these shortcuts be removed?

**Comment by WatchMkr** [comment]
Yes, focus monitor left and right appears to add unnecessary complexity when we have super+arrows and super+/ to navigate open windows.
