### ISSUE TITLE
Active hint disappears after suspend

### ISSUE THREAD

**Issue by Stup0r38** [pop-os/shell#360]
**Distribution (run `cat /etc/os-release`):**
NAME=Fedora
VERSION="32 (Workstation Edition)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=" "
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Workstation Edition)"

**Issue/Bug Description:**
The active hint disappears if the system is suspended and it doesn't appear again until the next reboot.

**Steps to reproduce (if you know):**
1)Enable active hint
2)Suspend the system
3)The hint disappeared

**Expected behavior:**
The hint around the active window should remain visible

**Comment by WatchMkr** [comment]
Are you using Wayland?

**Comment by Stup0r38** [comment]
No, I'm using Xorg, I tried with wayland and the system crashes when I try to open any app

**Comment by Stup0r38** [comment]
The bug appears to have been fixed in the latest update
