### ISSUE TITLE
nautilus fails to launch in pop-os 20.04

### ISSUE THREAD

**Issue by myleftshoe** [pop-os/shell#362]
Neither launching from the app icon nor the command line work:

Launching from the command prompt reports:
```
nautilus: symbol lookup error: nautilus: undefined symbol: pango_attr_insert_hyphens_new
```
Could not find a suitable fix from google.

I recently *upgraded* (i.e. not installed from scratch) to pop-os 20.04, it hasn't worked since.

**Comment by mmstick** [comment]
Sounds likely that some packages didn't upgrade. Make sure that all the sources in `/etc/apt/sources.list` are pointing to `focal`, and that both `sudo dpkg --configure -a` and `sudo apt full-upgrade` succeeds.

Other than that, closing since this is not related to pop-shell

**Comment by myleftshoe** [comment]
@mmstick, apologies, didn't know where to report the problem. Thanks for responding!
