### ISSUE TITLE
modal dialogs stay on top of other apps even when not using tiling mode

### ISSUE THREAD

**Issue by zebest-potato** [pop-os/shell#373]
-->

**Distribution (run `cat /etc/os-release`):**

`Pop!_OS 20.04 LTS`
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

pop-shell:  `0.1.0~1589754807~20.04~e5f3b4d`

**Issue/Bug Description:**

All modal dialogs are set to "always on top" by default when the extension is enabled despite not using the tiling mode. When switching to a different app it stays on screen and when i try to move it, it brings its parent window to focus.

**Steps to reproduce (if you know):**

example:
1-open files
2- open the about files modal dialog
3-switch to other window/app
4-the about file modal dialog stays on top

**Expected behavior:**

modal window to stay on top of its parent window when not using tiling mode

**Other Notes:**

![Screenshot from 2020-05-19 18-50-40](https://user-images.githubusercontent.com/51344986/82348524-aad5bb00-9a01-11ea-8d28-c32c481d62a5.png)

https://www.reddit.com/r/pop_os/comments/gmbv8c/modal_dialogs_always_on_top_is_this_a_bug/

Edit: added reddit post that has video of the issue

**Comment by grufelous** [comment]
Has there been any development on this issue? What does the community think about it?

**Comment by JHerseth** [comment]
This needs to be fixed for this extension to be usable imo. I had to disable it.

**Comment by grufelous** [comment]
@JHerseth agree. Unfortunately, I am unable to disable the Pop Shell extension due to which I have no work-around. If possible, I'd like to see how we can fix it.
