### ISSUE TITLE
Two titlebar on Firefox with Pop Shell.

### ISSUE THREAD

**Issue by laichiaheng** [pop-os/shell#378]
**Distribution (run `cat /etc/os-release`):**
 NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.manjaro.org/"
SUPPORT_URL="https://www.manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
r447.ff5f374-1

**Issue/Bug Description:**
There are two titlebar on firefox

**Steps to reproduce (if you know):**
Enable the Pop Shell plugin.
Disable the title bar in Firefox.

**Expected behavior:**
It looks normal without titlebar.

**Other Notes:**
![2020-05-20 11-32-58 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/82402105-3006b180-9a8e-11ea-89ee-acff15ce2d94.png)

**Comment by laichiaheng** [comment]
It also crashes when I right click on the firefox icon on dock.

**Comment by laichiaheng** [comment]
Can anyone fix it?

**Comment by jmmaranan** [comment]
@laichiaheng - from what I have seen, Dash to Dock is the only extension that duplicates a window instance that cannot be grabbed or focused (2 or more dots appearing after doing Firefox > Customize > Show TitleBar = true.) - and makes the CPU go high when you click the app icon.

**Freezing when clicking on dock:** Updating the Dash to Dock extension to version 68+ seems to work for me. If it freezes, without rebooting, log into another TTY (ctrl+alt+f3), login then `sudo killall gnome-shell`.

**When the Title Bar is duplicated and no freezes**: ALT+F2, then enter r, Enter works after toggling the Firefox titlebar.

**Comment by eh8** [comment]
I am also experiencing this issue without dash-to-dock enabled. 

![image](https://user-images.githubusercontent.com/22990581/85073745-556c0580-b189-11ea-8553-3c9442b86d8d.png)

**Comment by skewty** [comment]
This is perhaps related to the enable / disable titlebar feature in PopShell.

- start Firefox
- click Hamburger menu
- click Customize menu item
- [x] Titlebar

This feature does not seem to hide the titlebar in Firefox but does work in PyCharm.  I am expecting this issue to be a Firefox upstream one.

**Comment by jmmaranan** [comment]
#428 - should be able to fix the dash-to-dock ghosting - so clicking on the dock will not freeze when a persistent dot appears. I think I agree on the double title bars are something related to Firefox.

**Comment by laichiaheng** [comment]
> This is perhaps related to the enable / disable titlebar feature in PopShell.
> 
>     * start Firefox
> 
>     * click Hamburger menu
> 
>     * click Customize menu item
> 
>     * [x]  Titlebar
> 
> 
> This feature does not seem to hide the titlebar in Firefox but does work in PyCharm. I am expecting this issue to be a Firefox upstream one.

How? It does hide the title bar without Pop Shell.

**Comment by jmmaranan** [comment]
@laichiaheng, no, it will only resolve if you are using dash to dock and toggling the title bar on/off

**Comment by jmmaranan** [comment]
As for the title bar, that needs more research either that is pop-shell or the main Firefox app. The patch I did is for pop-shell.

**Comment by laichiaheng** [comment]
Does anyone have any clue now?

**Comment by eh8** [comment]
I installed this via `gnome-shell-extension-pop-shell-git` in the [AUR](https://aur.archlinux.org/packages/gnome-shell-extension-pop-shell-git/).

I solved it by disabling show title bars in the applet settings.

**Comment by jmmaranan** [comment]
@laichiaheng - just curious - did you follow @skewty 's suggestion? And would you be able to send a screenshot after? It pertains to Firefox Customize menu/page and not exactly pop-shell.

**Comment by laichiaheng** [comment]
@jmmaranan What does he suggest? Disable hiding the titlebar? I have disabled it since I noticed this issue.
If it were a Firefox issue, it should happen without Pop Shell.

**Comment by jmmaranan** [comment]
@laichiaheng - it is pop-shell conflicting with the title-bars. The last comment context is about Firefox's title bar. So it is both of them.

The setup should be like this for now when you have Firefox, Pop-Shell and VSCode (or any Electron app): 

- Tweaks > Extensions > Pop-Shell gear > Show Title Bars (should checked)
- Firefox > Customize > Show Title Bars (do not check)

The freezing when toggle Firefox Customize Title Bars should be fixed.

**Comment by laichiaheng** [comment]
@jmmaranan Thanks, after disabling "Show Title Bars" in the Pop Shell extension setting, it works as expected now.

**Comment by jmmaranan** [comment]
If you are going to use VS Code, reverse the two settings.

**Comment by laichiaheng** [comment]
@jmmaranan There is another problem, if I disable Show Title Bars, the title bar of qbittorrent is gone.

**Comment by jmmaranan** [comment]
If you follow my original suggestion of the two settings, pop shell show title, firefox off title bar. That should work

**Comment by laichiaheng** [comment]
@jmmaranan It does not.
![2020-07-14 00-04-00 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/87326644-94616100-c565-11ea-803d-000549001a3a.png)

**Comment by jmmaranan** [comment]
Could you restart popshell leaving them as is?

**Comment by laichiaheng** [comment]
> Could you restart gnome shell leaving them as is, as suggested? Alt + f2, r and popshell title check, Firefox off title.

The same.

**Comment by jmmaranan** [comment]
@laichiaheng - I do not use qbittorrent but here is how it looks like on my end with the suggested settings.
Curious also on the theme you are using. I am using the default `pop-dark/pop`.

![image](https://user-images.githubusercontent.com/348125/87350838-74f71380-c526-11ea-8d32-6d4498715834.png)

**Comment by laichiaheng** [comment]
I have tried it with the default Xorg session and Adwaita theme, the problem is still there.
![2020-07-14 21-29-53 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/87431598-75240b80-c619-11ea-8738-2770e3e92c72.png)

**Comment by laichiaheng** [comment]
Any clue yet?

**Comment by skewty** [comment]
This is more than likely a Firefox upstream bug.  Has anyone created one for this?  If yes, please post a link to it here.
We will likely have more traction getting this resolved by the Mozilla devs. as development on this extension seems dead (for now?).  It may / will hopefully pickup prior to the next PopOS release.

**Comment by laichiaheng** [comment]
> This is more than likely a Firefox upstream bug. Has anyone created one for this? If yes, please post a link to it here.
> We will likely have more traction getting this resolved by the Mozilla devs. as development on this extension seems dead (for now?). It may / will hopefully pickup prior to the next PopOS release.

This feature of Firefox works without the Pop Shell extension.

**Comment by jmmaranan** [comment]
@laichiaheng - sorry, do not have resolution for you because cannot replicate it on my end. Looking at the current code and history, @mmstick - has hidden the show title bar toggle in the prefs (Tweaks). If I am guessing correctly, it doesnt want to be found or changed just yet. The default on tweaks as far as I can remember, is that Pop-Shell Extension is enabled, inside it the Show Title Bar is enabled too. Then by default, Firefox ships with the Title Bar disabled from Customize.

@skewty - is this happening on your end too?

**Comment by laichiaheng** [comment]
@mmstick Holy Jesus! It is fixed! Thanks.
