### ISSUE TITLE
Tiling overwrites default application sizes

### ISSUE THREAD

**Issue by horvbalint** [pop-os/shell#379]
**Distribution:**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version**:
  Installed: 0.1.0~1589754807~20.04~e5f3b4d
  Candidate: 0.1.0~1589754807~20.04~e5f3b4d
  Version table:
     0.1.0~1589754807~20.04~e5f3b4d 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
After using the tiling mode and switching it off, the next time you launch an application, it opens with the size and in the position that is was, when tiling was enabled. Which can be annoying, because without the other applications being open it does not form a nice grid, and looks a bit funny.

**Steps to reproduce :**
1. Have an application sized the way you like it.
2. Turn on tiling.
3. Close the application.
4. Turn tiling off.
5. Reopen the application.
6. The application opens with its previous "tiling size' instead of the one you liked.

**Expected behavior:**
In my opinion the size and position of an application should be ignored, when tiling was enabled and applications should open with the size and position what they had the last time before tiling was enabled. It would make the experience much better.

**Other Notes:**
Tiling is awesome, I love pop-shell very much, thanks for making my life easier!

**Comment by mmstick** [comment]
Unsure if we can override this behavior of GNOME Shell, but I'll dig into their source code to find out.

**Comment by horvbalint** [comment]
Are there any updates on this issue @mmstick ?
