### ISSUE TITLE
Tiles on external monitor are sent to new workspace when disconnecting.

### ISSUE THREAD

**Issue by hazza203** [pop-os/shell#386]
**Distribution (run `cat /etc/os-release`):**
 `NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
`
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
`pop-shell:
  Installed: 0.1.0~1589925465~20.04~ff5f374
  Candidate: 0.1.0~1589925465~20.04~ff5f374
  Version table:
 *** 0.1.0~1589925465~20.04~ff5f374 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
`

**Issue/Bug Description:**
When disconnecting external monitor, tiles which were on the external monitor are sent to new workspaces.

**Steps to reproduce (if you know):**

1. Connect external monitor.
2. Create several workspaces with tiles on each monitor.
3. Disconnect external monitor.

**Expected behavior:**
Tiles from external monitor are auto-tiled in the same workspace.

**Comment by StephenRansom** [comment]
Honestly, I think this is a pretty good behavior for it to have. If a physical monitor is removed, its windows are instead placed on a virtual monitor, which won't disrupt the workflow.
Maybe there could be a setting where you could decided between this behaivor and having them retile onto the remaining monitor like you suggest?

**Comment by mmstick** [comment]
This is intended. Windows are not retiled onto an existing workspace, but kept as-is and moved to a new workspace.
