### ISSUE TITLE
Missing Appearance Settings

### ISSUE THREAD

**Issue by decapstrike** [pop-os/shell#389]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 **Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
Pop Settings App, fully updated

**Issue/Bug Description:**
The option to set the desktop and lock screen to a solid color/non-picture is missing; this is on a clean install of Pop OS! 20.04. Previous upgrade from 19.10 to 20.04 did not demonstrate the issue. 
A Deja Dup backup of my home folder was restored post install. 

**Steps to reproduce (if you know):**
Clean install, restore from backup?

**Expected behavior:**

Previously I could set the background to a solid color, as well as alter lockscreen appearance. Neither option is available currently. 
![Screenshot from 2020-05-24 13-06-52](https://user-images.githubusercontent.com/25558692/82761400-db31a680-9dbf-11ea-9111-23f041db2112.png)

**Other Notes:**
Screen shot attached of Settings -> Appearance.

**Comment by mmstick** [comment]
These aren't features in GNOME anymore, as of 20.04
