### ISSUE TITLE
Snap to grid leaves large gap at bottom of screen when windows are maximized

### ISSUE THREAD

**Issue by leviport** [pop-os/shell#39]
![Screenshot from 2020-02-28 15-01-42](https://user-images.githubusercontent.com/13512097/75591100-19772e00-5a3c-11ea-8ed6-ce2526bf94c4.png)

For this bug I have Snap to Grid and Show Window Titles activated. 

Maximized windows result in a large empty area at the bottom of the screen, almost like the outer gap gets applied multiple times, but only at the bottom. If I hit Super+M, the gap only appears after I click the top bar, but if I drag the window to the top of the screen, the empty area appears right away. The empty area was proportionally much larger on a 4K display.

**Comment by mmstick** [comment]
We will just need to add a check for maximization state before assuming that we should snap it

**Comment by mmstick** [comment]
Fixed by d133c95

**Comment by mmstick** [comment]
It's also now possible to toggle maximization with the keyboard in auto-tile mode

**Comment by brs17** [comment]
This looks to be resolved.
