### ISSUE TITLE
Qt WIndows start in floating mode and then break all tiling

### ISSUE THREAD

**Issue by depletionmode** [pop-os/shell#391]
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

pop-shell:
  Installed: 0.1.0~1589925465~20.04~ff5f374
  Candidate: 0.1.0~1589925465~20.04~ff5f374
  Version table:
 *** 0.1.0~1589925465~20.04~ff5f374 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
Some Qt (possibly Qt5/Python) apps start as floating windows which cannot be tiled/docked and once run, all subsequent applicaiton loads (no matter the application) start in floating mode.
pop-shell then breaks with windows semi-tiled all over.

**Steps to reproduce (if you know):**

Simply run some samples from here: https://github.com/pyqt/examples

**Expected behavior:**

These python/qt5 apps should tile like any other and not break.

**Other Notes:**

**Comment by timrichardson** [comment]
I can reproduce this by downloading this as main_helloworld.py and executing it:

```
from PyQt5.QtWidgets import *
app = QApplication([])
label = QLabel('Hello World!')
label.show()
app.exec_()
```

python3 main_helloworld.py

**Comment by timrichardson** [comment]
PS the easier way to recover is to restart the shell: alt-F2 r

**Comment by depletionmode** [comment]
Thanks for the recovery steps. At least I don't need to kill my shell manually any more to recover. :)
Would be great to get a fix though; I use pyqy5 for some custom tooling and my workflow is broken :(

**Comment by laichiaheng** [comment]
It also happens to Manjaro.

**Comment by mmstick** [comment]
Happens because of this:

```
JS ERROR: TypeError: name is null
ignore_decoration/<@/home/mmstick/.local/share/gnome-shell/extensions/pop-shell@system76.com/window.js:96:52
```

**Comment by mmstick** [comment]
Try out the `dev_focal` branch

**Comment by depletionmode** [comment]
I can confirm that the fix works perfectly. Many thanks!
