### ISSUE TITLE
Enabling the extension after you have minimized windows makes these windows' visible but not clickable until you really un-minimize them.

### ISSUE THREAD

**Issue by cansozbir** [pop-os/shell#393]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
pop-shell:
  Installed: 0.1.0~1589925465~20.04~ff5f374
  Candidate: 0.1.0~1589925465~20.04~ff5f374
  Version table:
 *** 0.1.0~1589925465~20.04~ff5f374 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
If I try to enable the shell extension after have some minimized windows, the shell extension makes these windows visible in the background but without unminimizing it (I mean the window is not clickable).
Sometimes it makes it visible over the tiled apps, but I couldn't record it because this happened just a few times.

![demo](https://user-images.githubusercontent.com/32648255/82821280-79029f80-9eac-11ea-8f8c-d79eb6357b52.gif)

**Steps to reproduce (if you know):**
1. Open windows a, b and c
2. Minimize window a
3. Enable shell extension
4. Notice you can see your minimized window behind your tiled windows with disabling the extension or not.

**Expected behavior:**
Minimized windows should keep their hidden state.

**Other Notes:**
I tried with disabling the dash-to-dock extension. Nothing changed.

**Comment by jmmaranan** [comment]
@mmstick - can verify fixed on the latest release. @cansozbir - did you get your machine to work again?

**Comment by jmmaranan** [comment]
@mmstick - I think this can be closed. Tried it in my laptop and desktop. Works fine.
