### ISSUE TITLE
MPV player overlaps other window.

### ISSUE THREAD

**Issue by laichiaheng** [pop-os/shell#394]
**Distribution (run `cat /etc/os-release`):**
```
 NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;2;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
r447.ff5f374-1

**Issue/Bug Description:**
![2020-05-25 22-26-35 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/82822368-42427e80-9ed8-11ea-8fa6-c978f097ce26.png)

**Steps to reproduce (if you know):**
Open 2 window, one of them is mpv player.

**Expected behavior:**
It doesn't overlap another window.

**Other Notes:**

**Comment by fproverbio** [comment]
this is not the extension's fault, as far as i know mpv keeps the aspect ratio of the video intact (thus preventing free xy resizing). if you want pop shell to tile mpv properly you should put the `no-keepaspect-window` in your `mpv.conf`

**Comment by laichiaheng** [comment]
Thanks, it works now.
