### ISSUE TITLE
Gnome Terminal doesn't aligned to the bottom of the screen.

### ISSUE THREAD

**Issue by laichiaheng** [pop-os/shell#397]
**Distribution (run `cat /etc/os-release`):**
 
```
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;2;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

r447.ff5f374-2

**Issue/Bug Description:**

Gnome Terminal doesn't align to the bottom of the screen

**Steps to reproduce (if you know):**

Open Gnome terminal

**Expected behavior:**

It reaches to the bottom of the screen

**Other Notes:**

![2020-05-28 08-04-00 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/83084017-53e37c00-a0ba-11ea-8636-4e02982efbce.png)

**Comment by mmstick** [comment]
GNOME Terminal cannot do this because the application has code which forces the height of the window to be rendered in increments of pixels larger than 1. So if the height of the tiling area is not exactly a multiple of this increment, the bottom of the window will have a gap.
