### ISSUE TITLE
Unexpected behaviour when drag and drop window between workspaces

### ISSUE THREAD

**Issue by danilopinotti** [pop-os/shell#399]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```
pop-shell:
  Installed: 0.1.0~1589925465~20.04~ff5f374
  Candidate: 0.1.0~1589925465~20.04~ff5f374
  Version table:
 *** 0.1.0~1589925465~20.04~ff5f374 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
When I try to change a window for a new workspace, it joins with the below existing workspace.

This behavior happens only when I try to drag and drop the window above a workspace with an existent window.

This bug only appears when the option "Tile Windows" is enabled.

![ezgif-3-c6729582aebd](https://user-images.githubusercontent.com/11338999/83173233-18af7000-a0ef-11ea-81d9-02469d11b68b.gif)

**Steps to reproduce (if you know):**
Try drag and drop a window between workspaces (not inside of an existing).

**Expected behavior:**
Create a new workspace with only the dropped window.

**Other Notes:**

**Comment by jacob-swenson** [comment]
I see similar behavior when using the Super+Shift+Up hotkey.

**Comment by mmstick** [comment]
This appears to be fixed
