### ISSUE TITLE
Should the management overlay not match up with windows in floating mode?

### ISSUE THREAD

**Issue by leviport** [pop-os/shell#40]
![Screenshot from 2020-02-28 15-27-32](https://user-images.githubusercontent.com/13512097/75592416-7e805300-5a3f-11ea-9872-a1e57b488a7f.png)

If I'm in floating mode and I open the management overlay, there is a good chance a window I select won't line up with the borders of the management overlay. I know the overlay is on a grid, while windows in floating mode are not, but it does look a little strange, and hitting enter without making adjustments will slightly resize the window to the size of the overlay. I'm wondering if the first view of the overlay shouldn't be forced to line up with the window, then return to its grid once adjustments are made?

**Comment by mmstick** [comment]
If you press return, it should snap to that exact position, unless we make the first movement calculate the `0, 0, 0, 0` position.

**Comment by leviport** [comment]
I'm just wondering if the window should be making any movements if the user has not yet directly moved anything with the arrow keys. For example: should `Super`+`Enter` then `Enter` move a window, or should arrow keys be hit to make movements first? I think UX input on this would be good, if @maria-komarova doesn't mind weighing in.

**Comment by maria-komarova** [comment]
My first inclination is to say that if the window is off grid and you hit Super+Enter, then hit Enter, it should move to the position of the overlay. But I had tiling for a while now and my perception might be clouded. Should we try to see how someone unfamiliar with tiling would behave? 
I think what we can do is make it work as descried above. Then on the next round of testing, I plan to sit and observe people using tiling at different stages (first use, after couple of days etc.). I can note that concern down and try to closely watch and then talk through whatever reactions will arise. What do you think?

**Comment by mmstick** [comment]
Okay, I'll have the overlay start in an undefined state, where `Enter` does nothing until they start moving the overlay

**Comment by maria-komarova** [comment]
I actually meant the defined state.

**Comment by leviport** [comment]
@pop-os/quality-assurance feels that if a change isn't made, <kbd>Enter</kbd> should not move the window.

<kbd>Super</kbd>+ <kbd>Enter</kbd> is just entering a mode. This mode should allow the user to apply changes, not apply changes automatically. If we are changing automatically, why not offer a potentially useful change (for example: quarter/half tiling)?

Also when the management overlay is launched, if it is not directly over the program that had focus, it is less clear what this blue rectangle is for.

**Comment by WatchMkr** [comment]
Yes, the overlay should start above the activated window. And not move if enter is pressed without adjustment.

There is an issue open for this one here: https://github.com/pop-os/shell/issues/6
