### ISSUE TITLE
Dash to Dock Incompatible With Pop Shell

### ISSUE THREAD

**Issue by TC68** [pop-os/shell#402]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
pop-shell:
  Installed: 0.1.0~1589925465~20.04~ff5f374
  Candidate: 0.1.0~1589925465~20.04~ff5f374
  Version table:
 *** 0.1.0~1589925465~20.04~ff5f374 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
Using the extension "dash to dock", with the dock set to intelligent autohide and a window sufficiently close to the screen edge to cause the dock to hide, triggering the dock to appear results in the dock "hiding" again before an item can be selected (and before the timeout setting in dash to dock is reached). Sometimes, an item gets "snagged" by the mouse for re-ordering and the dock stays present despite this not being the intention.

This only occurs with the window tiling active and the gap set to 1 or 2. Setting to 0 or 3+ causes normal expected behaviour.  A window tiling gap of 2 is the default setting.

In my case the dock is on the left of my screen.

**Steps to reproduce (if you know):**
Install dash to dock extension, and activate intelligent autohide in the extension settings.
Enable pop shell.
Enable "Tile windows" from the panel. Set "Gaps" to 1 or 2.
Place a window adjacent to the dock so that it hides.
Apply mouse "pressure" to trigger the dock to appear.

The dock does not remain visible and minimises too quickly, even when the mouse pointer is over the visible dock area.

**Expected behavior:**

Dock remains visible as long as the mouse pointer is present in dock area.

**Other Notes:**

Dash to dock is an extension recommended by System76 for use with Pop!_OS so would be expected to work correctly with new features.

There is some discussion of this issue in the pop_os subreddit

https://www.reddit.com/r/pop_os/comments/gjsppp/dash_to_dock_minimizing_quickly_and_odd_click/

The recommended solution there to delete and reinstall after rebooting did not solve the issue

**Comment by mmstick** [comment]
There's nothing we can do on this end. It's a behavior of Dash to Dock that it does this.
