### ISSUE TITLE
Unexpected Behavior when using pycharm as Full Screen

### ISSUE THREAD

**Issue by JeffLabonte** [pop-os/shell#407]
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

▶ apt policy pop-shell
pop-shell:
  Installed: 0.1.0~1589925465~20.04~ff5f374
  Candidate: 0.1.0~1589925465~20.04~ff5f374
  Version table:
 *** 0.1.0~1589925465~20.04~ff5f374 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

See screenshots below.... 

When I am running Pycharm in full-screen mode (Mod+m), I would expect to in full screen when I get a prompt from pycharm. It is the same application. 

**Steps to reproduce (if you know):**

Copy something phrase in your clipboard

You open pycharm with a terminal on your screen. Press Mod+m, to switch to full screen mode with pycharm. 

Paste your clipboard in a file in Pycharm.

**Expected behavior:**

The modal window to display over pycharm. and pycharm remains in full-screen mode.

**Other Notes:**

![image](https://user-images.githubusercontent.com/9425955/84059831-39968180-a989-11ea-8269-fce74b978359.png)
![image](https://user-images.githubusercontent.com/9425955/84060060-9003c000-a989-11ea-9776-2bd04a24b51c.png)

**Comment by skewty** [comment]
I am guessing that PyCharm being a Java app is not providing enough meta for the extension to know the window opened is a modal dialog.  Just a guess though.  Sadly, it is highly unlikely this will get fixed by JetBrains unless it affects MacOS.
