### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by ONX0** [pop-os/shell#410]
**Distribution (run `cat /etc/os-release`):**
 
 ```
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

_Not Applicable_

**Issue/Bug Description:**

Won't install from Makefile
```
UUID is "pop-shell@system76.com"
rm -rf /root/.local/share/gnome-shell/extensions/pop-shell@system76.com
mkdir -p /root/.local/share/gnome-shell/extensions/pop-shell@system76.com
cp -r _build/* /root/.local/share/gnome-shell/extensions/pop-shell@system76.com/
cp: cannot stat '_build/*': No such file or directory
make: *** [Makefile:62: install] Error 1
```

**Steps to reproduce (if you know):**
`
cd [directory in which shell source is located]
`
`
sudo make install
`
**Expected behavior:**

The program to install

**Comment by cpiber** [comment]
You need to transpile first. Easiest would be to simply run `sh rebuild.sh`, which executes the necessary commands in order (see README)

**Comment by ONX0** [comment]
> You need to transpile first. Easiest would be to simply run `sh rebuild.sh`, which executes the necessary commands in order (see README)

Ok got it
