### ISSUE TITLE
Dektops and tile windows get messed up after waking up system from suspend. 

### ISSUE THREAD

**Issue by l0vecr4ft** [pop-os/shell#414]
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="20.04 LTS"

 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

pop-shell:
  Installato: 0.1.0~1589925465~20.04~ff5f374
  Candidato:  0.1.0~1589925465~20.04~ff5f374

**Issue/Bug Description:**

After waking up the system from suspend sometimes desktops change disposition and tiled windows in desktop is messed up

**Steps to reproduce (if you know):**

- Tile windows in desktop 1 and desktop 2, 
- Move to dektop 2 and suspend the syste, 
- Wake up the system from suspend

**Expected behavior:**
The desktops disposition and the disposition of the tiled windows remain as they were before suspend

**Other Notes:**
Before suspend: 2 windows in desktop 1, 3 windows in desktop 2

![1 - Before suspend](https://user-images.githubusercontent.com/53183176/84361262-aac57700-abcb-11ea-9742-7e87fc35d1bb.png)

After wake up from suspend: 3 windows in desktop 1 with messed up tile, no windows in desktop 2, 2 windows in dektop 3

![2 - After suspend](https://user-images.githubusercontent.com/53183176/84361265-ad27d100-abcb-11ea-8588-50da228e6b09.png)

**Comment by skewty** [comment]
I think this is an upstream issue because even before PopShell extension I had this issue.

I believe the problem has to do with how fast displays are re-detected (and subsequently re-connected) after being in power saving on multiple display systems.  (aka a race-condition)

**Comment by mmstick** [comment]
Even though it's an upstream issue, we can still deploy a workaround to schedule the display change update until after a certain number of seconds after the most recent update, to at least give some time for GNOME Shell to regain its composure.
