### ISSUE TITLE
Some applications move around by themselves every time tiling is disabled/re-enabled

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/shell#415]
**Distribution (run `cat /etc/os-release`):**
```
jacob@pop-os:~$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
0.1.0~1589925465\~20.04\~ff5f374 and 0.1.0\~1591631045\~20.04\~830dd7a

**Issue/Bug Description:**
When three or four windows are open (and possibly in other configurations), turning tiling off and back on (without touching any of the windows) causes windows to move around. This appears to only happen when certain applications are present, such as the Pop!_Shop.

**Steps to reproduce (if you know):**
Case 1: Pop!_Shop top left corner, terminal bottom left corner, Firefox right half.
Case 2: Terminal top left corner, Pop!_Shop bottom left corner, Firefox right half.

Turn tiling off and on, observe windows move around. If windows don't move around, try selecting a different window and then turn tiling off and on again.

**Expected behavior:**
If tiling is turned off, the windows are not manually moved, and tiling is turned back on, the windows should stay where they are since they were already tiled.

**Other Notes:**

**Comment by jmmaranan** [comment]
@jacobgkau - I think it is because of the way the window list is being sourced, which seems to be from the workspace's tab list. But I could be wrong.

**Comment by mmstick** [comment]
It is sourced from each workspace's tab list, and their position on the screen doesn't really matter to Pop Shell. It just progressively attaches each window to the last window in the list. Their location on the screen has no effect on where they're placed.
