### ISSUE TITLE
Launcher does not switch to Settings when settings panels are launched if Settings is open in another workspace

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/shell#416]
**Distribution (run `cat /etc/os-release`):**
 ```
jacob@pop-os:~$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
 0.1.0~1589925465\~20.04\~ff5f374 and 0.1.0\~1591631045\~20.04\~830dd7a

**Issue/Bug Description:**
If Settings (GNOME Control Center) is open in one workspace, and the Pop Shell launcher is used to launch a specific settings panel (e.g. Bluetooth or Wi-Fi) while in another workspace, a notification is displayed that "Settings is ready," but the shell does not move to the workspace with Settings and does not focus the Settings window.

**Steps to reproduce (if you know):**
- Open Settings
- Switch to another workspace
- Use the launcher to search for and launch any settings panel

**Expected behavior:**
The Settings app is focused/the user is switched to that workspace when choosing a settings panel from the launcher.

**Other Notes:**

**Comment by skewty** [comment]
Perhaps a related issue that will give you a good place to start looking.. sometimes the dash/dock (no extensions) has a dot shown for Apps that are no longer running (example Firefox); confirmed in System Monitor that the app is not running.  I never had this problem before installing Pop Shell.

**Comment by skewty** [comment]
I just encountered this exact issue launching Firefox.  I don't think it is limited to Settings.  Perhaps the description should be changed to something less specific like "Launcher fails to switch to the target workspace of the launching app"

**Comment by jacobgkau** [comment]
> sometimes the dash/dock (no extensions) has a dot shown for Apps that are no longer running (example Firefox)

> I just encountered this exact issue launching Firefox. I don't think it is limited to Settings. Perhaps the description should be changed to something less specific like "Launcher fails to switch to the target workspace of the launching app"

What you are describing is a separate issue. It sounds like https://github.com/pop-os/shell/issues/220.

This issue still exists and only affects GNOME Control Center (Settings). The launcher is able to switch to a Firefox window on another workspace in my testing. Focus is not being switched to Settings if I choose a Settings panel (even the currently-open panel) if Settings is open on another workspace.
