### ISSUE TITLE
[Feature Request] Tab and Shift + Tab support in the launcher

### ISSUE THREAD

**Issue by Jom97** [pop-os/shell#417]
Tab and Shift+Tab support along with with Up and Down keys for moving up and down the list in the launcher you bring up with the 'Super + /' . This allows you to keep your hands in the home row when using the launcher.

I don't know why this isn't the default unless there is some clash with the keys.

**Comment by WatchMkr** [comment]
This was recently added with CTRL + J/K.

**Comment by Jom97** [comment]
Oh I wasn't aware aware of that. But I would still argue that it's such an expected behaviour in a menu.
