### ISSUE TITLE
Should Window Focus dialog show currently open windows by default?

### ISSUE THREAD

**Issue by leviport** [pop-os/shell#42]
When launching the Window Focus dialog with <kbd>Super</kbd>+<kbd>/</kbd>, should the currently open windows be shown by default? Currently you have to search for something before you are shown any results at all?

I feel as though within the last week the behavior of the Window Focus dialog was to show open programs on launch.

**Comment by WatchMkr** [comment]
I think so.

**Comment by mmstick** [comment]
This was done a few a days ago
