### ISSUE TITLE
Custom Shortcuts not working for shell script

### ISSUE THREAD

**Issue by MikeyBeez** [pop-os/shell#423]
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
 
 
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
❯ apt policy pop-shell
pop-shell:
  Installed: 0.1.0~1589925465~20.04~ff5f374
  Candidate: 0.1.0~1589925465~20.04~ff5f374
  Version table:
 *** 0.1.0~1589925465~20.04~ff5f374 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

 I'm having trouble running a custom shortcut.  It's a script that speaks selected text.  I've had this bash script working on Ubuntu Mate, Ubuntu 18.04, and even Pop!_OS 20.04, but it stopped working, and I can't get it to work again.  I call it with bash -c <path to executable shell script> and assign it a custom keyboard shortcut.  The script runs fine from the terminal, but nothing happens when I do the keystroke.     https://github.com/MikeyBeez/GoogSpeech

Reproduce:  Create a shell script or use the one in the above github repository.  Make it executable.  Assign it to a custom keyboard shortcut.  Try to run it.

**Expected behavior:**
Nothing happens.  The script doesn't run.

**Other Notes:**
This was working, then it stopped after updating.   

Thank you again.  Everything else is great!

**Comment by jmmaranan** [comment]
@MikeyBeez - can you check if `gtts-cli` is installed only on your $HOME or in SYSTEM? I tried your repo and I was able to make it work if the gtts-cli is available globally. (e.g. `sudo pip install gTTS`).

When I looked into `journalctl` it says that the gtts-cli was not found as the clue.

**Comment by MikeyBeez** [comment]
@jmmaranan  Thank you so much!  Now it's working.  I thought I understood pip, but I guess I've still a lot to learn about it.  Cheers!
