### ISSUE TITLE
Tiling mode persists when entering Activities overview or changing workspaces

### ISSUE THREAD

**Issue by leviport** [pop-os/shell#43]
After entering Tiling mode (<kbd>Super</kbd>+<kbd>Enter</kbd>), changing workspaces (<kbd>Super</kbd>+<kbd>Ctrl</kbd>+<kbd>Down</kbd>) or entering activities mode(<kbd>Super</kbd>) works.

Either these modes should be disabled when in Tiling mode, or upon selecting unexpected keys, tiling mode should cancel/close.

**Comment by mmstick** [comment]
Fixed by 18d6a5b

**Comment by leviport** [comment]
Indeed, that looks much better now.
