### ISSUE TITLE
Show Active Hint Box Remains After Changing Workspace

### ISSUE THREAD

**Issue by brian-avery** [pop-os/shell#430]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**Issue/Bug Description:**
When "Show Active Hint" is enabled, it draws a yellow box around the currently open window. Changing the workspace leaves the yellow box on the screen. 

**Steps to reproduce (if you know):**
1. Turn on "Show Active Hint"
1. Select a window
1. Observe that the window is outlined in yellow.
1. Change workspace
1. Observe that the yellow box still exists even though it's not outlining a window 

**Expected behavior:**
Yellow box would disappear when the active window is no longer present.

**Other Notes:**
May be related to https://github.com/pop-os/shell/issues/122

**Comment by jacobgkau** [comment]
Possible duplicate of https://github.com/pop-os/shell/issues/366?

**Comment by brian-avery** [comment]
Yeah, this is a duplicate of that. Thanks.
