### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by PitcherTear22** [pop-os/shell#433]
**Distribution (run `cat /etc/os-release`):**  
```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```
 
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
830dd7a9177d9ebebb0024d2fc5312caa485c099

**Issue/Bug Description:**
Extension does not work. No tiling, no launcher

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**
typescript 3.9.5-1
gnome-shell 1:3.36.3-1
make 4.3-3

**Comment by jmmaranan** [comment]
@PitcherTear22, would you be able to add what you did or what steps you tried?

**Comment by PitcherTear22** [comment]
1) `git clone https://github.com/pop-os/shell.git`
2) `cd pop-shell`
3) `sh rebuild.sh`
4) It said log out, so I did.
So far the only changes I observe are remapped shortcuts and an icon in the top bar.
5) Turn tiling off and on again.
6) Restart.
7) Uninstall this using the remove button in the extensions app.
8) Reinstall.
9) Uninstall again and use [this](https://aur.archlinux.org/packages/gnome-shell-extension-pop-shell-git/) aur package, to no avail (same thing hapens)

**Comment by jmmaranan** [comment]
@PitcherTear22, I do not have Arch but do you mind to provide more info? If not, that's OK.

While you are still on the cloned repo's root folder, would you be able to do:
```
$ make listen
```
This should run `journalctl -o cat -n 0 -f "$$(which gnome-shell)" | grep -v warning`. Either way it should open the journal logs.

Then interact with the extension again, toggling, doing the shortcuts, dragging to windows while extension is on, etc. And if you can, please report what you see on the those journal logs.

**Comment by PitcherTear22** [comment]
https://hastebin.com/uwoxonivat.coffeescript
My interaction: 
I toggled floating/tiling, did regular gnome half tiling, moved stuff to different workspaces

**Comment by PitcherTear22** [comment]
It suddenly started working today

**Comment by PitcherTear22** [comment]
Not at startup, but I launched newly installed a qt app https://github.com/Swordfish90/cool-retro-term. It didn't tile, but it showed active hint. When I restarted the shell using Alt+F2, everything started working

**Comment by PitcherTear22** [comment]
It stopped working again

**Comment by PitcherTear22** [comment]
> Not at startup, but I launched newly installed a qt app https://github.com/Swordfish90/cool-retro-term. It didn't tile, but it showed active hint. When I restarted the shell using Alt+F2, everything started working

So this happened again. Wierd af

**Comment by Eeems** [comment]
Are you running in wayland or xorg?

**Comment by PitcherTear22** [comment]
xorg

**Comment by jmmaranan** [comment]
@PitcherTear22 - I would suggest to disable or remember if you had the `development version`/or git clone installed vs the AUR package. Please remove the development version to rule out which one is causing it. I remember I had this issue when I started looking at the code and trying things out. Also remember that: `make enable` or `make disable` seems to disable both the .local and the system extensions at the same time - at least when I tested in my local user account.

Also, one thing that could help is using a `developer` user account in your machine to do development.

**Comment by PitcherTear22** [comment]
> AUR package
The aur package is a git clone
![image](https://user-images.githubusercontent.com/36493671/85633488-f92c4880-b696-11ea-8975-34f422218e25.png)

I have the git clone installed
> Also, one thing that could help is using a separate developer user account in your machine to do development.

I just want to use this awesome extension haha, if it doesn't work it's not a real problem because it would be exactly like the extension didn't exist.

**Comment by jmmaranan** [comment]
> > AUR package
> 
> The aur package is a git clone, anyway I have the git clone installed.
> ![image](https://user-images.githubusercontent.com/36493671/85633488-f92c4880-b696-11ea-8975-34f422218e25.png)
> 
> > Also, one thing that could help is using a separate developer user account in your machine to do development.
> 
> I just want to use this awesome extension haha, if it doesn't work it's not a real problem because it would be exactly like if the extension didn't exist.

:)  - do you still experience the original issue?

**Comment by PitcherTear22** [comment]
> It stopped working again

Not after this
