### ISSUE TITLE
Can't change keyboard shortcut for Toggle auto-tiling

### ISSUE THREAD

**Issue by nicad** [pop-os/shell#434]
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="20.04 LTS"

  
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

n/a

**Issue/Bug Description:**

SUPER+Y is mapped to toggle tiling on/off but I can't find any way to change it. All other options from the 'WIndow Shortcuts' section can be modified except this one. I had a very bad surprise where all my windows in all desktops got shuffled when I tried to use SUPER+Y in an app.
I would also be happy disabling that option completely as I would never un-tile my workspaces at once.

Is there a temporary workaround until it becomes remapable ?

**Steps to reproduce (if you know):**

view shortcuts in tiling menu then compare with Keyboard shortcuts from settings.

**Expected behavior:**

be able to remap "Toggle auto-tilin" in Keyboard Shortcuts

**Other Notes:**

**Comment by WatchMkr** [comment]
Add to GNOME Settings > Keyboard Shortcuts > Tiling

**Comment by ids1024** [comment]
This should be fixed in the latest update to `gnome-control-center` from the Pop!_OS 20.04 repository. Closing.
