### ISSUE TITLE
Game icon does not disappear from dock.

### ISSUE THREAD

**Issue by laichiaheng** [pop-os/shell#439]
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;2;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

r447.ff5f374-2

**Issue/Bug Description:**

When I exit the game, the game icon on dock does not disappear.

**Steps to reproduce (if you know):**

Exit a game on Steam.

**Expected behavior:**

The icon will disappear.

**Other Notes:**

![2020-06-26 16-25-12 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/85836978-072eb600-b7ca-11ea-98e2-d5f3c59616e0.png)

**Comment by jmmaranan** [comment]
@laichiaheng - can you try this in the latest release? And do you know which game is having this issue when exited?

**Comment by laichiaheng** [comment]
> @laichiaheng - can you try this in the latest release? And do you know which game is having this issue when exited?

The problem is gone, it was the Resident Evil 3 Remake.
