### ISSUE TITLE
disabling "Show window title" option doesn't work as expected?

### ISSUE THREAD

**Issue by VariabileAleatoria** [pop-os/shell#443]
**Distribution (run `cat /etc/os-release`):**
 ```
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
```
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```
pop-os shell commit: 9e8ab29cb976b078aa6e8fab59b09527a092a1b8
```

**Issue/Bug Description:**
With "Show window title" option turned off there are few programs that actually remove title bar (Telegram and Discord) while Spotify isn't affected by the option.
VSCode instead as an annoying behaviour, the option works but it has to be turned on and off every time, or after boot it will show the title bar even if the option is OFF.

![Schermata da 2020-07-01 21-13-33](https://user-images.githubusercontent.com/45683610/86282554-c1b22480-bbdf-11ea-8e47-a1850a39526a.png)

**Comment by mmstick** [comment]
It will be a toggle in the panel menu when it's ready

**Comment by jmmaranan** [comment]
Related to #378

**Comment by VariabileAleatoria** [comment]
to me this fixed only urxvt which now doesn't show titlebars, but other programs (spotify, vscode) still do
