### ISSUE TITLE
[Feature Request] When only one window exists in a workspace have it maximized by default

### ISSUE THREAD

**Issue by MechJM** [pop-os/shell#445]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
pop-shell:
  Instalado: 0.1.0~1593273798~20.04~9e8ab29
  Candidato: 0.1.0~1593273798~20.04~9e8ab29
  Tabela de Versão:
 *** 0.1.0~1593273798~20.04~9e8ab29 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
Gaps are shown when a single window is present in a workspace. 

**Steps to reproduce (if you know):**
Have gaps enabled, go to a new workspace and open an application (make sure the application only creates one window).

**Expected behavior:**
The window should be maximized (similar to how i3-gaps does it) and only when another window is created should the gaps appear.

**Other Notes:**
None.

**Comment by mmstick** [comment]
This was already discussed in a prior issue before release, and it was decided to not do so.
