### ISSUE TITLE
Keyboard attempts to resize GNOME Control Center one increment farther than its minimum width

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/shell#446]
**Distribution (run `cat /etc/os-release`):** Pop!_OS 20.04 LTS
 
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):** `0.1.0~1593273798~20.04~9e8ab29`

**Issue/Bug Description:** When using the keyboard to resize GNOME Control Center, once I'm at the minimum width for that window, I'm able to press the keyboard shortcut one more time, and while G-C-C does not get any smaller, the other windows do get larger (and the G-C-C window overlaps with them.)

**Steps to reproduce (if you know):** Place G-C-C on the left side of the screen and another window on the right side of the screen. Use the keyboard to horizontally shrink G-C-C as far as the keyboard shortcuts will allow.

**Expected behavior:** If the selected window can't get any smaller, the other windows shouldn't get any bigger.

**Other Notes:**

**Comment by mmstick** [comment]
Same issue as #85
