### ISSUE TITLE
Interface sometimes freezes on latest version

### ISSUE THREAD

**Issue by jannikbuhr** [pop-os/shell#449]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
pop-shell:
  Installed: 0.1.0~1593273798~20.04~9e8ab29
  Candidate: 0.1.0~1593273798~20.04~9e8ab29
  Version table:
 *** 0.1.0~1593273798~20.04~9e8ab29 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
Seemingly random interface freezes where nothing moves (mouse as well). System parameters such as CPU / RAM are fine, at least once I am able to check again.

**Steps to reproduce (if you know):**
I haven't been able to determine the cause yet. It seems to be connected to moving / opening windows and re-tiling.

**Expected behavior:**
No freeze.

**Other Notes:**

**Comment by mmstick** [comment]
Are you able to verify that it's caused by Pop Shell? Which commit did it start freezing?

**Comment by jannikbuhr** [comment]
Did some more digging and found out that it coincides with similar incidents for other users of the brave browser. It might be related to nvidia power saving but is most likely unrelated to the pop-shell itself. As far as I can tell it only happens when the browser is open. I am closing the issue and am leaving a link to the issue in the brave repo: https://github.com/brave/brave-browser/issues/9481.

**Comment by mmstick** [comment]
I did experience some freezing on the NVIDIA driver in stable, but it stopped after I installed the short-lived driver in our `450.51` branch

**Comment by jmmaranan** [comment]
@mmstick - Firefox max/un-max - has a bit of a stutter. Other window/apps seems to be OK. But no freezing.

**Comment by jannikbuhr** [comment]
I managed to isolate and reproduce the problem. It appears to be related to (re-)tiling and is not related to the browser. I am able to consistently get freezes by opening three windows (I used alacritty) and moving them around with Super+Mouse a bunch.

**Comment by WatchMkr** [comment]
I’ve started to experience this as well. I’m on integrated Intel graphics on the galp4.

**Comment by jannikbuhr** [comment]
Something weird happened. I cleared my `/var/logs/` files to see what new logs would pop up after a freeze... and now I am not able to recreate the freeze, no matter how many windows I create and frantically move around.

**Comment by mmstick** [comment]
Does it happen on the `stacking` branch? I've been actively developing it lately, and haven't experienced any issues with freezing with NVIDIA graphics.

**Comment by jannikbuhr** [comment]
No freeze so far on the `stacking` branch. Though it has a frame where a ghost border (the active hint) appears in the middle of the screen and the window that is being moved flashes in a different location.

**Comment by julianlam** [comment]
I'm also available to test, as I have been bitten by this bug. The interface locks up (keyboard/mouse inputs ignored) for 30 seconds at a time.

It only happens if a re-tile is triggered, like if a new window is opened.

**Comment by Booteille** [comment]
I am experimenting the same since days (or weeks, I can't say).

```console
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
