### ISSUE TITLE
Grid leaves empty area at bottom of screen

### ISSUE THREAD

**Issue by leviport** [pop-os/shell#45]
This seems like it may be related to https://github.com/pop-os/shell/issues/39

If I use <kbd>Super</kbd> + <kbd>Enter</kbd> to resize a window while in free-float mode, there is a region on the bottom of the screen that I cannot resize the window into with <kbd>Shift</kbd> + arrows. I can use the mouse to expand the window into that area, but it's almost like the grid does not extend that far.

![Screenshot from 2020-03-02 09-34-37](https://user-images.githubusercontent.com/13512097/75697954-0f874200-5c6b-11ea-8c1e-544ee4966b70.png)

The screenshot above shows my monitor setup with an Alacritty window on each display sized as large as I can make it in window management mode. The top display is 4K (100% scaling) and the bottom one is 1080p. The empty area is much larger on the 4K display in terms of pixels, but it seems roughly the same proportionally as the 1080p display.

Also this does not seem to happen with tiling mode activated, so that tiling grid seems to line up with the full area of my displays better.

**Comment by mmstick** [comment]
I think this one is because the tile-snapper assumes that every monitor is the same resolution

**Comment by leviport** [comment]
I'm also seeing similar behavior on portrait displays, even if they're the same resolution as the landscape primary display. This screenshot shows the largest I could make this window on this 1920x1080 portrait monitor with "Tile Windows" off and "Snap to Grid" on. If I disable "Snap to Grid", I can make it larger than this.
![portrait](https://user-images.githubusercontent.com/13512097/76359631-3ab00800-62e1-11ea-98d8-a2e081d1eed6.png)
