### ISSUE TITLE
DIfferent settings in locales and languages crash the installation

### ISSUE THREAD

**Issue by RochaLAJ** [pop-os/shell#454]
DISTRO:  Pop!_OS 20.04 LTS 
WHERE: Installation

**DESCRIPTION**
I tried to install the system in my laptop with the LANGUAGE set to English and the keyboard to Portuguese (Brazil) ABNT2. The installation crashes while is trying to configure the system (30%).  From the output, i saw a message like:
Failed to set the locale
en
en
en
..
LANG = [UNSET]
and the system ask if i want to try again or see the demo mode.  
The system works if i set  the language to portuguese. 
I Also tried to install with the language to English and on the second part i selected "NONE", same error happened.

**REPRODUCTION**
Download the nvidia proprietary iso
create a bootable USB with Balena
1. install with different settings for locales.(language english, keyboard portuguese)
2. install with language english, the second part select "NONE".

**EXPECTED BEHAVIOR**
Expect an error when the system setup reach 30%

**Comment by leviport** [comment]
I believe this is the same issue as https://github.com/pop-os/installer/issues/190 and https://github.com/pop-os/installer/issues/192 .
