### ISSUE TITLE
Gnome Shell is making Dash to Dock Bounce

### ISSUE THREAD

**Issue by RoBi1475** [pop-os/shell#456]
Distribution (run cat /etc/os-release):
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

Related Application and/or Package Version (run apt policy $PACKAGE NAME):

Dash to Dock version 68

Issue/Bug Description:
When using the auto hide function of dash to dock the dock will repeatedly try to re-hide itself while user trys to select am program from the dock. It ends up looking like the dock is twerking and while slightly humorous it makes trying to use the dock frustrating.

Steps to reproduce (if you know):
Configure dash to dock setting to place dock at bottom of the screen and activate the auto hide feature. Also makes sure gnome shell is active and set to its defaults. Open a program so that the dock auto hides. now move the mouse cursor to the middle of the bottom screen bezel. This will bring up the dock and the dock should start to twerk. It should be noted that the dock will not twerk if user brings the mouse cursor down to the bottom bezel to the right or left of the dock and then slide the cursor to the dock after it pops up. It only seems to twerk when the dock pops up and the mouse cursor is immediately on the dock.

Expected behavior:
The dock should pop up and remain visible while the mouse cursor is on the dock and it should not twerk.

Other Notes:
I believe that this is an issue with gnome shell and not dash to dock because the bug is not present when the gnome shell extension is turned off. Nor have I noticed this bug on Fedora which does not have gnome shell by default.

**Comment by mmstick** [comment]
Duplicate issue. Dash to Dock issue
