### ISSUE TITLE
Blurry Text on PopOS

### ISSUE THREAD

**Issue by RedTuxedo** [pop-os/shell#457]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

Hi guys, I got this issue where some of application looks blurry on PopOS when I turn on tile windows function.
The weird things is, in once screen, not all apps will look blurry (in my case only half-right part of the screen).
I can not really confirm that tile windows function is causing this, because when I exit the tile windows function, the blurry text is not gone, after I turn off the tile windows I still need to maximize/move/resize windows to make it look sharp again.

**Steps to reproduce (if you know):**

To reproduce:
1. Have some apps already opened (file manager, terminal, chrome), then turn on tile windows function on PopOS.
2. Put file manager in left half of the screen and move chrome and terminal to the right-half side of the screen. (in my case, Chrome on top, Terminal on bottom)
3. Initially, both terminal and chrome will look blurry.
4. Click on Terminal --> text instantly becomes sharp
5. Click on Chrome --> text stays blurry.
Note: **with tile windows on**, if I maximize Chrome windows, text instantly looks sharp, however if I minimize again (and it goes back to right-top part of the screen), it gets blurry again.

To resolve:
1. Close tile windows function, **at this time text is still blurry**
2. Maximize Chrome window, text will look sharper. And even so, if I try to minimize again, text will still look sharp. (even if it goes back to previous position)

**Expected behavior:**

Text should stay sharp at all times.

**Other Notes:**

My screenshot picture does not exactly same with the reproduction steps that I mentioned above but it can be seen that blurry text is there (on chrome on right part of the screen).
Additional: tried to change browser into Firefox and Firefox behaves like Terminal (looks sharp when I get focus on it)

Blurry text on chrome (right half) when tiling windows is on:
![blurry](https://user-images.githubusercontent.com/68474885/87857162-c3ede000-c94e-11ea-85a7-40864687c00a.png)

Sharp text after tiling windows is turned off and chrome windows is maximized and then minimized:
![not-blurry](https://user-images.githubusercontent.com/68474885/87857128-740f1900-c94e-11ea-8ccb-b28e4ba43154.png)

**Comment by jmmaranan** [comment]
@RedTuxedo - I think this is a limitation of the Clutter API that is currently being used by pop-shell to move windows. Re-focusing on the window or hover on it will make it clearer again.

**Comment by RedTuxedo** [comment]
> @RedTuxedo - I think this is a limitation of the Clutter API that is currently being used by pop-shell to move windows. Re-focusing on the window or hover on it will make it clearer again.

@jmmaranan not really in my case, even re-focusing or hovering on doesn;t make it sharper, however I do understand that this is not a big priority since not everyone is using tiling features.

**Comment by laichiaheng** [comment]
Not only text, but also the image/video, and it only happens to the bottom window.

**Comment by jmmaranan** [comment]
That is correct. In my case, I have the window raise option. Or moving the window would fix it. And only occurs on lower half tiled windows. If you get a really not readable screen that might be a different issue altogether.

**Comment by mmstick** [comment]
I have a strong feeling that it's a side effect of the animations applied to windows when they are moved. There have been bug reports filed upstream for windows having this blurry effect after unmaximizing or unfullscreening them, and I believe those have been fixed. Will need to track down the particular issue they fixed, and how they fixed it.

**Comment by laichiaheng** [comment]
@jmmaranan The problem is not solved, you still need to hover your mouse on the window.

**Comment by jmmaranan** [comment]
@mmstick - setting `ext.animate_windows = false` fixes it but we lose the UX especially when grab/swap windows. When slowing down the tweener (149 to 1000), can see that any bottom half windows underneath the window that's moving becomes blurry. Probably not caused by the unmaximize or unfullscreen. Maybe put animations in prefs.js

**Comment by laichiaheng** [comment]
> @mmstick - setting `ext.animate_windows = false` fixes it but we lose the UX especially when grab/swap windows. When slowing down the tweener (149 to 1000), can see that any bottom half windows underneath the window that's moving becomes blurry. Probably not caused by the unmaximize or unfullscreen. Maybe put animations in prefs.js but this has been there for a long time, and user workaround is to focus on the window.
> Also, I do not see it becoming blurry in a second monitor on the right (with 4 windows tiled to it)

Try to open 5 windows, and close the last 2 windows, the 2nd window will be blurry.

**Comment by marksumm** [comment]
What I'm seeing is that, with animations disabled, the issue still occurs but the affected window is quickly redrawn after it blurs.  It's very easy to see and reproduce by resizing the VLC playlist window.

**Comment by laichiaheng** [comment]
Any progress?

**Comment by mmstick** [comment]
@laichiaheng The cause hasn't been found yet

**Comment by marksumm** [comment]
I couldn't fix this by disabling animations, but disabling "Snap to Grid (Floating Mode)" enabled in Pop shell extension settings has fixed it for me.

**Comment by laichiaheng** [comment]
> I couldn't fix this by disabling animations, but disabling "Snap to Grid (Floating Mode)" enabled in Pop shell extension settings has fixed it for me.

What does the Snap to Grip mode do?

**Comment by marksumm** [comment]
It constrains the landing position of a dragged window, so that it is grid-aligned.  If it is enabled, you will see that dragged windows do not always land exactly where you release them and instead they float into the nearest "correct" place.

**Comment by MikhailTNY** [comment]
I can confirm that I haven't seen any more instance of blurry text once I turned off the grid option and I've been using stacked tiling mode on too. I used to have to log out and back in to fix blurry like a day before that.

**Comment by laichiaheng** [comment]
Weird, it has always been disabled.

**Comment by mmstick** [comment]
Disabling snap-to-grid fixes the blurry windows even with auto-tiling?

**Comment by laichiaheng** [comment]
> Disabling snap-to-grid fixes the blurry windows even with auto-tiling?

Not for me.

**Comment by Tinche** [comment]
Hi,

I installed the Pop shell the other day since seeing the stacking mode for tiling you folks have; I think it's excellent. However I'm also getting the blurry fonts issue. I have a 100% repro case.

In a fresh workspace, open Tilix and VS Code side-by-side (it works with gnome-terminal too). Tilix on the left, VS Code on the right. Switch to Tilix, and enable stacking on that window with Super+S. This triggers a small animation on the Tilix window (showing the new header bar for the stack) and blurs the fonts on the VS Code window. The fonts remain blurred until I move the window a little with the mouse, or I switch to the window and toggle stacking on it (which animates it, I guess, and clears the blur).

It works in reverse too, with VS Code being on the left and Tilix being in the right, but the Tilix blur clears as soon as it's focused. It's always the window on the right that gets blurred though, never the one on the left. Where can I disable the animations to test out if that affects it?

**Comment by Tinche** [comment]
I think I narrowed down my particular issue - it only happens when I have a persistent vertical dock enabled. Either the Ubuntu dock or Dash to Dock will trigger the problem.

**Comment by laichiaheng** [comment]
> I think I narrowed down my particular issue - it only happens when I have a persistent vertical dock enabled. Either the Ubuntu dock or Dash to Dock will trigger the problem. As soon as I disable both extensions the problem goes away. Which is unfortunate since I really want a persistent vertical dock :)

It happens without dock, too.

**Comment by GeneralPoxter** [comment]
I can confirm I also reproduce this issue. It does not occur consistently for me, but I have seen it happen for both chromium and Arduino IDE, and usually after another window is opened, filling the workspace with over 3 windows.

**Comment by GeneralPoxter** [comment]
It's been a while since there have been updates on this issue, but I found that both moving the window around, resizing the window, or just entering and exiting Window Management Mode with `Super` + `Enter` + `Enter` seem to temporarily remove the font blur. I'm really looking forward to a fix to this since it's really a significant nuisance when working with multiple windows in a workspace.

**Comment by laichiaheng** [comment]
Still no any clue?
