### ISSUE TITLE
Fail to open gnome-control-center with the error of pop-shell

### ISSUE THREAD

**Issue by XinzeZhang** [pop-os/shell#458]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
pop-shell:
  Installed: 0.1.0 1589925465 20.04 ff5f374
  Candidate: 0.1.0 1593273798 20.04 9e8ab29
  Version table:
     0.1.0 1593273798 20.04 9e8ab29 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
 *** 0.1.0 1589925465 20.04 ff5f374 100
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
I meet a bug which makes me cannot open the settings in the pop-desktop environment.
The error is that:
(gnome-control-center:3195): GLib-GIO-ERROR **: 20:54:25:251: Settings schema 'http://org.gnome.shell.extensions.pop-shell' does not contain a key named 'activate-laucher'

I have tried to reinstall gdm3 pop-desktop gnome-shell, but it does not work.

**Comment by mmstick** [comment]
Do you have a way to replicate this?

Your schema looks weird. Schemas don't start with `http://`

**Comment by ids1024** [comment]
This is probably due to https://github.com/pop-os/gnome-control-center/pull/99, which required a change in pop shell: https://github.com/pop-os/shell/pull/436.

> Installed: 0.1.0 1589925465 20.04 ff5f374
> Candidate: 0.1.0 1593273798 20.04 9e8ab29

It looks like you're not on the latest version of Pop Shell. Are you able to update, and does that resolve the issue?
