### ISSUE TITLE
Old Keyboard Shortcuts are Lost W/out warning

### ISSUE THREAD

**Issue by Gryzor** [pop-os/shell#47]
### Context
I wanted to try this to start offering early feedback and to start getting used to what I think is going to be amazing so I asked around and @mmstick got me hooked up right away (thanks!). 

I'm on Pop 19.10 and had to do `npm install -g typescript` (I already had `npm` set up). 
`tsc --version` now returns `Version 3.8.3`

This is an Oryx Pro 2019.

### Problem
After running the `rebuild.sh` script, I noticed all my mostly default familiar Pop!_OS shortcuts to move windows around no longer worked. This is obviously expected (that there will be new _conflicting_ shortcuts with a regular Gnome Session), but what was not necessarily expected was that I was going to "lose" my original shortcuts. 

Perhaps there's a way to mitigate this (warn users? allow to "save" them?)

### Expected
That there was a way to restore my shortcuts the way they were before.

### Why am I filing this?
At the request of "shpurk" on mattermost who said: (And I quote):

> Maybe you should file an issue about this, the fact that you didn't think to do this/etc, when people upgrade to 20.04, there will probably be a lot more people in the same spot you are in.

Thanks!

**Comment by mmstick** [comment]
This project won't be responsible for altering keyboard shortcuts. The rebuild script is for development / testing purposes only.

**Comment by mmstick** [comment]
I believe we'll have a warning in the OS upgrade's changelogs about the changes we're making.

**Comment by brs17** [comment]
In the changelog when updating to Pop!_OS 20.04, we mention the changing of keyboard shortcuts.

**Comment by brs17** [comment]
Thank you for posting the issue @Gryzor

**Comment by nicolae-stroncea** [comment]
I think this is still an issue for beta testers, and people running it on other distributions for their first time. They don't have the Pop 20.04 Changelog, so they don't expect their shortcuts to be modified.

It would probably be good to warn them in the README, and even better by prompting for a confirmation in rebuild.sh: "Pop Shell will change your shortcuts. Are you sure?". Type y/n.

Ideally the confirmation would be saved somehow so you don't get prompted again, but the simplest implementation would probably be. rebuilding with: `./rebuild.sh -y`.
