### ISSUE TITLE
[Feature Request] Smart-gaps

### ISSUE THREAD

**Issue by REIS0** [pop-os/shell#470]
A behaviour similar to smart-gaps in i3-gaps which when there's only one window/program open in a workspace, it fills the whole space without any gaps, when another program/window is started then the gaps are shown.

**Expected behaviour**:
1. If there's only one program in the workspace, the program's window is in maximized mode
2. When there's any other program, the gaps appears.

**Comment by moshiur05** [comment]
A smart "active hint" would be nice too.

**Comment by mmstick** [comment]
Will be added after the stacked tiles features is released
