### ISSUE TITLE
Keyboard shortcuts displayed in the tiling extension don't get updated

### ISSUE THREAD

**Issue by RafalSkolasinski** [pop-os/shell#475]
**Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 0.1.0~1593273798~20.04~9e8ab29
  Candidate: 0.1.0~1593273798~20.04~9e8ab29
  Version table:
 *** 0.1.0~1593273798~20.04~9e8ab29 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

Shortcuts displayed in the tiling extension does not reflect actual system settings.

**Steps to reproduce (if you know):**

1. change tiling related shortcuts
2. view shortcuts in tiling extension icon

**Expected behavior:**

tiling extension displays correct shortcuts

**Other Notes:**

**Comment by leviport** [comment]
Thanks for the report. This feature is currently in progress: https://github.com/pop-os/shell-shortcuts/issues/27
