### ISSUE TITLE
Windows unreliably resize after moving between workspaces with keyboard

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/shell#477]
**Distribution (run `cat /etc/os-release`):** Pop!_OS 20.04
  
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):** Occurs on Pop!_Shell versions `0.1.0~1593273798~20.04~9e8ab29` (current stable) and `0.1.0~1596479408~20.04~009eb19` (stacking branch.)

**Issue/Bug Description:** When moving an application between workspaces, it sometimes doesn't resize/retile in the new workspace. When this occurs, there is also a gap in the original workspace that I am unable to move other windows into.

**Steps to reproduce (if you know):** Quarter-tile four windows, then move one back and forth between two workspaces using the keyboard (Super-Shift-Down/Up).

**Expected behavior:** The window should always resize/re-tile to fit the new workspace. The behavior should be consistent.

**Other Notes:**
Example showing the application failing to resize: https://www.dropbox.com/s/75odqufdrvvl767/Screencast%20from%2008-03-2020%2003%3A02%3A22%20PM.webm?dl=0 
Example showing the resulting gap in the first workspace: https://www.dropbox.com/s/bpj9vbu4eohypiy/Screencast%20from%2008-03-2020%2003%3A09%3A52%20PM.webm?dl=0 
When this occurs, the fork in the second workspace seems to be limited to the size of the application window (e.g. a quarter of the screen in these examples) until I toggle tiling off and back on.

**Comment by depletionmode** [comment]
Yeah I've noticed this as well.

**Comment by mmstick** [comment]
Is this fixed now?

**Comment by jacobgkau** [comment]
Yes, this is no longer happening. I believe it was fixed in the stacking branch.

**Comment by expl0r3rgu1** [comment]
It's happening to me
