### ISSUE TITLE
Tiling not working on second monitors

### ISSUE THREAD

**Issue by shaun-ba** [pop-os/shell#478]
**Distribution (run `cat /etc/os-release`):**
 
 20.04
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

Master

**Issue/Bug Description:**

I have 3 monitors, 2 x 27inch Asus and 1 x Samsung 49inch.

Tiling doesn't work on the two higher 27inch monitors?

**Comment by benjaminlarin** [comment]
Same issue here. Workaround: use mouse or enter adjustment mode with super + enter. 

Is already been discussed here https://github.com/pop-os/shell/issues/246

**Comment by jmmaranan** [comment]
@shaun-ba - do you have a video tiling not working on the other monitor? 

@benjaminlarin - not much info to say it is related to #246.

**Comment by mmstick** [comment]
Closing since I still can't replicate this
