### ISSUE TITLE
Windows not moving to new workspace when second display is unplugged

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/shell#482]
**Distribution (run `cat /etc/os-release`):** Pop!_OS 20.04 LTS
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):** `0.1.0~1596663403~20.04~c976582` (shell-misc branch) and `0.1.0~1593273798~20.04~9e8ab29` (current stable).

**Issue/Bug Description:** When a second display is unplugged, its tree is supposed to be placed onto a new workspace on the remaining display.

**Steps to reproduce (if you know):**
- Open 8 windows (Firefox, Terminal, Gedit, Pop!_Shop, Files, Contacts, Calendar, Settings).
- Arrange windows in quarter-tiles on both displays.
- Unplug second display.
- The remaining display has windows hanging off of its edges, overlapping, and not able to be moved/resized properly.

**Expected behavior:** The four windows from the second display should move to a new workspace on the remaining display.

**Other Notes:**

**Comment by mmstick** [comment]
Do these monitors have different resolutions?

**Comment by jacobgkau** [comment]
> Do these monitors have different resolutions?

The issue occurs with different resolutions (1080p internal display and 1440p external display), and it still occurs if I make the monitors the same resolution (1080p internal display and 1080p external display). I initially saw the issue on the gaze14 in NVIDIA mode, just confirmed it on the darp6 with Intel graphics.

Today, testing with `990c626`, I'm seeing the four windows from the second display being placed directly on top of the four windows from the primary display (with subsequent issues accessing the windows in the back.)

**Comment by jacobgkau** [comment]
Resolved by https://github.com/pop-os/shell/pull/721.
