### ISSUE TITLE
Enable Super+G Keyboard Shortcut Before Super+Y

### ISSUE THREAD

**Issue by DamianRivas** [pop-os/shell#486]
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

qjackctl:
  Installed: 0.5.0-1ubuntu2
  Candidate: 0.5.0-1ubuntu2
  Version table:
 *** 0.5.0-1ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

When auto-tiling is toggled on, all windows that are open and opened in the future are automatically tiled. This is okay but there is no way to turn this behavior off that I know of.

Some applications do not handle the resize very well. The application I am using to showcase this problem is QjackCtl which is commonly used for professional audio work.

Super+G is the shortcut to toggle floating mode, but this shortcut doesn't seem to work until after auto-tiling has been enabled and by that time it's too late.

**Steps to reproduce (if you know):**

Open QjackCtl
press Super+G (attempt to toggle floating mode prior to toggling auto-tiling)
press Super+Y (toggle auto-tiling)

**Expected behavior:**

The QjackCtl window does not tile with the rest of the windows when auto-tiling is toggled on. Hence it keeps its original dimensions and location

**Other Notes:**

This problem would be less of an issue if toggling floating mode reverted the target application back to its original dimensions, or even location.

![image](https://user-images.githubusercontent.com/10257813/89608882-25f18500-d82b-11ea-8242-581ca49206ec.png)

![image](https://user-images.githubusercontent.com/10257813/89608717-be3b3a00-d82a-11ea-94dd-8c2ea1412dac.png)

**Comment by jacobgkau** [comment]
This seems like it would require https://github.com/pop-os/shell/issues/254 to be addressed first. That's being worked on here: https://github.com/pop-os/shell/pull/483.

**Comment by DamianRivas** [comment]
I'm glad to see it's being worked on!

**Comment by Honza-m** [comment]
If I may add my two cents here, I think the ideal solution to this would be for the shell to remember the original dimensions (and possibly location) of every new window before it gets tilled. When pressing Super + G, the window could then be automatically resized back to the original dimensions.

This way you wouldn't have to set anything up in advance, just press Super + G whenever the tilling doesn't really work for your window.

**Comment by jasonccox** [comment]
Just FYI, you can specify applications to float by default since https://github.com/pop-os/shell/pull/483. You just have to edit `~/.config/pop-shell/config.json`. There isn't much documentation on it as far as I can tell, but I have the following in there, for example:

```json
{
  "float": [
    {
      "class": "Gnome-calculator"
    },
    {
      "class": "zoom"
    }
  ],
  "log_on_focus": false
}
```

(`xprop` is really useful for figuring out what an application's window class is, by the way.)

It's not exactly what you're asking for, but it may solve the problem for you if you set QjackCtl to always float.

**Comment by jmmaranan** [comment]
@mmstick is working on the GUI, the manual doc is in the README on the `Customizing the Floating Window List` section
