### ISSUE TITLE
Ghost Windows

### ISSUE THREAD

**Issue by shaun-ba** [pop-os/shell#491]
**Distribution (run `cat /etc/os-release`):**
 
 20.04
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

master

**Issue/Bug Description:**

Ghost windows - I have an empty tile, how do i find out what process is occupying it so i can kill it?
![Screenshot from 2020-08-11 09-47-10](https://user-images.githubusercontent.com/3339587/89877221-b0cdd900-dbb7-11ea-9840-afc97f0c0974.png)

**Comment by mmstick** [comment]
It could be that a window is assigned to multiple locations in the tree. You can run `make listen` from this repository to watch gnome-shell's journald logs, as I do log the tree structure as it evolves.

**Comment by skewty** [comment]
I am having this issue about once every 2 days.  Is there something I can run in a shell to tell pop-os shell to list the windows it thinks exists?  And another to ask the window manager to generate a similar list?

NOTE: I have this issue using wayland session and don't think I every experienced it under x11

**Comment by mmstick** [comment]
There is no functionality like that. You'd have to edit the source code to log the state of all trees after making changes to it.

**Comment by mmstick** [comment]
If you can find a way to replicate it reliably, I can look into it

**Comment by mmstick** [comment]
Is this still an issue?

**Comment by skewty** [comment]
I don't have time to dig into this to try and fill the "needs reproduce instructions" at this time.  

Close it for now I suppose.  I'll check again after a Gnome 3.38 Pop!OS release.

**Comment by mmstick** [comment]
Okay, that would be helpful if you do
