### ISSUE TITLE
Active hint moves away from active floating window when tiling actions are performed

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/shell#493]
**Distribution (run `cat /etc/os-release`):** Pop!_OS 20.04 LTS
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):** Occurs in `0.1.0~1597190322~20.04~149061a` (current master) as well as `0.1.0~1597190879~20.04~52ded06`.

**Issue/Bug Description:** After floating a window, the active hint usually moves back to a window that is not currently active. Additionally, if a window is closed and causes other tiled windows to be adjusted, and the focus is placed on a floating window, the active hint ends up going to one of the adjusted windows instead of the active floating window.

**Steps to reproduce (if you know):**
- Scenario 1:
  - Enable active hints.
  - Tile two windows.
  - Float one of the windows with Super-G.
- Scenario 2:
  - Arrange four windows in a tree, then float one of them.
  - Select the floated window, then one of the tiled windows.
  - Close the tiled window with Super-Q.

**Expected behavior:** The active hint should always surround the active window, even if the active window is floated.

**Other Notes:**
- Video demonstrating both scenarios: https://www.dropbox.com/s/eyjx08s6b9zhpcu/active-hint-issue.webm?dl=0

**Comment by jmmaranan** [comment]
@jacobgkau - can this be closed? Implemented in #503
