### ISSUE TITLE
Authentication required to remove software not going away

### ISSUE THREAD

**Issue by Nicefisher** [pop-os/shell#494]
Pop OS 20.04
pop-shell:
  Installed: 0.1.0~1597190322~20.04~149061a
  Candidate: 0.1.0~1597190322~20.04~149061a
  Version table:
 *** 0.1.0~1597190322~20.04~149061a 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

When my laptop turned off, I pressed 2 keys on the keyboard to turn it back on and when I did the authentication required to remove software window popped up in my top left corner

Happened when i turned computer off and pressed 2 keyboard keys to turn it back on

The box was never supposed to show up as i wasnt removing software

this has happened before and the only thing i could do to make it go away was restart the system

Thinkpad T430s

**Comment by jacobgkau** [comment]
@Nicefisher Is there a reason you believe this is related to pop-shell, the window tiling extension, or should this issue have been placed on the catch-all Pop repository instead? https://github.com/pop-os/pop/issues 

Does the issue still occur if you open the Extensions app (green icon) and disable the Pop Shell extension?

What are the "2 keyboard keys" you are pressing to power on your computer? Is your computer actually turning off, or is it suspending?

Can you please provide a screenshot of the pop-up you are seeing, as well as the complete output of these terminal commands:
```
sudo apt update
sudo apt full-upgrade
flatpak update
```

**Comment by Nicefisher** [comment]
I meant to post in the catch all issues instead of the extension, I'll post it there instead, thanks for telling me.
https://github.com/pop-os/pop/issues/1186
