### ISSUE TITLE
Account for the GNOME shell top panel when tiling windows

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/shell#5]

**Comment by AAnzel** [comment]
I don't know how this is going to be implemented, but You should be cautious of various Gnome Extensions which purpose is to hide top panel, replace it with various docks or change its position (e.g. [hide](https://extensions.gnome.org/extension/545/hide-top-bar/), ...).

**Comment by mmstick** [comment]
The goal isn't to hide or replace it.

**Comment by cassidyjames** [comment]
I think @AAnzel is saying you should ensure your tiling accounts for those extensions. It should be easy enough to just use the display's struts instead of caring about the size of the panel specifically.

**Comment by mmstick** [comment]
The shell's already taking care of this automatically when snapping windows to the display, so I don't think there's anything for us to do here.

**Comment by AAnzel** [comment]
Yes @cassidyjames, that's exactly what I had in mind.
@mmstick great! Just wanted to give a heads-up. Keep up the good work!
