### ISSUE TITLE
Windows jumping to wrong monitor

### ISSUE THREAD

**Issue by leviport** [pop-os/shell#50]
When I'm starting with both monitors completely empty with tiling mode enabled, I can open one terminal window and it opens fullscreen as expected. However the next one I open pushes the new window and the one that was already open to my other monitor. 

![animation](https://user-images.githubusercontent.com/13512097/75924129-a139af80-5e23-11ea-9de9-2a826dbdd9bd.gif)
This gif was taken across two 1080p monitors. Having Peek any larger interfered with the bug I was seeing, so I had to make it a bit smaller. Hopefully it's still clear, but basically I opened a terminal on the right monitor, and opening one one more pushed both of them over to the left monitor.

**Comment by leviport** [comment]
The same thing seems to also be causing https://github.com/pop-os/shell/issues/61

**Comment by nathanielsystem76** [comment]
I can create a separate bug report if need be, but this seemed related. Dragging a window to snap it to the left or right side of the screen causes other windows/tiles to reshuffle. Sometimes causing a full-screen app on one monitor to jump to the other monitor and resize to a much smaller tile.

**Comment by leviport** [comment]
It sounds related, thank you for the report. Can you share your pop-shell settings when you see that happen? A screenshot of the dropdown menu would work. Also be sure you're pulling frequently and are running the most recent version.

**Comment by mmstick** [comment]
Can you verify if this is fixed?

**Comment by nathanielsystem76** [comment]
It is still appearing/has gotten worse. I just did another "git pull" and ./rebuild.sh
![Screenshot from 2020-03-12 15-50-31](https://user-images.githubusercontent.com/55410594/76569816-aa58fb00-6479-11ea-9942-4886bb1fa814.png)
![Screenshot from 2020-03-12 15-48-09](https://user-images.githubusercontent.com/55410594/76569818-aaf19180-6479-11ea-97e9-a0fc2b2ae1a0.png)

**Comment by nathanielsystem76** [comment]
Here's the terminal output as the issue is happening.
![Screenshot from 2020-03-12 16-00-34](https://user-images.githubusercontent.com/55410594/76570309-b1ccd400-647a-11ea-9973-c149f705723d.png)

**Comment by leviport** [comment]
It appears to be fixed on my setup, but I'll let @nathanielsystem76 confirm as well before I close this.

**Comment by storyaddict** [comment]
Working properly on my end as well after most recent update! Thanks all. :)
