### ISSUE TITLE
Pop Shell feedback

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/shell#505]
Not a problem but a suggestion for a future version of Pop!_OS.

I like the auto-tiling for the most part. Some windows don't play well but I can usually manually get them where I want.

It would be nice to have some method to tile windows into quadrants. As of right now, it seems that auto-tiling tries to put windows next to each other in a single row of columns. But this also depends on the screen size and ratio.

A lot of times, however, it would be nice to simply make an arbitrary arrangement. For example, having four windows parked in the monitor corners, or one/two windows in one row and several smaller windows in a second row.

I guess the easiest way to explain it is like GUI development, where you have basic VBOX and HBOX layouts and a more "granular" GRID layout.

I don't know how that works for window management; I know it can be difficult to figure it out for a single application.

But, just a suggestion. Otherwise, I'm very impressed with what you are accomplishing with Pop!_OS.

Thanks,
Cody

**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**Issue/Bug Description:**

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by mmstick** [comment]
Already supported, since every node is branch with either horizontal or vertical orientation. Toggling orientation of a node will get whatever layout you need.
