### ISSUE TITLE
Wayland-specific issues

### ISSUE THREAD

**Issue by mmstick** [pop-os/shell#510]
- In Wayland, some windows do not return to the proper position when un-maximizing with the keyboard. If I enter adjustment mode (Super+Enter), the adjustment overlay starts off where the window was supposed to be; if I resize other windows, that also makes the affected window return to its proper position. This only happens when tiling is enabled.
- When moving focus with the keyboard, the mouse cursor stays still in Wayland (where in Xorg, it moves to the top-left corner of the selected window.)

**Comment by jawadalkassim** [comment]
Telegram Desktop seems not working well when opening as the third application in tiling mode

**Comment by mmstick** [comment]
@jawadalkassim What is it doing that makes you say that?

**Comment by jawadalkassim** [comment]
![Screenshot from 2020-09-11 10-52-28](https://user-images.githubusercontent.com/48631694/92887317-0f87ac00-f41d-11ea-871b-943deb5f6cc7.png)

![Screenshot from 2020-09-11 10-52-39](https://user-images.githubusercontent.com/48631694/92887371-1a424100-f41d-11ea-8539-f8b72241bc65.png)

**Comment by jawadalkassim** [comment]
![Screenshot from 2020-09-11 10-59-38](https://user-images.githubusercontent.com/48631694/92888556-1a8f0c00-f41e-11ea-9c54-4d78ce4b6a61.png)

![Screenshot from 2020-09-11 10-59-26](https://user-images.githubusercontent.com/48631694/92888643-2d094580-f41e-11ea-86b5-16682c960bdc.png)

with different gaps size

**Comment by mmstick** [comment]
Duplicate of #85
