### ISSUE TITLE
Can't remove the tiling windows manager icon

### ISSUE THREAD

**Issue by MightyPrince1** [pop-os/shell#514]
**Distribution (run `cat /etc/os-release`):**
 Pop OS 20.04(most recent)
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**Issue/Bug Description:**

I don't use a tiling window manager and I find the unnecessary icon rather annoying.
How can I remove it properly?

**Steps to reproduce (if you know):**

**Expected behavior:**

No unnecessary icon

**Other Notes:**

thanks in advance

**Comment by WatchMkr** [comment]
Open the Extensions app and un-toggle the Pop Shell extension to remove the icon.

**Comment by MightyPrince1** [comment]
that's the thing

it's still there

**Comment by WatchMkr** [comment]
Perhaps you're disabling via the panel (which only turns on and off tiling). To disable the icon and feature entirely, use the "Extensions" application. See screenshot. Does this work for you?
![Screenshot from 2020-08-27 07-51-16](https://user-images.githubusercontent.com/3430283/91451212-6ea0ca80-e83a-11ea-853b-f9da2c49099b.png)
