### ISSUE TITLE
tag releases

### ISSUE THREAD

**Issue by carlwgeorge** [pop-os/shell#516]
**Distribution (run `cat /etc/os-release`):**

```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 0.1.0~1598032836~20.04~8416328
  Candidate: 0.1.0~1598032836~20.04~8416328
  Version table:
 *** 0.1.0~1598032836~20.04~8416328 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

There are no tags in this repository.  I would like to be able to correlate the package version (currently `0.1.0~1598032836~20.04~8416328`) with a git tag.

**Steps to reproduce (if you know):**

1. Navigate to https://github.com/pop-os/shell/tags.
2. Observe lack of tags.

**Expected behavior:**

Tags in this repository that indicate which commit each pop-shell package was built from.

**Other Notes:**

**Comment by mmstick** [comment]
`8416328` is the git commit that the package was built from

**Comment by carlwgeorge** [comment]
So the package is updated with every commit?  Is the `0.1.0` part of the version number ever incremented?  Which commit was the original version `0.1.0`?

**Comment by mmstick** [comment]
All repositories in the pop-os organization are built automatically by a CI that builds every commit on master into a debian package. When a PR is merged onto the master branch, it is immediately released.

**Comment by mmstick** [comment]
I'll be tagging a 1.0.0 release soon, given that we've been shipping pop-shell for 6 months now.

**Comment by mmstick** [comment]
Now tagged with a release

**Comment by carlwgeorge** [comment]
Thanks a bunch @mmstick, tagging releases will help Fedora and other distributions maintain packages for this.
