### ISSUE TITLE
Fork balancing sometimes makes Super+O reorient windows strangely

### ISSUE THREAD

**Issue by leviport** [pop-os/shell#52]
If I open a bunch of tiled windows and close a bunch on one side of the fork, I can make a whole bunch on one side of the fork reorient with the single window on the other side of the fork when I hit <kbd>Super</kbd> + <kbd>O</kbd>. Is this they way it's supposed to work, or should forks rebalance themselves so not so many windows change with an orientation change? 

![animation](https://user-images.githubusercontent.com/13512097/75932124-e239c000-5e33-11ea-98e2-7b6f233d3b6d.gif)

**Comment by mmstick** [comment]
I can have it recalculate the orientations

**Comment by mmstick** [comment]
Try out the new behavior in 336eca4

**Comment by leviport** [comment]
Oh yeah I think that's much better. Nice!
