### ISSUE TITLE
Readme: Mention that rebuild.sh restarts Gnome Shell

### ISSUE THREAD

**Issue by Henry78** [pop-os/shell#520]
Pls add a warning to the installation section of the Readme about rebuild.sh restarting the Shell (and disabling extensions?)

**Comment by jmmaranan** [comment]
@Henry78 - the restart notice is now mentioned in the section of https://github.com/pop-os/shell/blob/master_focal/README.md#developers.

The new commands are `make local-install` and `make debug` for source install and local development workflows.
