### ISSUE TITLE
Opening application start with hidden window

### ISSUE THREAD

**Issue by waynevanson** [pop-os/shell#536]
**(1) Issue/Bug Description:**
When I open my terminal `alacritty`, the window is invisible.

**(2) Steps to reproduce (if you know):**
Open `alacritty`  using any method.

The error does not occur when once window is open .

**(3) Expected behavior:**
Opening the terminal emulator `alacritty` appears visible.

**(4) Distribution (run `cat /etc/os-release`):**
 ```
NAME="void"
ID="void"
DISTRIB_ID="void"
PRETTY_NAME="void"
```

xuname
```
Void 5.8.7_1 x86_64 GenuineIntel uptodate rrFFF
```

**(5) Gnome Shell version:**
3.34.1

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

N/A, not using pop-os.

**(7) Where was Pop Shell installed from:**
 
N/A

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1920 x 1080 single display

**(9) Other Installed/Enabled Extensions:**
Defaults

**(10) Other Notes:**

It becomes visible once I minimize it and then alt-tab back to it.

This behavior is consistent upon every launch.

The space for the window is made in tile mode and the application is focused, but nothing can be seen.

**Comment by mmstick** [comment]
Cannot replicate on Pop!_OS
