### ISSUE TITLE
[Feature Request] Option to mark windows to automatically open in float mode

### ISSUE THREAD

**Issue by ycooreman** [pop-os/shell#552]
This would allow for modal-style windows, such as settings windows, to open in float mode
This is similar to what you can do in i3 etc.

**Comment by jmmaranan** [comment]
@ycooreman - this is already implemented when #254 was fixed. There is file `$HOME/.config/pop-shell/config.json` where you can add the following structure:
```
{
  class: "<WM_CLASS String from xprop>",
  title: "<Optional Window Title>"
}
```
For example, doing `xprop` on GNOME Settings (or GNOME Control Center)'s WM_CLASS is `gnome-control-center` and `Gnome-control-center`. Use the second value, which pop-shell will read. 

After applying changes in the config.json, you can reload the tiling if it doesnt work the first time.

**Comment by jmmaranan** [comment]
@mmstick - where would be the best place to document this? :)

**Comment by MagnusOffermanns** [comment]
How can I identify the VM_Vlass String if running on wayland on PopOS 24? In this case propx seems to not work for me.
