### ISSUE TITLE
Super-Down to switch window focus does not work on Ubuntu By Default

### ISSUE THREAD

**Issue by JonParton** [pop-os/shell#556]
**(1) Issue/Bug Description:**

When installing on Ubuntu 20.04 the `Super-Down` key does not work with Pop-Shell by default. It is still bound to `Restore Window` and so if you try to switch the focus down to a window lower in a vertical stack using `Super-Down` it does nothing.

This can be fixed by disabling the  `Restore Window` shortcut in the Ubunutu Keyboard Shortcuts settings but it seems to me this should be done as part of the Keybaord Shortcut remapping that the installation through Make does? 

**(2) Steps to reproduce (if you know):**

Install using Make --> Have a Vertical Stack in Auto Tile Mode --> Try to switch to the lower window from the top one using `Super-Down`. 

**(3) Expected behavior:**

`Super-Down` should switch focus to the lower window and this should work right from installation without having to manually tweak keyboard shortcuts.

Alternatively, this should be mentioned in the Project Readme as a known thing to work around when talking about the direction keys on Ubuntu. 

**(4) Distribution (run `cat /etc/os-release`):**

 ```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**(5) Gnome Shell version:**

3.36.3

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

Commit: 
e5a80ea39a4f0217989cb681eecd182ddc9a7c5d

**(7) Where was Pop Shell installed from:**

This repository using Make

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

2 Monitors
- Primary Laptop (Horizontal) - 1920x1200
- Secondary (Horizontal) - 3840x2160

**(9) Other Installed/Enabled Extensions:**

![image](https://user-images.githubusercontent.com/15039843/93748681-904e6100-fbf0-11ea-88c1-8e5f853d7151.png)

**(10) Other Notes:**

Thank you for all the effort in creating this project and making it open to other Distro's! It's awesome! :smiley:

**Comment by jmmaranan** [comment]
Hi @JonParton - right now, gnome-shell seems to prioritize any shortcut changes written via `dconf` over the GJS Window Manager API. The `<Super>Down to focus` is via the WM API. 

I think a future work to handle enable/restore shortcuts would be a feature. Either we send a command to dconf directly. And anything that is NOT commonly used by any distro would be GJS WM API shortcuts.

**Comment by mmstick** [comment]
If you're not using Pop, you have to make sure you've overridden default GNOME shortcuts.
