### ISSUE TITLE
Window resizing works only for one window 

### ISSUE THREAD

**Issue by Chrysostomus** [pop-os/shell#56]
In autotiling mode, when resizing a window with mouse, windows behave differently from each other. One of the windows behaves as expected: when you resize it, the neighboring windows are also resized to match it. However, all other windows simply snap back into their original size and refuse to be resized.

It would be preferable if all the windows behaved like this parent window.

**Comment by mmstick** [comment]
When windows go back to their original size, it's because a window failed to resize, and all operations are undone.

**Comment by Chrysostomus** [comment]
Yes, that is exactly what happens. Only one window manages to be resized
.

**Comment by mmstick** [comment]
Is this still an issue?

**Comment by Chrysostomus** [comment]
Testing within 3 hours

**Comment by Chrysostomus** [comment]
Issue has been resolved.
