### ISSUE TITLE
Ubuntu's default dock breaks down when using auto-hide

### ISSUE THREAD

**Issue by RickDW** [pop-os/shell#567]
There's couple of issues, I'll give a short description of my setup first, to make things clear. I've got two monitors positioned side by side. My dock is set up to be on the left side of both monitors, and I like to keep it hidden unless I need it. 

First of all, when auto-hide is off, everything works fine. Whenever auto-hide is on, the dock pops up when the mouse is at the border between the monitors, but then it goes right back into hiding while it should stay visible to be used. The second problem is connected to this: although the dock acts like it's playing whack-a-mole the mouse is still blocked from crossing the boundary onto the next monitor. After trying about a dozen times repeatedly it will sometimes allow the mouse to move across. Behaviour seems a lot better when the there is one big window on the monitor you're trying to move away from, *and* it is focused. 

The dock that is on my left monitor (so it's not on a boundary between monitors) does not have any of these issues, and works as expected.

**Distribution (run `cat /etc/os-release`):**
 NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**(5) Gnome Shell version:**
GNOME Shell 3.36.4

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
017c92e04f4eefead2561fa35559891eb83388c9

**(7) Where was Pop Shell installed from:**
From github using the provided instructions for installation. 

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
2x 1080p, side by side.

**Comment by jmmaranan** [comment]
Does it work when PopShell is disabled?

**Comment by RickDW** [comment]
I can check, but I'm not sure how to disable the extension without uninstalling it completely.

**Comment by jmmaranan** [comment]
If you don't mind checking when it is uninstalled.

**Comment by RickDW** [comment]
I just did and it works fine. It does block the cursor for a small while when trying to cross the boundary, but that is its intended behaviour. The dock also stays visible like it should.

**Comment by RickDW** [comment]
I reinstalled it and for some reason the problem disappeared. I'm not sure what's different compared to before though

**Comment by RickDW** [comment]
The problem seems to be toggling 'auto-hide the dock' in system settings. I just toggled it off and on and the problem is back.

**Comment by RickDW** [comment]
Sorry for the confusion, the problem doesn't seem to be toggling the setting. I reinstalled pop shell and didn't touch the switch, but it still only works when the window on the current monitor is active, like I described originally.

**Comment by RickDW** [comment]
I found a more specific reason it doesn't work: whenever the focused window is directly next to the border between monitors that you are trying to cross, it blocks the cursor. It only does this on this focused window's border, i.e. when the focused window occupies the top half of the second monitor and there's another window occupying the bottom half, the cursor only gets blocked when it tries to cross in the top half of the screen.

**Comment by mmstick** [comment]
This is their problem. Already discussed in prior issue. #402
