### ISSUE TITLE
Pop-shell interferes with move-to-workspace-below if bound to super+s 

### ISSUE THREAD

**Issue by rodrigo-pedro** [pop-os/shell#571]
**(1) Issue/Bug Description:**
I bound move to workspace below to super+s. Works fine until I enable pop-shell, which instead of doing the intended behaviour of moving to the below workspace, it shows a yellow title bar on the active window, even though no keybind is set to super+s other than move-to-workspace-below. 
Disabling the pop-shell does not fix the issue, only if I disable the extension in the extensions app or I uninstall it.

**(2) Steps to reproduce (if you know):**
Bind move-to-workspace-below to super+s. Test the keybind. Enable pop-shell. Try to change workspaces with the keybind (problem might not appear immediately). Super+s stops moving workspaces and instead shows a title bar.

**(3) Expected behavior:**
Move to workspace below bound to super+s to work fine with pop-shell installed/enabled in extensions.

**(4) Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**
3.36.3 on X11

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```pop-shell:
  Installed: 0.1.0~1601072739~20.04~9286532
  Candidate: 0.1.0~1601072739~20.04~9286532
  Version table:
 *** 0.1.0~1601072739~20.04~9286532 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**
Came with PopOS.

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1080p laptop

**(9) Other Installed/Enabled Extensions:**
Default extensions and Caffeine.

**Comment by mmstick** [comment]
That's the stacking feature

**Comment by rodrigo-pedro** [comment]
Yes but how do i change that keybind? It's not in the shortcut settings or the pop shell's shortcut menu.

**Comment by jmmaranan** [comment]
Hi @rodrigo-pedro, you can enable or install pop-shell first. And then _override it_ by going to the Keyboard shortcuts and adding Super+S. The default is CTRL + ALT + Down or CTRL + ALT + J for moving to workspace below.
