### ISSUE TITLE
rebuild.sh, bad UX when finished building

### ISSUE THREAD

**Issue by GaryBer** [pop-os/shell#576]
**(1) Issue/Bug Description:**
![image](https://user-images.githubusercontent.com/34002641/94516239-fd628780-01ea-11eb-9110-09343fdc0d43.png)

**(2) Steps to reproduce (if you know):**
Run `./rebuild.sh`

**(3) Expected behavior:**
You should show some sort of `Finished building. Press CTRL+C to exit or wait for 'make listen'.` message. Even though this mode is meant for development purposes. It is an installation method for some of us.

**(4) Distribution (run `cat /etc/os-release`):**
 

**(5) Gnome Shell version:**

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**(7) Where was Pop Shell installed from:**

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**
Duplicate of: https://github.com/pop-os/shell/issues/529

**Comment by jmmaranan** [comment]
Hi @GaryBer - this has been addressed, please use `make local-install` for compiling from `master_focal`
