### ISSUE TITLE
clearer way to distinguish that a window is highlighted in `Window Management Mode`

### ISSUE THREAD

**Issue by GaryBer** [pop-os/shell#577]
**(1) Issue/Bug Description:**
![image](https://user-images.githubusercontent.com/34002641/94520255-909ebb80-01f1-11eb-8f5e-e885053ef23d.png)

**(2) Steps to reproduce (if you know):**
Press `SUPER+Return` on a window then walk away from the PC for a few minutes, maybe make a phone call then come back and accidentally resort your windows by trying to scroll down a web page using the arrow keys or something.

**(3) Expected behavior:**
A clearer way to distinguish that a window is highlighted using `SUPER+Return` in "Window Management Mode
". Maybe make the `border dashed`. Still keep the existing color overlay idea.

**(4) Distribution (run `cat /etc/os-release`):**
 

**(5) Gnome Shell version:**

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**(7) Where was Pop Shell installed from:**

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

**Comment by leviport** [comment]
If your screenshot shows window management mode, I think you're seeing a bug. This is what window management mode should look like:
![Screenshot from 2020-09-29 07-55-23](https://user-images.githubusercontent.com/13512097/94568226-797bc000-0229-11eb-8dc4-2f1143c8dcb0.png)

The selected window has a transparent blue overlay across it to make it obvious that you're in window management mode.

Are you running Pop!_OS 20.04, or did you build pop-shell for a different distribution?

**Comment by GaryBer** [comment]
I am running this on Ubuntu 20.04, with the current master branch. Your screenshot is allot more obvious compared to mine.

**Comment by mmstick** [comment]
Is it fixed by installing and using the Pop Theme, or Adwaita?

**Comment by GaryBer** [comment]
Screenshots in Window Management Mode.

Adwaita:
![image](https://user-images.githubusercontent.com/34002641/94579921-ec436600-023e-11eb-9ad8-16f4335b9453.png)


Adwaita - Dark:
![image](https://user-images.githubusercontent.com/34002641/94579772-ccac3d80-023e-11eb-9789-11b980f631f1.png)

Pop:
![image](https://user-images.githubusercontent.com/34002641/94580581-b5ba1b00-023f-11eb-8b8d-2cdcb98bc507.png)

Pop Dark:
![image](https://user-images.githubusercontent.com/34002641/94580628-c1a5dd00-023f-11eb-81ff-cef73ea1c6c9.png)

Different themes do not seem to fix the problem.

**Comment by jmmaranan** [comment]
I thought the current chrome overlay CSS is coming from GNOME shell. Since what looks like St.Bin, we can add an override so it would not be affected by theme changes

**Comment by jmmaranan** [comment]
@GaryBer how does it look like when you try to Edge tile the windows by dragging left or right near the monitors edge look like? Please post a screenshot pop shell enabled and disabled.

**Comment by GaryBer** [comment]
The edge tiling highlight looks the same color and opacity as pop shell

![image](https://user-images.githubusercontent.com/34002641/94767672-bacbb700-0372-11eb-8484-b47687c248e2.png)

**Comment by GaryBer** [comment]
I would add an overwrite option and use a color picker just like on the `Active Hint Color` GUI option.

**Comment by jmmaranan** [comment]
@mmstick - we would probably need UX to decide if the `tile-preview` overlay needs to be color customizable like the `hint` implementation. Perhaps also include the stacking top bar colors.

**Comment by mmstick** [comment]
Why not have a single accent color that's applied to the hint and tabs?
