### ISSUE TITLE
Windows rearrange themselves in tiling mode after latest pop-shell update

### ISSUE THREAD

**Issue by deadlysyn** [pop-os/shell#578]
**Distribution (run `cat /etc/os-release`):**
 
```console
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
``` 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```console
pop-shell:
  Installed: 0.1.0~1601072739~20.04~9286532
  Candidate: 0.1.0~1601072739~20.04~9286532
  Version table:
 *** 0.1.0~1601072739~20.04~9286532 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

I usually have a couple desktops going w/ a few windows tiled on each. When I first enabled tiling, once my windows were positioned they would maintain their location within a session. After the latest pop-shell update (note I am guessing this ties in somehow since that's the only related package that's updated since behavior changed), any time my screen locks/sleeps windows get re-arranged. It seems to only affect electron apps (vscode and slack), but happens across desktops.

**Steps to reproduce (if you know):**

There may be other ways, here's one I just tried:

Turn on tiling, open a couple few (browser, terminal, vscode or slack). Arrange vscode or slack so they are full-length on the right and browser/terminal split on the left. super-escape to sleep display, unlock, window arrangement is changed so vscode flips to left-bottom.

**Expected behavior:**

Window position is maintained.

**Other Notes:**

I'm still new to PopOS. Could this be some mangled state sitting around somewhere?

Need to disable all extensions and reboot to eliminate some variables...if that changes anything I'll update.

**Comment by jacobgkau** [comment]
Confirmed with Visual Studio Code, but I'm also seeing the issue with only built-in apps. Locking the screen and unlocking seems to be disabling and re-enabling tiling-- stacks are un-stacked when this happens.

I'm getting `[INFO] disable` and `[INFO] enable` in the logs when locking/unlocking the screen, whether tiling is enabled or not, which sounds like the entire extension is being disabled/enabled.

**Comment by mmstick** [comment]
Yes, it does this, and we should be ignoring it as before
