### ISSUE TITLE
Restore issue after lock screen: Schema org.gnome.shell.extensions.pop-shell could not be found for extension pop-shell

### ISSUE THREAD

**Issue by dhiller** [pop-os/shell#600]
**(1) Issue/Bug Description:**

I had a Google Chrome window open with about a dozen tabs open (besides a lot of other windows) on the left monitor.

When unlocking the session after having locked it the Google Chrome window didn't seem to get restored to its original state somehow (at least that's how it looks). I.e. Google Chrome appeared aligned to to top left, while it's activation border appeared in the center of the window. Also the application once was not usable any more, it didn't respond to any mouse or keyboard input.

Unfortunately no screenshots for this :(

**(2) Steps to reproduce (if you know):**

Lock - unlock - see Google Chrome freezing / being awkward

**(3) Expected behavior:**

**(4) Distribution (run `cat /etc/os-release`):**
NAME=Fedora
VERSION="32 (Workstation Edition)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation

**(5) Gnome Shell version:**

3.36.6

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

master_focal branch via GitHub commit id ff702bcceb20e6eb70c9cc5559252f929b8cb30c

**(7) Where was Pop Shell installed from:**

see above (via rebuild.sh)

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

Thinkpad T480S with dual external monitor setup (not using the Laptop screen, Thunderbolt Dock) 2*WXGA

xrandr:

DP-1-1 connected 2560x1440+0+0 (normal left inverted right x axis y axis) 527mm x 296mm                   
   2560x1440     59.95*+         
...
DP-1-2 connected primary 2560x1440+2560+0 (normal left inverted right x axis y axis) 621mm x 341mm        
   3840x2160     60.00 +  60.00    50.00    59.94    30.00    25.00    24.00    29.97    23.98    29.97 
   2560x1440     59.95* 
...

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

Some possibly related journalctl output:

https://gist.github.com/dhiller/d19bd0d6fc588f4b56214a526a73d2a3

**Comment by mmstick** [comment]
This issue was fixed about a week ago, since https://github.com/pop-os/shell/commit/b9f8d96e60b530abb0883f47d229e661e6ffbba2

**Comment by dhiller** [comment]
@mmstick thanks for the heads up, I didn't see it in the issue list. So it is advised to use master_focal branch for users running it from GitHub repo?

/close

**Comment by dhiller** [comment]
Hm, strange. I think I encountered a different issue because I was actually running from `master_focal` branch with said commit (checked out yesterday morning). So I think there must be something else going on. Will retry at the weekend when I have more time. Reopening this as I think the fix you mentioned does not apply.

**Comment by dhiller** [comment]
/close

Could verify that it works as expected with the latest version a11d3c34db01987bb716b8b127b2b889130a4fc1 yesterday.
