### ISSUE TITLE
Window stacks fall apart when locking screen.

### ISSUE THREAD

**Issue by camtauxe** [pop-os/shell#605]
**(1) Issue/Bug Description:**
If the stacking feature (`Super+S`) is used to create a stack and then the screen is locked, when logging back in the stack will be gone and the windows in it laid out next to each other.

**(2) Steps to reproduce (if you know):**

1. Enable stacking on a window (`Super+S`)
2. Move another window into the stack
3. Lock the screen (`Super+Esc`) or let it lock automatically due to inactivity.
4. Enter password to log back in
5. The windows in the stack will be next to each other and the stack is gone.

**(3) Expected behavior:**
The window stack will be as it was before locking.

**(4) Distribution (run `cat /etc/os-release`):**
Pop!_OS 20.04 LTS
 

**(5) Gnome Shell version:**
GNOME Shell 3.36.4

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```
pop-shell:
  Installed: 0.1.0~1601935511~20.04~0fce7eb
  Candidate: 0.1.0~1601935511~20.04~0fce7eb
  Version table:
 *** 0.1.0~1601935511~20.04~0fce7eb 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

```

**(7) Where was Pop Shell installed from:**
Updated through the Pop!_Shop

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
2x 1440p Monitors (both horizontal, left-most one is primary)

**(9) Other Installed/Enabled Extensions:**

- Mpris Indicator Button
- Sound Input & Output Device Chooser
- Transparent Topbar
- Pomodoro

**(10) Other Notes:**
N/A

**Comment by mmstick** [comment]
When did you last restart since installing that commit? This was fixed last week

**Comment by camtauxe** [comment]
Incredible, that's all it needed. Thank you.

**Comment by zeeshansayyed** [comment]
@mmstick 
I am trying the most recent version from Github and I still seem to have this issue in a dual monitor setup. After the screen locks up, all the windows seem to move from the secondary desktop to the primary desktop. I am using Ubuntu (hence gnome) and have workspaces enabled only on the primary desktop. Should I open another issue for this?
