### ISSUE TITLE
Arch Gnome 3.36 auto_tiler error

### ISSUE THREAD

**Issue by charafau** [pop-os/shell#62]
Hi! Thank you for your work on this extension, I was trying to install it on arch with gnome 3.36 but unfortunetly it cannot load `auto_tiler`, maybe some change in gnome but google doesn't say anything.

Compiled with `sh rebuild.sh` script

Compilation output:
```
➜  shell (master_focal) ✔ make
UUID is "pop-shell@system76.com"
if ! command -v tsc >/dev/null; then \
	echo 'You must install TypeScript >= 3.8 to transpile: (node-typescript on Debian systems)'; \
	exit 1; \
fi
tsc
for file in target/*.js; do \
	sed -i \
		-e 's#export function#function#g' \
		-e 's#export var#var#g' \
		-e 's#export const#var#g' \
		-e 's#Object.defineProperty(exports, "__esModule", { value: true });#var exports = {};#g' \
		"${file}"; \
	sed -i -E 's/export class (\w+)/var \1 = class \1/g' "${file}"; \
	sed -i -E "s/import \* as (\w+) from '(\w+)'/const \1 = Me.imports.\2/g" "${file}"; \
done
rm -rf _build
mkdir -p _build
cp -r metadata.json schemas target/*.js imports/*.js stylesheet.css _build
➜  shell (master_focal) ✔ make install
UUID is "pop-shell@system76.com"
rm -rf /home/charafau/.local/share/gnome-shell/extensions/pop-shell@system76.com
mkdir -p /home/charafau/.local/share/gnome-shell/extensions/pop-shell@system76.com
cp -r _build/* /home/charafau/.local/share/gnome-shell/extensions/pop-shell@system76.com/
➜  shell (master_focal) ✔ 

```

Logs:
```
JS ERROR: Extension pop-shell@system76.com: ImportError: No JS module 'auto_tiler' found in search path
@/home/charafau/.local/share/gnome-shell/extensions/pop-shell@system76.com/panel_settings.js:8:23
@/home/charafau/.local/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:9:23
_callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:374:13
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:308:27
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:536:18
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:515:19
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:545:18
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:576:18
init@resource:///org/gnome/shell/ui/extensionSystem.js:54:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:244:22
start@resource:///org/gnome/shell/ui/main.js:138:5
@<main>:1:47

```

**Comment by vhdirk** [comment]
Same in Debian Bullseye

**Comment by senaki** [comment]
I get rid of this issue by replacing in $HOME/.local/share/gnome-shell/extension/system76.../panel_settings.js 

const { AutoTiler} = Me.imports.auto_tiler 

by : const {AutoTiler } = Me.import.forest 


Forest is the default module after a refactoring according recent commits

**Comment by senaki** [comment]
> Hi! Thank you for your work on this extension, I was trying to install it on arch with gnome 3.36 but unfortunetly it cannot load `auto_tiler`, maybe some change in gnome but google doesn't say anything.
> 
> Compiled with `sh rebuild.sh` script
> 
> Compilation output:
> 
> ```
> ➜  shell (master_focal) ✔ make
> UUID is "pop-shell@system76.com"
> if ! command -v tsc >/dev/null; then \
> 	echo 'You must install TypeScript >= 3.8 to transpile: (node-typescript on Debian systems)'; \
> 	exit 1; \
> fi
> tsc
> for file in target/*.js; do \
> 	sed -i \
> 		-e 's#export function#function#g' \
> 		-e 's#export var#var#g' \
> 		-e 's#export const#var#g' \
> 		-e 's#Object.defineProperty(exports, "__esModule", { value: true });#var exports = {};#g' \
> 		"${file}"; \
> 	sed -i -E 's/export class (\w+)/var \1 = class \1/g' "${file}"; \
> 	sed -i -E "s/import \* as (\w+) from '(\w+)'/const \1 = Me.imports.\2/g" "${file}"; \
> done
> rm -rf _build
> mkdir -p _build
> cp -r metadata.json schemas target/*.js imports/*.js stylesheet.css _build
> ➜  shell (master_focal) ✔ make install
> UUID is "pop-shell@system76.com"
> rm -rf /home/charafau/.local/share/gnome-shell/extensions/pop-shell@system76.com
> mkdir -p /home/charafau/.local/share/gnome-shell/extensions/pop-shell@system76.com
> cp -r _build/* /home/charafau/.local/share/gnome-shell/extensions/pop-shell@system76.com/
> ➜  shell (master_focal) ✔ 
> ```
> 
> Logs:
> 
> ```
> JS ERROR: Extension pop-shell@system76.com: ImportError: No JS module 'auto_tiler' found in search path
> @/home/charafau/.local/share/gnome-shell/extensions/pop-shell@system76.com/panel_settings.js:8:23
> @/home/charafau/.local/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:9:23
> _callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:374:13
> loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:308:27
> _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:536:18
> collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
> _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:515:19
> _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:545:18
> _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:576:18
> init@resource:///org/gnome/shell/ui/extensionSystem.js:54:14
> _initializeUI@resource:///org/gnome/shell/ui/main.js:244:22
> start@resource:///org/gnome/shell/ui/main.js:138:5
> @<main>:1:47
> ```

I get rid of this issue by replacing in $HOME/.local/share/gnome-shell/extension/system76.../panel_settings.js

const { AutoTiler} = Me.imports.auto_tiler

by : const {AutoTiler } = Me.import.forest

Forest is the default module after a refactoring according recent commits.

You need to restart GNOME to apply the change.
A permanent fix is to make the above modification into the source file src/panel_settings.ts

**Comment by underdoeg** [comment]
Yes, that works for me too

**Comment by mmstick** [comment]
Thanks for reporting. I'm surprised that I missed this yesterday
