### ISSUE TITLE
[FEATURE PROPOSAL] Window Adjustment mode move speed.

### ISSUE THREAD

**Issue by JacobMillner** [pop-os/shell#621]
Would it be possible to add a feature to the Window Adjustment mode to change the move speed of the windows? On 4k resolution it takes smaller windows a decent amount of time to travel from one corner of the screen to the other.

**Comment by maria-komarova** [comment]
@JacobMillner would you be able to provide a screencast to better see the issue with the speed?

**Comment by JacobMillner** [comment]
@maria-komarova I took a quick gif of what I mean. I'm specifically talking about the speed at which the window's shadow or new position moves. It would be nice if we could hold down a key like shift + arrow to allow it to move faster. ![window-speed](https://media3.giphy.com/media/IZY4WFXBzCx5hje1GP/giphy.gif)
