### ISSUE TITLE
Mockups for the floating window exceptions feature

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/shell#622]
This is a feature to help improve auto-tiling experience by having a list of exceptions to always open in floating mode. 

Because we can only rely on application class and title, and because users generally feel the need to add an application or a window to the exceptions when they encounter it, it seems the best way would be to enable people adding an exception by selecting an open window on the current workspace. 
Selecting "Floating Window Exceptions" in the tiling menu would open a window that lists both personal user exceptions and system defaults that are updated as we get more user reports and validate them. 
![extension-menu-1](https://user-images.githubusercontent.com/57502897/95624463-262d1d00-0a34-11eb-8065-a9e84bbc7f57.png)
![floating-exceptions-1](https://user-images.githubusercontent.com/57502897/95624447-20cfd280-0a34-11eb-867b-8283dde72d66.png)
![floating exceptions-2](https://user-images.githubusercontent.com/57502897/95624455-23322c80-0a34-11eb-8e55-4900d8bc943f.png)

Selection mode is similar to the window preview in GNOME Shell Overview: 
![floating-selection-mode](https://user-images.githubusercontent.com/57502897/95624468-288f7700-0a34-11eb-9ba3-fa199088f619.png)

System dialog that shows after a user clicks on the window offers an option to add all windows of an application or only the current one to the exceptions. 
![system-dialog-add-page](https://user-images.githubusercontent.com/57502897/95624478-2b8a6780-0a34-11eb-88ea-433ea8cdcc44.png)

The basic prototype shows the flow for adding Slack to the exception: https://www.figma.com/proto/uI6TbZgpvBwKDN6DO9VxX5/Pop-_OS-various?node-id=78%3A324&scaling=scale-down

**Comment by jmmaranan** [comment]
@maria-komarova what are your thoughts on floated windows indicator as mentioned in #369?
