### ISSUE TITLE
Stacks flashing and disappearing in multiple monitor setup

### ISSUE THREAD

**Issue by Artofaj** [pop-os/shell#623]
**(1) Issue/Bug Description:**
Stack of windows doesn't behave like normal tiled windows. Tiled windows stay in place when in a secondary monitor (without workspaces) while navigating through workspaces on the primary monitor. Stacked windows 'flash' for a moment when moving through workspaces. In rare cases, a stack can disappear completely and not reappear. so far this has happened when launching a new window that launches on the primary monitor. 

**(2) Steps to reproduce (if you know):**
Have two monitors. Set a stack on your secondary monitor. Have tiling active. Move between workspaces in your primary monitor. The stack will disappear for a moment (following the workspace change animation) and then reappear. Sometimes the stack will disappear altogether.

**(3) Expected behavior:**
Stacks behave like unstacked windows: The don't flicker or disappear when navigating through workspaces.

**(4) Distribution (run `cat /etc/os-release`):**
```
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```

**(5) Gnome Shell version:**
GNOME 3.36.6

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```r555.5c93ca0-1```

**(7) Where was Pop Shell installed from:**
AUR

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
2x 1080p, Primary(Horizontal), Secondary(Vertical).

**(9) Other Installed/Enabled Extensions:**
```['user-theme@gnome-shell-extensions.gcampax.github.com', 'gsconnect@andyholmes.github.io', 'impatience@gfxmonk.net', 'battery-percentage@nohales.org', 'updateindicator@aegirxx.googlemail.com', 'output-audio-devices@muflone', 'audio-switcher@AndresCidoncha', 'sound-output-device-chooser@kgshank.net', 'bluetooth-quick-connect@bjarosze.gmail.com', 'arc-menu@linxgem33.com', 'focus-my-window@varianto25.com', 'pamac-updates@manjaro.org', 'nightthemeswitcher@romainvigier.fr', 'pop-shell@system76.com', 'shade-inactive-windows@hepaajan.iki.fi', 'task-widget@juozasmiskinis.gitlab.io', 'gtktitlebar@velitasali.github.io', 'RemoveAppMenu@rastersoft.com']```

**(10) Other Notes:**
I'm running a wayland session.

**Comment by jmmaranan** [comment]
@Artofaj - do you have the Tweaks > Workspaces > Only on Primary toggled to true?

**Comment by Artofaj** [comment]
@jmmaranan Yes, of course. Like I said, the issue occurs only with stacks. non-stacked windows behave as expected, staying visible without flashing.

**Comment by mmstick** [comment]
Set it to workspaces span displays. Only on Primary isn't supported right now

**Comment by Artofaj** [comment]
@mmstick That is a complete different use case than mine. I need the windows on my secondary monitor to stay in place. If I span the workspaces, the workspace on my secondary monitor changes and the windows open there go with it. That is not a feasible workaround.

**Comment by Artofaj** [comment]
I switched to x11 to see if the behavior was the same. The bug is there too.

**Comment by csculley** [comment]
> Set it to workspaces span displays. Only on Primary isn't supported right now

Is this the correct issue to track when "Only on Primary" will be supported, or is there another one that I can follow?

**Comment by Artofaj** [comment]
I found a workaround. You can create a stack on the secondary monitor and the set that stack to take the whole screen (super + m). That prevents the stack from flashing and disappearing.

**Comment by mmstick** [comment]
Is this still an issue?

**Comment by Artofaj** [comment]
@mmstick I can confirm the issue is gone on wayland on gnome 3.38.3 :+1:
