### ISSUE TITLE
Looking for i3 scratchpad workspace functionality in Gnome on PopOS!

### ISSUE THREAD

**Issue by lcohenq** [pop-os/shell#624]
Anything like this?

From the i3 documentation:

> 6.20. Scratchpad
> 
> There are two commands to use any existing window as scratchpad window. move scratchpad will move a window to the scratchpad workspace. This will make it invisible until you show it again. There is no way to open that workspace. Instead, when using scratchpad show, the window will be shown again, as a floating window, centered on your current workspace (using scratchpad show on a visible scratchpad window will make it hidden again, so you can have a keybinding to toggle). Note that this is just a normal floating window, so if you want to "remove it from scratchpad", you can simple make it tiling again (floating toggle).
> 
> As the name indicates, this is useful for having a window with your favorite editor always at hand. However, you can also use this for other permanently running applications which you don’t want to see all the time: Your music player, alsamixer, maybe even your mail client…?

**Comment by WatchMkr** [comment]
This functionality can be accomplished by floating and then minimizing/unminimizing a window.

**Comment by itapai** [comment]
Well, these tricks kinda works but not really.

Scratchpad has fixed dimensions, so whatever you throw in, it will auto-resize and position. When you float a window, you have to resize and position it manually.
Minimizing the window works ok, I guess, but unminimizing takes you back to the workspace where you minimized the window.

Any chance we could have the complete scratchpad functionality?

**Comment by hiasr** [comment]
I think this feature would be awesome as well! 

I will have a go at implementing it. As I don't think it's possible to actually make a window disappear in gnome, the best option is to hide it. When you want to get the window back from scratchpad you and move it to the current workspace and unhide it. This should work as when you hide/unhide a floating window the position and size stay the same. 

If anyone else has a better idea for an implementation, always welcome!

**Comment by karimone** [comment]
Would be possible to do that using a script bind to a shortcut?
The script should be able to get if the terminal is active, if not show it otherwise hide it.

**Comment by hab25** [comment]
@itapai 
> unminimizing takes you back to the workspace where you minimized the window.

For me this is  the annoyance that most distances that workaround from being close to a i3-scratchpad-like experience; so I have further worked around by using the "Toggle window on all workspaces or one" GNOME keybind.
It's still a very clunky experience though; way too many key presses; very poor substitute to i3 scratchpad.

**Comment by marvin-te** [comment]
This! Please! So much!

Tried the quake-mode extension and external program tdrop already but neither worked as expected. I'd really LOVE to see the i3-scratchpad functionality in Gnome to hide apps like Discord, Spotify and Thunderbird.

If someone can do this, then it's probably you guys. <3

**Comment by static302** [comment]
Yeah, it could be just an amazing feature.
Really like qtile scratchpads, hope it will be possible to use something like that in pop!_os shell

**Comment by JoelMon** [comment]
I just came here to voice my support for this feature. 

1. **Task Segmentation**: Working from home often involves juggling multiple tasks at once. The scratchpad in i3 is a tool that can help manage these tasks effectively. For instance, someone might open a text editor on the scratchpad while working on a report. They could quickly switch to this scratchpad, jot down new ideas or tasks that come up unexpectedly, and then switch back to their main workspace without disrupting their workflow.

2. **Space Optimization**: When working with a limited number of screens, screen real estate becomes precious. Using a scratchpad can help free up this space by allowing less frequently used applications to be hidden when they're not in use. For example, users might keep their email client or a calendar app in the scratchpad, bringing it into view only when necessary and thus maintaining a cleaner, less cluttered workspace for their main tasks.

3. **Reducing Distractions**: In a work-from-home setting, there are countless potential distractions. Using the scratchpad can minimize these distractions by "hiding" apps that aren't immediately needed. For instance, someone might hide their social media or news app in the scratchpad during work hours to reduce the temptation to check these apps while working, but it can quickly bring them back into view during breaks.

I hope this becomes a feature for the new COSMIC DE.

**Comment by mmstick** [comment]
Feature requests for COSMIC should go to https://github.com/pop-os/cosmic-epoch.
