### ISSUE TITLE
Windows always raise when hovered

### ISSUE THREAD

**Issue by rodneydup** [pop-os/shell#627]
**(1) Issue/Bug Description:**
Windows always raise when focused even if "Raise Windows When Focused" is disabled in gnome-tweaks.

**(2) Steps to reproduce (if you know):**
Turn on Focus on Hover and turn off Raise Windows When Focused, open a floating window in front of another window. Hovering over the rear window will raise it to the front. (the problem doesn't seem to exist for dialog windows)

**(3) Expected behavior:**
Windows should not raise when focused if "Raise Windows When Focused" is turned off.

**(4) Distribution (run `cat /etc/os-release`):**
 Debian 11 (Testing)

**(5) Gnome Shell version:**
3.38.1

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
6fb9b764166d50feb3a5848c69b12f9956376c98 (Oct 9, 2020)

**(7) Where was Pop Shell installed from:**
github clone and make local-install

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
2x1080p

**(9) Other Installed/Enabled Extensions:**
Tested with all extensions disabled

**Comment by jloh** [comment]
I can replicate this, disabling the shell extension fixes the functionality.

**Comment by tiramiseb** [comment]
Same here, with Ubuntu 20.04, GNOME Shell 3.36.4, Pop Shell v1.2.0, installed from release downloaded on GitHub.

It happens for instance with the Signal windows, that I configured as a floating window exception. It's extremely annoying, because the windows goes to the background as soon as the cursor leaves it.
