### ISSUE TITLE
[FEATURE PROPOSAL] Gestures settings

### ISSUE THREAD

**Issue by dodalovic** [pop-os/shell#631]
Hi,
first of all - thanks for the great piece of software! 

So.... I believe gestures are hard. As a former MacOS user, I liked very much how they provided a very nice UI to set up system gestures. 
I believe it would be beneficial to control the gestures via GUI. 

:shrug: ?

**Comment by jmbuhr** [comment]
In case you are still searching for gesture support, the libinput-gestures package has a straightforward installation manual: https://github.com/bulletmark/libinput-gestures

**Comment by mmstick** [comment]
Out of scope of Pop Shell, but is a feature to be experimented with in COSMIC
