### ISSUE TITLE
TypeError: ExtensionUtils.getSettings is not a function

### ISSUE THREAD

**Issue by joeltonguerreiro** [pop-os/shell#635]
**(1) Issue/Bug Description:**

The extension is not loading.

TypeError: ExtensionUtils.getSettings is not a function

Stack trace:
  log_level@/home/joelton/.local/share/gnome-shell/extensions/pop-shell@system76.com/log.js:11:20
  logging_combo@/home/joelton/.local/share/gnome-shell/extensions/pop-shell@system76.com/prefs.js:117:29
  settings_dialog_view@/home/joelton/.local/share/gnome-shell/extensions/pop-shell@system76.com/prefs.js:73:5
  settings_dialog_new@/home/joelton/.local/share/gnome-shell/extensions/pop-shell@system76.com/prefs.js:9:23
  buildPrefsWidget@/home/joelton/.local/share/gnome-shell/extensions/pop-shell@system76.com/prefs.js:127:18
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:83:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:235:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:389:5
  @<main>:1:43
  

**(2) Steps to reproduce (if you know):**

**(3) Expected behavior:**

**(4) Distribution (run `cat /etc/os-release`):**
 
NAME="Zorin OS"
VERSION="15.3"
ID=zorin
ID_LIKE=ubuntu
PRETTY_NAME="Zorin OS 15.3"
VERSION_ID="15"
HOME_URL="https://www.zorinos.com"
SUPPORT_URL="https://www.zorinos.com/help"
BUG_REPORT_URL="https://bugs.launchpad.net/zorin-os"
PRIVACY_POLICY_URL="https://www.zorinos.com/legal/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**(5) Gnome Shell version:**

GNOME Shell 3.30.2

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**(7) Where was Pop Shell installed from:**

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

**Comment by mmstick** [comment]
GNOME 3.36 is the minimum requirement.
