### ISSUE TITLE
[FEATURE PROPOSAL] Automatic Active Hinting

### ISSUE THREAD

**Issue by JoelMon** [pop-os/shell#638]
At the moment the hinting is _always_ visible, even when there is only one window open. I propose that active hinting is turned off when the following two conditions are met:

- tiling window is turned on
- There is only one window on the desktop (full screen)

Seems redundant to have tiling windows turned on with only one window opened, full screen, _and_ with active hinting. The user can turn off active hinting on their own but it would be nice if the conditions above are met that active hinting turns off until the condition isn't true any longer. Once the user opens another window, active hinting turns on automatically once again.

**Comment by WatchMkr** [comment]
We put put an emphasis on consistency to help with a clear UX. With active hint tuned on, the hint is active regardless of the number of windows.
