### ISSUE TITLE
Pop-shell forces Dash To Dock border to be rounded

### ISSUE THREAD

**Issue by Benguin** [pop-os/shell#64]
With pop-shell enabled, the dash to dock border radius is forced to be a certain value, regardless of what the dash to dock "force straight corner" setting is set to.

This can be seen here:
[pop-shell enabled](https://user-images.githubusercontent.com/3020843/76548704-12faa480-6487-11ea-815a-4e3e37c3270d.png)
[pop-shell disabled](https://user-images.githubusercontent.com/3020843/76548707-142bd180-6487-11ea-971c-1a228f9b8107.png)

System:
Archlinux on linux 4.19-lts
Gnome-shell 3.34.4
Pop-shell git latest (r233.6b0cd23-1)

**Comment by mmstick** [comment]
If anyone knows why this occurs, that would be helpful.

**Comment by Benguin** [comment]
> If anyone knows why this occurs, that would be helpful.

I'm also curious why it changes certain other shell styles. In those screenshots you can see that by default on my system I don't have a dropdown indicator on the "places" menu, yet with pop-shell it appears. Theres a few other notable differences in the screenshot-- seems relevant. Are you overriding any shell styles somehow?

**Comment by mmstick** [comment]
```js
// Supplements the GNOME Shell theme with the extension's theme.
function load_theme() {
    try {
        Log.info(`loading theme`)
        let theme = new St.Theme({
            application_stylesheet: Gio.File.new_for_path(Me.path + "/stylesheet.css"),
            theme_stylesheet: _defaultCssStylesheet,
        });

        Log.info(`setting theme`);

        St.ThemeContext.get_for_stage(global.stage).set_theme(theme);
        Log.info(`theme set`);
    } catch (e) {
        Log.error("failed to load stylesheet: " + e);
    }
}
```
