### ISSUE TITLE
I get this error on instalation on lubuntu 18.04

### ISSUE THREAD

**Issue by gabrielknot** [pop-os/shell#643]
**(1) Issue/Bug Description:**

I tried to install the pop shell cloning the repository and following the instructions from README.md. When i run the "make local-install". I get this message of error: 
"Makefile:25: recipe for target 'transpile' failed
make: *** [transpile] Error 1" 

**(2) Steps to reproduce (if you know):**
$ sudo apt install node-typescript make git
$ mkdir Git && cd Git/
$ mkdir PopShell cd PopShell/
$ git clone https://github.com/pop-os/shell && cd shell
$ make local-install

**(3) Expected behavior:**
Expected the installation of the application.

**(4) Distribution (run `cat /etc/os-release`):**
 

**(5) Gnome Shell version:**
I used  tilix 1.7.7.

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

Current version on 10/19/2020

**(7) Where was Pop Shell installed from:**

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
12880x720, Primary

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

**Comment by mmstick** [comment]
Too old. 20.04 is the minimum requirement, and this extension is for GNOME.

**Comment by gabrielknot** [comment]
Sorry i use another shell, because i see an pop-os video and i liked the functionality, but wanna this without change my distro. Whatever  this make me search another tile window management like i3.

hugs from Brazilian linux beginner. Sorry for my English
