### ISSUE TITLE
GNOME screenshot being tiled

### ISSUE THREAD

**Issue by carlwgeorge** [pop-os/shell#650]
**(1) Issue/Bug Description:**

The GNOME screenshot application is being tiled, despite being having a [floating exception](https://github.com/pop-os/shell/blob/a11d3c34db01987bb716b8b127b2b889130a4fc1/src/config.ts#L30).

**(2) Steps to reproduce (if you know):**

Run GNOME screenshot, either via the launcher or with the command `gnome-screenshot --interactive`.

**(3) Expected behavior:**

GNOME screenshot to always be a floating window.

**(4) Distribution (run `cat /etc/os-release`):**

```
NAME=Fedora
VERSION="33 (Workstation Edition)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora 33 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f33/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=33
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=33
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

**(5) Gnome Shell version:**

gnome-shell-3.38.1-2.fc33.x86_64

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

gnome-shell-extension-pop-shell-0.1.0-0.9.20201016gita11d3c3.fc33.noarch (built from commit a11d3c34db01987bb716b8b127b2b889130a4fc1)

**(7) Where was Pop Shell installed from:**

https://copr.fedorainfracloud.org/coprs/carlwgeorge/gnome-shell-extension-pop-shell/

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

3 x 4k
secondary(horizontal) / primary(horizontal) / secondary(horizontal)

**(9) Other Installed/Enabled Extensions:**

```
$ gnome-extensions list --enabled
pop-shell@system76.com
background-logo@fedorahosted.org
sound-output-device-chooser@kgshank.net
```

**(10) Other Notes:**

**Comment by ids1024** [comment]
Doesn't seem to happen on Pop!_OS 20.04.

If you use something like `xprop` to get the `WM_CLASS` of the window, is it the same as the one in the floating exception?

**Comment by carlwgeorge** [comment]
I'm using wayland so I don't believe xprop works, but GNOME's looking glass tool reports that the wmclass is `gnome-screenshot`.  The exception is for `Gnome-screenshot`.  Is there a way to make that exception case-insensitive?

**Comment by mmstick** [comment]
It's possible to enable case-insensitive regular expression support in JavaScript, and it's likely a good idea that we do so.

**Comment by ids1024** [comment]
Ah right, I wasn't thinking of the fact that Fedora is using wayland.

On Pop!_OS with X, xprop shows `WM_CLASS(STRING) = "gnome-screenshot", "Gnome-screenshot"`. So just having the lower case version should be fine. Though there might not be any harm in including both.

**Comment by carlwgeorge** [comment]
a86296371620450a75a7070371957d1ecf75025f appears to have fixed this for me.  Thanks!
