### ISSUE TITLE
When we will get this in extensions.gnome.org web site as a gnome extension?

### ISSUE THREAD

**Issue by rahul8548** [pop-os/shell#652]
When we will get this in **extensions.gnome.org** web site as a **gnome extension** specially for **ubuntu** users?

**Comment by Findarato** [comment]
I think the biggest thing that is holding them back is wayland support.  From all I have read this is still not working properly there.  I know it fails last time I tried on my Fedora 32 laptop running Intel + Wayland

**Comment by Chrysostomus** [comment]
Weird, I thought it was ready because it has worked with Wayland on Manjaro for about an month or so. Fedora is a good benchmark, when it works with Fedora and PopOs, it's probably ready.

**Comment by Findarato** [comment]
also this is a dupe of #69

**Comment by mmstick** [comment]
@Findarato Wayland support is not a problem, and hasn't been for about 3-4 months now.

Same as with #69, the extension requires extensive modifications to default shortcuts and features, so it's not currently feasible to submit it there.
