### ISSUE TITLE
Keybindings are not set up during installation & keybindings overview doesn't work

### ISSUE THREAD

**Issue by RickDW** [pop-os/shell#657]
I have updated pop shell on my laptop today and it refuses to set up the correct keybindings, is there a way to to do this manually?

Additionally, the 'view all keyboard shortcuts' in the pop shell menu doesn't work on ubuntu (hasn't ever worked for since I installed it months ago), which makes learning to use pop shell for people who are new to it much more difficult than it needs to be. It would be nice to get an overview of some kind.

**Comment by arnogon** [comment]
> I have updated pop shell on my laptop today and it refuses to set up the correct keybindings, is there a way to to do this manually?

Which keybindings don't work?

> Additionally, the 'view all keyboard shortcuts' in the pop shell menu doesn't work on ubuntu (hasn't ever worked for since I installed it months ago), which makes learning to use pop shell for people who are new to it much more difficult than it needs to be. It would be nice to get an overview of some kind.

[shell-shortcuts](https://github.com/pop-os/shell-shortcuts) needs to be installed separately.

**Comment by RickDW** [comment]
Seems like none of them work, maximize window, close window, navigate up/down/left/right, turn a tile into a stack. I just got them to work again after deleting the entire pop shell folder, but before that no amount of reinstalling could get it to budge. 

About the shortcuts, I think it makes much more sense to include basic functionality that you will need to use pop shell in pop shell itself, or at least reference the required repo somewhere in the readme or in the menu next to the button. I only found out about it because I opened an issue.

**Comment by arnogon** [comment]
> Seems like none of them work, maximize window, close window, navigate up/down/left/right, turn a tile into a stack. I just got them to work again after deleting the entire pop shell folder, but before that no amount of reinstalling could get it to budge.

So is it working now?

`scripts/configure.sh` and `schemas/org.gnome.shell.extensions.pop-shell.gschema.xml` has the default keybindings you need, but keying them in one by one would be quite tedious.

> About the shortcuts, I think it makes much more sense to include basic functionality that you will need to use pop shell in pop shell itself, or at least reference the required repo somewhere in the readme or in the menu next to the button. I only found out about it because I opened an issue.

Agree. I only found out about it by accident as well.

**Comment by RickDW** [comment]
It does, but I managed to break it again, this time on purpose. You know how it asks you whether you want to set custom keybindings during installation? After I ran 'make uninstall' and reset my keybindings in the ubuntu settings, I logged out and in again and ran 'make local-install'. This time, however, it didn't ask to overwrite my keybindings, and seems to think it already did that task. So I think there's an issue with it not fully resetting after an uninstall. Here's the output of the installation after an uninstall: 
![ReinstallOutput](https://user-images.githubusercontent.com/25059442/97088779-7d85dc80-1633-11eb-9748-03a17136a6d3.png)

**Comment by arnogon** [comment]
Try removing `.confirm_shortcut_change` and run `sh scripts/configure.sh` again. It still remembered the last time you changed the default keybindings and so skipped the steps this time.

**Comment by RickDW** [comment]
That worked, thanks! I think it would be good to include this behaviour in the readme.

**Comment by mmstick** [comment]
This is a duplicate request for #shortcuts
