### ISSUE TITLE
ignore WM_NORMAL_HINTS for tiled windows

### ISSUE THREAD

**Issue by FelschR** [pop-os/shell#66]
For example Signal & keybase-gui have a minimum height specified which causes overlapping windows.
There's also the option for resize increments which I haven't encountered in any of my apps yet.

It appears that most tiling window managers just ignore those settings.

**Comment by mmstick** [comment]
It can't be ignored, but we can watch for the hint and compensate for it.

**Comment by mmstick** [comment]
Merging issue with #85
