### ISSUE TITLE
Active hint border shown in full screen

### ISSUE THREAD

**Issue by rybber78** [pop-os/shell#662]
**(1) Issue/Bug Description:**
In 20.10 active hint (border around window) id shown when viewing full screen videos in Firefox and Chrome/Brave

**(2) Steps to reproduce (if you know):**
Start video, double click to full screen it

**(3) Expected behavior:**
Border should disappear in full screen mode

**(4) Distribution (run `cat /etc/os-release`):**
 20.10

**(5) Gnome Shell version:**

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

pop-shell:
  Installed: 0.1.0~1603503416~20.10~05e531e
  Candidate: 0.1.0~1603503416~20.10~05e531e

**(7) Where was Pop Shell installed from:**
Pop shop

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
laptop full HD

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

**Comment by wenzeslaus** [comment]
I'm on _20.04_ and recently the active hint started to show also for maximized windows (as well as fullscreen windows as in OP). Before it was shown only when they are smaller than maximized, e.g. tiled. Unfortunately, the hint is a visual clutter for maximized windows (and strange for fullscreen windows).

**Comment by jmmaranan** [comment]
Hint was changed to show now on maximized. Fullscreen should not show and that's a bug.

**Comment by wenzeslaus** [comment]
> Hint was changed to show now on maximized.

Thanks for the reply. Hm, is there any reason for that?

**Comment by jmmaranan** [comment]
@wenzeslaus - yeah - it was discussed here. https://github.com/pop-os/shell/issues/219 - I think the solution to this is giving user an option to have it on max by default true, then they can change it on prefs window.

**Comment by wenzeslaus** [comment]
@jmmaranan Given your comment in #637, it seems the settings for this is only planned, not available, right? I don't see it in Tile Windows menu or elsewhere. I can disable the hint completely, but I don't see option to disable it for maximized windows only.

In case it is relevant, to add to #219, I have Gaps set to 0 and I find the Hint on maximized window distracting and eating space (and I have Tile Windows usually disabled).

**Comment by jmmaranan** [comment]
The smart gaps from what I can tell is still not working with the active hint.

The option to disable on maximize is not yet there. This one can easily be added in the future. There is a great deal of consideration on having the prefs window grow in items to show. So not starting on it. But can be added but no real GUI and have to have the user dive into gsettings

**Comment by wenzeslaus** [comment]
Thanks for the info @jmmaranan. I would be fine with any type of settings as long as I can use it disable that. To be clear, I was quite happy with the tiling menu features when I got my new System76, but with the Hint for maximized I will probably disable it till the settings is in place. Can't comment on the smart gaps, but I will keep an eye on that and the fullscreen issue.
