### ISSUE TITLE
"Recursion" error crash while running Zoom

### ISSUE THREAD

**Issue by GeneralPoxter** [pop-os/shell#666]
**(1) Issue/Bug Description:**
I was attending online class using Zoom and was trying to shuffle around the windows (pop-shell has a habit of leaving empty spaces in my workspace for windows that Zoom has minimized). Suddenly, GNOME froze and I was unable to restart it nor fix it by switching ttys. I was forced to reboot the system.
The journal logs for that boot can be found [here](https://pastebin.com/u2KyUJ4e).
The crash began at about 9:06, which corresponds to line 2277 of the journal log. A glaring error in the log is from pop-shell (look for the big mess that begins "JS ERROR: too much recursion"), so I'm pretty sure it's a bug related to pop-shell.

**(2) Steps to reproduce (if you know):**
So far I have been unable to reproduce this error, but I know that it occured when multiple Zoom-related windows were open (I was moving into a breakout room). Like I said before, pop-shell sometimes leaves large spaces in the tiling for the Zoom settings windows when I enter a Zoom meeting room, despite Zoom having automatically minimized that window. As a result, I need to retoggle tiling in order for the tiling engine to reformat my windows. I was trying to do just that when I found that GNOME had froze.

**(3) Expected behavior:**
GNOME should not die when I use Zoom.

**(4) Distribution (run `cat /etc/os-release`):**
Arch Linux

**(5) Gnome Shell version:**
3.38

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
Using the latest commit of dev jmmaranan's [flicker_focal branch](https://github.com/jmmaranan/shell/tree/flicker_focal).

**(7) Where was Pop Shell installed from:**
It was installed from the above source.

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
Single 2560x1440 Dell monitor

**(9) Other Installed/Enabled Extensions:**
Auto Move Windows, Launch new instance, Native Window Placement, and User Themes extensions are also enabled.

**Comment by WatchMkr** [comment]
We recently added Zoom to the do-not-tile list. Its 20 poorly named windows aren’t conducive to tiling. 

Pull master and see if that helps improve the experience.

**Comment by GeneralPoxter** [comment]
I see. Unfortunately, I don't want to pull directly from master_focal, because it seems that only the flicker_focal branch has implemented fixes that reduce animation stuttering on my system.

**Comment by jmmaranan** [comment]
The flicker fix should already be in master_focal or master_groovy. Please backup your copy of the branch you are currently on. Then try with master_focal.

**Comment by GeneralPoxter** [comment]
All right sorry about that. I am now on the master_focal branch, but I would still like to know whether I can set the default mode for Zoom to float but still have the ability to toggle tiling.

**Comment by jmmaranan** [comment]
Great. No problem. Not sure on the Floating rules but for your OP, let know if the too much recursion still happens from master.

**Comment by WatchMkr** [comment]
In master_focal Zoom should be set to float. You can also now view and set floating exceptions from the tiling menu.

We also intend to add the ability to override a floating exception with Super + G but that's not in yet. https://github.com/pop-os/shell/issues/667

**Comment by GeneralPoxter** [comment]
All right. Thanks for the help!
