### ISSUE TITLE
Installing extension under debian 10

### ISSUE THREAD

**Issue by skjorrface** [pop-os/shell#67]
Hi, I'm trying to install the extension under debian 10, the last lines of output from rebuild.sh are the following:

`+ make enable
UUID is "pop-shell@system76.com"
gnome-extensions enable "pop-shell@system76.com"
/bin/sh: 1: gnome-extensions: not found
make: *** [Makefile:49: enable] Error 127`

of course I have gnome-shell-extensions installed but can't find that binary anywhere. What am I doing wrong?

**Comment by MiguelMoll** [comment]
My first guess is it's not in your $PATH so it's not found:
```
❯ which gnome-extensions
/usr/bin/gnome-extensions
```
I assume  this binary is part of a standard gnome install.

**Comment by skjorrface** [comment]
Thanks for your replay, I tried that, there's no such binary in /usr/bin, neither in other $PATH locations. I have these binaries though:
![Schermata 2020-03-13 15:33:13](https://user-images.githubusercontent.com/9011806/76630539-7eed1380-6540-11ea-90e8-3152c8a59c48.png)

**Comment by mmstick** [comment]
The binary comes with the `gnome-shell` package. Debian 10's GNOME Shell is far too old for Pop Shell, which is being developed against GNOME 3.36

**Comment by skjorrface** [comment]
oh okay, then I'll have to find a way to install gnome 3.36 under debian 10 which is not easy as gnome 3.36 is not even considered "experimental" in debian 10. Thanks anyways, not it figures out.
