### ISSUE TITLE
Show Window Titlebars setting not respected on Fedora

### ISSUE THREAD

**Issue by leggettc18** [pop-os/shell#670]
**(1) Issue/Bug Description:**

Titlebars are always shown on Fedora with PopShell extension, even if Show Window Titles is turned off in the extension settings. Works as expected in Pop OS

**(2) Steps to reproduce (if you know):**

1. `sudo dnf install gnome-shell-extensions-pop-shell` (actual package name might be slightly different)
2. Open Extensions App
3. Go to Pop Shell Settings
4. Turn off "Show Window Titles"
5. Open a window that I know wouldn't normally show the titlebar on PopOS

**(3) Expected behavior:**

Titllebars not rendered

**(4) Distribution (run `cat /etc/os-release`):**

 ```
NAME=Fedora
VERSION="33 (Workstation Edition)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora 33 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f33/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=33
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=33
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

**(5) Gnome Shell version:**

3.38.1

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
Installed Packages
Name         : gnome-shell-extension-pop-shell
Version      : 0.1.0
Release      : 1.20201016gita11d3c3.fc33
Architecture : noarch
Size         : 886 k
Source       : gnome-shell-extension-pop-shell-0.1.0-1.20201016gita11d3c3.fc33.src.rpm
Repository   : @System
From repo    : updates
Summary      : GNOME Shell extension for advanced tiling window management
URL          : https://github.com/pop-os/shell
License      : GPLv3 and ASL 2.0
Description  : Pop Shell is a keyboard-driven layer for GNOME Shell which allows for quick and
             : sensible navigation and management of windows.  The core feature of Pop Shell
             : is the addition of advanced tiling window management - a feature that has been
             : highly-sought within our community.  For many - ourselves included - i3wm has
             : become the leading competitor to the GNOME desktop.
```
Obtained from `dnf info gnome-shell-extension-pop-shell`

**(7) Where was Pop Shell installed from:**

Fedora Official Repos

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1 x 1080p

**(9) Other Installed/Enabled Extensions:**

- User Themes
- Background Logo

**(10) Other Notes:**

**Comment by mmstick** [comment]
Are you using Wayland? Only X11 supports it

**Comment by leggettc18** [comment]
That would make sense, I didn't even consider that. Wayland is default on Fedora and this is a fresh installl of Fedora 33. I can go without removing Window Titles, given that this is an intentionally unsupported use-case (at least for now). I just reported it because I thought it was a bug at first.

For the record, the rest of the extension seems to work great in Wayland!
