### ISSUE TITLE
Maximized Windows Cause Gnome-shell To Crash

### ISSUE THREAD

**Issue by scrufulufugus** [pop-os/shell#671]
**(1) Issue/Bug Description:**
- Closing a window while having another window maximized on a different desktop pane will cause gnome-shell to crash. Disabling *pop-shell* will fix the issue.

**(2) Steps to reproduce (if you know):**
1. Open any application and maximize the window.
2. Switch to new desktop pane.
3. Open another application.
4. Close the second application.
5. Observe gnome-shell crashing.

**(3) Expected behavior:**
- Gnome-shell does not crash

**(4) Distribution (run `cat /etc/os-release`):**
- Pop!_OS 20.10

**(5) Gnome Shell version:**
- 3.38.1

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
$ apt policy pop-shell
pop-shell:
  Installed: 1.0.0~1603994289~20.10~ecc9b38
  Candidate: 1.0.0~1603994289~20.10~ecc9b38
  Version table:
 *** 1.0.0~1603994289~20.10~ecc9b38 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**
- System76 PPA

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
- One 1080p Monitor

**(9) Other Installed/Enabled Extensions:**
- Reproducible with the stock Pop!_OS extensions.

**(10) Other Notes:**
- Before 20.10 following the above steps would cause the first window to revert back to tilling; which was itself an annoying bug. 
- Attempting to reproduce this on an Arch box running `gnome-shell 3.38.1` and `pop-shell 1.0.0` will cause the previous non-crashing behavior.

**Comment by mmstick** [comment]
You're saying that the crash only happens in Pop, and not Arch? If you're using 1.0.0 on arch, that's the same commit as master right now, released on Pop.

**Comment by scrufulufugus** [comment]
Yes. It was also occurring with 0.1.0 on Pop. I originally noticed this last week after upgrading from 20.04 and assumed it was a botched upgrade. I reverted back to 20.04 using a btrfs snapshot and waited a week. I upgraded again and had the same issue.

**Comment by mmstick** [comment]
Can you get logs from a boot where this happened? `journalctl -b0 -o cat /usr/bin/gnome-shell > gnome-shell.log`

**Comment by scrufulufugus** [comment]
https://gist.github.com/scrufulufugus/a84a92bf5491e8a6c1e6263ac3e9e95b

**Comment by mmstick** [comment]
Doesn't look like the complete log. Did GNOME Shell crash since your last reboot? That command only shows entries that were recorded during the current boot.

**Comment by scrufulufugus** [comment]
I booted the machine up and triggered the crash using the steps I listed. Maybe crash is the wrong word. It is more like the desktop restarts.

**Comment by GeneralPoxter** [comment]
I reproduce this on Arch Linux.
[Here's ](https://pastebin.com/PSEGPXxv)the result of `journalctl -b0 -o cat /usr/bin/gnome-shell > gnome-shell.log`.
There's a lot more stuff related to the gnome-shell stack trace in just `sudo journalctl -b` too if you want that as well.

**Comment by mmstick** [comment]
`Error in freeze/thaw accounting` is an error in mutter. Claims it happened around line 194 in `src/window.js`, but that line doesn't call anything. Unsure if your copy is different from the latest version. The line that follows it is `const actor = meta.get_compositor_private()`, but we check if it's valid before trying to use it.

**Comment by GeneralPoxter** [comment]
I installed directly from source with latest commit a11d3c34db01987bb716b8b127b2b889130a4fc1. Should I install the first public release version and modify the journal log to match the new error?

**Comment by mmstick** [comment]
Best to always have logs from the latest version, since behaviors could have been fixed, and line numbers won't match in logs. When GNOME Shell crashes, it always signals what the last lines of code it executed in gjs before aborting.

**Comment by GeneralPoxter** [comment]
Okay I installed the latest version and replaced the same log file above with the new error from the crash.

**Comment by mmstick** [comment]
It's failing to call `meta.unmaximize(Meta.MaximizeFlags.HORIZONTAL);`, but I'm not sure what we can do to know that this will cause gnome-shell to crash.
