### ISSUE TITLE
chrome tab dragging buggy

### ISSUE THREAD

**Issue by jbytes1027** [pop-os/shell#673]
**(1) Issue/Bug Description:**
chrome tabs rapidly jumping from the starting point of drag to the position of the mouse several times a second

**(2) Steps to reproduce (if you know):**
drag an individual chrome tab

**(4) Distribution (run `cat /etc/os-release`):**
Pop!_OS 20.10

**(5) Gnome Shell version:**
3.38.1

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```1.0.0~1603994289~20.10~ecc9b38```

**(7) Where was Pop Shell installed from:**
pop-os default

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1x 1080p

**Comment by mmstick** [comment]
Windows moved by their tab does not register as a grab by GNOME Shell, which causes this behavior. I've been looking for workarounds so we can still auto-tile windows that resize or move themselves out of place.

**Comment by moniquelive** [comment]
Dragging Chrome tabs even inside its original window is still buggy. It detaches and it's impossible to drag it back to the window.
The dragged window moves super slowly making it impossible to control it.
