### ISSUE TITLE
Super+H minimises window sometimes

### ISSUE THREAD

**Issue by FelschR** [pop-os/shell#68]
So, at first the Super+H key is working as intended. But after a while of usage the the shortcut reverts back to minimising the window instead of switching the focus.
When I restart GNOME Shell it starts working again (for a while).
I suspect that some specific action is triggering this but I haven't yet figured out what it is.

I'm running nixos-unstable.

**Comment by FelschR** [comment]
Apparently the same is true for Super+L which, you know, locks the system by default. 😆

**Comment by mmstick** [comment]
Did you install this with `sh rebuild.sh`? The script redefines these shortcuts.

**Comment by FelschR** [comment]
Ah, I see. I haven't used it.
The `rebuild.sh` doesn't really fit into NixOS's declarative approach.
Thanks for the hint. I guess I'll just set the dconf values in my user config for now.
