### ISSUE TITLE
install(Debian Bullseye/GNOME Shell 3.38.1): "pop-shell@system76.com" extension does not exist

### ISSUE THREAD

**Issue by Toub** [pop-os/shell#694]
**(1) Issue/Bug Description:**

The following error message appends trying to install pop-os locally from master branch on Debian Bullseye (GNOME Shell 3.38.1):

```bash
gnome-extensions enable "pop-shell@system76.com"
> "pop-shell@system76.com" extension does not exist
```

Original error message (in french):
> L’extension « pop-shell@system76.com » n’existe pas

**(2) Steps to reproduce (if you know):**

```bash
git clone https://github.com/pop-os/shell
cd shell
sudo make local-install .
```

Log output:

```log
UUID is "pop-shell@system76.com"
depcheck
rm -rf _build schemas/gschemas.compiled target
tsc
for proj in color_dialog floating_exceptions; do tsc --p src/${proj}; done
sh scripts/transpile.sh
glib-compile-schemas schemas
touch schemas
rm -rf _build
mkdir -p _build
cp -r metadata.json icons schemas target/*.js imports/*.js *.css _build
for proj in color_dialog floating_exceptions; do \
	mkdir -p _build/${proj}; \
	cp -r target/${proj}/*.js _build/${proj}; \
done
rm -rf /home/toub/.local/share/gnome-shell/extensions/pop-shell@system76.com
mkdir -p /home/toub/.local/share/gnome-shell/extensions/pop-shell@system76.com
cp -r _build/* /home/toub/.local/share/gnome-shell/extensions/pop-shell@system76.com/
sh scripts/configure.sh
+ set_keybindings
+ shortcut_applied
+ test -f ./.confirm_shortcut_change
+ read -p Pop shell will override your default shortcuts. Are you sure? (y/n)  CONT
Pop shell will override your default shortcuts. Are you sure? (y/n) y
+ test y = y
+ touch ./.confirm_shortcut_change
+ return 1
+ left=h
+ down=j
+ up=k
+ right=l
+ KEYS_GNOME_WM=/org/gnome/desktop/wm/keybindings
+ KEYS_GNOME_SHELL=/org/gnome/shell/keybindings
+ KEYS_MUTTER=/org/gnome/mutter/keybindings
+ KEYS_MEDIA=/org/gnome/settings-daemon/plugins/media-keys
+ KEYS_MUTTER_WAYLAND_RESTORE=/org/gnome/mutter/wayland/keybindings/restore-shortcuts
+ dconf write /org/gnome/mutter/wayland/keybindings/restore-shortcuts @as []
+ dconf write /org/gnome/desktop/wm/keybindings/minimize @as ['<Super>comma']
+ dconf write /org/gnome/shell/keybindings/open-application-menu @as []
+ dconf write /org/gnome/shell/keybindings/toggle-message-tray @as ['<Super>v']
+ dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-left @as []
+ dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-right @as []
+ dconf write /org/gnome/desktop/wm/keybindings/move-to-monitor-up @as []
+ dconf write /org/gnome/desktop/wm/keybindings/move-to-monitor-down @as []
+ dconf write /org/gnome/desktop/wm/keybindings/move-to-monitor-left @as []
+ dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-down @as []
+ dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-up @as []
+ dconf write /org/gnome/desktop/wm/keybindings/move-to-monitor-right @as []
+ dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-down ['<Primary><Super>Down','<Primary><Super>j']
+ dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-up ['<Primary><Super>Up','<Primary><Super>k']
+ dconf write /org/gnome/mutter/keybindings/toggle-tiled-left @as []
+ dconf write /org/gnome/mutter/keybindings/toggle-tiled-right @as []
+ dconf write /org/gnome/desktop/wm/keybindings/toggle-maximized ['<Super>m']
+ dconf write /org/gnome/settings-daemon/plugins/media-keys/screensaver ['<Super>Escape']
+ dconf write /org/gnome/settings-daemon/plugins/media-keys/home ['<Super>f']
+ dconf write /org/gnome/settings-daemon/plugins/media-keys/email ['<Super>e']
+ dconf write /org/gnome/settings-daemon/plugins/media-keys/www ['<Super>b']
+ dconf write /org/gnome/settings-daemon/plugins/media-keys/rotate-video-lock-static @as []
+ dconf write /org/gnome/desktop/wm/keybindings/close ['<Super>q']
+ gnome-extensions list
+ grep native-window
native-window-placement@gnome-shell-extensions.gcampax.github.com
+ grep native-window
+ gnome-extensions list
+ gnome-extensions enable native-window-placement@gnome-shell-extensions.gcampax.github.com
+ dconf write /org/gnome/mutter/workspaces-only-on-primary false
gnome-extensions enable "pop-shell@system76.com"
L’extension « pop-shell@system76.com » n’existe pas
make: *** [Makefile:61 : enable] Erreur 2
```

**(3) Expected behavior:**

install successfull :-)

**(4) Distribution (run `cat /etc/os-release`):**
 
```bash
cat /etc/os-release
# PRETTY_NAME="Debian GNU/Linux bullseye/sid"
# NAME="Debian GNU/Linux"
# ID=debian
# HOME_URL="https://www.debian.org/"
# SUPPORT_URL="https://www.debian.org/support"
# BUG_REPORT_URL="https://bugs.debian.org/"

uname -a
# Linux asus 5.9.0-1-amd64 #1 SMP Debian 5.9.1-1 (2020-10-17) x86_64 GNU/Linux
```

**(5) Gnome Shell version:**

```bash
gnome-shell --version
> GNOME Shell 3.38.1
```

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

From git default branch `master_groovy` (7th of November, 2020):

```bash
git log
# commit d1d2b0e0cd77a57d9f50f2b4d6199faf60d9531d (HEAD -> master_groovy, origin/master_groovy, origin/HEAD)
# Author: Michael Aaron Murphy <mmstick@pm.me>
# Date:   Fri Nov 6 05:38:23 2020 -0700
```

**(7) Where was Pop Shell installed from:**

build from sources

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

**Comment by KeironO** [comment]
Having the same issues.

**Comment by CrazyBolillo** [comment]
Yep, can confirm. Running sid with Gnome 3.38.1 and I get the exact same message.

**Comment by jmmaranan** [comment]
I think this is an issue of GNOME 3.38 on Wayland, because there is no way for it to restart the gnome-shell without logging out. Please try to logout and log back in. Use the gnome-tweaks to enable pop-shell.

**Comment by CrazyBolillo** [comment]
I downloaded the latest release (only one) from Github. Placed it on my local gnome-shell/extensions folder and logged in and out. I have now enabled it from Gnome-Tweaks and it is working. Altough the tiling seems buggy.

**Comment by Toub** [comment]
Thanks @jmmaranan !

After a reboot, this command works:

```sh
gnome-extensions enable "pop-shell@system76.com"
```

Maybe catching this error and display a message in install script would do the job?

**Comment by jmmaranan** [comment]
@Toub, yeah that's the shortest and fastest way to fix it in the `Makefile#enable`

Are you on Wayland? `ALT + F2, r` should tell you quickly that you cannot do it while on that mode. You might want to go back to xorg if you are going to contribute to the extension as the code/debug cycle would be annoying if keeps logging you out just to test and have to reopen the project workspace again.

The `enable` extension failure on first time build affects both display modes, xorg and wayland.

It could also be that the fix to the Makefile#restart would be just to do the "disable, enable extension" instead of restarting the shell or logging out. Would try this later.

**Comment by Toub** [comment]
> @Toub, yeah that's the shortest and fastest way to fix it in the `Makefile#enable`
> 
> Are you on Wayland? `ALT + F2, r` should tell you quickly that you cannot do it while on that mode. You might want to go back to xorg if you are going to contribute to the extension as the code/debug cycle would be annoying if keeps logging you out just to test and have to reopen the project workspace again.

> Are you on Wayland?

Sorry, but I have no idea. Probably not? 

I am a long-term linux user, but not a linux expert, and I don't consider to contribute to the development of this extension.

> 
> The `enable` extension failure on first time build affects both display modes, xorg and wayland.
> 
> It could also be that the fix to the Makefile#restart would be just to do the "disable, enable extension" instead of restarting the shell or logging out. Would try this later.

Great, thanks for your work!

**Comment by jmmaranan** [comment]
No problem. Just being curious.

**Comment by mmstick** [comment]
Using sudo to install will install the extension for root. Not what `local-install` is intended for
