### ISSUE TITLE
Changing display configuration

### ISSUE THREAD

**Issue by leviport** [pop-os/shell#70]
There are a few strange things that happen when the display configuration changes, whether that's done in display settings, or by plugging in or unplugging a display. 

One thing I saw was when I was using my laptop with external displays plugged in. With a 1080p (same as internal display) external display, if I have windows on the secondary monitor then unplug it, the windows get moved to the primary display, but are not resized to accommodate Gnome's top bar. This hides parts of my windows underneath the top bar. With a 4K display and doing the same thing, some windows remain expanded to sizes that don't fit on my internal display if they were that large on the 4K display. 

Portrait displays also behave a little strangely with "Snap to Grid" mode. Instead of subdivisions lining up nicely like they do in tiled mode, the sections of the grid don't always line up with the screen, meaning there are regions that can't have a window resized into them. I mentioned this in https://github.com/pop-os/shell/issues/45 but it also seemed relevant here.

If I am working on only my internal display and have windows open across several workspaces, then connect to my 1080p external display, the windows' workspace locations are preserved, but every single window sometimes moves onto the external monitor. I have "workspaces span displays" activated in gnome-tweaks, and the times I've seen it have been with tiling mode activated..

**Comment by mmstick** [comment]
I can watch for monitors being added and destroyed. Question is the exact behavior we should use to move windows to the remaining displays, and perhaps if we should restore windows back to their original monitor if the monitor is re-plugged within a certain timeout.

**Comment by WatchMkr** [comment]
Broken into two issues

https://github.com/pop-os/shell/issues/112
https://github.com/pop-os/shell/issues/113
