### ISSUE TITLE
Stacking and moving windows leads to crashing the shell.

### ISSUE THREAD

**Issue by bryanpaget** [pop-os/shell#700]
**(1) Issue/Bug Description:**

When I enable stacking mode and move windows around sometimes the stack takes up the whole screen and then can sometimes lead to crashing my Wayland session.

**(2) Steps to reproduce (if you know):**

0. Start with a fresh session with tiling disabled.
1. Open a new window (terminal will do).
2. Enable tiling.
3. Create a stack.
![image](https://user-images.githubusercontent.com/8212170/98625805-489ea880-2308-11eb-981c-46e773147cc3.png)
4. Add a new window/terminal.
![image](https://user-images.githubusercontent.com/8212170/98625794-42a8c780-2308-11eb-8e69-2b530caa3a7b.png)
5. Drag the new window/terminal to the left or right side of the screen.
![image](https://user-images.githubusercontent.com/8212170/98625828-57855b00-2308-11eb-8818-e17c1db13b83.png)
6. Click the stack switcher (maybe back and forth a few times, but often just one click will do it).
7. Crash.

**(3) Expected behavior:**

No crash. Also the window that is dragged to the side should conform to tiling layout.

**(4) Distribution (run `cat /etc/os-release`):**

```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**

```
GNOME Shell 3.38.1
```

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.0.0~1604688242~20.10~d1d2b0e
  Candidate: 1.0.0~1604688242~20.10~d1d2b0e
  Version table:
 *** 1.0.0~1604688242~20.10~d1d2b0e 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

Pop!_OS 20.10

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

This happens with just the built-in display on my Darter Pro and it also happens with my external 4k monitor.

**(9) Other Installed/Enabled Extensions:**

I disabled all extensions before submitting the bug report, the issue persists with and without extensions (except for the pop shell extension of course).

**(10) Other Notes:**
 
I like the stacking feature!

**Comment by mmstick** [comment]
If your journald logs for gnome-shell mention an error with freeze / thaw, this is another case of the issue fixed in 3.38.2

**Comment by bryanpaget** [comment]
Aha!

![image](https://user-images.githubusercontent.com/8212170/98626432-aa134700-2309-11eb-9427-eca0c8f78e9e.png)

Thanks!

**Comment by bryanpaget** [comment]
I think the dragging behaviour could be more elegant. I'm sure someone is working on that though. :-)

**Comment by mmstick** [comment]
Another case of #647

**Comment by sitepodmatt** [comment]
This happens if you open either Firefox/Chrome (doesnt matter if HW accelerated or not), and another app, put them into a stacking mode, maximize the browser than try to alt+tab to the other app. Consistent crash.

**Comment by sitepodmatt** [comment]
@mmstick how do we get our hands on 3.38.2?

**Comment by mmstick** [comment]
Waiting on Ubuntu to release it. I monitor their git repository daily, but there hasn't been any activity on that yet.
