### ISSUE TITLE
gnome-terminal window height not set correctly

### ISSUE THREAD

**Issue by lmachegger** [pop-os/shell#702]
**(1) Issue/Bug Description:**
gnome-terminal's window size is not set to the correct height. It is always a tiny bit smaller than what it should be.
See the attached screenshots: [https://imgur.com/a/Lmk2rm4](https://imgur.com/a/Lmk2rm4)

**(2) Steps to reproduce (if you know):**
Open gnome-terminal and some other applications with active tiling.

**(3) Expected behavior:**
Both windows should have the same height.

**(4) Distribution (run `cat /etc/os-release`):**
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux

**(5) Gnome Shell version:**
```
<?xml version="1.0"?>
<gnome-version>
 <platform>3</platform>
 <minor>38</minor>
 <micro>1</micro>
 <distributor>Arch Linux</distributor>
 <!--<date></date>-->
</gnome-version>
```

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

community/gnome-shell-extension-pop-shell 1.0.0-1 

**(7) Where was Pop Shell installed from:**
It came installed with manjaro gnome.

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1x 2560 x 1440

**(9) Other Installed/Enabled Extensions:**
- ArcMenu
- Dash to Panel
- KStatusNotifierItem/AppIndicator Support
- Pamac Updates Indicator
- Pop Shell
- User Themes
- Workspace Indicator

**(10) Other Notes:**

**Comment by jacobgkau** [comment]
GNOME Terminal forces its own size to be an increment of a character. We patch GNOME Terminal in Pop!_OS to not do this, but I'm not sure there's anything we can do about it on Manjaro. (We've tried ignoring windows' own sizing restrictions before, but it caused too many other issues.)

The Pop!_OS patch is currently not working 100% of the time, and I opened https://github.com/pop-os/gnome-terminal/issues/2 about that yesterday.

**Comment by lmachegger** [comment]
Thanks for clarifying! 

It seems like the Manjaro Team is not planning on patching gnome-terminal.
The best solution is probably to just use another terminal-app.

Which is a bit sad, since gnome-terminal is integrated into the right-click-menu from nautilus ("open in terminal") and i haven't found a nice way of changing the terminal that this context-menu opens.

Anyway, since this is a problem with gnome-terminal, I'm going to close this issue, as there is not much pop-shell can do about it!

Thanks.
