### ISSUE TITLE
Cannot make local-install

### ISSUE THREAD

**Issue by prismspecs** [pop-os/shell#703]
**(1) Issue/Bug Description:**

```
grayson@schlinux:~/Desktop/workbench/shell$ sudo make local-install
UUID is "pop-shell@system76.com"
depcheck
rm -rf _build schemas/gschemas.compiled target
tsc
for proj in color_dialog floating_exceptions; do tsc --p src/${proj}; done
sh scripts/transpile.sh
glib-compile-schemas schemas
touch schemas
rm -rf _build
mkdir -p _build
cp -r metadata.json icons schemas target/*.js imports/*.js *.css _build
for proj in color_dialog floating_exceptions; do \
	mkdir -p _build/${proj}; \
	cp -r target/${proj}/*.js _build/${proj}; \
done
rm -rf /root/.local/share/gnome-shell/extensions/pop-shell@system76.com
mkdir -p /root/.local/share/gnome-shell/extensions/pop-shell@system76.com
cp -r _build/* /root/.local/share/gnome-shell/extensions/pop-shell@system76.com/
sh scripts/configure.sh
+ set_keybindings
+ shortcut_applied
+ test -f ./.confirm_shortcut_change
+ read -p Pop shell will override your default shortcuts. Are you sure? (y/n)  CONT
Pop shell will override your default shortcuts. Are you sure? (y/n) y
+ test y = y
+ touch ./.confirm_shortcut_change
+ return 1
+ left=h
+ down=j
+ up=k
+ right=l
+ KEYS_GNOME_WM=/org/gnome/desktop/wm/keybindings
+ KEYS_GNOME_SHELL=/org/gnome/shell/keybindings
+ KEYS_MUTTER=/org/gnome/mutter/keybindings
+ KEYS_MEDIA=/org/gnome/settings-daemon/plugins/media-keys
+ KEYS_MUTTER_WAYLAND_RESTORE=/org/gnome/mutter/wayland/keybindings/restore-shortcuts
+ dconf write /org/gnome/mutter/wayland/keybindings/restore-shortcuts @as []
+ dconf write /org/gnome/desktop/wm/keybindings/minimize @as ['<Super>comma']
+ dconf write /org/gnome/shell/keybindings/open-application-menu @as []
+ dconf write /org/gnome/shell/keybindings/toggle-message-tray @as ['<Super>v']
+ dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-left @as []
+ dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-right @as []
+ dconf write /org/gnome/desktop/wm/keybindings/move-to-monitor-up @as []
+ dconf write /org/gnome/desktop/wm/keybindings/move-to-monitor-down @as []
+ dconf write /org/gnome/desktop/wm/keybindings/move-to-monitor-left @as []
+ dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-down @as []
+ dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-up @as []
+ dconf write /org/gnome/desktop/wm/keybindings/move-to-monitor-right @as []
+ dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-down ['<Primary><Super>Down','<Primary><Super>j']
+ dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-up ['<Primary><Super>Up','<Primary><Super>k']
+ dconf write /org/gnome/mutter/keybindings/toggle-tiled-left @as []
+ dconf write /org/gnome/mutter/keybindings/toggle-tiled-right @as []
+ dconf write /org/gnome/desktop/wm/keybindings/toggle-maximized ['<Super>m']
+ dconf write /org/gnome/settings-daemon/plugins/media-keys/screensaver ['<Super>Escape']
+ dconf write /org/gnome/settings-daemon/plugins/media-keys/home ['<Super>f']
+ dconf write /org/gnome/settings-daemon/plugins/media-keys/email ['<Super>e']
+ dconf write /org/gnome/settings-daemon/plugins/media-keys/www ['<Super>b']
+ dconf write /org/gnome/settings-daemon/plugins/media-keys/rotate-video-lock-static @as []
+ dconf write /org/gnome/desktop/wm/keybindings/close ['<Super>q']
+ gnome-extensions list
+ grep native-window
Failed to connect to GNOME Shell
+ dconf write /org/gnome/mutter/workspaces-only-on-primary false
gnome-extensions enable "pop-shell@system76.com"
Failed to connect to GNOME Shell
make: *** [Makefile:61: enable] Error 2
```

**(2) Steps to reproduce (if you know):**

**(3) Expected behavior:**

**(4) Distribution (run `cat /etc/os-release`):**
 

**(5) Gnome Shell version:**

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**(7) Where was Pop Shell installed from:**

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

**Comment by mmstick** [comment]
> Failed to connect to GNOME Shell

Something's wrong with your system

**Comment by matas-valuzis** [comment]
I had same issues installing on Ubuntu 20.10. Make sure you run `make local-install` as local user (without sudo). If you get error `Extension “pop-shell@system76.com” does not exist
`  just run alt+F2 and enter `r` command. After gnome shell restarts you can enable pop shell by running `gnome-extensions enable "pop-shell@system76.com"` or `gnome-tweaks` and enable it in extensions menu.

**Comment by jmmaranan** [comment]
This happens if the extension is not available beforehand. Since pop typically comes with the shell in /usr/ you just have to logout and back in. And then GNOME tweaks, enable.

There is something that needs to be fixed on the Makefile. But this is the workaround for non pop os users.

**Comment by prismspecs** [comment]
> > Failed to connect to GNOME Shell
> 
> Something's wrong with your system

It's a literal fresh install of ubuntu 20.10

**Comment by prismspecs** [comment]
matas-valuzis solution worked.

GNOME Shell 3.38.1

Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy

**Comment by jacobgkau** [comment]
If restarting GNOME Shell fixed the issue, then https://github.com/pop-os/shell/pull/782 should address this. If the issue turns out to be something else, please let us know and we can re-open.

**Comment by afonsojramos** [comment]
> I had same issues installing on Ubuntu 20.10. Make sure you run make local-install as local user (without sudo). If you get error Extension “pop-shell@system76.com” does not exist just run alt+F2 and enter r command. After gnome shell restarts you can enable pop shell by running gnome-extensions enable "pop-shell@system76.com" or gnome-tweaks and enable it in extensions menu.

Thanks @matas-valuzis!

**Comment by mwetzel7r** [comment]
> I had same issues installing on Ubuntu 20.10. Make sure you run `make local-install` as local user (without sudo). If you get error `Extension “pop-shell@system76.com” does not exist ` just run alt+F2 and enter `r` command. After gnome shell restarts you can enable pop shell by running `gnome-extensions enable "pop-shell@system76.com"` or `gnome-tweaks` and enable it in extensions menu.

worked perfectly for me

**Comment by Nakamerica** [comment]
> I had same issues installing on Ubuntu 20.10. Make sure you run `make local-install` as local user (without sudo). If you get error `Extension “pop-shell@system76.com” does not exist ` just run alt+F2 and enter `r` command. After gnome shell restarts you can enable pop shell by running `gnome-extensions enable "pop-shell@system76.com"` or `gnome-tweaks` and enable it in extensions menu.

thank you, this worked for me even today on gnome-shell --version 41.4 running on EndeavourOS.

**Comment by dfo-db** [comment]
> I had same issues installing on Ubuntu 20.10. Make sure you run `make local-install` as local user (without sudo). If you get error `Extension “pop-shell@system76.com” does not exist ` just run alt+F2 and enter `r` command. After gnome shell restarts you can enable pop shell by running `gnome-extensions enable "pop-shell@system76.com"` or `gnome-tweaks` and enable it in extensions menu.

My issue was a bit different where it would just show a black screen with a load of @ symbols. Solved by pressing ctrl + c, which takes you to the log in screen. Then just open a terminal and use the gnome-extensions terminal command above. Works!
