### ISSUE TITLE
how to install and uninstall ?

### ISSUE THREAD

**Issue by noelzubin** [pop-os/shell#71]
Is the rebuild.sh the script to build and install the extension. How do i completely uninstall the extension once installed.

**Comment by danto7** [comment]
First you need to build the extension with `make all`.
Then you have to install it with `make install` and enable it with `make enable` and restart your shell with `make restart-shell`. (Before restarting your shell please save all your work)
On my machine took around 1 min to get gnome up again.
To disable again type `make disable && make uninstall`

**Comment by mmstick** [comment]
@danto7 You have to run `sh rebuild.sh`, which calls `make` for you. This is necessary to install Pop Shell properly because it also sets the necessary keyboard shortcuts and overrides.

**Comment by danto7** [comment]
oooh I see. Thanks :)

**Comment by noelzubin** [comment]
The `make uninstall` doesn't revert the keyboard shortcut changes, does it ?
Is this a problem ?

**Comment by lriverawong** [comment]
I am using Gnome 3.36 and to revert the keyboard shortcuts go to `Settings` -> `Keyboard Shortcuts` -> `Reset All...`
That should reset your keyboard shortcuts to the default.

**Comment by lriverawong** [comment]
Can someone please close this issue?
