### ISSUE TITLE
Cannot move application with mouse when "show window titles" is off

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#72]
When "Show window titles" is off, VSCode only has the menu bar available. Dragging the application by the menu bar or by any other element of its UI does not move it around/ tile it somewhere else on the screen.

P.S Thanks for building such an intuitive tiling extension. Everything about it is fantastic.

**Comment by Benguin** [comment]
Possible workaround: hold the super key and drag anywhere on the window. The modifier key may be different for you (ALT for instance).

**Comment by mmstick** [comment]
It's always Super. No one should be binding shortcuts to alt because they're reserved for application shortcuts.
