### ISSUE TITLE
Double gap pixels on HiDPI displays

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/shell#73]
It appears gaps need to be doubled on HiDPI displays for a consistent gap appearance.

**Comment by leviport** [comment]
Should this be only when HiDPI scaling is enabled? Doubled gaps might be a little big for those who use 100% scaled HiDPI displays.

**Comment by mmstick** [comment]
It's currently scaling by the shell's scaling factor

**Comment by WatchMkr** [comment]
@mmstick I think you're right. I compare my HiDPI and non-HiDPI Galago's to be sure and re-open if necessary.
