### ISSUE TITLE
Add stacking shortcut to shortcuts hint dialog & gnome settings

### ISSUE THREAD

**Issue by daveriedstra** [pop-os/shell#730]
**(1) Issue/Bug Description:**
The shortcut for stacking / tabbed windows (which is `super+s` for future googlers) isn't in the shortcuts hint dialogue, nor is it in the Gnome keyboard settings.

**(2) Steps to reproduce (if you know):**
* look for the shortcut in the shortcut hints
* cannot find the shortcut
* look for the shortcut in gnome-settings
* cannot find the shortcut

**(3) Expected behavior:**
* find the shortcut

**(4) Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**
3.38.1

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.0.0~1605292722~20.10~e1a9db9
  Candidate: 1.0.0~1605292722~20.10~e1a9db9
  Version table:
 *** 1.0.0~1605292722~20.10~e1a9db9 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**
With OS

**Comment by ids1024** [comment]
This was actually added in both places in Focal, but it seems those changes didn't make it into the Groovy package. `pop-shell-shortcuts` should be fixed now, and https://github.com/pop-os/shell/pull/734 should add the bindings in gnome-control-center.

Thanks for pointing it out!
