### ISSUE TITLE
Tiling and/or stacking going rouge

### ISSUE THREAD

**Issue by Pivion** [pop-os/shell#731]
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

gnome:
  Installed: (none)
  Candidate: 1:3.30+3
  Version table:
     1:3.30+3 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/universe amd64 Packages

**Issue/Bug Description:**
Tiling with stacking goes rouge after some time. stack tabs strip stays in place but windows can be dragged and resized out of tile and do not snap to place. other stack tabs cannot be switched, and turning tiling on and off does not do anything 

**Steps to reproduce (if you know):**

dont know, appears to happen randomly

edit:
Might be caused by poping out chrome tab to a window

**Expected behavior:**

turning tiling off should let all windows go to floating mode and tiling stack should dissapear
when turning tiling back on windows should snap back into place filling the screens

**Other Notes:**

I have two 4K displays connected to MSI GT1030 if that has any significance
I have updated from 20.04 to 20.10 from pop shop
Only way that i found to reset the issue is to logout or restart system

knowing where logs (if are any) for tiling and/or stacking are would help

**Comment by mmstick** [comment]
You can watch logs with

```
journalctl -o cat -n 0 -f "$$(which gnome-shell)" | grep -v warning
```

**Comment by Pivion** [comment]
clutter_actor_hide: assertion 'CLUTTER_IS_ACTOR (self)' failed
Object St.Bin (0x5583103b1730), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
clutter_actor_hide: assertion 'CLUTTER_IS_ACTOR (self)' failed
Object St.Bin (0x55831160de80), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x55830d68c220 ==
#0   55830f81f8b8 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/window.js:368 (3791139a4830 @ 51)
#1   55830f81f7f0 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:569 (379113983790 @ 107)
#2   55830f81f758 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:561 (3791139837e0 @ 23)
#3   55830f81f690 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:511 (379113983a10 @ 599)
#4   55830f81f5f8 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1231 (379113982470 @ 56)
== Stack trace for context 0x55830d68c220 ==
#0   7ffe3b0533f0 b   /usr/share/gnome-shell/extensions/pop-shell@system76.com/window.js:368 (3791139a4830 @ 51)
#1   7ffe3b053a90 b   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:569 (379113983790 @ 107)
#2   55830f81f758 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:561 (3791139837e0 @ 23)
#3   55830f81f690 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:511 (379113983a10 @ 599)
#4   55830f81f5f8 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1231 (379113982470 @ 56)
== Stack trace for context 0x55830d68c220 ==
#0   7ffe3b0539c0 b   /usr/share/gnome-shell/extensions/pop-shell@system76.com/window.js:368 (3791139a4830 @ 51)
#1   7ffe3b053a90 b   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:569 (379113983790 @ 107)
#2   55830f81f758 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:561 (3791139837e0 @ 23)
#3   55830f81f690 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:511 (379113983a10 @ 599)
#4   55830f81f5f8 i   /usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1231 (379113982470 @ 56)

**Comment by mmstick** [comment]
Is this still an issue today?

**Comment by Pivion** [comment]
no, the issue got fixed with some update
