### ISSUE TITLE
Correct gpl3 license for nix package manager

### ISSUE THREAD

**Issue by remunds** [pop-os/shell#738]
Hi, i am currently packaging pop-os-shell for nix (see  https://github.com/NixOS/nixpkgs/pull/104160).
During review they pointed out that gpl3 is unclear and that it could be either gpl3-only or gpl3-or-later.

Just GPL is ambiguous: https://gnu.org/licenses/identify-licenses-clearly.html.

The GPL-3-or-later is strongly recommended by GNU Foundation: https://www.gnu.org/licenses/gpl-faq.html.en#VersionThreeOrLater

Could you please let me know which license is meant in this case?

**Comment by mmstick** [comment]
GPL3-only
