### ISSUE TITLE
Remapped escape key does not close launcher

### ISSUE THREAD

**Issue by jfkimmes** [pop-os/shell#74]
Hi,
I have remapped my caps-lock to be an additional ESC key and I realized that the remapped escape key does not close the launcher.

I had a look at the code and it seems that in `search.ts` you are checking the hardware keycode on the `key-press-event`:

```js
let c = event.get_key_code();
            if (c == 9) {
                this.reset();
                this.close();
                cancel();
                return;
            }
```
I don't really know anything about mutter but I had a quick look at the documentation and it seems that there is a differentiation between the hardware key code and a key symbol.
 
By checking on the symbol you might be independent from user's remapping their keys. 

In a quick test

```js
log.error("PRESSED CODE:" + event.get_key_code());
log.error("PRESSED SYMBOL:" + event.get_key_symbol());
```
I got the right results:

![image](https://user-images.githubusercontent.com/19751637/76709614-5f9ce480-6700-11ea-9d03-a4937cd83d4f.png)

Do you see any obvious problems with this approach? 

Best regards!

P.S. Thank you for this amazing project. I just stumbled upon it today and it works amazingly well, already! I've been looking for a i3+GNOME combo for a long time.

**Comment by mmstick** [comment]
Seems fine to me. Want to submit a merge request?
