### ISSUE TITLE
Failed to set address: No such file or directory

### ISSUE THREAD

**Issue by eduardoArgenton** [pop-os/shell#742]
I'm trying to install this extension on Solus with gnome 3.36.5. But always return this:

Failed to set address: No such file or directory
make: *** [Makefile:81: restart-shell] Erro 1

Can anyone help me?

**Comment by illuminati1546** [comment]
echo "Restart shell!"
Restart shell!
if bash -c 'xprop -root &> /dev/null'; then \
	busctl --user call org.gnome.Shell /org/gnome/Shell org.gnome.Shell Eval s 'Meta.restart("Restarting Gnome...")'; \
else \
	gnome-session-quit --logout; \
fi
Failed to set address: No such file or directory
make: *** [Makefile:81: restart-shell] Error 1


am facing the same issue. help anyone

many thanks in advance.

**Comment by julianferres** [comment]
Are you running the installer with sudo? 

In that case, please remove _build and target folders (in case they are in the shell folder) and rerun without sudo (`make local-install`)
