### ISSUE TITLE
Tile Window just desapeared 

### ISSUE THREAD

**Issue by rtheodoro** [pop-os/shell#744]
Hi!

I have been using Pop!_OS 20.1 for a few weeks.

But few days ago, suddenly the Tile Window just desapeared and some keyboard shortcuts too (like ctrl + shift + right).
Does anyone has this problem? How can I solve?

```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```
GNOME Shell 3.38.1

```
pop-shell:
  Instalado: 1.0.0~1605809546~20.10~1a8b13f
  Candidato: 1.0.0~1605809546~20.10~1a8b13f
  Tabela de versão:
 *** 1.0.0~1605809546~20.10~1a8b13f 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status
```
Multi Monitors Add On and Sound Input and Output Device Chooser

**Comment by rtheodoro** [comment]
Solved with: https://github.com/pop-os/gnome-control-center/issues/130
> So I'm pretty sure ldconfig should be run without any manual intervention or changes to the package. Not sure why that isn't (consistently) working...

**Comment by max-weber** [comment]
Hello people!
Hello people!
I need help, i have been using Pop!_OS 20.10 and my pop-shell extension stoped work :/

NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

![image](https://user-images.githubusercontent.com/55796559/100674104-64afcb80-3343-11eb-8c2a-17f02bb0c11a.png)



> The settings of extension pop-shell@system76.com had an error:
> ```
> Error: Schema org.gnome.shell.extensions.pop-shell could not be found for extension pop-shell@system76.com. Please check your installation
> ```
> 
> Stack trace:
> ```
> getSettings@resource:///org/gnome/Shell/Extensions/js/misc/extensionUtils.js:151:15
> log_level@/usr/share/gnome-shell/extensions/pop-shell@system76.com/log.js:11:35
> logging_combo@/usr/share/gnome-shell/extensions/pop-shell@system76.com/prefs.js:117:33
> settings_dialog_view@/usr/share/gnome-shell/extensions/pop-shell@system76.com/prefs.js:73:18
> settings_dialog_new@/usr/share/gnome-shell/extensions/pop-shell@system76.com/prefs.js:9:23
> buildPrefsWidget@/usr/share/gnome-shell/extensions/pop-shell@system76.com/prefs.js:127:18
> _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
> OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
> asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
> run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
> main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
> run@resource:///org/gnome/gjs/modules/script/package.js:222:19
> start@resource:///org/gnome/gjs/modules/script/package.js:206:8
> @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
