### ISSUE TITLE
the screen freezes when I drag a file

### ISSUE THREAD

**Issue by rtheodoro** [pop-os/shell#745]
My screen freezes every time I drag a file from my computer to a program (like Firefox or OBS Studio).
I need to reboot my system to work again.

```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```
GNOME Shell 3.38.1

```
pop-shell:
  Instalado: 1.0.0~1605809546~20.10~1a8b13f
  Candidato: 1.0.0~1605809546~20.10~1a8b13f
  Tabela de versão:
 *** 1.0.0~1605809546~20.10~1a8b13f 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status
```
Multi Monitors Add On and Sound Input and Output Device Chooser

**Comment by jacobgkau** [comment]
This repository is for the tiling window manager extension, Pop Shell. This issue doesn't sound like it's related to Pop Shell-- if you disable Pop Shell in the Extensions app, does the issue still occur?

> Multi Monitors Add On and Sound Input and Output Device Chooser

Does the issue still occur if you disable these two third-party extensions?

> I need to reboot my system to work again.

If you restart GNOME Shell by pressing Alt-F2, r, and Enter, does that bring the system back without having to reboot entirely?

When you say the issue occurs when you drag a file from "my computer", do you mean from the desktop, from the Files app, or both? If it's the desktop, can you please provide the output of this command to make sure you're running the correct version of the desktop icons extension included with Pop!_OS:

```
apt policy gnome-shell-extension-desktop-icons-ng gnome-shell-extension-desktop-icons
```

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by rtheodoro** [comment]
> Does the issue still occur if you disable these two third-party extensions?

Yes!

> If you restart GNOME Shell by pressing Alt-F2, r, and Enter, does that bring the system back without having to reboot entirely?

No, nothing happens when I press Alt-F2. 

> When you say the issue occurs when you drag a file from "my computer", do you mean from the desktop, from the Files app, or both? 

Both!

```
$apt policy gnome-shell-extension-desktop-icons-ng gnome-shell-extension-desktop-icons

gnome-shell-extension-desktop-icons-ng:
  Instalado: 0.14.0~1605122430~20.10~fe84f29
  Candidato: 0.14.0~1605122430~20.10~fe84f29
  Tabela de versão:
 *** 0.14.0~1605122430~20.10~fe84f29 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status
gnome-shell-extension-desktop-icons:
  Instalado: (nenhum)
  Candidato: 0.14.0~1605122430~20.10~fe84f29
  Tabela de versão:
     20.04.0+git20200908-1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/main amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu groovy/main i386 Packages
     0.14.0~1605122430~20.10~fe84f29 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
```

**Comment by rtheodoro** [comment]
Solved:

I just put `sudo ldconfig`, updated everything and rebooted my system.

As said in another problem:
https://github.com/pop-os/gnome-control-center/issues/130
