### ISSUE TITLE
Add configurable or more international keybindings

### ISSUE THREAD

**Issue by Chrysostomus** [pop-os/shell#75]
Some of the keybindings are really in accessible with certain keyboard layouts. For example, in finnish layout / is produced with shift+7 and ~ is produced with alt_gr+"+space. This makes some of the keybindings practically inaccessible. 

It would be better to have configurable keybindings, so that people outside USA can set the bindings suitable to their keyboard layout.  Other than that, using more generic keybindings like super+t (toggle tiling/floating) could be useful.

**Comment by mmstick** [comment]
That particular key is going to be replaced soon

**Comment by mmstick** [comment]
The key is currently mapped to the default of `G`. If you want to, you can use gsettings to change any of the default key bindings in this extension.

**Comment by Chrysostomus** [comment]
Thanks!
