### ISSUE TITLE
Some gnome default shortcuts aren't being disabled after make local-install

### ISSUE THREAD

**Issue by rodzappa** [pop-os/shell#751]
**(1) Issue/Bug Description:**

Gnome (3.38.1 on Ubuntu 20.10 and possibly other releases) has some default keyboard shortcuts in conflicting with pop-shell shortcuts. Make local-install is not disabling these shortcuts, notably these:

- super + s: showing workspaces, instead of toggling stacking;
- super + up: resizing (increasing) window, instead of selecting window above;
- super + down: resizing (decreasing) window, instead of selecting window bellow;

**(2) Steps to reproduce (if you know):**
- Clone master branch, run make local-install and reload gnome-shell

**(3) Expected behavior:**
- Gnome default shortcuts have to be disabled in order to not breaking pop-shell behavior.

**(4) Distribution (run `cat /etc/os-release`):**
```
NAME="Ubuntu"
VERSION="20.10 (Groovy Gorilla)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.10"
VERSION_ID="20.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
```

**(5) Gnome Shell version:**
```
3.38.1-1ubuntu1.1
```

**(6) Pop Shell version:**
```
commit ee943b87bd00b2bb7b3ecf970f4f88741346982e (HEAD -> master, origin/master, origin/HEAD)
Author: Michael Aaron Murphy <mmstick@pm.me>
Date:   Mon Nov 23 10:01:42 2020 -0700

    fix: Handle regression in 3.38.2 backports that caused nautilus to resize without moving
```

**(7) Where was Pop Shell installed from:**

Github repo: https://github.com/pop-os/shell.git

**(8) Monitor Setup:**

- Left Monitor: 1680x1050
- Right Monitor: 1920x1200

**(9) Other Installed/Enabled Extensions:**
```
$ gnome-extensions list --enabled
pop-shell@system76.com
sound-output-device-chooser@kgshank.net
system-monitor@paradoxxx.zero.gmail.com
ubuntu-appindicators@ubuntu.com
native-window-placement@gnome-shell-extensions.gcampax.github.com
GPaste@gnome-shell-extensions.gnome.org
```

**(10) Other Notes:**

Manuaally disabling conflicting gnome shortcuts, solves this issue.

**Comment by mphojele** [comment]
I can reproduce the issue on Fedora 33 with shell from master at commit specified above. Can also confirm that your fix works. The issue seems trivial, the aforementioned keys are not included in those disabled in `scripts/configure.sh`
