### ISSUE TITLE
Gaps causes Firefox, Nautilus and other applications resizing themselves.

### ISSUE THREAD

**Issue by laichiaheng** [pop-os/shell#752]
**(1) Issue/Bug Description:**
Nautilus resizes itself when I open a new window and see the window overview.
Firefox resizes itself when I open a new window and close it, and see the window overview.
https://youtu.be/hgPXa0A5dDo

**(2) Steps to reproduce (if you know):**
1. Open a new window for Firefox or Nautilus.
2. See the workspace overview like how I did in the video above.
3. Go back to the window.

**(3) Expected behavior:**
It doesn't resize itself.

**(4) Distribution (run `cat /etc/os-release`):**
```
 NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```

**(5) Gnome Shell version:**
3.38.2

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
Name            : gnome-shell-extension-pop-shell-git
Version         : r613.ee943b8-1
Description     : Pop Shell - Tiling window management in Gnome (WIP)
Architecture    : any
URL             : https://github.com/pop-os/shell
Licenses        : GPLv3
Groups          : None
Provides        : None
Depends On      : gnome-shell  pop-shell-shortcuts-git
Optional Deps   : gnome-shell-extensions: native-window extension for improved window placement
                  [installed]
Required By     : None
Optional For    : None
Conflicts With  : gnome-shell-extension-pop-shell
Replaces        : None
Installed Size  : 863.63 KiB
Packager        : Unknown Packager
Build Date      : Wed Dec 2 08:42:15 2020
Install Date    : Wed Dec 2 08:42:25 2020
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : None
```

**(7) Where was Pop Shell installed from:**
AUR

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1 x 1080p

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

It has never happened to the old version of Pop Shell.
I also noticed that it happened to other applications.

It is caused by the outer gap.

**Comment by laichiaheng** [comment]
If I set the gap to 0, it doesn't happen.

**Comment by REIS0** [comment]
Can confirm this also happening in Pop_OS! 20.04

**Comment by laichiaheng** [comment]
I suggest the development team to fix these bugs before adding new features.

**Comment by mmstick** [comment]
Is this still an issue for you? I've not been able to replicate it.

**Comment by laichiaheng** [comment]
@mmstick It has been fixed, thanks.

**Comment by sssemil** [comment]
Still happens with firefox, leaves black boxes sometimes.
