### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by BlackHawk185** [pop-os/shell#758]
**(1) Issue/Bug Description:**
Installation failure

**(2) Steps to reproduce (if you know):**
Cloned from this repo, sudo make local-install

**(3) Expected behavior:**
 Clean Installation

**(4) Distribution (run `cat /etc/os-release`):**
 NAME="Solus"
VERSION="4.1"
ID="solus"
VERSION_CODENAME=fortitude
VERSION_ID="4.1"
PRETTY_NAME="Solus 4.1 Fortitude"
ANSI_COLOR="1;34"
HOME_URL="https://getsol.us"
SUPPORT_URL="https://getsol.us/articles/contributing/getting-involved/en/"
BUG_REPORT_URL="https://dev.getsol.us/"

**(5) Gnome Shell version:**
GNOME Shell 3.38.1

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**(7) Where was Pop Shell installed from:**
Local

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

**(9) Other Installed/Enabled Extensions:**
Default by OS, will list more if needed

**(10) Other Notes:**

+ dconf write /org/gnome/mutter/workspaces-only-on-primary false
gnome-extensions enable "pop-shell@system76.com"
Failed to connect to GNOME Shell

**Comment by mmstick** [comment]
Don't use sudo
