### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by BlackHawk185** [pop-os/shell#759]
**(1) Issue/Bug Description:**
Installation failure

**(2) Steps to reproduce (if you know):**
Cloned from this repo, make local-install

**(3) Expected behavior:**
 Clean Installation

**(4) Distribution (run `cat /etc/os-release`):**
 NAME="Solus"
VERSION="4.1"
ID="solus"
VERSION_CODENAME=fortitude
VERSION_ID="4.1"
PRETTY_NAME="Solus 4.1 Fortitude"
ANSI_COLOR="1;34"
HOME_URL="https://getsol.us"
SUPPORT_URL="https://getsol.us/articles/contributing/getting-involved/en/"
BUG_REPORT_URL="https://dev.getsol.us/"

**(5) Gnome Shell version:**
GNOME Shell 3.38.1

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**(7) Where was Pop Shell installed from:**
Local

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

**(9) Other Installed/Enabled Extensions:**
Default by OS, will list more if needed

**(10) Other Notes:**

UUID is "pop-shell@system76.com"
depcheck
rm -rf _build schemas/gschemas.compiled target
rm: cannot remove '_build/log.js': Permission denied
rm: cannot remove '_build/dialog_launcher.js': Permission denied
rm: cannot remove '_build/color_dialog/main.js': Permission denied
rm: cannot remove '_build/stack.js': Permission denied
rm: cannot remove '_build/dialog_add_exception.js': Permission denied
rm: cannot remove '_build/dialog_search.js': Permission denied
rm: cannot remove '_build/shell.js': Permission denied
rm: cannot remove '_build/keybindings.js': Permission denied
rm: cannot remove '_build/once_cell.js': Permission denied
rm: cannot remove '_build/ecs.js': Permission denied
rm: cannot remove '_build/floating_exceptions/main.js': Permission denied
rm: cannot remove '_build/floating_exceptions/utils.js': Permission denied
rm: cannot remove '_build/floating_exceptions/config.js': Permission denied
rm: cannot remove '_build/grab_op.js': Permission denied
rm: cannot remove '_build/icons/pop-shell-auto-on-symbolic.svg': Permission denied
rm: cannot remove '_build/icons/pop-shell-auto-off-symbolic.svg': Permission denied
rm: cannot remove '_build/tags.js': Permission denied
rm: cannot remove '_build/arena.js': Permission denied
rm: cannot remove '_build/schemas/gschemas.compiled': Permission denied
rm: cannot remove '_build/schemas/org.gnome.shell.extensions.pop-shell.gschema.xml': Permission denied
rm: cannot remove '_build/extension.js': Permission denied
rm: cannot remove '_build/events.js': Permission denied
rm: cannot remove '_build/result.js': Permission denied
rm: cannot remove '_build/node.js': Permission denied
rm: cannot remove '_build/panel_settings.js': Permission denied
rm: cannot remove '_build/xprop.js': Permission denied
rm: cannot remove '_build/metadata.json': Permission denied
rm: cannot remove '_build/light.css': Permission denied
rm: cannot remove '_build/movement.js': Permission denied
rm: cannot remove '_build/settings.js': Permission denied
rm: cannot remove '_build/tweener.js': Permission denied
rm: cannot remove '_build/tiling.js': Permission denied
rm: cannot remove '_build/error.js': Permission denied
rm: cannot remove '_build/utils.js': Permission denied
rm: cannot remove '_build/launcherext.js': Permission denied
rm: cannot remove '_build/app_info.js': Permission denied
rm: cannot remove '_build/executor.js': Permission denied
rm: cannot remove '_build/fork.js': Permission denied
rm: cannot remove '_build/prefs.js': Permission denied
rm: cannot remove '_build/shortcut_overlay.js': Permission denied
rm: cannot remove '_build/window.js': Permission denied
rm: cannot remove '_build/widgets.js': Permission denied
rm: cannot remove '_build/math.js': Permission denied
rm: cannot remove '_build/rectangle.js': Permission denied
rm: cannot remove '_build/forest.js': Permission denied
rm: cannot remove '_build/lib.js': Permission denied
rm: cannot remove '_build/focus.js': Permission denied
rm: cannot remove '_build/dark.css': Permission denied
rm: cannot remove '_build/geom.js': Permission denied
rm: cannot remove '_build/auto_tiler.js': Permission denied
rm: cannot remove '_build/config.js': Permission denied
rm: cannot remove 'target/tags.js.map': Permission denied
rm: cannot remove 'target/geom.d.ts': Permission denied
rm: cannot remove 'target/executor.js.map': Permission denied
rm: cannot remove 'target/window.d.ts': Permission denied
rm: cannot remove 'target/prefs.js.map': Permission denied
rm: cannot remove 'target/error.js.map': Permission denied
rm: cannot remove 'target/dialog_add_exception.js.map': Permission denied
rm: cannot remove 'target/log.js': Permission denied
rm: cannot remove 'target/app_info.d.ts': Permission denied
rm: cannot remove 'target/dialog_launcher.js': Permission denied
rm: cannot remove 'target/color_dialog/main.js': Permission denied
rm: cannot remove 'target/color_dialog/main.d.ts': Permission denied
rm: cannot remove 'target/color_dialog/tsconfig.tsbuildinfo': Permission denied
rm: cannot remove 'target/color_dialog/main.js.map': Permission denied
rm: cannot remove 'target/stack.js.map': Permission denied
rm: cannot remove 'target/lib.js.map': Permission denied
rm: cannot remove 'target/stack.js': Permission denied
rm: cannot remove 'target/panel_settings.d.ts': Permission denied
rm: cannot remove 'target/dialog_add_exception.js': Permission denied
rm: cannot remove 'target/dialog_search.js': Permission denied
rm: cannot remove 'target/log.js.map': Permission denied
rm: cannot remove 'target/shell.js': Permission denied
rm: cannot remove 'target/fork.d.ts': Permission denied
rm: cannot remove 'target/launcherext.js.map': Permission denied
rm: cannot remove 'target/xprop.d.ts': Permission denied
rm: cannot remove 'target/dialog_launcher.js.map': Permission denied
rm: cannot remove 'target/keybindings.js': Permission denied
rm: cannot remove 'target/node.js.map': Permission denied
rm: cannot remove 'target/ecs.d.ts': Permission denied
rm: cannot remove 'target/once_cell.js': Permission denied
rm: cannot remove 'target/events.js.map': Permission denied
rm: cannot remove 'target/result.d.ts': Permission denied
rm: cannot remove 'target/forest.js.map': Permission denied
rm: cannot remove 'target/shell.js.map': Permission denied
rm: cannot remove 'target/ecs.js': Permission denied
rm: cannot remove 'target/movement.d.ts': Permission denied
rm: cannot remove 'target/app_info.js.map': Permission denied
rm: cannot remove 'target/auto_tiler.d.ts': Permission denied
rm: cannot remove 'target/floating_exceptions/main.js': Permission denied
rm: cannot remove 'target/floating_exceptions/main.d.ts': Permission denied
rm: cannot remove 'target/floating_exceptions/utils.d.ts': Permission denied
rm: cannot remove 'target/floating_exceptions/tsconfig.tsbuildinfo': Permission denied
rm: cannot remove 'target/floating_exceptions/utils.js': Permission denied
rm: cannot remove 'target/floating_exceptions/utils.js.map': Permission denied
rm: cannot remove 'target/floating_exceptions/config.d.ts': Permission denied
rm: cannot remove 'target/floating_exceptions/main.js.map': Permission denied
rm: cannot remove 'target/floating_exceptions/config.js.map': Permission denied
rm: cannot remove 'target/floating_exceptions/config.js': Permission denied
rm: cannot remove 'target/utils.d.ts': Permission denied
rm: cannot remove 'target/extension.js.map': Permission denied
rm: cannot remove 'target/log.d.ts': Permission denied
rm: cannot remove 'target/rectangle.d.ts': Permission denied
rm: cannot remove 'target/grab_op.js': Permission denied
rm: cannot remove 'target/shortcut_overlay.js.map': Permission denied
rm: cannot remove 'target/tags.js': Permission denied
rm: cannot remove 'target/events.d.ts': Permission denied
rm: cannot remove 'target/settings.js.map': Permission denied
rm: cannot remove 'target/arena.js': Permission denied
rm: cannot remove 'target/xprop.js.map': Permission denied
rm: cannot remove 'target/error.d.ts': Permission denied
rm: cannot remove 'target/dialog_search.js.map': Permission denied
rm: cannot remove 'target/settings.d.ts': Permission denied
rm: cannot remove 'target/tweener.js.map': Permission denied
rm: cannot remove 'target/dialog_launcher.d.ts': Permission denied
rm: cannot remove 'target/focus.js.map': Permission denied
rm: cannot remove 'target/extension.js': Permission denied
rm: cannot remove 'target/tiling.js.map': Permission denied
rm: cannot remove 'target/events.js': Permission denied
rm: cannot remove 'target/result.js': Permission denied
rm: cannot remove 'target/stack.d.ts': Permission denied
rm: cannot remove 'target/node.js': Permission denied
rm: cannot remove 'target/panel_settings.js': Permission denied
rm: cannot remove 'target/xprop.js': Permission denied
rm: cannot remove 'target/window.js.map': Permission denied
rm: cannot remove 'target/once_cell.js.map': Permission denied
rm: cannot remove 'target/movement.js': Permission denied
rm: cannot remove 'target/movement.js.map': Permission denied
rm: cannot remove 'target/panel_settings.js.map': Permission denied
rm: cannot remove 'target/settings.js': Permission denied
rm: cannot remove 'target/once_cell.d.ts': Permission denied
rm: cannot remove 'target/tweener.js': Permission denied
rm: cannot remove 'target/tiling.js': Permission denied
rm: cannot remove 'target/error.js': Permission denied
rm: cannot remove 'target/shortcut_overlay.d.ts': Permission denied
rm: cannot remove 'target/tsconfig.tsbuildinfo': Permission denied
rm: cannot remove 'target/utils.js': Permission denied
rm: cannot remove 'target/launcherext.d.ts': Permission denied
rm: cannot remove 'target/dialog_search.d.ts': Permission denied
rm: cannot remove 'target/utils.js.map': Permission denied
rm: cannot remove 'target/widgets.js.map': Permission denied
rm: cannot remove 'target/launcherext.js': Permission denied
rm: cannot remove 'target/executor.d.ts': Permission denied
rm: cannot remove 'target/auto_tiler.js.map': Permission denied
rm: cannot remove 'target/arena.d.ts': Permission denied
rm: cannot remove 'target/forest.d.ts': Permission denied
rm: cannot remove 'target/app_info.js': Permission denied
rm: cannot remove 'target/shell.d.ts': Permission denied
rm: cannot remove 'target/rectangle.js.map': Permission denied
rm: cannot remove 'target/executor.js': Permission denied
rm: cannot remove 'target/fork.js': Permission denied
rm: cannot remove 'target/config.d.ts': Permission denied
rm: cannot remove 'target/keybindings.js.map': Permission denied
rm: cannot remove 'target/prefs.js': Permission denied
rm: cannot remove 'target/shortcut_overlay.js': Permission denied
rm: cannot remove 'target/node.d.ts': Permission denied
rm: cannot remove 'target/ecs.js.map': Permission denied
rm: cannot remove 'target/widgets.d.ts': Permission denied
rm: cannot remove 'target/prefs.d.ts': Permission denied
rm: cannot remove 'target/lib.d.ts': Permission denied
rm: cannot remove 'target/keybindings.d.ts': Permission denied
rm: cannot remove 'target/tiling.d.ts': Permission denied
rm: cannot remove 'target/window.js': Permission denied
rm: cannot remove 'target/widgets.js': Permission denied
rm: cannot remove 'target/grab_op.d.ts': Permission denied
rm: cannot remove 'target/grab_op.js.map': Permission denied
rm: cannot remove 'target/arena.js.map': Permission denied
rm: cannot remove 'target/extension.d.ts': Permission denied
rm: cannot remove 'target/rectangle.js': Permission denied
rm: cannot remove 'target/tags.d.ts': Permission denied
rm: cannot remove 'target/fork.js.map': Permission denied
rm: cannot remove 'target/forest.js': Permission denied
rm: cannot remove 'target/lib.js': Permission denied
rm: cannot remove 'target/config.js.map': Permission denied
rm: cannot remove 'target/focus.js': Permission denied
rm: cannot remove 'target/focus.d.ts': Permission denied
rm: cannot remove 'target/tweener.d.ts': Permission denied
rm: cannot remove 'target/geom.js.map': Permission denied
rm: cannot remove 'target/dialog_add_exception.d.ts': Permission denied
rm: cannot remove 'target/result.js.map': Permission denied
rm: cannot remove 'target/geom.js': Permission denied
rm: cannot remove 'target/auto_tiler.js': Permission denied
rm: cannot remove 'target/config.js': Permission denied
make: *** [Makefile:27: clean] Error 1

**Comment by mmstick** [comment]
Since you used sudo, you need to use sudo to remove the files owned by root.
