### ISSUE TITLE
Fails to Install

### ISSUE THREAD

**Issue by BlackHawk185** [pop-os/shell#760]
```<!--
If this is a bug, please use the template below. If this is a question or general discussion topic, please start a conversation in our chat https://chat.pop-os.org/ or post on our subreddit https://reddit.com/r/pop_os - as those are the proper forums for that type of discussion.
-->

**(1) Issue/Bug Description:**
Fails to Install


**(2) Steps to reproduce (if you know):**
make local-install


**(3) Expected behavior:**
Clean Install


**(4) Distribution (run `cat /etc/os-release`):**
 NAME="Solus"
VERSION="4.1"
ID="solus"
VERSION_CODENAME=fortitude
VERSION_ID="4.1"
PRETTY_NAME="Solus 4.1 Fortitude"
ANSI_COLOR="1;34"
HOME_URL="https://getsol.us"
SUPPORT_URL="https://getsol.us/articles/contributing/getting-involved/en/"
BUG_REPORT_URL="https://dev.getsol.us/"



**(5) Gnome Shell version:**
GNOME Shell 3.38.1



**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
<!--
Use triple back ticks ```<value here>``` to paste the apt policy pop-shell value, so it formats nicely
Pop-shell does not exist on the system



**(7) Where was Pop Shell installed from:**
ee943b87bd00b2bb7b3ecf970f4f88741346982e

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1 Monitor 1080p Horizontal


**(9) Other Installed/Enabled Extensions:**
ls ~/.local/share/gnome-shell/extensions/
hidetopbar@mathieu.bidon.ca  pop-shell@system76.com


**(10) Other Notes:**
+ dconf write /org/gnome/mutter/workspaces-only-on-primary false
gnome-extensions enable "pop-shell@system76.com"
Extension “pop-shell@system76.com” does not exist
make: *** [Makefile:61: enable] Error 2

I installed a prior version of this on the same OS fine, Gnome shell version was 3.36.3 at that time, and the commit used rebuild.sh still, I don't know how to find the version```

**Comment by nyx010** [comment]
Can confirm this issue on **Ubuntu 20.10** - **Gnome 3.38.1**. **Kernel: 5.8.0-31-generic**

**Error:** gnome-extensions enable "pop-shell@system76.com"
Extension “pop-shell@system76.com” does not exist
make: *** [Makefile:61: enable] Error 2

When run "make local-install"

Hoping someone comes up with a solution soon I love the pop-shell but can't migrate to pop-os.

**Comment by romanakash** [comment]
I get a similar error in ubuntu 18.04

+ gnome-extensions list
+ scripts/configure.sh: 105: scripts/configure.sh: gnome-extensions: not foundgrep
 native-window
+ dconf write /org/gnome/mutter/workspaces-only-on-primary false
gnome-extensions enable "pop-shell@system76.com"
/bin/sh: 1: gnome-extensions: not found
Makefile:61: recipe for target 'enable' failed
make: *** [enable] Error 127

**Comment by BlackHawk185** [comment]
> **(1) Issue/Bug Description:**
> Fails to Install
> 
> **(2) Steps to reproduce (if you know):**
> make local-install
> 
> **(3) Expected behavior:**
> Clean Install
> 
> **(4) Distribution (run `cat /etc/os-release`):**
> NAME="Solus"
> VERSION="4.1"
> ID="solus"
> VERSION_CODENAME=fortitude
> VERSION_ID="4.1"
> PRETTY_NAME="Solus 4.1 Fortitude"
> ANSI_COLOR="1;34"
> HOME_URL="https://getsol.us"
> SUPPORT_URL="https://getsol.us/articles/contributing/getting-involved/en/"
> BUG_REPORT_URL="https://dev.getsol.us/"
> 
> **(5) Gnome Shell version:**
> GNOME Shell 3.38.1
> 
> **(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**Comment by BlackHawk185** [comment]
Updated first comment, I realized that it for some reason was cutting the bottom half off, not just hiding it

**Comment by ChrisKeefe** [comment]
Note: some users who are here troubleshooting this error
> Extension “[pop-shell@system76.com](mailto:pop-shell@system76.com)” does not exist

may find these comments useful. https://github.com/pop-os/shell/issues/703#issuecomment-726084846 https://github.com/pop-os/shell/issues/703#issuecomment-726321757. Can any of the users above confirm that the issue exists after restarting gnome shell?

**Comment by BlackHawk185** [comment]
> Note: some users who are here troubleshooting this error
> 
> > Extension “[pop-shell@system76.com](mailto:pop-shell@system76.com)” does not exist
> 
> may find these comments useful. [#703 (comment)](https://github.com/pop-os/shell/issues/703#issuecomment-726084846) [#703 (comment)](https://github.com/pop-os/shell/issues/703#issuecomment-726321757). Can any of the users above confirm that the issue exists after restarting gnome shell?

I just tried reinstalling it and it works fine now. The System has been updated since then, but it might be a result of a gnome-shell restart. Should I close?

**Comment by jmmaranan** [comment]
Hello @BlackHawk185 - I am adding some relief on this - once PR merged, should handle this and future local-installs.

**Comment by fivitti** [comment]
I freshly updated Ubuntu to the 22.04 version with Gnome 42. I tried to update the `pop-shell` too, but I got this message:

```
gnome-extensions enable "pop-shell@system76.com"
Extension “pop-shell@system76.com” does not exist
make: *** [Makefile:52: enable] Error 2
```

I noticed that the changes provided in #782 are reverted. The installation works well after restoring them.

My changes:

```diff
diff --git a/Makefile b/Makefile
index ce05a6b..2f3609a 100644
--- a/Makefile
+++ b/Makefile
@@ -57,12 +57,13 @@ disable:
 listen:
 	journalctl -o cat -n 0 -f "$$(which gnome-shell)" | grep -v warning
 
-local-install: depcheck compile install configure enable restart-shell
+local-install: depcheck compile install configure restart-shell enable
 
 install:
 	rm -rf $(INSTALLBASE)/$(INSTALLNAME)
 	mkdir -p $(INSTALLBASE)/$(INSTALLNAME) $(PLUGIN_BASE) $(SCRIPTS_BASE)
 	cp -r _build/* $(INSTALLBASE)/$(INSTALLNAME)/
+	sleep 3
 
 uninstall:
 	rm -rf $(INSTALLBASE)/$(INSTALLNAME)
```

**Comment by adittes** [comment]
> I noticed that the changes provided in #782 are reverted. The installation works well after restoring them.

Restoring that commit worked for me, thanks for that. I used `git cherry-pick 425f1e4dd851017be80b83cd3eeda803f0ac8f1f` to restore the commit locally. 

Is there an open issue for this? If not I'd be glad to create one.

**Comment by leviport** [comment]
>Is there an open issue for this? If not I'd be glad to create one.

It's probably better to reopen this one

**Comment by nazgee** [comment]
`git cherry-pick 425f1e4dd851017be80b83cd3eeda803f0ac8f1f` helps with clean install on Ubuntu 22.04

**Comment by ghnk** [comment]
I have installed on Ubuntu 22.04 LTS by this way:
```
sudo apt install git node-typescript make 
git clone https://github.com/pop-os/shell.git 
cd shell 
make local-install
```
and installed **GNOME Tweaks** afterwards.
Now I have a problem that changing input source from Englist(en) to Thai(th) turns on Scroll Lock.
Can anyone please teach me how to uninstall and reinstall Pop Shell ?

**Comment by yossefsabry** [comment]
> I have installed on Ubuntu 22.04 LTS by this way:
> 
> ```
> sudo apt install git node-typescript make 
> git clone https://github.com/pop-os/shell.git 
> cd shell 
> make local-install
> ```
> 
> and installed **GNOME Tweaks** afterwards. Now I have a problem that changing input source from Englist(en) to Thai(th) turns on Scroll Lock. Can anyone please teach me how to uninstall and reinstall Pop Shell ?

thanks this works with me

**Comment by jacobgkau** [comment]
This issue is two years old, I'm going to go ahead and close it.

Anyone installing on Ubuntu 22.04 now should remember to `git checkout master_jammy` before running `make local-install`.
