### ISSUE TITLE
When changing primary display, windows on newly-primary display sometimes move to new workspace

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/shell#762]
**(1) Issue/Bug Description:** When changing the primary display, the windows on the display that is now primary sometimes move off of their current workspace and onto a new workspace. This results in one workspace with windows on the first display, and another workspace with windows on the second display, requiring the user to manually move the windows back into position on a single workspace where they started.

**(2) Steps to reproduce (if you know):**
1. The issue does not occur with all window layouts, but here is an example where it does occur consistently:
![Screenshot from 2020-12-04 12-41-34](https://user-images.githubusercontent.com/7199422/101208211-09295a80-362f-11eb-95bc-5ac75a26fe6b.png)
(Using this layout as an example, the issue does occur if the Settings app is on the left or right, but if I change orientation with `Super+O`, it does not occur if Settings is on the top or bottom.)
2. After arranging the windows on a single workspace spanning both displays, change the primary display. (In the above screenshot, I have arranged the windows while the internal display is primary, changed the dropdown, and am about to click "Apply.")

**(3) Expected behavior:** Changing the primary display should not move windows at all (it should only resize them as much as required to fit the top panel.)

**(4) Distribution (run `cat /etc/os-release`):** Pop!_OS 20.10 and 20.04.

**(5) Gnome Shell version:** 3.38.1.

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
- `1.0.0-1606763695~20.04~ee943b8` (`master`, 20.04)
- `1.0.0~1606875310~20.10~b931471` (`testing-pr753`, 20.10).
- `1.0.0~1606875310~20.04~b931471` (`testing-pr753`, 20.04).

**(7) Where was Pop Shell installed from:** Staging repository.

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):** 1x 1080p (internal), 1x 1440p (external.)

**(9) Other Installed/Enabled Extensions:** Pop!_OS defaults only.

**Comment by mmstick** [comment]
Was this fixed by our recent display update patch?

**Comment by jacobgkau** [comment]
Yes, I think it was. I'll re-open if it starts happening again.
