### ISSUE TITLE
Annoying Window Size Change when opening programs

### ISSUE THREAD

**Issue by jawadalkassim** [pop-os/shell#771]
**(1) Issue/Bug Description:**
changing in window size when opening
App Starts fine then app window size shrink a little,  after that goes back to the actual size

**(2) Steps to reproduce (if you know):**
Tile windows: on
open any program

**(3) Expected behavior:**
opens in tiles windows size with provided gaps

**(4) Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**
3.38.1

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.0.0~1607112536~20.10~9e13d5d
  Candidate: 1.0.0~1607112536~20.10~9e13d5d
  Version table:
 *** 1.0.0~1607112536~20.10~9e13d5d 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status

```

**(7) Where was Pop Shell installed from:**
By default

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1 x 1080p

**(9) Other Installed/Enabled Extensions:**
Dash to Dock
Caffeine
User themes
**(10) Other Notes:**
This Video explain the issue:
https://imgur.com/a/jEFcuU0
this happens to all apps

**Comment by maglund** [comment]
I am experiencing the same issue. Started a few weeks back (I think).

I differ somewhat in setup compared to jawadalkassim:

X11 and not Wayland

**(4) Distribution (run cat /etc/os-release):**
```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
**(5) Gnome Shell version:**
3.36.3

```
pop-shell:
  Installed: 1.1.0~1607723907~20.04~d72a2f3
  Candidate: 1.1.0~1607723907~20.04~d72a2f3
  Version table:
 *** 1.1.0~1607723907~20.04~d72a2f3 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**(8) Monitor Setup:**
1 x 2K (2560 x 1440)

**(9) Other Installed/Enabled Extensions:**
"Caffeine" (tried to turn it off as jawadalkassim also had it installed -> no difference)
"Brightness control using ddcutil"

**Comment by jawadalkassim** [comment]
I've disabled all Extensions just in case there's a conflict but nothing changed.
yeah it's started few weeks back as @maglund mentioned

**Comment by laichiaheng** [comment]
#752 ?

**Comment by jawadalkassim** [comment]
> They make this issue into their release now.

It's not fixed after 1.1 release

**Comment by rivenirvana** [comment]
Observing this on Xorg for a while now, as well. The issue also occurs when closing programs. The size change doesn't occur sometimes, but it is certain something odd still happens, indicated by the blinking of the active window hint of the immediate focused window after opening/closing a program.

**Comment by pstrode** [comment]
I've found that on a multi monitor setup - if I open a system dialog within an app, then close it (e.g. within VS Code, save new file), that the window manager tries to quickly resize windows on my other monitors and then puts them back. 

Not sure if its related but I've also noticed they seem to resize down a small margin (20-30 px) about the height of the top bar on my primary monitor.

**Comment by laichiaheng** [comment]
![2020-12-23 22-05-09 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/103003133-2e90f080-456b-11eb-9498-70e39c3674c4.png)
This is my temporary solution.

**Comment by skewty** [comment]
On my 3-monitor setup with the leftmost and rightmost monitor in portrait mode and the Gnome Files app on the leftmost monitor and Firefox on the rightmost monitor, I open Gnome calendar on the leftmost monitor (which is set as a floating exception).  I click on an existing calendar entry and the calendar entry dialog window opens and then a few seconds later you will see both the leftmost monitor tile for Gnome Files and the rightmost tile for Firefox resize down as if another window was about to be included as a tile and then it goes back to full size because no other window was tiled.

**Comment by rivenirvana** [comment]
I am not experiencing this issue anymore after the latest commit (90585cb).
