### ISSUE TITLE
"Show Window Titles" remains deactivated when Tile Windows is turned off

### ISSUE THREAD

**Issue by redbarnnobrakes** [pop-os/shell#775]
**(1) Issue/Bug Description:**
"Show Window Titles" stays toggled off when turning off Pop's [Tile Windows](https://youtu.be/-fltwBKsMY0)

**(2) Steps to reproduce (if you know):**
1. Enable Pops Tile Windows
2. From the Tile Windows drop-down settings, toggle "Show Window Titles" off
3. Turn off Tile Windows
3. Window Titles remain off even though the Tile Windows tools is off.

**(3) Expected behavior:**
Turning off Tile Windows should also revert any visible desktop settings changed as part of the Tile Windows configuration including Window Titles.

**(4) Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**
3.38.1

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1607723907~20.10~d72a2f3
  Candidate: 1.1.0~1607723907~20.10~d72a2f3
  Version table:
 *** 1.1.0~1607723907~20.10~d72a2f3 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status

```

**(7) Where was Pop Shell installed from:**
Base install

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
Just laptop (Lemur) screen

**(9) Other Installed/Enabled Extensions:**
Dash to Dock. Still happens when this is turned off.

**(10) Other Notes:**

**Comment by mmstick** [comment]
It's still useful to have windows without titles even without tiling.

**Comment by redbarnnobrakes** [comment]
> It's still useful to have windows without titles even without tiling.

I don't disagree that there is a valid use-case for disabling window titles when not using tiling. I think the way this is currently implemented leads to confusion though.

Previously, all user configurable settings were around _Tile Windows_ as it was was the main function / focus in the extensions drop-down menu. _Show Active Hint_ and _Gaps_ only pertain to the system when _Tile Windows_ is toggled on. 

![image](https://user-images.githubusercontent.com/14085766/102275458-0827e100-3eeb-11eb-9528-94f20b2dbe88.png)

With the inclusion of the _Show Window Titles_ feature, this is no longer the case. The toggled value of _Show Window Titles_ is the only configuration item in the extension settings that visibly persists across the toggling of the top tier _Tile Windows_ setting. This, to me, is a very confusing UX.

![image](https://user-images.githubusercontent.com/14085766/102275937-c0558980-3eeb-11eb-8aed-d6c2e11a3e33.png)

**Comment by jacobgkau** [comment]
> The toggled value of Show Window Titles is the only configuration item in the extension settings that visibly persists across the toggling of the top tier Tile Windows setting.

For what it's worth, Show Active Hint and Active Hint Color (which are in the same section as Show Window Titles) also persist across the toggling of Tile Windows.

**Comment by redbarnnobrakes** [comment]
> > The toggled value of Show Window Titles is the only configuration item in the extension settings that visibly persists across the toggling of the top tier Tile Windows setting.
> 
> For what it's worth, Show Active Hint and Active Hint Color (which are in the same section as Show Window Titles) also persist across the toggling of Tile Windows.

Somehow I missed this. Thank you for the correction!

**Comment by brandoningli** [comment]
I'd love to see these settings be able to be changed on a per-mode basis (tiling vs floating). Personally, I prefer no menu bars and an active hint in tiling mode, but menu bars and no hint in floating mode.

**Comment by afonsocraposo** [comment]
I agree with @brandoningli
Is there any update on this?

**Comment by 4a454646** [comment]
Agreed, I just wish I could set the window titles to disappear when I enter tiling mode, and have them stay normally.
