### ISSUE TITLE
Window is not maximized when number of windows on workspace is reduced to 1

### ISSUE THREAD

**Issue by Chrysostomus** [pop-os/shell#78]
When a new window is spawned on an empty workspace, it starts out in maximized state. This is good behavior. However, if you open a second window and close it, the original window does not return to maximized state. It would be better if it did, to avoid the awkward empty space below the window.

First window is spawned in maximizd state:
![Screenshot from 2020-03-16 09-19-01](https://user-images.githubusercontent.com/12002226/76731969-3f544080-6767-11ea-82f9-b5626c045102.png)
Second window is spawned, and because it is gnome-terminal, it does not respect it's intended size, leaving the awkward space below:
![Screenshot from 2020-03-16 09-18-58](https://user-images.githubusercontent.com/12002226/76731973-42e7c780-6767-11ea-8a5a-0a111c059dcc.png)
Second window is killed, awkward space remains:
![Screenshot from 2020-03-16 09-18-53](https://user-images.githubusercontent.com/12002226/76731983-47ac7b80-6767-11ea-836b-cc7489de9ad0.png)

Of course, it would be even better if you could force gnome-terminal to just obey the size it is instructed to use, but I have understood that mutter does not permit this, so re-enabling maximized state when number of windows is reduced to 1 would be a passable workaround.

**Comment by Chrysostomus** [comment]
This would also improve behavior when outer gaps is set to non 0 value. That way there would be no unnecessary gaps for single window.

**Comment by mmstick** [comment]
This change was reverted. Windows will not maximize when they are only window on a workspace, as that behavior provides an inconsistent experience which ignores defined outer gaps.

**Comment by mmstick** [comment]
I will note that if you want a terminal which will listen to the window manager, Tilix is a great choice. Lightweight terminals like Alacritty will also do as the window manager asks, rather than only sizing in specific increments.

**Comment by Chrysostomus** [comment]
I know, but it would be weird to ship some other terminal with gnome desktop.

Could this be implemented as toggleable option? Ignoring the outer gaps with single window is the desired behavior for many users, but naturally not all. On bspwm it is an option called single_monocle, and many other tiling wms have it too as an option.

**Comment by mmstick** [comment]
It'd be possible to add an option for this in our extension prefs. I've yet to make the prefs dialog, though.

**Comment by Chrysostomus** [comment]
Thank you for your consideration!
