### ISSUE TITLE
Enabling pop-shell makes right side icons in top panel do drop too low

### ISSUE THREAD

**Issue by Chrysostomus** [pop-os/shell#79]
When the extension is enabled, all icons in the right side of the top panel are lowered a bit and spill out of the panel. Reloading the shell brings the icons back up.

After reloading gnome-shell:
![Screenshot from 2020-03-16 09-47-32](https://user-images.githubusercontent.com/12002226/76734470-a7a52100-676b-11ea-9d57-1f424e7bb892.png)

Before reloading gnome-shell:
![Screenshot from 2020-03-16 09-46-52](https://user-images.githubusercontent.com/12002226/76734474-a83db780-676b-11ea-8caf-0e2a217a729d.png)

**Comment by mmstick** [comment]
You seem to have the wrong icon from an older version of this extension

**Comment by Chrysostomus** [comment]
Thanks, I'll update to latest commit to see if the issue persists.

**Comment by Chrysostomus** [comment]
Issue is fixedwith the current master.
