### ISSUE TITLE
All windows on secondary monitor jump more or less randomly to the primary one

### ISSUE THREAD

**Issue by luismcv** [pop-os/shell#794]
**(1) Issue/Bug Description:**

Several times every day all the windows on my secondary monitor jump to the primary one and I have to move them back and arrange them again.

**(2) Steps to reproduce (if you know):**

I think it happens more frequently when a floating dialogue is opened or closed on the primary screen, but I've also seen it happen when a tiled window is opened or closed or even just switching workspaces.

**(3) Expected behavior:**

Whatever I do or happens in the main monitor shouldn't affect windows on the secondary monitor, let alone move these windows to the primary one.

**(4) Distribution (run `cat /etc/os-release`):**

Pop!_OS 20.10

**(5) Gnome Shell version:**

3.38.2 (```3.38.2-1pop1~1608219591~20.10~9602e64``` currently, but happened too with previous package releases)

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```
pop-shell:
  Installed: 1.1.0~1608318806~20.10~19ebae0
  Candidate: 1.1.0~1608318806~20.10~19ebae0
  Version table:
 *** 1.1.0~1608318806~20.10~19ebae0 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status
```

Also happened with previous versions

**(7) Where was Pop Shell installed from:**

Installed by default by the distribution

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

Primary: 4K Horizontal
Secondary: 1080p Vertical

Dynamic workspaces, workspaces on primary display only

Tile Windows enabled

X.Org

Nvidia proprietary drivers (```455.38-1pop0~1605144088~20.10~3cf77da```)

**(9) Other Enabled Extensions:**

**Manually Installed**
CPU Power Manager
Extension Update Notifier
Frippery Move Clock
Notifications Alert
OpenWeather
Panel OSD
Permanet notifications
Places Status Indicator
Screenshot Locations
Scroll Panel
Sound Input & Ouput Device Chooser

**Built-In**
Alt Tab
Always Show Workspaces
Pop Shop Details
System76 Power
Ubuntu AppIndicators

**Comment by luismcv** [comment]
I forgot to mention that if I have any windows stacked on the primary monitor they usually get unstacked too.

**Comment by mmstick** [comment]
Could be fixed by #798

**Comment by mmstick** [comment]
Is this still an issue with the latest version? You'll need to restart the shell after updating.

**Comment by luismcv** [comment]
It hasn't happened since I installed the new version yesterday. But I'll get back to you if it happens again.

What I still see is some weird resizing of the windows on one screen when a floating dialogue is closed on the other one. It keeps doing it if you keep opening and closing these dialogues so, for example, if your start with a half-half distribution you'll eventually end with a very wide window and a very narrow one. Is there any shortcut to quickly readjust all windows to a halves, quarters, etc... grid? I couldn't find any.

**Comment by luismcv** [comment]
Well, I can confirm this hasn't happened again since I installed that and newer versions.

Still seeing unfounded resizing, similar to #838, but not at regular intervals like described there (and I don't have Dash to Dock, Conky or any other dock).
