### ISSUE TITLE
Keyboard shortcuts application

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/shell#8]

**Comment by cassidyjames** [comment]
[elementary/shortcut-overlay](https://github.com/elementary/shortcut-overlay) is available as a starting point if you'd like; it's a super lightweight GTK app and pulls its shortcuts from GSettings.

![screenshot](https://raw.githubusercontent.com/elementary/shortcut-overlay/master/data/Screenshot%402x.png)

You'd need to customize which shortcuts are shown, of course.

**Comment by WatchMkr** [comment]
Thanks, Cassidy! I _think_ this is going to need to be in the shell for us being that it's likely activated by a long-press on the Super key. But we'll see.

**Comment by cassidyjames** [comment]
I think Shell can probably launch a GTK app on long-press, but I'm not 100% sure. In Gala, we have it on a tap of the Super key but obviously in GNOME Shell that launches the Activities Overview.

**Comment by WatchMkr** [comment]
Moved here: https://github.com/pop-os/shell/issues/23
