### ISSUE TITLE
When previewing an image on telegram-desktop, it acts like a new window has been opened

### ISSUE THREAD

**Issue by Elyhaka** [pop-os/shell#80]
The picture preview of telegram opens a full screen window.

When clicking on a picture in telegram, it acts like a window has been opened beside and "jumps".

It is not a really blocking bug, but when the window is too small with Telegram, it tends to have a forced min size behavior and it do some strange things to other window besides.

Let me know if you need more details about it.

**Comment by leviport** [comment]
Thanks for the bug report! I'm not quite sure what you mean about the window jumping. When I open an image in Telegram, I get a fullscreen preview of the image, which is what I would expect, whether Telegram is maximized or not. Can you describe this more so I can attempt to reproduce it?

I did verify that it does have a minimum size that doesn't resize below 380 px wide by 482 px tall. I'm not sure about the usability of the application much below that, so I think it's more of a question about how pop-shell handles windows that refuse to get smaller than their minimum sizes.

**Comment by Elyhaka** [comment]
Hello, sorry for the bad explaination, english is not my mother tongue thus it can be complicated for me to explain issues.

When I open a preview a picture in telegram, the shell acts like a new window has been opened and  allocates a slot (but the preview will not take that slot, it will remain full-screen).
On small screens (like mine), it tries to reduce telegram more than it can be reduced, provoking some kind of "jump" of the window.

**Comment by leviport** [comment]
Aha, I see what you mean now. I can confirm that Telegram does subdivide to open a slot underneath the preview, and it goes away after the preview closes causing a quick change, or jump, in the window as it fills the slot that was just opened. I just wasn't seeing it under the darkened backdrop of the preview at first. Good catch!

**Comment by mmstick** [comment]
What's the `wm_class` of the preview? Telegram should be hinting to the window manager that the preview is a dialog, but if it is not, we can add an exception to blacklist it from tiling.

**Comment by leviport** [comment]
It looks like it's the same as the Telegram main window, which might explain it:
```
pop-shell:  [INFO] focused Window(5,0) {
  name: Telegram Desktop,
  rect: Rect(962,27,958,525),
  wm_class: "TelegramDesktop",
  monitor: 0 
  workspace: 4 
  fork: (5,1),
}
```

**Comment by mmstick** [comment]
Found a related issue: https://github.com/telegramdesktop/tdesktop/issues/5048

**Comment by mmstick** [comment]
A referenced commit at the bottom of the issue claims it's setting the window to be a `Qt::WindowModal`, but GNOME must not be seeing this value, as it's still returning `Meta.WindowType.NORMAL`.

I'll try the transient window trick

**Comment by mmstick** [comment]
Check if 8bf126d6ce55919a38834dc24bb5eaf68afb1d5e has fixed this

**Comment by Elyhaka** [comment]
I can still reproduce the issue with `36467cf` ?

**Comment by leviport** [comment]
I'm still seeing it as well. If this one's too tricky, I'd probably knock it down in priority. It looks a little strange, but it's sort of an upstream bug and it's relatively minor compared to the other stuff we have to work on.

**Comment by Elyhaka** [comment]
No problem, I understand, keep up the great work :+1: ! Even if it's still a work in progress, its one of the best tiling extension I ever tried for Gnome ! :)

**Comment by RememberTheAir** [comment]
This is kinda off-topic, but can I add other apps in the blacklist as it has been done in e5c89cc? I'm currently using [a fork of Telegram Desktop](https://github.com/kotatogram/kotatogram-desktop), which of course has the same tiling issue. I wonder if I can fix that myself manually
