### ISSUE TITLE
latest update to pop shell seems to have borked the launcher

### ISSUE THREAD

**Issue by thunderrabbit** [pop-os/shell#804]
**(1) Issue/Bug Description:**

https://chat.pop-os.org/community/pl/trer6iq7o3d1pmhmp59s4cbzye

launcher (super+/) no longer searches for unopen programs, only allowing access to the open ones.

**(2) Steps to reproduce (if you know):**

Install latest update approx 2021 January 01

super+/

**(3) Expected behavior:**

Show non-running applications

**(4) Distribution (run `cat /etc/os-release`):**

20.04 LTS

**(5) Gnome Shell version:**

3.36.8

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
$ apt policy pop-shell
pop-shell:
  Installed: 1.1.0~1609457265~20.04~c97b9b2
  Candidate: 1.1.0~1609457265~20.04~c97b9b2
  Version table:
 *** 1.1.0~1609457265~20.04~c97b9b2 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

Pop Shop

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

Lemur laptop and external monitor

**Comment by mmstick** [comment]
Have you tried restarting the shell? I'm not seeing the issue

**Comment by jwallemacq** [comment]
Problem disappeared after restart (and possibly update of Pop!_OS).

$ apt policy pop-shell
pop-shell:
  Installed: 1.1.0~1609457265~20.10~c97b9b2
  Candidate: 1.1.0~1609457265~20.10~c97b9b2
  Version table:
 *** 1.1.0~1609457265~20.10~c97b9b2 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status

**Comment by thunderrabbit** [comment]
Thank you very much.   A restart fixed it for me as well.
