### ISSUE TITLE
Method to accomodate non default language in launcher plug-in web searches.

### ISSUE THREAD

**Issue by derpmatt** [pop-os/shell#806]
**(10) Other Notes:**

During a sneak peek of the new plugin functionality in Pop's live chat support, it became apparent that language support for the Web plugin handling searches from the Launch bar, is not included.  A method to help non-English speakers use this brilliant tool in their [cctld](https://en.wikipedia.org/wiki/Country_code_top-level_domain) would be a welcome addition. Not a priority, but something for consideration.

**Comment by mmstick** [comment]
I think many of these URLs can be changed to point to the generic TLD of the website and let the website decide what language to give the user based on browser or site-specific settings.

**Comment by derpmatt** [comment]
I tried editing the Wikipedia entry to point to Brunie, .bn ( a specific request).  Originally it didn't work just by editing the URL with the TLD only. The entire URL changes. For example:

https://en.wikipedia.org/w/index.php?search=

https://bn.wikipedia.org/wiki/.bn/index.php?search=

The difference is minimal, but could be difficult for non-technical people. It's probably safe to assume that not everyone who buys a System76 computer with OEM Pop!_OS will be able to sort that out. 

By editing the URL in `main.js` only, you can search Wikipedia with your TLD. However you lose the ability to search the main `.en` site via the launcher.  The alternate method is to add a complete extra entry, so you can search with `wiki` or `dewiki` (whatever TLD you want).

How to do it;

Making a new entry with the appropriate URL and `case` in the `main.js` file. You also need to add whatever you chose for `case` in the `meta.json` file. You need all three changes for it to work successfully. 

Still, not a priority, but an easy way to do this would be great. At minimum some documentation, or `man page` would work too. Give me a format to work in, and I'd happily do it -  Unless a better option was to make a tool to convert them?

**Comment by mmstick** [comment]
I'll just change the URL to use `wikipedia.org/wiki/` instead of `en.wikipedia.org`. The website will automatically direct them to whatever language is the default language in their web browser, or if they have a cookie on a site that tells it to use a different language otherwise.

**Comment by derpmatt** [comment]
Nice! Good simple solution.
