### ISSUE TITLE
Keyboard shortcut to toggle window titles

### ISSUE THREAD

**Issue by d4n3sh** [pop-os/shell#817]
**(1) Issue/Bug Description:**
Use a shortcut key to toggle window titles.

Would be nice to have a shortcut key assigned to toggle windows titles. Some applications don't honor hiding the title so I normally have to toggle the window title to hide the window title.

**(3) Expected behavior:**
Use a shortcut key to toggle window titles

**(4) Distribution (run `cat /etc/os-release`):**
 ```
❯ cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**
```3.38.1```

**(6) Pop Shell version 
```
❯ apt policy pop-shell
pop-shell:
  Installed: 1.1.0~1609890630~20.10~3b05ab5
  Candidate: 1.1.0~1609890630~20.10~3b05ab5
  Version table:
 *** 1.1.0~1609890630~20.10~3b05ab5 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status
```

**Comment by mmstick** [comment]
What if I add a shortcut in the launcher for toggling the tiling?

**Comment by d4n3sh** [comment]
@mmstickwhen thanks for looking into this.  

My preference would still be a keyboard shortcut as it would be much quicker.

An example workflow would be like this;

1. super + y - enable tiling
2. super + u - toggle window tile (off)
3. super + / launch my apps
4. continue working
5. super + / - launch another app
6. app comes up but the window title is enabled. 
5. super + u - toggle window title on/off again.

Also, sometimes when I have duplicate windows open I use the window title to quickly identify them.

**Comment by WatchMkr** [comment]
Adding a “Toggle Window Titles” option to keyboard shortcuts would be fine. I don’t think we should set the value by default.

**Comment by mmstick** [comment]
#826 Adds this as a searchable option in the launcher
