### ISSUE TITLE
aces in pop!_os

### ISSUE THREAD

**Issue by WildSilo** [pop-os/shell#818]
**(1) Issue/Bug Description:**

**(2) Steps to reproduce (if you know):**

**(3) Expected behavior:**

**(4) Distribution (run `cat /etc/os-release`):**
 

**(5) Gnome Shell version:**

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**(7) Where was Pop Shell installed from:**

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

**Comment by leviport** [comment]
This issue is very unclear, so I'm going to close it for now. If you edit the post and better explain the issue, let me know and I will reopen it.
