### ISSUE TITLE
Resizing paradigm is unintuitive

### ISSUE THREAD

**Issue by Chrysostomus** [pop-os/shell#82]
The current model of resizing the overlay makes it difficult predict to which direction window border moves when you press shift+direction. It is more difficut to know which window is the master than with static tiling wms. 

Suggestion: instead of resizing the overlay,you could resize the selected window. That way the border between the windows would always move to the direction of the pressed arrow keys, resulting in a more intuitive experience. 

This is how I did it with Manjaro bspwm edition, which uses the same tiling paradigm as this extension does:

https://github.com/Chrysostomus/bspwm-scripts/blob/master/bin/bspwm_resize.sh

The comments in the script are mislabeled and the code is not directly applicable to this extension, but it might hopefully demonstrate what I'm trying to suggest. If needed/desired, I can post a screencast to demonstrate the suggested behavior.

**Comment by mmstick** [comment]
I assume you're referring to the stacking mode resizes?

**Comment by leviport** [comment]
I've noticed something that I think is probably similar. When in tiling mode and I resize windows on the right side of the screen, it feels like the arrow keys do the inverse of what I would expect. I suspect that it is resizing the right edge of the window and and the window is re-snapping to the correct position almost instantly, which just makes it appear that it goes the other direction. 

The same thing happens with windows on the bottom of the screen when being resized with the up & down arrows. 

This animation hopefully shows what I mean. I used screenkey to try to show which keys I was hitting. Hopefully it comes across reasonably well.

![screencast](https://user-images.githubusercontent.com/13512097/76798300-f0bd9b00-6794-11ea-85a6-9b6e4f8dd735.gif)

**Comment by Chrysostomus** [comment]
This is exactly what I mean, the issue is with tiling, not the stacking mode. If the right window is selected, window border goes to the direction of the arrow keys. If a wrong one is selected, window border foes to the direction opposite of the pressed arrow keys. This makes for an inconsistent experience.

**Comment by mmstick** [comment]
The shortcuts have the same behavior as in i3, where:

- Up: shrink vertically
- Down: grow vertically
- Left: shrink horizontally
- Right: grow horizontally

But there are also some bugs in resizing where it doesn't quite do what we'd expect.

**Comment by leviport** [comment]
Ah I see, if that's intended behavior then I'm okay with it. I haven't used i3 much, so the behavior just felt like it was backwards on the right and bottom edges of the screen. I'm not sure why, but I initially assumed arrow keys would be moving the border closest to the middle of the screen. Grow/shrink makes sense now that it's been explained to me though.

**Comment by Chrysostomus** [comment]
I understand it is same behavior as i3 default. Bspwm also started doing after certain version, so I scripted back it's old behavior :

When pressing $dir, increase window size to that $dir. If that does not work (because there is monitor border that way), decrease the window size from the opposite $dir instead. For example, when pressing left, increase window size to the left. If that does not work (because there is monitor border that way), decrease the window size from the right instead.

It sounds crazy on paper, but it is really intuitive and visual to use in practice. You get the feeling that you are moving the window border with your arrow keys.

So, while I'm under no illusion that this is a bug, I'm suggesting an alternatvie paradigm.

**Comment by mmstick** [comment]
That's what we were doing at one time, but it required double the amount of shortcuts to differentiate between growing or shrinking in a given direction. If we instead grow and shrink the width and height, ignoring a specific side to grow or shrink, we can get away with a single set of shortcuts that can both grow and shrink.

**Comment by Chrysostomus** [comment]
It doesn't need two sets of keybindings if you make the shrinking/growing conditional like I did in that script I linked: grow window to the pressed direction, but if growing it there move the window border out of screen or over the panel, shrink from the opposite direction instead. 

I'm sure it is much harder to do with mutter than with bspwm, because in mutter the windows are not really tiled but only resized and placed floating windows. And it might have more overhead than in bspwm, since you can't just check for the exit status of resize command. But from the keybindings point of view, it's totally doable with one set of keybindings.

**Comment by TS-CUBED** [comment]
In this discussion to OP is assuming that there are only 2 rows/columns of windows. I usually work with more than that (currently i3, but keeping an eye on this with a view to migrate back to gnome/pop shell once is has matures a bit). So when resizing the window in the middle, the current/i3 binding makes sense if a single set of bindings is required.

**Comment by Chrysostomus** [comment]
This is true, I mostly operate on small screens. I3 style bindings are likely to work better on bigger number of columns. I'll do some further testing.

**Comment by taranjlu** [comment]
I also find the resizing controls feel very unnatural (although I do understand why they were made the way they were), and I prefer the style mentioned by @Chrysostomus. I don't quite follow why that method would not work with 3+ columns or rows... @TS-CUBED could you give a specific example where it falls apart? I would think that case wouldn't be any different - the window would still attempt to resize in the direction of the command, either pushing the boundary in that direction or pulling from the other side if there is not room to expand.

I know you mentioned that the goal was to have a single set of hotkeys for resizing @mmstick, but maybe it would also make sense to make a distinction between resizing (moving a single window border) and sliding (moving both borders together if possible)?

**Comment by Chrysostomus** [comment]
With my system, you cannot diminish the window if the middle window is focused. Super+left grows it to the left and super+right grows it to the right. So if you want to make the middle window smaller, you have to focus the left or right window first. It's not a big issue with three columns, but might feel weird with 4 or more.

**Comment by taranjlu** [comment]
Right, of course, that does make sense... I think that maybe it is just a different way of looking at it though, since "decreasing" the size of a window always means increasing the size of adjacent windows. I still feel like the directionality is much more natural feeling.

**Comment by Chrysostomus** [comment]
Me too. With bspwm and i3 you can script this. @mmstick, would it be feasible to make this configurable, or provide a cli interface for manipulating windows with pop shell?

**Comment by akainth015** [comment]
I am also in support of this being an option (even the default behaviour) because I was incredibly confused upon first using this feature. If i3 users who switch to this would like the i3 behaviour as an option, it makes perfect sense, but for a default I don't think it's very fitting.

**Comment by mmstick** [comment]
There were some resizing issues but these have been corrected in the last ~2 months

**Comment by nicolidin** [comment]
Why is this issue closed ? Did we find a way to make it configurable ?
