### ISSUE TITLE
[Pop OS 20.10] Cursor suddenly slowing down

### ISSUE THREAD

**Issue by dodalovic** [pop-os/shell#825]
Latest POP OS

Many times a day I experience behavior that my mouse suddenly slows down, that lasts for a minute or so, and then gets back to normal.
This happens unrelated to the workload at the moment and CPU activity.

I'm using Dell XPS 9700

Any hint?

**Comment by pvojnisek** [comment]
I experienced similar after the latest update. It was no problem before.
I experienced slow focus change and the right mouse click did not function.
It is normal again after reboot.
Nitro AN515, AMD Ryzen 7 4800H, NVIDIA GeForce GTX 1650 Ti

**Comment by mmstick** [comment]
Unrelated to Pop Shell
