### ISSUE TITLE
Apps not positioned correctly after unplugging display from HiDPI system

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/shell#831]
**(1) Issue/Bug Description:** After unplugging an external display from a HiDPI laptop, the windows that were already on the internal laptop screen are not positioned correctly (they are restricted to a very small area and do not tile.) The windows previously on the external display aren't affected.

For example, starting with this layout:
![Screenshot from 2021-01-14 14-14-07](https://user-images.githubusercontent.com/7199422/104653071-485bba00-5677-11eb-8b91-d7f42cb5ad67.png)

After unplugging the external display, one workspace looks like this:
![Screenshot from 2021-01-14 14-14-25](https://user-images.githubusercontent.com/7199422/104653089-4f82c800-5677-11eb-959e-9a2fce994e64.png)

Opening further windows on the workspace overlaps the misplaced windows:
![Screenshot from 2021-01-14 14-14-37](https://user-images.githubusercontent.com/7199422/104653106-57426c80-5677-11eb-991f-d2aae93ac17d.png)

Another example, starting with this layout:
![Screenshot from 2021-01-14 14-42-38](https://user-images.githubusercontent.com/7199422/104653119-5c072080-5677-11eb-9e8a-3f85d2e7e30a.png)

After unplugging the external display, one workspace looks like this:
![Screenshot from 2021-01-14 14-42-50](https://user-images.githubusercontent.com/7199422/104653140-65908880-5677-11eb-81f4-769821583fb3.png)

**(2) Steps to reproduce (if you know):**
1. Plug in an external display to a laptop with a HiDPI internal display.
2. Arrange some windows on the internal and external displays.
3. Unplug the external display.

**(3) Expected behavior:** Windows should be positioned in valid locations on the internal display.

**(4) Distribution (run `cat /etc/os-release`):** Pop!_OS 20.04 LTS

**(5) Gnome Shell version:** 3.36.4

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
- master (`891525b`)
- active (`bf45d5b`)

**(7) Where was Pop Shell installed from:** Staging repos.

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):** 1x 4k internal, 1x 1440 external.

**(9) Other Installed/Enabled Extensions:** Pop!_OS defaults.

**(10) Other Notes:** This may have something to do with the HiDPI daemon. It only seems to occur when the daemon is enabled and set to LoDPI mode.

**Comment by skewty** [comment]
I think this is an upstream issue.  After plugging / un-plugging a monitor, I always need to leave my session and start a fresh one (logout and back in again) or weird behaviour is experienced.  This weirdness happens even without pop-shell extension which is why I suspect the issue to be upstream.
