### ISSUE TITLE
FR [launcher plugin] Allow to switch to browser tab

### ISSUE THREAD

**Issue by edgar-vincent** [pop-os/shell#836]
Hello,

First I'd like to thank you for your excellent work. The PopOS shell extension brings fantastic, well designed features to the Gnome Shell, without which I wouldn't have switched over from Sway. 

The launcher's new plugins are brilliant. Might I suggest offering one which allows the user to switch to a given browser tab? Perhaps with the help of https://github.com/osnr/TabFS?

Thanks again!

ev

**Comment by mmstick** [comment]
Anyone's free to create a plugin, but it's out of scope of the shell project itself
