### ISSUE TITLE
Tiled windows on right shift left

### ISSUE THREAD

**Issue by yochananmarqos** [pop-os/shell#838]
**(1) Issue/Bug Description:**

While I wait for my System76 Serval WS (serw12) replacment to ship out, I'm using my Dell Inspiron 5575. I wasn't using it that much until a week ago or so, so I can't say exactly when this started happening. I put this off because I usually am able to eventually figure problems out on my own, but this one has me stumped.

When tiling is enabled, the window(s) on the right will shift left slightly pushing the window(s) on the left with it. This happens about every 5 - 10 seconds. It will keep going until the window on the right has taken up most of the screen with the window on the left pushed so far over it probably reached the minimum width size. This occurs on both monitors as well as with the secondary monitor disabled. I've tried disabling all other extensions and tried both X11 and Wayland sessions.

**(2) Steps to reproduce (if you know):**

I've yet to figure out why it's happening.

**(3) Expected behavior:**

Tiled windows should not move once snapped into place.

**(4) Distribution (run `cat /etc/os-release`):**

 ```
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```

**(5) Gnome Shell version:**

3.38.3

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

1.2.0.r5.g1557528-1

**(7) Where was Pop Shell installed from:**

My own [PKGBUILD](https://github.com/yochananmarqos/pkgbuilds/tree/master/pop-shell-git) which is a variation of the AUR package, [`gnome-shell-extension-pop-shell-git`](https://aur.archlinux.org/packages/gnome-shell-extension-pop-shell-git/).

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

Primary: eDP connected primary 1920x1080+0+0
Secondary: HDMI-A-0 connected 1920x1080+1920+0

**(9) Other Installed/Enabled Extensions:**

```
pop-shell@system76.com
dash-to-dock@micxgx.gmail.com
appindicatorsupport@rgcjonas.gmail.com
tweaks-system-menu@extensions.gnome-shell.fifi.org
applications-overview-tooltip@RaphaelRochet
apps-menu@gnome-shell-extensions.gcampax.github.com
auto-move-windows@gnome-shell-extensions.gcampax.github.com
drive-menu@gnome-shell-extensions.gcampax.github.com
horizontal-workspaces@gnome-shell-extensions.gcampax.github.com
launch-new-instance@gnome-shell-extensions.gcampax.github.com
native-window-placement@gnome-shell-extensions.gcampax.github.com
places-menu@gnome-shell-extensions.gcampax.github.com
screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com
user-theme@gnome-shell-extensions.gcampax.github.com
window-list@gnome-shell-extensions.gcampax.github.com
windowsNavigator@gnome-shell-extensions.gcampax.github.com
workspace-indicator@gnome-shell-extensions.gcampax.github.com
gnome-fuzzy-app-search@gnome-shell-extensions.Czarlie.gitlab.com
mullvadindicator@pobega.github.com
weatherintheclock@JasonLG1979.github.io
lockkeys@vaina.lt
gamemode@christian.kellner.me
gsconnect@andyholmes.github.io
GPaste@gnome-shell-extensions.gnome.org
disconnect-wifi@kgshank.net
pamac-updates@manjaro.org
```

**(10) Other Notes:**

N/A

**Comment by mmstick** [comment]
What applications? Do you have a video to demonstrate how to replicate it?

**Comment by yochananmarqos** [comment]
Any application that's tiled together. I'm working through my extensions one by one to determine which one might be causing issues. It turns out just disabling them after being active isn't enough. After disabling them, logging off and back in I can't reproduce the issue. Now I'm enabling them one one allowing some time in between to play around. 

One thing I discovered in the process that I may need to open a separate issue for is with Conky. While running, it causes windows to jump to different workspaces and/or monitors when toggling tiling or disabling / enabling monitors. This is my [conkyrc](https://pastebin.com/yyF2mnQJ).

**Comment by WatchMkr** [comment]
Try with Dash to Dock disabled. This sounds similar to another reported experience.

**Comment by yochananmarqos** [comment]
It appears Dash to Dock is the culprit, indeed. Thanks for confirming.

**Comment by yochananmarqos** [comment]
It's not just Dash to Dock, it's also Conky that causes it. After a day of running this normally without Dash to Dock or Conky, I just fired up Conky and the issue immediately started again.

So really it's anything that fights Pop Shell for adjusting window sizes. Conky is it's own window and wants to push other windows out of it's way on the bottom of my screen. Dash to Dock wants to display on the left side of my sceen and have it's own space. That apparently freaks out Pop Shell, especially when both are active.

**Comment by moniquelive** [comment]
I don't have conky but had dash to dock:

1. disabled dash to dock
2. open obs studio
3. open settings modal dialog (first shift left after 1 second)
4. close settings modal dialog (second shift left after 1 second)

100% repro. Super annoying

**Comment by rschuetz** [comment]
For Dash to Dock, the issue disappears if Dash to Dock has been switched to "Panel mode" (one big panel on the screen edge, with icons left/top aligned instead in the middle only, which looks unfortunately a bit ugly IMHO). 

Btw, the tiled windows still shift to the left (and only to the left), even if the dock is on the bottom of the screen.

**Comment by alaborderie** [comment]
hey! I've made a post about this on [reddit](https://www.reddit.com/r/pop_os/comments/mpzkms/pop_os_tiling_bug_everything_resizes_when_a_pop/) and got sent here.

I also experience this bug (You can find a video on the reddit post linked up there) and also happen to use Dash to dock!

I'll try disabling it later and will keep you updated if it still happens without it.

**Comment by alaborderie** [comment]
With Dash to Dock disabled in "Extensions" it looks good. I'll keep it disabled for now on my end, but would love to be able to use it again.

**Comment by spirkinator** [comment]
I've encountered this issue, too.  It usually happens and is most easily repeatable on my dual-monitor setup running PopOS 20.04.  No dock is enabled or installed.  Open Gnome Tweaks, then set Workspaces -> Display Handling -> _Workspaces on primary display only_.

With tiling enabled, open at least 2 tiled windows on each screen.  Initiate a pop-up in a program, then other windows will begin to shift left.

https://user-images.githubusercontent.com/67397983/115100328-b91da700-9ef0-11eb-8253-735879598fcf.mov

On my single monitor setup running PopOS 20.04, it happens less often, but can be replicated by opening 2 windows, then toggling Gnome Tweaks -> Workspaces -> Display Handling between the 2 options.

https://user-images.githubusercontent.com/67397983/115100473-c1c2ad00-9ef1-11eb-8d3e-871b0089f7e0.mp4

**Comment by jackpot51** [comment]
I believe this was fixed in https://github.com/pop-os/shell/pull/939 but will need to be backported for 20.04 and 20.10

**Comment by moniquelive** [comment]
I generally use 2 windows groups (stacks) side-by-side.
Now the left-shifting of the left window group turned into a "auto 50% / 50% screen width groups resize".
The trigger is the same: opening a pop window (eg.: open file dialog).
