### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by alexfornuto** [pop-os/shell#84]
I'd love to test out this extension. There are no install instructions or list of dependencies. My make is failing, and I'm willing to bet it's because I don't have a dependency that, as a mere power-user, I don't know I need.

Documentation is what makes these tools accessible to those who can't figure it out from the code. Please help us little guys out.

**Comment by alexfornuto** [comment]
FWIW [here](https://gist.github.com/alexfornuto/cabe525ddde7c517983b273ffe735d55) is my output for `rebuild.sh` or `make`. I have `node-typescript` installed.

**Comment by alexfornuto** [comment]
To solve my install issue, I needed typescript installed from npm, as the version installed from Ubuntu's repos failed as linked above.

**Comment by wezm** [comment]
Yeah it's not in the README but the [Makefile notes that TypeScript >= 3.8 is needed](https://github.com/pop-os/shell/blob/843f1c764a165896787f539bd2532c52e458aa46/Makefile#L44). The Ubuntu one [appears to be 1.7](https://packages.ubuntu.com/xenial/web/node-typescript).

**Comment by alexfornuto** [comment]
@wezm all the more reason for project documentation.

In my case, I was unable to get the extension to work, but don't know how to debug or where to look for error messages to share, so I suppose I just can't use it.

**Comment by mmstick** [comment]
The extension is targeting Pop!_OS 20.04, which has TypeScript 3.8 in the repository. If you get transpiler errors, it's because your version of TypeScript is too old.

**Comment by mmstick** [comment]
Extra documentation added to README
