### ISSUE TITLE
Q: launcher search path for executables/apps

### ISSUE THREAD

**Issue by jmbuhr** [pop-os/shell#840]
This is a question regarding the new launcher:

Could you point me to where I can find out more about the way the launcher discovers executables/apps?

I want to investigate this because some apps turn up multiple times in the launcher, but only one of the entries actually opens the app. E.g. for zotero:

![image](https://user-images.githubusercontent.com/17450586/104902653-464b7100-597f-11eb-9c8f-f8dd9a95af77.png)

only the entry with the capital letter opens zotero. In the regular `Super+A` app launcher, only one entry is shown:

![image](https://user-images.githubusercontent.com/17450586/104902776-6da23e00-597f-11eb-880b-14479ab21f39.png)

**Comment by jacobgkau** [comment]
Pop Shell checks each of these locations: https://github.com/pop-os/shell/blob/15575287dc82f91823d44be0c0dd31f62079510d/src/dialog_launcher.ts#L25 

It also checks anything in `$XDG_DATA_DIRS`: https://github.com/pop-os/shell/blob/15575287dc82f91823d44be0c0dd31f62079510d/src/dialog_launcher.ts#L263 

There is some discussion about the search order and duplicate removal in https://github.com/pop-os/shell/pull/764.

If you figure out what's adding the second entry and it appears to be a bug, please let us know.

**Comment by jmbuhr** [comment]
Thanks a lot!
I was able to find out that the `zotero.desktop` file in `~/.local/share/applications` was also executable, which lead to it being found twice. Once in it's role as a `.desktop` file and a second time as being executable. `chmod -x zotero.desktop` resolved the issue.
Not sure if this is something that the launcher could eliminate.

**Comment by MostHated** [comment]
Does this only show *.desktop files? I have a specific folder that has a bunch of my binary execs in it that is on my $PATH, but I can't seem to search for them. It seems like a pain to have to create .desktop files for all of them. Is there no way to have the launcher show and fire up an executable file?

**Comment by mmstick** [comment]
@MostHated Only desktop entries
