### ISSUE TITLE
Clicking top bar teleports cursor to top left of maximized window

### ISSUE THREAD

**Issue by vanitasvitae** [pop-os/shell#841]
**(1) Issue/Bug Description:**
When the pop! shell extension is enabled, this strange behaviour occurs:
When a window is maximized and I click somewhere on the top bar of the Gnome shell where there is empty space (eg. next to the time), then my mouse cursor is instantly teleported to the left onto the close button of the maximized window.

**(2) Steps to reproduce (if you know):**
Enable pop! shell extension, maximize some window, click on the gnome top bar

**(3) Expected behavior:**
the mouse stays where the click was made

**(4) Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**
GNOME Shell 3.38.2

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```1.1.0~1610693127~20.10~1557528```

**(7) Where was Pop Shell installed from:**
preinstalled

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
dual monitor 2x 1080p, both horizontal, left primary

**(9) Other Installed/Enabled Extensions:**
nothing too fancy

**(10) Other Notes:**

**Comment by leviport** [comment]
Hmm, I can't seem to reproduce this behavior. Could you take a screen cap of it happening and post it on this issue?

**Comment by jacobgkau** [comment]
I can recreate it: https://www.dropbox.com/s/w1zmlxt6xygshvz/shell-i841-screencast1.webm?dl=0 

In my case, the close button is in the top right of the window (the default for Pop!_OS), but the mouse still gets moved to the top left.

**Comment by birobirobiro** [comment]
Same here, when click menu bar my mouse go to left

**Comment by spxak1** [comment]
Same here.
Only started after last update of pop-shell. The problem goes away once pop-shell is disabled.

NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os


pop-shell:
  Installed: 1.1.0~1610693127~20.10~1557528
