### ISSUE TITLE
Minimize button doesnt work when pop shell enabled

### ISSUE THREAD

**Issue by rengare** [pop-os/shell#842]
**(1) Issue/Bug Description:**
I enabled minimize button with gnome tweaks. After a recent update, the button stops working. 
When I disable pop shell from extensions, the minimize button works

**(2) Steps to reproduce (if you know):**
1. Enable minimize button
2. Open tilix or chrome app (that's the one which I have knowledge about)
3. Click minimize button and observe the behaviour

**(3) Expected behaviour:**
Minimize button should minimize the window

**(4) Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

**Comment by GJRTimmer** [comment]
Same problem

**Comment by radam9** [comment]
I have the same issue, I have experienced it with:
- VSCode 1.51.2
- DB Browser for SQLite3 Version 3.11.2

**Comment by FoamyGuy** [comment]
Same issue here. Minimize button stopped working on about half of the windows 2 days ago after update:
```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

I have also witnessed the pointer teleport to top left as well.

**Comment by leviport** [comment]
You could also just add the staging branch that it's in:
1. Clone https://github.com/pop-os/pop/
2. run `./pop/scripts/apt add dev`
3. Once that `dev` branch is merged, remove the staging branch with the apt script: `./pop/scripts/apt remove dev`
