### ISSUE TITLE
Launcher does not learn on my system

### ISSUE THREAD

**Issue by kahironimashte** [pop-os/shell#849]
**(1) Issue/Bug Description:**
Launcher does not learn preferred commands

**(2) Steps to reproduce (if you know):**
Start an app multiple times does not reduce the keys necessary to make app default selection

**(3) Expected behavior:**
After multiple starts typing "f" should default select "firefox"
This works is how the Kupfer Launcher works. 

**(4) Distribution (run `cat /etc/os-release`):**
 VERSION="20.04.1 LTS (Focal Fossa)"

**(5) Gnome Shell version:**
3.36.4

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**(7) Where was Pop Shell installed from:**
github

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

**Comment by NonLogicalDev** [comment]
I would second that, coming from Alfred on MacOS. It honestly brings a ton of fluidity if the results and apps/windows (tricky duality in linux) especially are ordered by frecency (recency + frequency).

If possible can someone knowledgeable at point at a few files where to look for how the window/result list is built? Would be a good way to help someone to take a stab at it.

**Comment by scaryrawr** [comment]
> I would second that, coming from Alfred on MacOS. It honestly brings a ton of fluidity if the results and apps/windows (tricky duality in linux) especially are ordered by frecency (recency + frequency).
> 
> If possible can someone knowledgeable point at a few files where to look for how the window/result list is built? Would be a good way to help someone to take a stab at it.

I think you're interested in [dialog_launcher.ts](https://github.com/pop-os/shell/blob/master/src/dialog_launcher.ts#L128) specifically the sorter.

Depending on what else though, there's also a special case when the launcher is opened, but the user hasn't typed anything yet [pattern empty](https://github.com/pop-os/shell/blob/master/src/dialog_launcher.ts#L56), it might be good to have the Window List + frequently launched apps list.
