### ISSUE TITLE
Apps opening in background

### ISSUE THREAD

**Issue by scanevaro** [pop-os/shell#853]
**(1) Issue/Bug Description:**
When using something like Firefox or Steam or Atom and some other apps and I want to open an app like the Calculator, Geary or System Config the apps go to the background first.

**(2) Steps to reproduce (if you know):**
1) Open Firefox
2) Press Super, type Calculator and open it
3) Calculator opens in the background

**(3) Expected behavior:**
Calculator should come to the top when opening

**(4) Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```<pop-shell:
  Installed: 1.1.0~1611349201~20.10~2b9e4a4
  Candidate: 1.1.0~1611349201~20.10~2b9e4a4
  Version table:
 *** 1.1.0~1611349201~20.10~2b9e4a4 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status
>``` 


**(7) Where was Pop Shell installed from:**
System installed it


**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
2x1080p


**(9) Other Installed/Enabled Extensions:**



**(10) Other Notes:**

**Comment by mmstick** [comment]
Unable to replicate this. Any other extensions installed?

**Comment by bflanagin** [comment]
I can confirm and replicate the issue. Will update this comment when I have done some digging.

**Comment by bflanagin** [comment]
Here is a link to a video showing what I'm seeing. @scanevaro is this similar to what you are experiencing? 

https://drive.google.com/file/d/17-r1PAsIqjtjIXxRKCs7s2r9qhouw58U/view?usp=sharing

This is with stock Pop!_OS 20.10 with only work related applications installed (slack,dropbox,mattermost) on a Gazelle 15 (which probably doesn't matter.

**Comment by bflanagin** [comment]
A little more testing shows that using `super + /`  instead of just `super` doesn't trigger the issue. It seems that new applications launched from activities (forgive my ignorance on the specifics) aren't receiving focus on launch.

**Comment by jacobgkau** [comment]
I wonder if it's related to the new lines added here. https://github.com/pop-os/shell/pull/843/files#diff-04bba6a35cad1c794cbbe677678a51de13441b7a6ee8592b7b50be1f05c6f626R1253 

That PR was addressing regressions caused by https://github.com/pop-os/shell/pull/843, but in addition to undoing https://github.com/pop-os/shell/pull/843, it also added additional lines:

```
    on_overview_hidden() {
        const win = this.focus_window()
        if (win) win.activate()
    }
```

"Focusing a window on overview hidden" would seem to describe this issue. (Seems like it's happening on 20.10 but not 20.04.)

**Comment by mmstick** [comment]
Should be getting called when the overview is unhidden. Wrong place for that code
