### ISSUE TITLE
[FEATURE PROPOSAL] Quit currently highlighted app

### ISSUE THREAD

**Issue by dodalovic** [pop-os/shell#857]
Hi, first of all - I totally enjoy Pop OS! Thanks for your wonderful product!

I have one feature proposal: the ability to quit the currently highlighted running app:

![image](https://user-images.githubusercontent.com/6358061/106061062-30634c00-60f5-11eb-8b11-31339e128fd5.png)

I feel it would be very interesting if I could be able to press `ctrl+Q` to quit the currently highlighted app. 

Any thoughts?

Thanks once again!

**Comment by mmstick** [comment]
`Super+Q` does this

**Comment by mmstick** [comment]
Oh you mean through the launcher

**Comment by dodalovic** [comment]
Maybe it'd be nice to support both `ctrl+Q` and `super+Q` (if the idea is interesting at all :smile: )

**Comment by mmstick** [comment]
Implemented as Ctrl+Q

**Comment by dodalovic** [comment]
Nice! Any idea about when would it be released?

**Comment by mmstick** [comment]
Shortly after the linked PR is merged

**Comment by dodalovic** [comment]
Thanks, Michael, hope more people than just me will use it! 🤝
