### ISSUE TITLE
Moving a "Floating Window Exceptions" window to another workspace causes them to tile.

### ISSUE THREAD

**Issue by expe** [pop-os/shell#859]
**(1) Issue/Bug Description:**
Moving a "Floating Window Exceptions" window to another workspace causes them to tile.

**(2) Steps to reproduce (if you know):**
1. Add an application to "Floating Window Exceptions"
2. Open the application you added in (1) or just open the "Floating Window Exceptions" window
3. Move the application to another workspace
4. The application / window is now tiled

**(3) Expected behavior:**
The application in (4) above should still be floating. This is working as expected with windows floated manually (`meta + g`)

**(4) Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**
3.38.1

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```
pop-shell:
  Installed: 1.1.0~1611349201~20.10~2b9e4a4
  Candidate: 1.1.0~1611709512~20.10~673b87a
  Version table:
     1.1.0~1611709512~20.10~673b87a 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
 *** 1.1.0~1611349201~20.10~2b9e4a4 100
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

Installed by Pop!_OS

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1x 3440x1440 horizontal

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

**Comment by Tessag159** [comment]
Having this bug as well, providing my system specs in case it will help with providing a fix.

**(4) Distribution (run `cat /etc/os-release`):**
```
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```

**(5) Gnome Shell version:**
GNOME Shell 3.38.3


**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
`Commit 77650a9`


**(7) Where was Pop Shell installed from:**
Local build with TypeScript v 4.2.2


**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
2x 1920x1080, Primary(Horizontal), Secondary(Horizontal, Laptop Screen)


**(9) Other Installed/Enabled Extensions:**
AlternateTab
Freon
Lock Keys
Auto Move Windows
Dash to Panel
KStatusNotifierItem/AppIndicator Support
Launch New Instance
Pamac Updates Indicator
Removeable Drive Menu
User Themes
Workspace Navigator


**(10) Other Notes:**

**Comment by dhollinger** [comment]
I am also seeing this bug. I see it when moving a window from the exception list to a different workspace OR to a different monitor.

**(4) Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**
`3.38.3-2ubuntu0.20.10.2pop1~1614116211~20.10~0176ca0`


**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```
pop-shell:
  Installed: 1.1.0~1615925109~20.10~77650a9
  Candidate: 1.1.0~1615925109~20.10~77650a9
  Version table:
 *** 1.1.0~1615925109~20.10~77650a9 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**
Pop_OS Apt repository


**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
2x 1080p
Primary(Horizontal, Dynamic Workspaces)
Secondary(Horizontal, Single Workspace)

**(9) Other Installed/Enabled Extensions:**
* ArcMenu
* Caffeine
* Clipboard Indicator
* Dash to Panel
* Lock Keys
* Sound Input & Output Device Chooser

Pop_OS Included Extensions:
* Alt Tab
* Always Show Workspaces
* Desktop Icons NG
* Pop Shell
* Pop Shop Details
* System76 Power
* Ubuntu AppIndicators

**(10) Other Notes:**

**Comment by expe** [comment]
I was pleasantly surprised that the issue was fixed recently. Thanks!

Here's my pop shell version:

```
pop-shell:
  Installed: 1.1.0~1623101914~20.10~df8b27b
  Candidate: 1.1.0~1623101914~20.10~df8b27b
  Version table:
 *** 1.1.0~1623101914~20.10~df8b27b 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status
```
