### ISSUE TITLE
[Feature request] Option to set tiling/stacking per workspace

### ISSUE THREAD

**Issue by hliebert** [pop-os/shell#860]
It would be great if tiling/stacking could be enabled on a per workspace (or per display) basis, or to select  some workspaces that are exempt from the selection. I generally use tiling mode, but typically have a single workspace that has a library database and a lot of pdf research papers open where stacking mode is more convenient. 

This is somewhat related to #606, but I'd prefer to have pdfs tile on other displays or when moving them around.

**Comment by jacobgkau** [comment]
Closing as a duplicate of https://github.com/pop-os/shell/issues/380.

**Comment by hliebert** [comment]
Sorry, didn't see that one.
