### ISSUE TITLE
No applications populate in search window

### ISSUE THREAD

**Issue by davidskeck** [pop-os/shell#861]
**Distribution (run `cat /etc/os-release`):**
 
 ```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

N/A

**Issue/Bug Description:**

Pressing Super+/ produces the search window, but nothing is returned when I enter a search term, i.e. "terminal".

**Steps to reproduce (if you know):**

Press Super+/, enter a search term. Nothing populates.

**Expected behavior:**

Applications are populated.

**Other Notes:**

![image](https://user-images.githubusercontent.com/1740630/103386306-23d6de00-4acc-11eb-8ee6-3850adb743b1.png)

**Comment by DavidPeltz** [comment]
This behaviour stopped after an update this week.  At present it is working again so I suspect it was one of those never identified but fixed through some other change, kind of bugs!

**Comment by davidskeck** [comment]
I haven't seen this issue for about a week also. It went away after a recent reboot. I think we can close this for now. I'll reopen if I see it again. Thanks everyone.
