### ISSUE TITLE
Chromium unable to access Downloads directory on an NTFS partition [flatpak]

### ISSUE THREAD

**Issue by arvigeus** [pop-os/shell#862]
**(1) Issue/Bug Description:**

Pop!_OS suggested me to switch to flatpak version of Chromium. After the switch I am unable to access my downloads directory, which is situated on an NTFS partition.

I tried running it with `flatpak run org.chromium.Chromium --filesystem=/mnt/d/Downloads` - no success.

**(2) Steps to reproduce (if you know):**

Save something from the web. When a dialog appears, try navigating to directory on an NTFS partition (in my case it's Downloads).

**(3) Expected behavior:**

Save to Downloads

**(4) Distribution (run `cat /etc/os-release`):**
 
Pop!_OS 20.10

**(5) Gnome Shell version:**

3.38.1

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1611709512~20.10~673b87a
  Candidate: 1.1.0~1611709512~20.10~673b87a
  Version table:
 *** 1.1.0~1611709512~20.10~673b87a 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status

```

**(7) Where was Pop Shell installed from:**

Default

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1080p, horizontal, primary

**(9) Other Installed/Enabled Extensions:**

Gnome Tweaks

**(10) Other Notes:**

**Comment by mmstick** [comment]
Use Flatseal to manage permissions for Flatpaks
