### ISSUE TITLE
Terminal Windows opened after upgrade is not placed in the right place.

### ISSUE THREAD

**Issue by Shandun** [pop-os/shell#863]
**(1) Issue/Bug Description:**
I used pop shell on my laptop with ubuntu 20.04 os for a while. It's always work until last week I upgrade ubuntu. When update was done, I open terminal and find the window start in the middle of screen. I also test new app window, it works well. But terminal and system windows like terminal and file manager will happen to be in the middle when I open them. Even when I use windows + y twice to trim the windows, the windows shows in the middle of the screen. 
update: Today I also find when I open an app window, the window show on the right half of the screen, but I can only click the left half to click the right half button.

**(2) Steps to reproduce (if you know):**
I'm not pretty sure how to exactly reproduce it, I just know it happened after I update the ubuntu 20.04 last week.

**(3) Expected behavior:**
windows show in the middle of the screen.
just like this:
![image](https://user-images.githubusercontent.com/32905893/106371933-65eb7d80-631f-11eb-9561-b53c81744230.png)

**(4) Distribution (run `cat /etc/os-release`):**
 
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**(5) Gnome Shell version:**
3.36.8

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

version 3.0

**(7) Where was Pop Shell installed from:**
github 
master_focal branch

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1x1080p

**(9) Other Installed/Enabled Extensions:**

![image](https://user-images.githubusercontent.com/32905893/106372069-c202d180-6320-11eb-97fe-a78cfb944a9c.png)

**(10) Other Notes:**
Today I also find when I open an app window, the window show on the right half of the screen, but I can only click the left half to click the right half button.

**Comment by bflanagin** [comment]
@Shandun could you provide a video of the issue. I can't reproduce it on my machine.

**Comment by PaulMcMillan** [comment]
I'm seeing similar issues - I hadn't updated the popos shell in a while, but a regular system update resulted in the terminal behaving weirdly. I updated popos and still get the weird behavior. As far as I can tell, the terminal window is being _sized_ correctly for tiling windows, but there's something wrong with where it is being positioned, resulting in weird jumpiness. It moves around like a floating window, but if you get it near a snap point where it would normally slot into a split, it resizes for that and jumps away somewhere else on the screen.

I'm using Ubuntu 20.04, with the NVIDIA graphics driver stack. I recently updated to the latest `master_focal` branch, and get the same behavior. I'll try and upload a video later on.

**Comment by grahamPegNetwork** [comment]
Adding a +1 to this issue. I've been seeing this issue for several days since I ran an apt update and restarted. It's rather annoying. I can attempt to semi manually position the terminal where it should go, but sometimes it doesn't work, or resizing throws spacing off.  

![image](https://user-images.githubusercontent.com/37225848/107741664-7954fc00-6cc2-11eb-8379-9d3b7eed054b.png)

Let me know if there is any additional information that can help.

**Comment by mmstick** [comment]
Is this issue only being experienced on Ubuntu?

**Comment by grahamPegNetwork** [comment]
It does appear that three of us experiencing it are on Ubuntu, so it would appear so thus far.

**Comment by Shandun** [comment]
> @Shandun could you provide a video of the issue. I can't reproduce it on my machine.

https://user-images.githubusercontent.com/32905893/110227133-f3376a00-7ea9-11eb-8bb5-8ac65d2dcf52.mp4


https://user-images.githubusercontent.com/32905893/110227136-f9c5e180-7ea9-11eb-81dc-10150cfde634.mp4

**Comment by Shandun** [comment]
Finally I found solution. 
1. Upgrade your ubuntu to make sure OS is the newest.
2. Delete your "shell" directory which was down loaded from https://github.com/pop-os/shell. Mine is located in "/home/user/shell".
3. Then download it again, I use command below:
    git clone https://github.com/pop-os/shell
4. Change directory to shell, for me:
    cd home/user/shell
5. Install with branch master, I use command below(Do not change branch. I use branch master_focal, which I thought has something wrong in that):
    make local-install
