### ISSUE TITLE
Dragging a window over a stack no longer adds it to the stack

### ISSUE THREAD

**Issue by lccro** [pop-os/shell#873]
**(1) Issue/Bug Description:**

After updating, dragging a window over a stack no longer adds it to the stack.

**(2) Steps to reproduce (if you know):**

Create a stack (meta+s)
Drag a window (using the mouse) over it

**(3) Expected behavior:**

The dragged window to be added to the stack.

**(4) Distribution (run `cat /etc/os-release`):**

``` 
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**

```
3.38.2-1pop1~1610298831~20.10~41092e5
```

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```
pop-shell:
  Installed: 1.1.0~1612935070~20.10~0657c59
  Candidate: 1.1.0~1612935070~20.10~0657c59
```

**(7) Where was Pop Shell installed from:**

apt

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

irrelevant, it was working fine until I updated pop-shell today (2021-02-10)

**(9) Other Installed/Enabled Extensions:**

irrelevant, it was working fine until I updated pop-shell today

**(10) Other Notes:**

"dragging" the window using the keyboard: `meta+enter` and arrow to move it over the stack *does* work

**Comment by jacobgkau** [comment]
I see that you closed this, but for anyone else who finds the issue by searching: the behavior of the overlay has slightly changed to allow more control via the mouse. To drag a window into a stack, try moving the mouse slightly higher or lower until you see the overlay cover the entire area that will become a stack.
