### ISSUE TITLE
mod + P resets diplay layout

### ISSUE THREAD

**Issue by nshmn** [pop-os/shell#875]
**(1) Issue/Bug Description:**
When pressing mod + p the display layout is rested to the standard layout. Every time you have to rearrange the displays.

**(2) Steps to reproduce (if you know):**
Press mod + P while having a non-standard display layout

**(3) Expected behavior:**
the display layout for each mode is saved

**(4) Distribution (run `cat /etc/os-release`):**
```
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**
```
gnome-shell:
  Installed: 3.38.2-1pop1~1610298831~20.10~41092e5
  Candidate: 3.38.2-1pop1~1610298831~20.10~41092e5
  Version table:
     3.38.2-1ubuntu1~20.10.1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy-updates/main amd64 Packages
 *** 3.38.2-1pop1~1610298831~20.10~41092e5 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
        100 /var/lib/dpkg/status
     3.38.1-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/main amd64 Packages
```

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1612395769~20.10~190ad70
  Candidate: 1.1.0~1613083995~20.10~6b2287f
  Version table:
     1.1.0~1613083995~20.10~6b2287f 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
 *** 1.1.0~1612395769~20.10~190ad70 100
        100 /var/lib/dpkg/status


```

**(7) Where was Pop Shell installed from:**
clean PopOS install

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
2x External(4k and 1080p), 1x Internal. 

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

**Comment by bflanagin** [comment]
@nshmn when you have a moment please fill out more of the issue so that we can better track down the problem. In particular we need to know the versions of Gnome Shell, Pop Shell, and how many monitors you have. 

You can get the information on Gnome Shell and Pop Shell by running the following:
```
apt policy gnome-shell
```
and
```
apt policy pop-shell
```

**Comment by mmstick** [comment]
Cannot replicate. Reopen if you have more info

**Comment by rxn7** [comment]
I have this problem as well

**Comment by jskulski** [comment]
Ran into this, looking for a way to display this. This short cut gives me a selection to join or mirror displays. Even if choose to join displays (the option I'm using), some of my settings are reset to defaults: rotation (portrait left -> landscape), and zoom % (200% -> 100%) 

```
jskulski@workbench:~$ apt policy gnome-shell
gnome-shell:
  Installed: 42.3.1-2ubuntu1pop1~1660592271~22.04~ca01bf8
  Candidate: 42.3.1-2ubuntu1pop1~1660592271~22.04~ca01bf8
  Version table:
     42.4-0ubuntu0.22.04.1 500
        500 http://apt.pop-os.org/ubuntu jammy-updates/main amd64 Packages
 *** 42.3.1-2ubuntu1pop1~1660592271~22.04~ca01bf8 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     42.0-2ubuntu1 500
        500 http://apt.pop-os.org/ubuntu jammy/main amd64 Packages
```

```
jskulski@workbench:~$ apt policy pop-shell
pop-shell:
  Installed: 1.1.0~1662496692~22.04~91a8599
  Candidate: 1.1.0~1664465783~22.04~aaf86e4
  Version table:
     1.1.0~1664465783~22.04~aaf86e4 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
 *** 1.1.0~1662496692~22.04~91a8599 100
        100 /var/lib/dpkg/status
```
```
jskulski@workbench:~$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

Update: I was able to disable the keyboard shortcut. It does not display in the settings, but can be disabled with the dconf-editor: https://www.reddit.com/r/pop_os/comments/hw4kgm/disable_superp_shortcut/
