### ISSUE TITLE
Pop!_OS Tiling breaks when leaving workspace

### ISSUE THREAD

**Issue by kevinjcliao** [pop-os/shell#876]
**(1) Issue/Bug Description:** Leaving a Workspace causes tiling to break for a single window workspace
I love Pop and adding tiling support to GNOME has been a dream, but this bug is making Pop pretty unusable for me. 

**(2) Steps to reproduce (if you know):**
https://user-images.githubusercontent.com/8745371/107797615-16349980-6d96-11eb-8bb5-0419add5341c.mp4
1. Open up a window in my workspace
2. Leave my workspace and return to it. 
3. Observe that the window now only takes up half the screen. 
4. Also observe that window stacking is enabled, and there is a mysterious window that is stacked with my browser that shouldn't exist. 

Also: 
1. Toggle workspace tiling on and off with only one window present. 
2. Observe that window now takes up half of the workspace. 

**(3) Expected behavior:** Workspace tiling does not reset. 

**(4) Distribution (run `cat /etc/os-release`):** Pop!_OS 20.10
 

**(5) Gnome Shell version:** 3.38.2

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```
pop-shell:
  Installed: 1.1.0~1613083995~20.10~6b2287f
  Candidate: 1.1.0~1613083995~20.10~6b2287f
  Version table:
 *** 1.1.0~1613083995~20.10~6b2287f 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status                    
```

**(7) Where was Pop Shell installed from:** POP!_OS install. 

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):** Single display on my LEMP9

**(9) Other Installed/Enabled Extensions:** 
* Alt-Tab: Raise First Window
* Always Show Workspaces
* Dash to Dock
* Desktop Icons ng (ding)
* Extended gestures
* Openweather
* Pop shell
* Pop shop details
* System76 power
* Transparent top bar
* Ubuntu appindicators
* Wikimedia commons wallpaper changer

**(10) Other Notes:**

**Comment by blacksails** [comment]
Might be a duplicate of #850

**Comment by kevinjcliao** [comment]
I was able to solve this by disabling the Gnome-Desktop Icons Extension. From System76 support: 

> Could you see if disabling the Gnome Desktop Icons extension fixes things? To do this, hit the super key or click on the Activities in the upper left and type in "exten" and then click on the Extensions program; its icon is a green puzzle piece. Then make sure the Desktop Icons is turned off.
