### ISSUE TITLE
Unable to install on Ubuntu Unity 20.04

### ISSUE THREAD

**Issue by phuongortheeast** [pop-os/shell#879]
**(1) Issue/Bug Description:**
When execute: `make local-install`

UUID is "pop-shell@system76.com"
depcheck
rm -rf _build schemas/gschemas.compiled target
tsc
for proj in color_dialog floating_exceptions; do tsc --p src/${proj}; done
sh scripts/transpile.sh
glib-compile-schemas schemas
touch schemas
rm -rf _build
mkdir -p _build
cp -r metadata.json icons schemas target/*.js *.css _build
for proj in color_dialog floating_exceptions; do \
	mkdir -p _build/${proj}; \
	cp -r target/${proj}/*.js _build/${proj}; \
done
rm -rf /home/theeast/.local/share/gnome-shell/extensions/pop-shell@system76.com
mkdir -p /home/theeast/.local/share/gnome-shell/extensions/pop-shell@system76.com /home/theeast/.local/share/pop-shell/launcher /home/theeast/.local/share/pop-shell/scripts
cp -r _build/* /home/theeast/.local/share/gnome-shell/extensions/pop-shell@system76.com/
cp -r src/plugins/* /home/theeast/.local/share/pop-shell/launcher
cp -r src/scripts/* /home/theeast/.local/share/pop-shell/scripts
chmod +x /home/theeast/.local/share/pop-shell/launcher/**/*.js /home/theeast/.local/share/pop-shell/scripts/*
if ! command -v gnome-extensions >/dev/null; then \
	echo 'You must install gnome-extensions to configure or enable via this script' \
	'(`gnome-shell` on Debian systems, `gnome-extensions` on openSUSE systems.)'; \
	exit 1; \
fi
sh scripts/configure.sh
+ set_keybindings
+ shortcut_applied
+ test -f ./.confirm_shortcut_change
+ read -p Pop shell will override your default shortcuts. Are you sure? (y/n)  CONT
Pop shell will override your default shortcuts. Are you sure? (y/n) y
+ test y = y
+ touch ./.confirm_shortcut_change
+ return 1
+ left=h
+ down=j
+ up=k
+ right=l
+ KEYS_GNOME_WM=/org/gnome/desktop/wm/keybindings
+ KEYS_GNOME_SHELL=/org/gnome/shell/keybindings
+ KEYS_MUTTER=/org/gnome/mutter/keybindings
+ KEYS_MEDIA=/org/gnome/settings-daemon/plugins/media-keys
+ KEYS_MUTTER_WAYLAND_RESTORE=/org/gnome/mutter/wayland/keybindings/restore-shortcuts
+ dconf write /org/gnome/mutter/wayland/keybindings/restore-shortcuts @as []
+ dconf write /org/gnome/desktop/wm/keybindings/minimize @as ['<Super>comma']
+ dconf write /org/gnome/shell/keybindings/open-application-menu @as []
+ dconf write /org/gnome/shell/keybindings/toggle-message-tray @as ['<Super>v']
+ dconf write /org/gnome/shell/keybindings/toggle-overview @as []
+ dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-left @as []
+ dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-right @as []
+ dconf write /org/gnome/desktop/wm/keybindings/maximize @as []
+ dconf write /org/gnome/desktop/wm/keybindings/unmaximize @as []
+ dconf write /org/gnome/desktop/wm/keybindings/move-to-monitor-up @as []
+ dconf write /org/gnome/desktop/wm/keybindings/move-to-monitor-down @as []
+ dconf write /org/gnome/desktop/wm/keybindings/move-to-monitor-left @as []
+ dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-down @as []
+ dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-up @as []
+ dconf write /org/gnome/desktop/wm/keybindings/move-to-monitor-right @as []
+ dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-down ['<Primary><Super>Down','<Primary><Super>j']
+ dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-up ['<Primary><Super>Up','<Primary><Super>k']
+ dconf write /org/gnome/mutter/keybindings/toggle-tiled-left @as []
+ dconf write /org/gnome/mutter/keybindings/toggle-tiled-right @as []
+ dconf write /org/gnome/desktop/wm/keybindings/toggle-maximized ['<Super>m']
+ dconf write /org/gnome/settings-daemon/plugins/media-keys/screensaver ['<Super>Escape']
+ dconf write /org/gnome/settings-daemon/plugins/media-keys/home ['<Super>f']
+ dconf write /org/gnome/settings-daemon/plugins/media-keys/email ['<Super>e']
+ dconf write /org/gnome/settings-daemon/plugins/media-keys/www ['<Super>b']
+ dconf write /org/gnome/settings-daemon/plugins/media-keys/terminal ['<Super>t']
+ dconf write /org/gnome/settings-daemon/plugins/media-keys/rotate-video-lock-static @as []
+ dconf write /org/gnome/desktop/wm/keybindings/close ['<Super>q']
+ gnome-extensions list
+ grep native-window
+ dconf write /org/gnome/mutter/workspaces-only-on-primary false
echo "Restart shell!"
Restart shell!
if bash -c 'xprop -root &> /dev/null'; then \
	busctl --user call org.gnome.Shell /org/gnome/Shell org.gnome.Shell Eval s 'Meta.restart("Restarting Gnome...")'; \
else \
	gnome-session-quit --logout; \
fi
Call failed: No such method “Eval”
make: *** [Makefile:98: restart-shell] Error 1

When execute: `./rebuild.sh`

`bash: ./rebuild.sh: No such file or directory`

**(2) Steps to reproduce (if you know):** 
`$ cd shell`
Execute the commands above

**(3) Expected behavior:**

After rebooting, the Pop-shell appear on the top bar

**(4) Distribution (run `cat /etc/os-release`):**
 
Ubuntu Unity 20.04.2 LTS

**(5) Gnome Shell version:**

3.36.4

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

Jan 13 2021

**(7) Where was Pop Shell installed from:**

git clone https://github.com/pop-os/shell.git

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

Single monitor 1366x768

**(9) Other Installed/Enabled Extensions:**

Unity DE
Compiz WM

*not extensions but I think it affected the installation*
*no extensions were installed/enabled*

**(10) Other Notes:**

**Comment by jacobgkau** [comment]
Pop Shell is a GNOME extension. I don't think we would expect it to work on Unity. See answers like [this](https://askubuntu.com/questions/608806/is-it-possible-to-install-gnome-shell-extension-in-unity) and [this](https://askubuntu.com/questions/85915/are-gnome-shell-extensions-compatible-with-unity).

**Comment by anafvana** [comment]
Although it has been pointed out that it won't work because it's Ubuntu Unity, the reason for this fail is that they have used `./rebuild.sh`
That no longer seems to work for installing. If you, like me, were trying to install on good ol' Ubuntu, it seems like you should use `make install` or `make local-install`.
