### ISSUE TITLE
Last stacked window gets unstacked automatically

### ISSUE THREAD

**Issue by PeSader** [pop-os/shell#881]
**(1) Issue/Bug Description:**
When I'm stacking two windows and I remove one of them from the stack, stacking mode is disabled. This started happening since commit [0657c59](https://github.com/pop-os/shell/commit/0657c5908859f67ab688b7bab35eda0465e54941).

**(2) Steps to reproduce (if you know):**
- Make sure the shell has been updated recently (on or ahead of commit [0657c59](https://github.com/pop-os/shell/commit/0657c5908859f67ab688b7bab35eda0465e54941))
- Stack two windows
- Remove one window from the stack
- Both windows will leave stacking mode

**(3) Expected behavior:**
- The window that was not moved should remain on stacking mode

**(4) Distribution (run `cat /etc/os-release`):**
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**(5) Gnome Shell version:**
```
$ apt policy gnome-shell:
  Installed: 3.36.4-1ubuntu1~20.04.2
  Candidate: 3.36.4-1ubuntu1~20.04.2
  Version table:
 *** 3.36.4-1ubuntu1~20.04.2 500
        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
        500 http://br.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.36.1-5ubuntu1 500
        500 http://br.archive.ubuntu.com/ubuntu focal/main amd64 Packages
```

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
commit 6b2287fa7ed61043d629325bd5ed17f74028418c (HEAD -> master, origin/master, origin/HEAD)
Author: Michael Aaron Murphy <mmstick@pm.me>
Date:   Thu Feb 11 14:18:03 2021 -0700

    fix: Mouse dropping from stack to adjacent sibling

```

After a bit of investigation though, the bug only starts appearing on commit [0657c59](https://github.com/pop-os/shell/commit/0657c5908859f67ab688b7bab35eda0465e54941), which improved support for mouse tilling. Rolling back to its [parent](https://github.com/pop-os/shell/commit/190ad70fe9e7ebea928892443e3787f86d1dddb7) solved the bug!

**(7) Where was Pop Shell installed from:**
Built locally

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1 x 1080p

**(9) Other Installed/Enabled Extensions:**
None since it started happening

**(10) Other Notes:**
Thanks for developing Pop!_OS shell! It made GNOME orders of magnitude more powerful.

**Comment by bettyvschmartz** [comment]
I can confirm the same behaviour since upgrading. This has broken stacking. When I unstack the last window it exits stack mode and I have to `super+s` every time. 

-- BVS

**Comment by jacobgkau** [comment]
Thank you for opening an issue. This is expected behavior since https://github.com/pop-os/shell/pull/865, although it may be wise to reconsider-- it seems to make using the mouse slightly simpler at the cost of potentially over-simplifying the keyboard.

> This has broken stacking. When I unstack the last window it exits stack mode and I have to super+s every time.

I would not say this has "broken stacking," it just makes destroying a stack quicker by avoiding one of the situations where a single-window stack existed.

**Comment by PeSader** [comment]
Just read your comment [here](https://github.com/pop-os/shell/pull/865#issuecomment-773532031)!

I really like the idea of using the mouse to manipulate the window layout, not for my personal use but because I think it makes the user experience much more beginner friendly. Considering System76's mission to bring high quality open-source software to the masses, I think this tradeoff makes sense. However, I'd still love to be able to turn stacking off only when I need it off. Would it be possible to make this behavior an option (maybe a setting that can be toggled)?

Thanks again for developing this!

**Comment by mmstick** [comment]
I'm sure there's a way to determine if a window was unstacked by mouse or keyboard, and only auto-unstacking if moved by mouse.

**Comment by bettyvschmartz** [comment]
@jacobgkau thanks for your reply. I personally would appreciate it being reconsidered. 

> I would not say this has "broken stacking," it just makes destroying a stack quicker by avoiding one of the situations where a single-window stack existed.

OK let's agree it hasn't _'broken'_ stacking but in my use case (and I'm sure that of many others) it makes stacking _less_ intuitive and/or user friendly than before. I use stacking for applications that don't support tabs. Take email, for example; if I open several emails, they were added to the stack in new tabs. If I closed all of my open emails then I would still be in stacking mode and could open new ones. Now, when I close my last _compose_ window I lose stacking and opening new emails results in lots of small windows in tile mode, which isn't usable. I either need to `super+s` each time, leave one random _compose_ window open, or add a floating window exception. Another use is for _remmina_ and _virt-manager_ so I can have the console window stacked with the VM or VNC windows. The same applies for lots of applications.

This was a killer feature to maximize screen space, and avoid lots of floating windows, or unusable tiled windows. 

> However, I'd still love to be able to turn stacking off only when I need it off. Would it be possible to make this behavior an option (maybe a setting that can be toggled)?

This would be a good way to resolve it. 

-- BVS

**Comment by PeSader** [comment]
Thank @mmstick for such a timely fix!

I'm still experiencing a minor issue, though. When I close one of two windows in a stack, the remaining window still gets unstacked automatically.

In the screencast below I first remove one of two windows from a stack and the last window does not get unstacked (which was the fix merged by @mmstick). However, if I close one of two windows in the stack, the last window is unstacked.

![](https://i.imgur.com/wY9B96Q.gif)

For reference, here is how it used to behave before mouse tilling:

![](https://i.imgur.com/hVV6sWP.gif)

**Comment by bettyvschmartz** [comment]
I can confirm this; the last window remains in stack mode if you remove the penultimate window from the stack, however closing that windows destroys the stack. 

Unfortunately the commit doesn't fix the issue. 

-- bvs

**Comment by enricofadly** [comment]
> I can confirm this; the last window remains in stack mode if you remove the penultimate window from the stack, however closing that windows destroys the stack.
> 
> Unfortunately the commit doesn't fix the issue.
> 
> -- bvs

Is there a way to make them not to destroy the stack even tho I close the window? because in my usual twm they won't destroy the stack even tho I close it,

**Comment by bettyvschmartz** [comment]
@mmstick this issue has been closed by the commit in #888 but as mentioned that doesn't fix this entirely. It fixes part of the issue. 

It has been opened again in #1301. Is this issue to be re-opened, or as you mentioned it's expected behavior in a previous comment, is it not to be fixed? If the later is the case, I'm not sure why moving windows with the mouse retains the stack but closing windows doesn't. 

-- bvs

**Comment by jacobgkau** [comment]
> I'm not sure why moving windows with the mouse retains the stack but closing windows doesn't.

@bettyvschmartz The reason for this was that when using the keyboard, the last window can be un-stacked with Super+S. When using the mouse, there would be no way to destroy the stack if it wasn't destroyed automatically (i.e. nothing you can click would destroy the stack.) The behavior is still open for discussion, but that was the rationale for the current behavior.

> It has been opened again in https://github.com/pop-os/shell/issues/1301. Is this issue to be re-opened,

I would say let's keep only one open issue at a time per issue, so let's keep discussion in https://github.com/pop-os/shell/issues/1301 now.

**Comment by 392781** [comment]
I'm on the opposite boat, I wish that stacking mode would automatically turn off when I remove all but 1 windows from the stack.  This should be a toggle or a config that can be added to the shell.
