### ISSUE TITLE
[FEATURE PROPOSAL] Save and load Sessions

### ISSUE THREAD

**Issue by hovo1990** [pop-os/shell#886]
Hi, 
Thanks for the POP shell, it's a wonderful tool!

I have one feature proposal: It would be really awesome if it was possible to save and reload opened programs and the positions of their windows (stacking included).

**Comment by trevarj** [comment]
Came here looking for this too. I wonder if it would something that can be done with a plugin.

**Comment by mmstick** [comment]
Duplicate of #735
