### ISSUE TITLE
Error thrown after new user creation

### ISSUE THREAD

**Issue by brs17** [pop-os/shell#89]
When creating a second user on a 20.04 system, after completing GNOME Initial Setup, I get a notification of an error with Pop Shell.

![error](https://user-images.githubusercontent.com/7460774/77113765-00392000-69f1-11ea-9616-4c4843f6f1fd.png)

**Comment by mmstick** [comment]
Should be fixed by 57e9db1

**Comment by leviport** [comment]
Confirmed, I'm not seeing it anymore
