### ISSUE TITLE
Designs for default tiling, launcher, menu and a section in Settings > Desktop & Workspaces

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/shell#9]
**Design for the default tiling (the logic is open to discussion).** 
Rules/Steps:
1. Maximum number of tiles before the system starts splitting windows horizontally:
    - regular format - 2
    - ultrawide - 4
2. The focus shifts to the newly opened window.
3. Open the next window to the right from the one with the focus untill you reach the horizontal split point. 
4. When splitting windows horizontally, open the new window at the bottom. 
5. Then split the window to the left.
6. After that, open the new window to the left of the one with focus.
![Default-Tiling(1)](https://user-images.githubusercontent.com/57502897/70447669-5a266300-1a5c-11ea-9734-4dc5e6404882.png)

**Menu design** that includes: 
keyboard shortcuts,
gap setting,
the option to launch windows tiled,
custom layout.
All of the small designs in one window - just to show where the menu will be.
![Combined](https://user-images.githubusercontent.com/57502897/70449005-7925f480-1a5e-11ea-8a2d-580c30cbe156.png)

![1](https://user-images.githubusercontent.com/57502897/70448081-0e27ee00-1a5d-11ea-9229-9b6b7dd62614.png)
![1-1](https://user-images.githubusercontent.com/57502897/70448088-108a4800-1a5d-11ea-8c86-81e97b351a14.png)

Step by step saving the new custom layout (Click Save Current in the menu - name the layout and click save - confirmation that the layout was saved - new layout added to the list of custom layouts).
1. ![1-2](https://user-images.githubusercontent.com/57502897/70448105-18e28300-1a5d-11ea-9bd4-1d4bd1008125.png)

2. ![Name](https://user-images.githubusercontent.com/57502897/70448236-4e876c00-1a5d-11ea-956c-433c74176749.png)

3. ![Confirmation](https://user-images.githubusercontent.com/57502897/70448241-50512f80-1a5d-11ea-8914-95cc16d61dca.png)

4. ![1-3](https://user-images.githubusercontent.com/57502897/70448114-1aac4680-1a5d-11ea-9ff1-da1785201408.png)

**Launcher design**
![Launcher](https://user-images.githubusercontent.com/57502897/70448016-f51f3d00-1a5c-11ea-8569-3b9dd50c68bf.png)

**Section of the Settings > Desktop & Workspaces page.** 
The page is part of the upcoming Gnome design: [https://gitlab.gnome.org/GNOME/gnome-control-center/merge_requests/590](url)
![DesktopWorkspaces](https://user-images.githubusercontent.com/57502897/70447997-eb95d500-1a5c-11ea-8ffe-4b551c6a5e8f.png)

**Comment by maria-komarova** [comment]
Here is the updated Settings page design (no custom layout and keyboard shortcuts after the in-person conversation):
![DesktopWorkspaces](https://user-images.githubusercontent.com/57502897/71635975-21a32080-2be7-11ea-939a-99bea2d86bb2.png)

**Comment by WatchMkr** [comment]
Note that ultrawide is designated as a ratio of 21:9 or greater.

**Comment by mmstick** [comment]
Search-based window navigation now complete.
Now for the tile-by-default mode

**Comment by mmstick** [comment]
I'm thinking that we'll also need a session exit dialog, which would contain options such as:

- _Lock Screen
- _Suspend
- Log _Out
- _Restart
- Shut _Down

Currently, the shortcuts defined for the shell do conflict with the keybinding for GNOME's lock screen shortcut.

**Comment by WatchMkr** [comment]
@mmstick the plan is to move lock screen to super + escape.

**Comment by flukejones** [comment]
I would love to see a horizontally scrolled tiling **option** like what [`PaperWM`](https://github.com/paperwm/PaperWM) has done. With the usability enhancements the System76 team are doing here this would be a game changer for many. There are many windows I would rather not tile or have on another workspace, but also would like to tile other windows next to - the way PaperWM does it means that this can be done, and it's also easy to switch between them all.

**Comment by Cicorione** [comment]
Hi there, I am a POP user as well as a S76 costumer and I would like to give my two cents... Tiling is a cool idea however Tiling WMs have an inner issue, those aren't designed to be smart, that's why you have to figure out how to handle all the different configurations.

But now let's try to watch the issue from another perspective rather than having a TWM we want a have **windows that do not overlap each others**, while try to fill all the space available. You see now we have smart windows that react to your action, and with few rules (or constraining) you can avoid all the weird combination.

I have not idea if it is feasible (Blender does not overlap panels for example) but surely is a modern approach to an old issue.

Thanks!

**Comment by badmannen** [comment]
for the "launcher" maybe the easiest would be to bake in "Rofi" ? looks the same so I assume that  is what is shown up there perhaps.

**Comment by SouthernWolf95** [comment]
Out of curiosity, would this be purely optional to use? Or will this become the new default for Pop!_OS? Just asking, as I tend to dislike windows mangers such as i3 and others, and I'd rather not be forced to use a window manager by default.

**Comment by WatchMkr** [comment]
Automatically tiling is off by default and can switched on by a toggle in settings or a drop down menu.

**Comment by anzanhoshin** [comment]
Wonderful. Pop!_OS is approaching closer and closer to my ideal desktop and workflow. My deep appreciation to all making this not only possible but actual.

**Comment by KevinStirling** [comment]
> Here is the updated Settings page design (no custom layout and keyboard shortcuts after the in-person conversation):
> ![DesktopWorkspaces](https://user-images.githubusercontent.com/57502897/71635975-21a32080-2be7-11ea-939a-99bea2d86bb2.png)

so are custom layouts and keyboard shortcuts in the options gone for good? or just in the initial implementation? both would be quite useful to me. looking great so far either way

**Comment by maria-komarova** [comment]
@KevinStirling thanks for your feedback! It's great to know you would find those features useful. We still have custom layouts and keyboard shortcuts on our roadmap. We have kept them in the design of the dropdown menu. 
![1](https://user-images.githubusercontent.com/57502897/74550696-07ab6c00-4f0f-11ea-91f1-8570fa68a57d.png)
We are also working on making shortcuts easier to learn so stay tuned.

**Comment by nkerschb** [comment]
> @KevinStirling thanks for your feedback! It's great to know you would find those features useful. We still have custom layouts and keyboard shortcuts on our roadmap. We have kept them in the design of the dropdown menu.
> ![1](https://user-images.githubusercontent.com/57502897/74550696-07ab6c00-4f0f-11ea-91f1-8570fa68a57d.png)
> We are also working on making shortcuts easier to learn so stay tuned.

I would also very much like to use custom layouts. I am currently using a 5120x1440 screen with a main work window in the center and two smaller windows on left/right side e.g.: |__|____|__|

I also wanted to ask if there any layout/window preserving options that are considered? Currently, when I undock my notebook from the ultra-wide and then later redock it I have to rearrange the windows again in the layout that I had them before manually. Would be nice to have a save/restore option that considers the windows, their size and workspaces.

**Comment by Zalastra** [comment]
As an ultra-wide monitor user, (21:9 3440x1440) I'd prefer a max of 3 vertical tiles before going horizontal. Dividing by 4 would result in windows 860 pixels width which to me is uncomfortably small for many use cases. A division of 4 seems more fitting for the actual dual size monitors like the above mentioned 5120x1440.

Perhaps the simplest way to handle this without having to be dpi aware is to define aspect ratio thresholds to go to 3 and 4 max vertical tiles. Lets says 3 vertical tiles for aspect ratio bigger than 2 and 4 vertical tiles for aspect ratios bigger than 3. But if it's possible to take dpi into account perhaps more can be done here?

List potentially relevant aspect ratios > 16:9 and monitor sizes & resolutions*:

aspect ratio | resolution | dpi | monitor size(s)
--- | --- | --- | ---
1.9 : 1 (1.9) | 4096x2160 | 149 | 31.1"
21 : 9 (2.33) | 2560x1080 | 111 | 25"
21 : 9 (2.33) | 2560x1080 | 96 | 29"
21 : 9 (2.33) | 2560x1080 | 82 | 34" (35")
21 : 9 (2.33) | 3440x1440 | 110 | 34" (35")
21 : 9 (2.33) | 5120x2160 | 163 | 34"
12 : 5 (2.4) | 3840x1600 | 111 | 37.5"
32 : 10 (3.2) | 3840x1200 | 93 | 43.4"
32 : 9 (3.55) | 3840x1080 | 81 | 49"
32 : 9 (3.55) | 5120x1440 | 109 | 49"

The first is one is a curious case but is probably similar enough to a regular large 4k monitor to treat it like that. These might want more than 2 tiles vertically but shouldn't based on aspect ratio. Vice versa the (smaller) 2560x100 might not want 3 tiles vertically even though they'd might get it based on aspect ratio.

How would monitors in portrait mode be dealt with? I personally don't use it but I figure enough people do that it should be kept into account.

_*list compiled based on available monitors on price comparison website [tweakers.net pricewatch](https://tweakers.net/categorie/344/monitoren/producten/)_

**Comment by WatchMkr** [comment]
We brought in a 25" 21:9 monitor (2560 x 1080) to test just this scenario. You might be right about having another option between display ratios - we'll take a look at it. We also have vertical monitor setups to cover that use case as well.

**Comment by nkerschb** [comment]
@maria-komarova I just wanted to inquiry if custom layouts are still planned for release with 20.04? (because in current beta version I don't see the option). Thank you!

**Comment by maria-komarova** [comment]
@nkerschb Sadly, I don't think we will be able to include it in this release but it is still on our roadmap. We wanted to make sure the essential things work well before focusing on this feature. I am still looking forward to making it a reality so I am excited to learn there is still an interest in this feature.

**Comment by anzanhoshin** [comment]
I am very interested in this feature.

Anzan Hoshin roshi

**Comment by BobbyByrne** [comment]
I"m also looking forward to custom layouts. It would help with the default behaviour on vertical monitors.

I also wonder if there's an option on the road map for a max number of windows preference? So auto-tile but once there's say 3 windows open on 1 monitor open the window on the second if available, and if no space is available, overlap the first position. Could even do a cascade on the two windows that are now sharing the same tile space. See image below for cascading example when max number of windows is reached.

![Screenshot from 2020-05-14 14-44-54](https://user-images.githubusercontent.com/7388850/81973037-8b99f080-95f1-11ea-926d-375be8f163f7.png)

If this should be setup as a separate FR let me know.

**Comment by mmstick** [comment]
@BobbyByrne Instead of cascading, we're going to do stacking

**Comment by BobbyByrne** [comment]
@mmstick, sounds good. Would stacking just be one window covering the window below?

**Comment by shaun-ba** [comment]
Hi,

I have a 5120x1400 and would like to test some of these changes and help debug any issues, do i just run dev_focal?

Thanks

**Comment by Keltirion** [comment]
I also use 5120x1440 if you need someone to test just let me know. This feature would be a blessing :)

**Comment by mmstick** [comment]
@Keltirion Which feature? We probably need to close this issue since all of these things have been implemented, besides memorizing layouts.

**Comment by morey-tech** [comment]
@mmstick has the custom layouts feature been added yet or is that what you are referring to with "memorizing layouts"?

**Comment by Keltirion** [comment]
@mmstick I'm talking about 2-4 column layout with even space for ultrawide. On which branch are those implemented. I'm on master_focal and i dont have those.

**Comment by mmstick** [comment]
There's no predefined layouts. You just make them however you wish by changing orientations of a node with `Super + O`

**Comment by Pietryszak** [comment]
How possible it is that is not implemented yet. It's ridiculous. Super + O doesn't remember a layout. When on the vertical view we have 2 windows and another one shown everything is ok. But when we close these third window a whole layout is a mess. It's come back to horizontal view

**Comment by mpareja** [comment]
Has the Ultrawide (4-vertical splits) mode been implemented? I have a 3440 x 1440 display but tiling appears to be acting like a regular display.
