### ISSUE TITLE
Default gap sizes

### ISSUE THREAD

**Issue by leviport** [pop-os/shell#90]
These seem to change quite a bit, so I think we should talk about what the defaults should be. 

Currently it looks like the default is 16, which I think is probably too big. I think 4 for inner and outer is good, although my personal preference would be 4 inner, 0 outer. 

@WatchMkr what do you think?

**Comment by mmstick** [comment]
I'll set it to 4. This needed updated since we switched from pixels to units.

**Comment by leviport** [comment]
Oh I didn't know about that switch. I wonder if 4 is too much then? It looks really good, I just worry about using too many pixels.

**Comment by WatchMkr** [comment]
Let's go with 8. 8 has felt best across the displays I've tested.

**Comment by leviport** [comment]
Just to clarify: is that 8 pixels or 8 units? 8 units looks huge to me, so I wanted to double-check. @mmstick is 1 unit == 4 px, or is it a fractionally calculated thing?

**Comment by mmstick** [comment]
1 unit = 4 pixels, multiplied by the scaling factor in GNOME

**Comment by WatchMkr** [comment]
I had a local copy running so I was still seeing pixels in the menu. Back to the latest! Okay, let's set the default value to 2.
