### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by PeSader** [pop-os/shell#901]
**(1) Issue/Bug Description:**
Cannot build pop shell locally, as multiple errors happen when running ```make local-install```
Logs provided [here](https://pastebin.com/3Bje7aAH).

**(2) Steps to reproduce (if you know):**
```
git clone https://github.com/pop-os/shell/
cd shell
make local-install
```

**(3) Expected behavior:**
Should be able to build locally.

**(4) Distribution (run `cat /etc/os-release`):**
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**(5) Gnome Shell version:**
```
$ apt policy gnome-shell:
  Installed: 3.36.4-1ubuntu1~20.04.2
  Candidate: 3.36.4-1ubuntu1~20.04.2
  Version table:
 *** 3.36.4-1ubuntu1~20.04.2 500
        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
        500 http://br.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.36.1-5ubuntu1 500
        500 http://br.archive.ubuntu.com/ubuntu focal/main amd64 Packages
```

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
commit aecd7ec30a6c55d5752008e84fb7c16f42e24066 (HEAD -> master, origin/master, origin/HEAD)
Author: Michael Aaron Murphy <mmstick@pm.me>
Date:   Mon Mar 8 09:07:42 2021 -0700

    fix: Reassignment of last-stacked window resorting in ghost window
```

**(7) Where was Pop Shell installed from:**
Built locally

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1 x 2256p (Horizontal)

**(9) Other Installed/Enabled Extensions:**
 None since it started happening

**(10) Other Notes:**
Pop Shell is still amazing. Thanks for developing it!

**Comment by mmstick** [comment]
You have a node_modues directory in a parent directory. It's conflicting with definitions found there.
