### ISSUE TITLE
Error with "make local-install"

### ISSUE THREAD

**Issue by Hamenak** [pop-os/shell#907]
Hello!

I've tried to install the pop-shell on my machine.
I am using slackware-current (64bit, x86_64) and have installed nodejs and typescript. I also installed the GNOME DE itself (3.38.2). 
Now I try to install the pop-shell via "make local-install" in the shell folder and get the following error:

+ gnome-extensions list
Failed to connect to GNOME Shell
+ dconf write /org/gnome/mutter/workspaces-only-on-primary false
echo "Restart shell!"
Restart shell!
if bash -c 'xprop -root &> /dev/null'; then \
        busctl --user call org.gnome.Shell /org/gnome/Shell org.gnome.Shell Eval s 'Meta.restart("Restarting Gnome...")'; \
else \
        gnome-session-quit --logout; \
fi
Failed to set address: No such file or directory
make: *** [Makefile:98: restart-shell] Error 1

I already took a look at the following issue: https://github.com/pop-os/shell/issues/742 and followed the instructions, same problem.
Is this because I use the 3.38 GNOME DE? I know that the readme stats 3.36.

Thanks in advance!

**Comment by mmstick** [comment]
Are you using sudo to install this?

**Comment by Hamenak** [comment]
I'm running it as the root user.

**Comment by mmstick** [comment]
Can't do that with shell extensions. Install without root
