### ISSUE TITLE
Feature request: should Tab switch to outer gap box?

### ISSUE THREAD

**Issue by leviport** [pop-os/shell#91]
If I want to change the gap size values, I can click on inner gap and change it, but pressing <kbd>Tab</kbd> does not switch my cursor to the outer gap input box. It would be much faster to set both if I could <kbd>Tab</kbd> to the next box, and conversely, <kbd>Shift</kbd> + <kbd>Tab</kbd> back from outer value to inner value.

**Comment by WatchMkr** [comment]
There will be one only one gaps box in the menu that sets both values in the backend.

The outer gap box is being removed from the menu and added to the shell extensions preferences as "“Disable Outer Window Gaps”. Turning this on sets the outer gap to 0 and the front-end drop down can’t change the setting.

**Comment by mmstick** [comment]
As soon as Ubuntu updates GNOME Shell to 3.36, I'll be able to add the prefs dialog. It's currently broken in 3.35.91
