### ISSUE TITLE
Super + L to lock screen not working with Pop Shell enabled

### ISSUE THREAD

**Issue by Razer0123** [pop-os/shell#913]
**(1) Issue/Bug Description:**

I used to lock my PC using Super + L, i'veread Pop Shel remapped it as Super + Esc but i get some tab explorer using that

**(2) Steps to reproduce (if you know):**

Just enable the extension

**(3) Expected behavior:**

Screen locking when combination pressed

**(4) Distribution (run `cat /etc/os-release`):**
 
Archlinux

**(5) Gnome Shell version:**

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**(7) Where was Pop Shell installed from:**

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

**Comment by octos4murai** [comment]
Do you have your Settings > Keyboard > Keyboard Shortcuts > Lock Screen set to `Super+L`?

**Comment by mtrcn** [comment]
I have the same problem with Ubuntu 20.10 + GNOME

**Comment by mmstick** [comment]
The correct shortcut is Super + Esc

**Comment by mtrcn** [comment]
This shortcut doesn't work with keyboards that have a Lock button.
