### ISSUE TITLE
chosen keybindings conflict with dconf default keybindings

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#92]
Some shortcuts that are set inside of keyboard shortcuts are not reset inside of dconf. The only one I found is  `Super m`, but there may be more. `Super m` is "toggle-message-tray" in `/org/gnome/shell/keybindings/`. As a result, whenever I press `Super m`, sometimes it will toggle the message tray, and other times it will maximize the window.

Ways to fix it might be to either choose a shortcut which does not conflict with dconf editor shortcuts, or to override dconf editor shortcut as well.

**Comment by scaryrawr** [comment]
Sorry, didn't realize I was making noise on the issue. Unpublished my personal branch.

**Comment by nicolae-stroncea** [comment]
PR was merged to dev_focal

**Comment by raghuramos1987** [comment]
looks like this is an issue with super + q also
