### ISSUE TITLE
Unable to resize or move window with mouse on Arch Gnome40.

### ISSUE THREAD

**Issue by laichiaheng** [pop-os/shell#932]
**(1) Issue/Bug Description:**
I can't resize or move the window by dragging it with my mouse.

**(2) Steps to reproduce (if you know):**
Try to resize or move the window with my mouse.

**(3) Expected behavior:**
It resizes or moves the window.

**(4) Distribution (run `cat /etc/os-release`):**
```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

**(5) Gnome Shell version:**
40.0.0

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
Name            : gnome-shell-extension-pop-shell-git
Version         : r677.163d207-1
Description     : Pop Shell - Tiling window management in Gnome (WIP)
Architecture    : any
URL             : https://github.com/pop-os/shell
Licenses        : GPLv3
Groups          : None
Provides        : None
Depends On      : gnome-shell  pop-shell-shortcuts-git
Optional Deps   : gnome-shell-extensions: native-window extension for improved window
                  placement [installed]
Required By     : None
Optional For    : None
Conflicts With  : gnome-shell-extension-pop-shell
Replaces        : None
Installed Size  : 1049.04 KiB
Packager        : Unknown Packager
Build Date      : Fri Apr 9 16:46:46 2021
Install Date    : Fri Apr 9 16:46:53 2021
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : None
```

**(7) Where was Pop Shell installed from:**
AUR

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1 x 1080p

**(9) Other Installed/Enabled Extensions:**
cpufreq, freon, gamemode, gsconnect, sound-output-device-chooser, appindicator

**(10) Other Notes:**

**Comment by laichiaheng** [comment]
Can anyone help?

**Comment by VeryLongNicknameSuchWow** [comment]
Having the same issue on Arch Linux on Gnome 40 with both Wayland and Xorg.

**Comment by laichiaheng** [comment]
> Having the same issue on Arch Linux on Gnome 40 with both Wayland and Xorg.

Wayland is even worse, the extension can not work correctly.

**Comment by jlaunay** [comment]
Same issue too on Arch Linux Gnome 40.0-1, gnome-shell-extension-pop-shell-git r677.163d207-1

**Comment by Arjdroid** [comment]
Same here; (Arch Linux GNOME 40 NVIDIA Proprietary with X org) disabling auto-tiling allows me to resize windows and it work like before but I really miss the auto-tiling feature. I suspect this is just general incompatibility due to changes in the GNOME Shell / Mutter API. Other features like the launcher still work but there are some updates needed to ensure proper compatibility like adding GTK4 support to the Pop GTK theme.

**Comment by laichiaheng** [comment]
> Same here; ( Arch Linux GNOME 40 with AUR pop-shell-shortcuts-git 1:r27.a653635-1 on NVIDIA Proprietary with X org ) disabling auto-tiling allows me to resize windows and it work like before but I really miss the auto-tiling feature. I suspect this is just general incompatibility due to changes in the GNOME Shell / Mutter API. Other features like the launcher still work but there are some updates needed to ensure proper compatibility like adding GTK4 support to the Pop GTK theme.

Isn't disabling auto-tiling equals to disabling this extension?

**Comment by Arjdroid** [comment]
> > Same here; ( Arch Linux GNOME 40 with AUR pop-shell-shortcuts-git 1:r27.a653635-1 on NVIDIA Proprietary with X org ) disabling auto-tiling allows me to resize windows and it work like before but I really miss the auto-tiling feature. I suspect this is just general incompatibility due to changes in the GNOME Shell / Mutter API. Other features like the launcher still work but there are some updates needed to ensure proper compatibility like adding GTK4 support to the Pop GTK theme.
> 
> Isn't disabling auto-tiling equal to disable this extension? Auto-tiling is what this extension for.

Well, auto tiling might be the _main_ and definitely favourite feature but the launcher is pretty good too as well as some other features.

**Comment by Arjdroid** [comment]
BTW, If you have a look at the keyboard shortcuts for the Pop!_Shell, you can still resize and move windows using Adjustment Mode like a proper Tiling WM although I gotta say even this mode is a little buggy with the "Swap Windows" shortcut and they do not work as expected... I would say that this is an acceptable workaround for now...

**Comment by farmerbobathan** [comment]
Resizing with mouse works for me on Arch Gnome40 on wayland with and without auto-tiling enabled but I am experiencing issue #912.

**Comment by laichiaheng** [comment]
> Resizing with mouse works for me on Arch Gnome40 on wayland with and without auto-tiling enabled but I am experiencing issue #912.

It can't even auto-tiling on my Arch Gnome40 Wayland properly.

**Comment by nikolowry** [comment]
Not to derail this issue, but from lurking the issues the past week I've noticed a lack of responses to the numerous GNOME 40 issues.

Is pop-shell abandoned after the announcement of Cosmic: https://blog.system76.com/post/648371526931038208/cosmic-to-arrive-in-june-release-of-popos-2104? Can any maintainer clarify whether these issues are being worked on and the future of this extension?

**Comment by laichiaheng** [comment]
@nikolowry I can't live without this auto-tiling extension now, especially on Gnome.

**Comment by Arjdroid** [comment]
> @nikolowry I can't live without this auto-tiling extension now, especially on Gnome.

I mentioned a workaround we can use for the time being... 

Pop Shell extension is probably abandoned and the Cosmic Extension will probably replace it and be open source so yeah...

I'm pretty sure Cosmic is a shell extension because that's what's there in the source code repo as of now

**Comment by laichiaheng** [comment]
@Arjdroid Do they replace the whole Gnome interface in this extension? Such as the Activities Overview, I like how Gnome40 does now.

**Comment by Arjdroid** [comment]
> @Arjdroid Do they replace the whole Gnome interface in this extension like the Activities Overview? Or they are just shortcuts? I like how Gnome40 does now.

So far what they've shown from the preview it seems that they're making pretty major changes and shifts away from the original GNOME 40 stuff which imo is fine by me although others may dislike it...

**Comment by laichiaheng** [comment]
> > @Arjdroid Do they replace the whole Gnome interface in this extension like the Activities Overview? Or they are just shortcuts? I like how Gnome40 does now.
> 
> So far what they've shown from the preview it seems that they're making pretty major changes and shifts away from the original GNOME 40 stuff which imo is fine by me although others may dislike it...

If they are optional, that will be fine.

**Comment by nikolowry** [comment]
I'm just confused because of how Cosmic was framed in [Phoronix](https://www.phoronix.com/scan.php?page=news_item&px=System76-COSMIC-Desktop) and that blog -- they both clearly state Cosmic is a "Desktop Environment", but the repo just looks like it's another extension?

They even check if pop-shell is installed, https://github.com/pop-os/cosmic/blob/master_hirsute/extension.js#L33 -- so maybe they just integrate together? Any clarity from maintainers would be greatly appreciated.

---

> @nikolowry I can't live without this auto-tiling extension now, especially on Gnome.

@laichiaheng agree, my favorite thing about this extension is how it makes it easy for me to go from "work" mode to "home" mode. 

> I mentioned a workaround we can use for the time being...

@Arjdroid I resize in tiling mode with the keyboard, so this particular issue doesn't effect me too much. I'm more inconvenienced by the fact that I had to switch to GNOME's Xorg fallback DE (Can't get WebRTC and pipewire audio to work on Xorg sessions in Chromium or Firefox, which means I have switch to Wayland for work-related Zoom meetings) 

---

Regardless, I really do appreciate the System76 team's development efforts.

**Comment by mmstick** [comment]
COSMIC is a GNOME Shell extension. We've always had our own desktop environment in the form of a custom GNOME Shell session (Pop). Pop Shell brings tiling, and COSMIC brings UX improvements. GNOME Control Center is also patched to expose all the desktop configuration options.

**Comment by nikolowry** [comment]
@mmstick thank you for clarifying that. 

As someone that doesn't use System76 hardware or PopOS, it would have been helpful to have included the technical context about COSMIC being a GNOME Shell extension that compliments/integrates with Pop Shell (apologizes if I overlooked that somewhere in the blog post and/or Phoronix article).

Historically, language like "Desktop Environment" conveys a very specific meaning (see: https://wiki.archlinux.org/index.php/Desktop_environment). It be great if the marketing/PR team could account for that in future press releases.

I won't derail this issue anymore, sorry again for the unrelated aside.

**Comment by GustavoPeredo** [comment]
The auto-resizing isn't working here on wayland either
OS: Fedora 34 (GNOME 40)
Version: master (16/04/2021)
Installed: from git

PS: Pop shell always rocks!

**Comment by laichiaheng** [comment]
> COSMIC is a GNOME Shell extension. We've always had our own desktop environment in the form of a custom GNOME Shell session (Pop). Pop Shell brings tiling, and COSMIC brings UX improvements. GNOME Control Center is also patched to expose all the desktop configuration options.

Can some of the features be switched off in this extension just acting like the old pop shell extension?

**Comment by MichaelAquilina** [comment]
@mmstick I am tempted to give a go at trying to debug this issue and open a fix - but I was wondering if you could give any indications of the best place to start looking (in terms of code)?

**Comment by bferrarese** [comment]
I'm sorry y'all but I got lost. What's the fix again to be able to resize windows in (GNOME 40 / Wayland / ArchLinux)?

**Comment by Arjdroid** [comment]
> I'm sorry y'all but I got lost. What's the fix again to be able to resize windows in (GNOME 40 / Wayland / ArchLinux)? 

Use the keyboard shortcuts, it takes some getting used to but after a while you won't miss it; you might even want to customise some of the shortcuts to be more usable for you

**Comment by rengare** [comment]
I'll try to work on in since I'm running fedora (waiting for gnome 40 on pop and I'm going back ;))

**Comment by laurentlbm** [comment]
I fixed it for myself (Arch with GNOME 40.3) with this change: https://github.com/laurentlbm/pop-shell/commit/e334b8d346db4d454034e53d18bdafcab7aacb17

The callback for the signal seems to have changed in [GNOME's Meta API version 8](https://gjs-docs.gnome.org/meta8~8_api/meta.display#signal-grab-op-end). I've never programmed with GNOME APIs before, so I don't have any explanation more than this.

**Comment by yochananmarqos** [comment]
@laurentlbm That works, thanks! Why not create a PR?

**Comment by laurentlbm** [comment]
> @laurentlbm That works, thanks! Why not create a PR?

It would probably break compatibility on older versions of GNOME. I would need to modify the code to type check the parameters and do the correct thing depending on the order they were passed in. 

I might look into it later, but I have limited time and would first need to set up a VM to test it in GNOME 3.38. If someone else does it in the meantime, I wouldn't mind.

**Comment by mmstick** [comment]
You could submit a PR that just connects a different closure based on the GNOME version. There's already some preexisting code that checks GNOME version strings.

**Comment by laurentlbm** [comment]
Good idea, I'll do that. It'll be cleaner than checking the arguments, especially if the codebase already does things this way.

**Comment by rengare** [comment]
@laurentlbm good job, I had no time to finish it but I'm glad you did this ;)
