### ISSUE TITLE
rebuild.sh fails

### ISSUE THREAD

**Issue by sethfl** [pop-os/shell#94]
Running both `sh rebuild.sh` and `sudo make` in the root directory both give the same output (on [pastebin](https://pastebin.com/c23ZEHPD) because it's very long), with the final error being the `transpile` function in the makefile.

I am running Fedora 31 with kernel `5.5.10-200.fc31.x86_64`, GNU Make `4.2.1`, and TypeScript `2.8.3`.

Thanks for any help!

**Comment by mmstick** [comment]
The version of TypeScript being used is too old.
