### ISSUE TITLE
VLC Exits full-screen when mouse is moved in tiling mode

### ISSUE THREAD

**Issue by manujchandra** [pop-os/shell#942]
**(1) Issue/Bug Description:**
VLC 3.0.12 exits full screen in tiling mode when mouse is moved. When tiling is turned off, then vlc does not exist full screen on mouse movement.

**(2) Steps to reproduce (if you know):**
1) Turn tiling on
2) Open a video in vlc
3) Press f to go fullscreen
4) Move mouse. The video will move to one half of the screen while playback controls show as if video is full-screen
5) Turn tiling off
6) Full screen the video
7) Now move the mouse and it will stay in full screen (expected behaviour)

**(3) Expected behavior:**
When mouse is moved when video is full screen in tile mode in vlc, the playback controls should appear while the video remains full screen. It should not move to one half of the screen.

**(4) Distribution (run `cat /etc/os-release`):**
```
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**
3.36.8

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```pop-shell:
  Installed: 1.1.0~1617950178~20.04~163d207
  Candidate: 1.1.0~1617950178~20.04~163d207
  Version table:
 *** 1.1.0~1617950178~20.04~163d207 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**
It came with pop os

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
Single 1080p laptop screen

**(9) Other Installed/Enabled Extensions:**
Draw on my screen for gnome

**(10) Other Notes:**
The tiling with VLC was working fine. Last couple of days it broke either due to some update I believe or a crash. Also, the problem started appearing after popos froze and had to be hard rebooted 3 times. These 3 crashes happened when vagrant virtualbox was running while vlc was playing a video and handbrake was encoding videos. I have used this configuration before and it was working fine.

**Comment by yasserkaddour** [comment]
Commit https://github.com/pop-os/shell/pull/910/commits/113863d6f8f56ae69e701ed6a512638c216ced60  is responsible for this, moving the mouse in VLC displays the full-screen controller windows that trigger `unmake_fullscreen().
