### ISSUE TITLE
Audacity crash recovery dialogue is missing with Auto-Tiling on

### ISSUE THREAD

**Issue by KillYourFM** [pop-os/shell#944]
**(1) Issue/Bug Description:**
Audacity 2.4.2 crashed, and upon relaunching the Recovery dialogue appears. However, the buttons normally visible that enable you to take action are simply not there, preventing any forward progress. Disabling auto-tiling solves the issue (examples attached).

**(2) Steps to reproduce (if you know):**
-Audacity crashes (for example when the system locks up or there's a power outage)
-Relaunch audacity with Pop OS auto-tiling enabled. 

**(3) Expected behavior:**
Audacity's Crash Recovery window will show you the projects that were not properly saved. You can then select one/all, and choose "Quit / Discard / Recover." (These buttons are missing with auto tiling enabled)

**(4) Distribution (run `cat /etc/os-release`):**
Pop OS 20.10
 

**(5) Gnome Shell version:**
3.38.3

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```1.1.0~1617950178~20.10~163d207```

**(7) Where was Pop Shell installed from:**
Fresh installation via Pop OS 20.10 installer.

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1 4K monitor (primary), 1 1080p monitor (secondary)

**(9) Other Installed/Enabled Extensions:**
Gnome Tweaks

**(10) Other Notes:**
Dracula Theme is installed and enabled.

![audacity with tiling](https://user-images.githubusercontent.com/47599547/115262367-c3c87e00-a134-11eb-9692-fb9f32bdbd49.jpg)
![audacity without tiling](https://user-images.githubusercontent.com/47599547/115262375-c5924180-a134-11eb-9e4b-f1bc52024857.jpg)

**Comment by bflanagin** [comment]
@KillYourFM: I'm not sure how often Audacity crashes on you, or if you can manually bring up this dialog, but the next time you see it could you add a Floating Window Exception for that dialog? 

Tiling indicator --> Floating Window Exception: Then select the dialog using the "select" option. 

Let us know if the buttons come back automatically or at the next time you have to auto recover. (Hopefully, its not that common)

**Comment by jacobgkau** [comment]
I can recreate the crash dialog by killing Audacity (e.g. `xkill`) while recording. However, I'm seeing the dialog float (dialogs don't tile by default) on 21.04 beta with the Audacity deb installed:

![Screenshot from 2021-04-22 09-32-03](https://user-images.githubusercontent.com/7199422/115742332-cf42c180-a34d-11eb-900a-736951aa77b3.png)

I'll try on 20.10 with the Dracula theme, and will also try the Flatpak version.

**Comment by jacobgkau** [comment]
Not able to recreate this with the deb or flatpak versions of Audacity on 20.10 with the Dracula theme enabled.

![Screenshot from 2021-04-22 09-51-47](https://user-images.githubusercontent.com/7199422/115746208-60fffe00-a351-11eb-8767-f84add9c5176.png)

![Screenshot from 2021-04-22 09-58-09](https://user-images.githubusercontent.com/7199422/115746216-61989480-a351-11eb-8c3b-d673518d7d16.png)

Also tried on a 4k internal display w/ 1080p external to match the reported setup, still not seeing it:

![Screenshot from 2021-04-22 10-34-45](https://user-images.githubusercontent.com/7199422/115751442-6d3a8a00-a356-11eb-88b0-c687edddcbd5.png)

**Comment by KillYourFM** [comment]
> @KillYourFM: I'm not sure how often Audacity crashes on you, or if you can manually bring up this dialog, but the next time you see it could you add a Floating Window Exception for that dialog?
> 
> Tiling indicator --> Floating Window Exception: Then select the dialog using the "select" option.
> 
> Let us know if the buttons come back automatically or at the next time you have to auto recover. (Hopefully, its not that common)

It's not that common, bug brilliant solution, thank you!

**Comment by KillYourFM** [comment]
> Not able to recreate this with the deb or flatpak versions of Audacity on 20.10 with the Dracula theme enabled.

I appreciate the effort guys, thank you.
