### ISSUE TITLE
Cycle display modes shortcut (super + p) cannot be reassigned and overwrites customs shortcuts

### ISSUE THREAD

**Issue by daenny** [pop-os/shell#947]
**(1) Issue/Bug Description:**
Cycle display modes shortcut cannot be re-assigned to another function. When external display is connected it defaults back to "cycle display modes"   
I put the "launcher" on super+P, which works fine, when only working on a singe display. As soon as an external display is connected, it defaults back to "cycle display".

**(2) Steps to reproduce (if you know):**
Assign some shortcut to `super+P` in settings. with single display setup this works. Connect external display -> super+P cycles display again.

**(3) Expected behavior:**
Custom `super+P` shortcut should not be overwritten, it should be possible to re-assign "cycle display modes" to another key. 

**(4) Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**
`GNOME Shell 3.36.7`

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1617950178~20.04~163d207
```

**(7) Where was Pop Shell installed from:**
pop_OS 20.04 LTS nvidia ISO

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
one 4K laptop screen (primary), 4K monitor external screen

**(9) Other Installed/Enabled Extensions:**
n/a

**(10) Other Notes:**

**Comment by mmstick** [comment]
We don't bind this key in Pop Shell. So something else is doing that
