### ISSUE TITLE
Adjustment mode shows wrong tile being moved

### ISSUE THREAD

**Issue by dawaltconley** [pop-os/shell#950]
**(1) Issue/Bug Description:**
When moving tiles in adjustment mode (`Super + Enter`), if I select a different tile than the one I originally had focused (using `Ctrl + Arrows`) and then move that tile (`Arrows`) the display incorrectly rearranges as if I had performed that movement on the _originally_ selected tile. However, once I confirm the operation and leave adjustment mode (`Enter`), the tiles update and show that they have moved correctly, i.e., according to my keystrokes.

**(2) Steps to reproduce (if you know):**
Using the steps above. It's easiest to see with at least three tiles in a workspace. I reproduced this running a bootable drive using a fresh download of Pop!_OS 20.10 with nothing else installed.

**(3) Expected behavior:**
Adjustment mode should only move the selected tile and show the correct arrangement of tiles before exiting.

**(4) Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**
`GNOME Shell 3.38.3`

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1617950178~20.10~163d207
  Candidate: 1.1.0~1617950178~20.10~163d207
  Version table:
 *** 1.1.0~1617950178~20.10~163d207 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**
Came with system (I also tried `sudo apt install --reinstall pop-shell`).

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1440p single 27" monitor.

**(9) Other Installed/Enabled Extensions:**
```
freon@UshakovVasilii_Github.yahoo.com
clipboard-indicator@tudmotu.com
extensions@abteil.org
caffeine@patapon.info
openweather-extension@jenslody.de
dash-to-dock@micxgx.gmail.com
alt-tab-raise-first-window@system76.com
always-show-workspaces@system76.com
ding@rastersoft.com
pop-shell@system76.com
pop-shop-details@system76.com
system76-power@system76.com
ubuntu-appindicators@ubuntu.com
```

**Comment by jacobgkau** [comment]
> When moving tiles in adjustment mode (`Super + Enter`), if I select a different tile than the one I originally had focused (using `Ctrl + Arrows`) and then move that tile (`Arrows`) the display incorrectly rearranges as if I had performed that movement on the _originally_ selected tile.

To clarify what's happening here, `Ctrl + Arrows` isn't meant to select a different window, that shortcut is for swapping two windows. It looks to me like if I use `Ctrl + Arrows` to start swapping two windows, then use the arrow keys before I confirm that swap, the preview shows moving the originally selected window, but the swap is still queued and is applied (after the move) on confirmation.

I would probably just expect the swap to not be queued like that, but if it's going to be queued, then the preview should reflect that somehow. (Not sure how that would be shown without actually applying the swap.)

**Comment by dawaltconley** [comment]
Wow thank you I did not understand that at all lol. So what I've actually been telling it is "swap these windows, then move the focused window over here," but since they swap on enter the focused window becomes the swapped window after the move (ultimately doing the thing I wanted). I feel like showing the swap, with the option to `Esc` and not apply would make more sense, but maybe that involves basically prematurely applying the swap.

Confusing, but I'm gonna close since I don't have a good suggestion for that atm.
