### ISSUE TITLE
Bluetooth switch buggy

### ISSUE THREAD

**Issue by luisfelipesdn12** [pop-os/shell#953]
**(1) Issue/Bug Description:**
When I turn on Bluetooth, it displays "On", but doesn't actually is activated.

Demonstration:
https://user-images.githubusercontent.com/60361387/116094068-9a03df80-a67d-11eb-93b7-6c47b3f95ddc.mp4

To make it work properly, I have to:
1. "Turn on" Bluetooth
2. Run `service Bluetooth restart`

**(2) Steps to reproduce (if you know):**
Try to turn Bluetooth on.

**(3) Expected behavior:**
To be able to see available devices.

**(4) Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
**(5) Gnome Shell version:**
3.36.8

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```
pop-shell:
  Instalado: 1.1.0~1619032486~20.04~969e2c5
  Candidato: 1.1.0~1619032486~20.04~969e2c5
  Tabela de versão:
 *** 1.1.0~1619032486~20.04~969e2c5 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```
**(7) Where was Pop Shell installed from:**
Directly from https://pop.system76.com/

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1x 1366-768 (16:9)

**(9) Other Installed/Enabled Extensions:**
- [Activities Configurator](https://extensions.gnome.org/extension/358/activities-configurator/)
- [Audio Switcher](https://extensions.gnome.org/extension/1092/audio-switcher/)

**(10) Other Notes:**
I'm using a Lenovo IdeaPad S145, and the Bluetooth worked pretty fine initially.

**Comment by jacobgkau** [comment]
This repository is for the window tiling GNOME extension, Pop Shell. For general issues with Pop!_OS (when you're not sure which repository an issue belongs in), the correct repository to use is the general Pop repository: https://github.com/pop-os/pop 

Please take a look through the current [Bluetooth-related issues for Lenovo devices](https://github.com/pop-os/pop/issues?q=is%3Aissue+is%3Aopen+bluetooth+lenovo), and feel free to open a new issue if you don't see one that covers what you're experiencing. Please keep in mind that we're only able to guarantee compatibility with System76 hardware, as drivers for non-System76 products come from upstream Ubuntu and the Linux kernel, and we don't have Lenovo hardware to develop against or test with.

**Comment by luisfelipesdn12** [comment]
> This repository is for the window tiling GNOME extension, Pop Shell. For general issues with Pop!_OS (when you're not sure which repository an issue belongs in), the correct repository to use is the general Pop repository: https://github.com/pop-os/pop
> 
> Please take a look through the current [Bluetooth-related issues for Lenovo devices](https://github.com/pop-os/pop/issues?q=is%3Aissue+is%3Aopen+bluetooth+lenovo), and feel free to open a new issue if you don't see one that covers what you're experiencing. Please keep in mind that we're only able to guarantee compatibility with System76 hardware, as drivers for non-System76 products come from upstream Ubuntu and the Linux kernel, and we don't have Lenovo hardware to develop against or test with.

Thank you for the super-useful answer!
