### ISSUE TITLE
Tiling Window don't really maximize a unique window

### ISSUE THREAD

**Issue by rtheodoro** [pop-os/shell#959]
**(1) Issue/Bug Description:**

I have been using Tiling Window and when I open only one window, it is not actually maximized. The size fill my workspace, but I can press super+m and then it is really maximized.

This also happens when I have two windows open and then I close one.

**(2) Steps to reproduce (if you know):**

Open two windows and then close one. For example: Mozilla browser

Not maximized:
![Captura de tela de 2021-04-30 18-49-33](https://user-images.githubusercontent.com/36709613/116757706-fac84a80-a9e4-11eb-86f3-a8c45c347a62.png)

Maximized:
![Captura de tela de 2021-04-30 18-49-44](https://user-images.githubusercontent.com/36709613/116757719-0451b280-a9e5-11eb-897d-60474167ed37.png)

**(3) Expected behavior:**
The window be maximized

**(4) Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**
3.38.3

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
pop-shell:
  Instalado: 1.1.0~1619554528~20.10~42e8ac0
  Candidato: 1.1.0~1619554528~20.10~42e8ac0
  Tabela de versão:
 *** 1.1.0~1619554528~20.10~42e8ac0 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status

**(7) Where was Pop Shell installed from:**

system76 website

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1366x768 (16:9) and 1440x900 (16:10)

**(9) Other Installed/Enabled Extensions:**

no

**(10) Other Notes:**
no

**Comment by bflanagin** [comment]
This is intended. If you set gaps to a higher number you'll see more visual difference between the two.
