### ISSUE TITLE
screenshot application inconsistency

### ISSUE THREAD

**Issue by kvaneesh** [pop-os/shell#96]
Will shell be able to identify applications like these? They should by default be in the float mode? With auto tiling and trying to select save folders, the folder selection window is not visible.

**Comment by mmstick** [comment]
GNOME Screenshot already defaults to floating. Any window which is a dialog also defaults to floating. Only windows with a `Normal` window type are considered for tiling.

**Comment by kvaneesh** [comment]
With commit 0c480fb8c0f0c39a5842cff89f38d807600c2a14 I am not finding screen shot application starting in floating mode and also the folder selection is not visible.

**Comment by kvaneesh** [comment]
Attaching the images that show the layout and what happens when I
![IMG_20200323_122403](https://user-images.githubusercontent.com/19270/77290188-a5117100-6d01-11ea-9deb-79b8bece0efb.jpg)
![IMG_20200323_122419](https://user-images.githubusercontent.com/19270/77290195-a93d8e80-6d01-11ea-8a17-a0d743df267e.jpg)

 select the folder
