### ISSUE TITLE
Pop-Shell freezes Gnome-Shell when using GJS 1.68.1

### ISSUE THREAD

**Issue by philmmanjaro** [pop-os/shell#969]
**(1) Issue/Bug Description:**

As soon as you start the [Manjaro 21.0.5 Review ISO](https://github.com/manjaro/release-review/releases/tag/202105140823) either in VirtualBox or baremetal Gnome-Shell will totally freeze when **Pop-Shell** is activated. We narrowed it down to **[GJS 1.68.1](https://gitlab.gnome.org/GNOME/gjs/-/tags/1.68.1)** to be the issue. Having the older version **1.68.0** running, it seems to be fine.

**(2) Steps to reproduce (if you know):**

- Start the image as normal and boot into Gnome Shell
- It will freeze in under one minute, in Wayland session you can't even switch to another TTY

---

- Start the image but edit grub entry to boot into run level 3
- login as `manjaro:manjaro`
- install `downgrade` via: `sudo pacman -Sy downgrade`
- downgrade **gjs** to 1.68.0 via: `sudo downgrade gjs`
- either start gnome-shell with `startx` or `dbus-run-session -- gnome-shell --display-server --wayland`
- **Pop-Shell** won't freeze the shell

**(3) Expected behavior:**

**Pop-Shell** should not freeze with newer **gjs**

**(4) Distribution (run `cat /etc/os-release`):**
 
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux

**(5) Gnome Shell version:**

1:3.38.4+13+gcf9d73ed5-1

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**(7) Where was Pop Shell installed from:**

Official Manjaro Repositories: 1.2.0-1

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

One Monitor in VirtualBox

**(9) Other Installed/Enabled Extensions:**

Seems has nothing to do with other extensions .

**(10) Other Notes:**

We may need to debug this by rebuilding **gjs** and **js78** with [debug symbols](https://wiki.archlinux.org/title/GNOME/Troubleshooting#Shell_freezes) ...

**Comment by mmstick** [comment]
Sounds like a regression in GJS 1.68.1 then. If you can find a workaround that would be great. Ubuntu 21.04 ships 1.67.2 so that's what we're supporting right now.

**Comment by philmmanjaro** [comment]
Might do a git-bisect on gjs to see which commit might causing that issue ...

**Comment by philmmanjaro** [comment]
Here is the result of my **git-bisect** of **gjs**:

```
[phil@development gjs]$ git bisect start
[phil@development gjs]$ git bisect bad 1.68.1
[phil@development gjs]$ git bisect good 1.68.0
binäre Suche: danach noch 28 Commits zum Testen übrig (ungefähr 5 Schritte)
[a34823b9250877322c4d927515d155b3d5f081b5] object: Switch back to normal references on disposal
[phil@development gjs]$ git bisect good
binäre Suche: danach noch 14 Commits zum Testen übrig (ungefähr 4 Schritte)
[ca54e46d9ccad62c381ce9afed6647726c36e6ea] gjs-test-tools: Ensure we use thread safe access to the saved object
[phil@development gjs]$ git bisect good
binäre Suche: danach noch 7 Commits zum Testen übrig (ungefähr 3 Schritte)
[ccacc18f19b3992bf6859cd135e3bd1c5ac4956f] context: Ensure we check atomically if we're destroying from other threads
[phil@development gjs]$ git bisect bad
binäre Suche: danach noch 3 Commits zum Testen übrig (ungefähr 2 Schritte)
[fa53702e478c2609bfbc8261f60b6be60c70cb66] toggle: Rely on wrapper to cancel finalized objects in queue
[phil@development gjs]$ git bisect good
binäre Suche: danach noch 1 Commit zum Testen übrig (ungefähr 1 Schritt)
[696d1e18321a1118068bb13b842c7a4a08b49eea] toggle: Enforce thread-safety using a per-thread spin-lock
[phil@development gjs]$ git bisect bad
binäre Suche: danach noch 0 Commits zum Testen übrig (ungefähr 0 Schritte)
[9ee7d7fa1f6277dd321f63cdbb881087e597a3ce] toggle: Keep track of objects via ObjectInstance not GObject's
[phil@development gjs]$ git bisect good
696d1e18321a1118068bb13b842c7a4a08b49eea is the first bad commit
commit 696d1e18321a1118068bb13b842c7a4a08b49eea
Author: Marco Trevisan (Treviño) <mail@3v1n0.net>
Date:   Thu Apr 29 04:04:19 2021 +0200

    toggle: Enforce thread-safety using a per-thread spin-lock
    
    While the ToggleQueue is expected to be thread-safe, unfortunately the
    way we use isn't always true.
    In fact, while we always perform operations locking the shared data, we
    may act on it depending on results that may have been changed by another
    thread. For example, we check if an object is queued or we cancel a
    queued object and we assume that this is true for the rest of the
    execution, but this may have been already changed meanwhile, thus we
    error later.
    
    This happens repeatedly with applications doing many fast threaded
    operations (an example can be triggered via GFileMonitor when the fs is
    particularly active as bug #297 shows).
    
    To avoid this, we need to ensure that all the access to the queue are
    locked till we're not done with it, but at the same time we must not to
    stop the owner thread to access multiple time to the queue while it owns
    the lock (as it may happen on recursion of we want group various
    operations).
    
    To do this, control public access to the queue only via a structure that
    uses a spin-lock to block non-holder threads and that uses a refcounted
    system to handle the unlocking.
    
    So, any time we get the queue, we have a locked control of it, once the
    ToggleQueue::Locked structure is released, we unlock it only if no other
    instances in the current thread are using it.
    
    This serves us particularly well in the toggle notification callback
    where we had cases in which we were adding duplicate objects to the queue
    even if they were already there or vice versa we were not adding them
    because we the situation changed since the call to is_queued().
    Now instead, we can be sure that each thread will work on the current
    queue state and behave accordingly.
    
    Related-to: #297
    
    (cherry-picked from commit 02df4431)

 gi/object.cpp | 42 ++++++++++++++++++++++++------------------
 gi/toggle.cpp | 52 ++++++++++++++++++++++++++++++++++++----------------
 gi/toggle.h   | 32 +++++++++++++++++++++++++++-----
 3 files changed, 87 insertions(+), 39 deletions(-)
```

Will now try to run it with an revert of this commit on 1.68.1. Files of the **git-bisect** can be found here: https://sourceforge.net/projects/manjarodev/files/users/philm/gjs/

**Comment by philmmanjaro** [comment]
Also to note: it only happens on first fresh boot without starting Gnome. After killing Gnome-Shell it all is fine. So this is rather an odd issue.

**Comment by ReillyBrogan** [comment]
I've seen a similar issue after switching to gnome-shell 40.1. The UI locks up as soon as gnome-shell starts if Pop Shell is enabled (using the latest from master). Strangely this didn't happen with gnome-shell 40.0 even though I was using GJS 1.68.1 in both cases.
