### ISSUE TITLE
[BUG] No window size and location preview and no window stacking when mouse drag - arch gnome 40.1.0

### ISSUE THREAD

**Issue by brunobmello25** [pop-os/shell#984]
**(1) Issue/Bug Description:**

Window size and location preview (that semi transparent rectangle with the configured accent color) does not show when dragging windows with mouse, and we cannot stack windows either.

**(2) Steps to reproduce (if you know):**

1. Running archlinux with Gnome 40.1.0, install these AUR packages:
- pop-shell-shortcuts-git
- pop-shell-extension-pop-shell-git
2. reboot the system and enable the extension
3. try dragging a window on top of another to enable stacking

**(3) Expected behavior:**

On Pop!_OS 20.04 with Gnome 3.38 I could drag windows with mouse and it would show a colored preview of how this window would be positioned and sized, and I could also stack windows on top of each other (this would create tabs on top of the window). Neither of these features work on archlinux with gnome 40.1.0

**(4) Distribution:**
Here is my "cat /etc/os-release" output:

```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```
 
**(5) Gnome Shell version:**
40.1.0

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
AUR r696.9507dc3-1

**(7) Where was Pop Shell installed from:**
this AUR repo https://aur.archlinux.org/packages/gnome-shell-extension-pop-shell-git/

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
4k display as primary (left monitor) and full HD display as secondary (right monitor)

**(9) Other Installed/Enabled Extensions:**
- Nothing to Say
- KStatusNotifierItem/AppIndicator Support
- Gnome 40 UI Improvements
- Desktop Icons NG (DING)
- Audio Switcher 40
- Always Show Workspace Thumbnails
- Applications Menu
- User Themes

**Comment by mmstick** [comment]
Extension is not compatible with GNOME 40 yet

**Comment by laichiaheng** [comment]
Will it ever be compatible with Gnome40?

**Comment by mmstick** [comment]
Until either the regressions in GNOME 40 are fixed, or someone contributes patches to fix what has changed in the GNOME APIs. If no one contributes such a patch, then I will have fixes by the time we release a Pop!_OS version with GNOME 40+.

**Comment by brunobmello25** [comment]
hey everyone. I opened this issue almost three years ago when gnome 40 was still fresh new. I don't even use gnome anymore (switched to awesomewm) and I believe pop shell fully supports gnome 40 nowadays (I might be wrong on this one?). Besides, soon we will have cosmic made in rust if I'm not mistaken?

I'll close this issue because it doesn't seem to be useful anymore, but feel free to open it back up if you guys disagree
