### ISSUE TITLE
Lost autotiling with recent commit

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/shell#99]
Currently on db6dc50. Auto tiling stopped working with the following error somewhere around 8d16ced. Windows end up in floating mode. Tested on two laptops.

pop-shell: [DEBUG] attempting to attach Alacritty to Terminal
pop-shell: [DEBUG] attaching Window(2,1) onto Window(1,0)
pop-shell: [DEBUG] attached Window(2,1) to Fork(0,0)
pop-shell: [DEBUG] xprop -id 0x2200004 WM_NORMAL_HINTS
pop-shell: [DEBUG] WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified size: 1600 by 1200

pop-shell: [DEBUG] Window(1,0) shall be moved to [Rect(16,70,1576,1714)]
pop-shell: [DEBUG] Window(2,1) shall be moved to [Rect(1608,70,1576,1714)]
pop-shell: [DEBUG] Moving Window(1,0) from [Rect(1600,54,1600,1746)] to [Rect(16,70,1576,1714)]
**JS ERROR: TypeError: window.meta.block_signal_handler is not a function**
move_window@/usr/share/gnome-shell/extensions/pop-shell@system76.com/forest.js:531:5
arrange@/usr/share/gnome-shell/extensions/pop-shell@system76.com/forest.js:49:21
tile@/usr/share/gnome-shell/extensions/pop-shell@system76.com/forest.js:31:9
tile@/usr/share/gnome-shell/extensions/pop-shell@system76.com/auto_tiler.js:186:9
attach_to_window@/usr/share/gnome-shell/extensions/pop-shell@system76.com/auto_tiler.js:65:17
auto_tile@/usr/share/gnome-shell/extensions/pop-shell@system76.com/auto_tiler.js:98:13
window_entity/id<@/usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:491:81

clutter_actor_destroy: assertion 'CLUTTER_IS_ACTOR (self)' failed

**Comment by mmstick** [comment]
Sadly, I haven't been able to replicate this, so finding a solution may be difficult. We may need to try some trial and error until we find a solution that works. I'll have a commit out soon which changes how we're calling the block and unblock functions. Hopefully that will solve the problem we're seeing. Every GObject variable should have this method, but something is causing a Meta.Window to lack this method.

**Comment by mmstick** [comment]
See if e1c7eb5 fixes this

**Comment by WatchMkr** [comment]
Fixed

**Comment by RrOoSsSsOo** [comment]
> Currently on [db6dc50](https://github.com/pop-os/shell/commit/db6dc505f551069e661af96a6203b566d7a80eb9). Auto tiling stopped working with the following error somewhere around [8d16ced](https://github.com/pop-os/shell/commit/8d16ced78eb2366aebeb4d17d94203089fb33d64). Windows end up in floating mode. Tested on two laptops.
> 
> pop-shell: [DEBUG] attempting to attach Alacritty to Terminal
> pop-shell: [DEBUG] attaching Window(2,1) onto Window(1,0)
> pop-shell: [DEBUG] attached Window(2,1) to Fork(0,0)
> pop-shell: [DEBUG] xprop -id 0x2200004 WM_NORMAL_HINTS
> pop-shell: [DEBUG] WM_NORMAL_HINTS(WM_SIZE_HINTS):
> program specified size: 1600 by 1200
> 
> pop-shell: [DEBUG] Window(1,0) shall be moved to [Rect(16,70,1576,1714)]
> pop-shell: [DEBUG] Window(2,1) shall be moved to [Rect(1608,70,1576,1714)]
> pop-shell: [DEBUG] Moving Window(1,0) from [Rect(1600,54,1600,1746)] to [Rect(16,70,1576,1714)]
> **JS ERROR: TypeError: window.meta.block_signal_handler is not a function**
> move_window@/usr/share/gnome-shell/extensions/pop-shell@system76.com/forest.js:531:5
> arrange@/usr/share/gnome-shell/extensions/pop-shell@system76.com/forest.js:49:21
> tile@/usr/share/gnome-shell/extensions/pop-shell@system76.com/forest.js:31:9
> tile@/usr/share/gnome-shell/extensions/pop-shell@system76.com/auto_tiler.js:186:9
> attach_to_window@/usr/share/gnome-shell/extensions/pop-shell@system76.com/auto_tiler.js:65:17
> auto_tile@/usr/share/gnome-shell/extensions/pop-shell@system76.com/auto_tiler.js:98:13
> window_entity/id<@/usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:491:81
> 
> clutter_actor_destroy: assertion 'CLUTTER_IS_ACTOR (self)' failed

This log was obtained with `journalctl -f`?

**Comment by mmstick** [comment]
@RrOoSsSsOo Your version of the shell is very old. We do not use that method anywhere in Pop Shell.
