### ISSUE TITLE
Active hint out of screen bug

### ISSUE THREAD

**Issue by TahsinTariq** [pop-os/shell#990]
**Distribution (run `cat /etc/os-release`):**  20.10 x86_64

**Issue/Bug Description:**
When a window is moved out of screen to the left, the active hint stays on screen.
![Screenshot from 2021-06-03 17-29-56](https://user-images.githubusercontent.com/62146852/120642092-45326080-c496-11eb-8345-7cc2ab01fa9e.png)

**Steps to reproduce (if you know):**
just move any window out of screen to the left

**Expected behavior:**
This doesn't happen if the window is moved to the right side
![Screenshot from 2021-06-03 17-30-10](https://user-images.githubusercontent.com/62146852/120642287-83c81b00-c496-11eb-923c-541e2a79d2a5.png)

**Comment by TC68** [comment]
I have this issue (although I didn't notice it until I saw it mentioned on Reddit).
I use window tiling in pop-shell, but also drag windows around when they are not where I want them.

I am not coding, I am writing complex text documents and reviewing multiple PDFs at the same time so my use case is different to some. I end up using a combination of keyboard and mouse

**Comment by jmmaranan** [comment]
This is caused by the following change on getting the x, y coordinates from workarea instead of the frame rect: 
https://github.com/pop-os/shell/commit/ca579c54eaf39cff7fae24df343c242e5f30fd8d#diff-9e13cab61f6b4bbb06ef29422f0dc0251bcdfd15a9f139008b491f7d1a78e981R555-R556
