### ISSUE TITLE
Moving full screened window with tiling shortcuts removes "Activities" bar

### ISSUE THREAD

**Issue by Kartonrealista** [pop-os/shell#992]
**(1) Issue/Bug Description:**
![Screenshot from 2021-06-05 07-19-25](https://user-images.githubusercontent.com/63356574/120881035-8ded3500-c5ce-11eb-818c-489d36e4ca87.png)

![Screenshot from 2021-06-05 07-22-31](https://user-images.githubusercontent.com/63356574/120881071-d147a380-c5ce-11eb-9a43-84d6a8dd94cf.png)

After moving a full screened window to another monitor with Pop Shell gnome's "Activities" bar disappears. 

**(2) Steps to reproduce (if you know):**

1. Full screen a window
2. Press SUPER + ENTER
3. Move the window to another monitor
4. The Activities bar disappears
5. If you un-fullscreen a window the bar comes back

**(3) Expected behavior:**

It doesn't happen when you full screen a window normally without moving it, so it would look like this:
![Screenshot from 2021-06-05 07-26-22](https://user-images.githubusercontent.com/63356574/120881132-58951700-c5cf-11eb-902e-26bda2e99f0f.png)

**(4) Distribution (run `cat /etc/os-release`):**
 
Pop!_OS 20.10 x86_64

**(5) Gnome Shell version:**

GNOME Shell 3.38.3

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
 ```1.1.0~1620418263~20.10~9507dc3```

**(7) Where was Pop Shell installed from:**

Came with OS.

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1920:1080, 1152:864

**(9) Other Installed/Enabled Extensions:**

![Screenshot from 2021-06-05 07-35-20](https://user-images.githubusercontent.com/63356574/120881336-9d6d7d80-c5d0-11eb-851e-be1c7ba7b4a8.png)

**(10) Other Notes:**

-

**Comment by jmmaranan** [comment]
Fullscreen windows are not allowed to be moved by the mouse. So I think tiling should prevent windows from moving as well via Super+Enter.

**Comment by Kartonrealista** [comment]
@jmmaranan That is a way to solve it, although it seems like removing a functionality. 

To maybe add a bit to the initial report: moving windows like that works and produces the same bug with Super + Shift + Right/Left, and un-fullscreening additionally ping-pongs the window from the display it is on to the display from which it was moved and back, like so: 2->1->2. Maybe it's a bug with how window trees work in the pop shell since the window temporarily comes back to it's old display when un-fullscreened and the top bar disappears as if the window was still on the original display.

**Comment by jmmaranan** [comment]
> @jmmaranan That is a way to solve it, although it seems like removing a functionality.

No problem: https://github.com/pop-os/shell/pull/1015
