### ISSUE TITLE
Launcher search results order

### ISSUE THREAD

**Issue by dodalovic** [pop-os/shell#994]
Pop OS 20.10

When I search for **shop**, although typed precisely as it should, doesn't get promoted to top.

![image](https://user-images.githubusercontent.com/6358061/121136600-1faaab80-c836-11eb-9213-ef4462c30961.png)

**Comment by jacobgkau** [comment]
Duplicate/continuation of https://github.com/pop-os/shell/issues/979 (the example case in that issue was fixed, but this new case isn't ideal.)

The launcher should probably prioritize longer-length exact matches.

**Comment by leviport** [comment]
There have been many improvements to search results in the Launcher, and "shop" seems to put Pop Shop at the top of the list now.
