### ISSUE TITLE
Feature parity of launcher with gnome activities overview search

### ISSUE THREAD

**Issue by jmbuhr** [pop-os/shell#995]
Previously, the old _activities overview_ would show workspaces and seamlessly switch to searching apps, settings and files once the user started typing. With the launcher being established as the new one-stop-shop for all those activities, I am trying to incorporate it more and more into my workflow. However, I find myself having to go back to the regular gnome search for certain search results. As such, here is my wishlist for the launcher:

- [ ] Searching files and folders that have not very recently been opened: For example, when I search `hello` in the gnome search, I get 2 hello_world folders and an email address that contains the word hello. In the launcher I just get the `help` app and with `d: hello` nothing pops up.
- [x] Continuation of autocompletion: When I type e.g. `~/Doc` I can use tab to complete to  `/home/jannik/Documents/`, but there is no more autocompletion popping up after the first completion.
- [ ] Starting to type in the workspaces view could automatically open up the launcher. Back with the gnome overview, I would often open the overview to see what is happening and then remember what application I want to launch. Right now there is no way do directly get to either the search or the launcher from the workspaces view.

Note: I originally opened a related issue in the pop/beta repo: https://github.com/pop-os/beta/issues/169. Pop-os is a blast to work with, keep up the good work! :)

**Comment by jacobgkau** [comment]
Thank you for the feedback! The final point (configuration of search results being confusing) is covered in the Settings repository here: https://github.com/pop-os/gnome-control-center/issues/164 and https://github.com/pop-os/gnome-control-center/issues/165

**Comment by jmbuhr** [comment]
Updated my list above with a proposition to replace automatic search in the workspaces view with automatic opening of the launcher on typing (see https://github.com/pop-os/cosmic/commit/cf34204fd965e5a69dc2e618a5d1c0365a8ddf45)

**Comment by jmbuhr** [comment]
Point 2 has been implemented :) But I am hesitant to tick of point 1, because even though between `d:` and `file` the functionality is now there, it is still considerably slower than gnome search and split between two keywords even though conceptually files and folders are very similar. I wonder if it wouldn't be possible to tap into gnome search for file and folder search results.
