### ISSUE TITLE
Launcher: searching "gimp" returns no results, but "gnu im" shows GIMP

### ISSUE THREAD

**Issue by leviport** [pop-os/shell#997]
**(1) Issue/Bug Description:**
When trying to launch GIMP, searching "gimp" returns no results. Instead, I have to type something that matches its full name (GNU Image Manipulation Program).
![launcher1](https://user-images.githubusercontent.com/13512097/121723319-98fb0600-caa3-11eb-86b1-1f5d9c3106ec.png)
![launcher2](https://user-images.githubusercontent.com/13512097/121723361-a87a4f00-caa3-11eb-86eb-8ac1e55335df.png)

**(2) Steps to reproduce (if you know):**
- Install GIMP (I have the .deb installed)
- Open launcher
- Type "gimp"
- See no results

**(3) Expected behavior:**
- Open launcher
- Type "gimp"
- I'd expect GIMP to be the first result

**(4) Distribution (run `cat /etc/os-release`):**
 Pop!\_OS 21.04

**(5) Gnome Shell version:**
`3.38.4-1ubuntu3~21.04.1ubuntu1pop1~1622878927~21.04~ee2c101`

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
`1.1.0~1623101914~21.04~df8b27b`

**(7) Where was Pop Shell installed from:**
PPA

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1x 4K at 100% scale, positioned above built-in 1080p laptop display

**(9) Other Installed/Enabled Extensions:**
![2021-06-11_10-46](https://user-images.githubusercontent.com/13512097/121722203-5e449e00-caa2-11eb-98c9-6c5263307e70.png)

**(10) Other Notes:**

**Comment by jacobgkau** [comment]
I can recreate this on df8b27b, but not 9507dc3, so it's a recent regression, probably related to https://github.com/pop-os/shell/commit/df8b27b006f9ae113e05056f2025e655044f6176 (the search algorithm improvements.) The following aspects of the .desktop file contain GIMP/gimp:

- Filename (`gimp.desktop`)
- Keywords (`GIMP`)
- Exec (`gimp-2.10 %U`)
- TryExec (`gimp-2.10`)
- Icon (`gimp`)
- MimeType (`x-gimp-gbr` and others)
- X-Ubuntu-Gettext-Domain (`gimp20`)

So one of those items was probably being read before and is no longer being taken into account. I'm fairly sure keywords used to be read (and I see they aren't now), but I also see `app.desktop_name` used to be read and now is not, so my guess would be either of the first two.

**Comment by mmstick** [comment]
Yeah, just need to add the keywords to the search filters

**Comment by leviport** [comment]
Cool, sounds like a quick fix then. Just in case it needs added as well, it looks like Popsicle is doing the same thing. It shows up if I search "USB Flasher", but not if I search "popsicle".

**Comment by jmbuhr** [comment]
Related issue in `cosmic`: https://github.com/pop-os/cosmic/issues/69
